<wsdl:definitions name="CreateUpdatePS" targetNamespace="http://www.example.org/CreateUpdatePS/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.example.org/CreateUpdatePS/" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessSFDCSyncCust/V1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://www.sunpowercorp.com/BOD/ProcessSFDCSyncCust/V1" schemaLocation="../xsd/CDM/BOD/Nouns/SyncAccCustomers/V1/ProcessSFDCSyncCustomers.xsd"/>
        </schema>
    </wsdl:types>
  <wsdl:message name="NewOperationRequest">
    <wsdl:part element="ns1:ProcessSFDCSyncCust" name="parameters"/>
  </wsdl:message>
  
  <wsdl:portType name="CreateUpdatePS">
    <wsdl:operation name="CreateUpdateCust">
      <wsdl:input message="tns:NewOperationRequest"/>    
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="CreateUpdatePSSOAP" type="tns:CreateUpdatePS">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="CreateUpdateCust">
      <soap:operation soapAction="http://www.example.org/CreateUpdatePS/NewOperation"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>     
    </wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="CreateUpdatePS">
    <wsdl:port binding="tns:CreateUpdatePSSOAP" name="CreateUpdatePSSOAP">
      <soap:address location="http://www.example.org/"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>