<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:imp1="http://www.sunpowercorp.com/WriteOrgConSFDCToLMSFile" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ens="urn:sobject.partner.soap.sforce.com" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:fns="urn:fault.partner.soap.sforce.com" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/file/LMS_DEV/OrgConnectorSFDCtoLMS/WriteOrgConSFDCToLMSFile" xmlns:tns="urn:partner.soap.sforce.com" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl soap ens fns xsd tns imp1 plt wsdl jca ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/partner.wsdl"/>
            <oracle-xsl-mapper:rootElement name="queryResponse" namespace="urn:partner.soap.sforce.com"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/WriteOrgConSFDCToLMSFile.wsdl"/>
            <oracle-xsl-mapper:rootElement name="SFDCORGCONLMSFlatFile" namespace="http://www.sunpowercorp.com/WriteOrgConSFDCToLMSFile"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [SAT OCT 08 16:38:31 IST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <imp1:SFDCORGCONLMSFlatFile>
      <imp1:Header>
        <imp1:ORG_ID>
          <xsl:text disable-output-escaping="no">ORG_ID</xsl:text>
        </imp1:ORG_ID>
        <imp1:ORG_DESC>
          <xsl:text disable-output-escaping="no">ORG_DESC</xsl:text>
        </imp1:ORG_DESC>
        <imp1:ORG_ID_PARENT>
          <xsl:text disable-output-escaping="no">ORG_ID_PARENT</xsl:text>
         </imp1:ORG_ID_PARENT>
      </imp1:Header>
      <xsl:for-each select="/tns:queryResponse/tns:result/tns:records">
        <xsl:variable name="pos" select="position()"/>
        <imp1:SFDCORGCONLMSFlatFileItems>
        
        <!--
          <imp1:ORG_ID>
            <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:Account/ens:AccountNumber"/>
          </imp1:ORG_ID>
          <imp1:ORG_DESC>
            <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:Account/ens:Name"/>
          </imp1:ORG_DESC>
           <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:Country_Domain__c"/>
                       <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:Country_Domain__c"/>
          -->
          
           <imp1:ORG_ID>
            <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:AccountNumber"/>
          </imp1:ORG_ID>
          <imp1:ORG_DESC>
            <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:Name"/>
          </imp1:ORG_DESC>
          <imp1:ORG_ID_PARENT>
            <xsl:value-of select="dvm:lookupValue(&quot;Country.dvm&quot;,&quot;SFDC&quot;,/tns:queryResponse/tns:result/tns:records[$pos]/ens:Country_Domain__c,&quot;LMS&quot;,&quot;&quot;)"/>
          </imp1:ORG_ID_PARENT>
        </imp1:SFDCORGCONLMSFlatFileItems>
      </xsl:for-each>
    </imp1:SFDCORGCONLMSFlatFile>
  </xsl:template>
</xsl:stylesheet>