<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:client="http://xmlns.oracle.com/SFDCUtilityService/SFDCUtilityService"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Lease2Outbound/Lease2OutboundSFDCProv/FetchEBSLeasePaymentDtls"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/FetchEBSLeasePaymentDtls"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:ns0="http://xmlns.oracle.com/SFDCUtilityService/SFDCUtilityServiceMediator"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns db plt xsd wsdl client ns0 bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref ora socket ldap"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/FetchEBSLeasePaymentDtls.wsdl"/>
        <oracle-xsl-mapper:rootElement name="FetchEBSLeasePaymentDtlsOutputCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/FetchEBSLeasePaymentDtls"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7003/soa-infra/services/default/SFDCUtilityService/SFDCUtilityServiceMediator.wsdl"/>
        <oracle-xsl-mapper:rootElement name="upsert"
                                       namespace="http://xmlns.oracle.com/SFDCUtilityService/SFDCUtilityService"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <oracle-xsl-mapper:mapShowPrefixes type="true"/>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON OCT 10 16:52:09 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <client:upsert>
      <client:externalIDFieldName>
        <xsl:text disable-output-escaping="no">Id</xsl:text>
      </client:externalIDFieldName>
      <xsl:for-each select="/db:FetchEBSLeasePaymentDtlsOutputCollection/db:FetchEBSLeasePaymentDtlsOutput">
        <client:sObject>
          <client:type>
            <xsl:text disable-output-escaping="no">FPO_Order_Line__c</xsl:text>
          </client:type>
          <client:Id>
            <xsl:value-of select="db:l_SFDC_ID"/>
          </client:Id>
          <client:Lease_Payment__c>
            <xsl:value-of select="db:h_SFDC_ID"/>
          </client:Lease_Payment__c>
          <client:Line_Id__c>
            <xsl:value-of select="db:l_LINE_ID"/>
          </client:Line_Id__c>
          <xsl:choose>
            <xsl:when test="db:l_VENDOR_TYPE=''">
              <client:fieldsToNull>Vendor_Type__c</client:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <client:Vendor_Type__c>
                <xsl:value-of select="db:l_VENDOR_TYPE"/>
              </client:Vendor_Type__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="db:l_VENDOR_NAME=''">
              <client:fieldsToNull>Vendor__c</client:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <client:Vendor__c>
                <xsl:value-of select="db:l_VENDOR_NAME"/>
              </client:Vendor__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="db:l_PO_CREATION_DATE=''">
              <client:fieldsToNull>PO_Creation_Date__c</client:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <client:PO_Creation_Date__c>
                <xsl:value-of select="db:l_PO_CREATION_DATE"/>
              </client:PO_Creation_Date__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="db:l_PO_AMOUNT=''">
              <client:fieldsToNull>PO_Amount__c</client:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <client:PO_Amount__c>
                <xsl:value-of select="db:l_PO_AMOUNT"/>
              </client:PO_Amount__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="db:l_PO_RECEIPT_DATE=''">
              <client:fieldsToNull>PO_Receipt_Date__c</client:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <client:PO_Receipt_Date__c>
                <xsl:value-of select="db:l_PO_RECEIPT_DATE"/>
              </client:PO_Receipt_Date__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="db:l_SUPPLIER_INVOICE_NUMBER=''">
              <client:fieldsToNull>Supplier_Invoice__c</client:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <client:Supplier_Invoice__c>
                <xsl:value-of select="db:l_SUPPLIER_INVOICE_NUMBER"/>
              </client:Supplier_Invoice__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="db:l_PAYMENT_AMOUNT=''">
              <client:fieldsToNull>Payment_Amount__c</client:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <client:Payment_Amount__c>
                <xsl:value-of select="db:l_PAYMENT_AMOUNT"/>
              </client:Payment_Amount__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="db:l_PAYMENT_DATE=''">
              <client:fieldsToNull>Payment_Date__c</client:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <client:Payment_Date__c>
                <xsl:value-of select="db:l_PAYMENT_DATE"/>
              </client:Payment_Date__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="db:l_SCHEDULE_PAYMENT_DATE=''">
              <client:fieldsToNull>Schedule_Payment_Date__c</client:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <client:Schedule_Payment_Date__c>
                <xsl:value-of select="db:l_SCHEDULE_PAYMENT_DATE"/>
              </client:Schedule_Payment_Date__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="db:l_ITEM_NUMBER=''">
              <client:fieldsToNull>Item_Number__c</client:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <client:Item_Number__c>
                <xsl:value-of select="db:l_ITEM_NUMBER"/>
              </client:Item_Number__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="db:l_ITEM_DESCRIPTION=''">
              <client:fieldsToNull>MileStone__c</client:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <client:MileStone__c>
                <xsl:value-of select="db:l_ITEM_DESCRIPTION"/>
              </client:MileStone__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="db:l_PO_NUMBER=''">
              <client:fieldsToNull>PO__c</client:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <client:PO__c>
                <xsl:value-of select="db:l_PO_NUMBER"/>
              </client:PO__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="db:l_SUPPLIER_INVOICE_AMOUNT=''">
              <client:fieldsToNull>Supplier_Invoice_Amount__c</client:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <client:Supplier_Invoice_Amount__c>
                <xsl:value-of select="db:l_SUPPLIER_INVOICE_AMOUNT"/>
              </client:Supplier_Invoice_Amount__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="db:l_PO_RECEIPT_NUMBER=''">
              <client:fieldsToNull>PO_Receipt__c</client:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <client:PO_Receipt__c>
                <xsl:value-of select="db:l_PO_RECEIPT_NUMBER"/>
              </client:PO_Receipt__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="db:l_INVOICE_DATE=''">
              <client:fieldsToNull>Invoice_Creation_Date__c</client:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <client:Invoice_Creation_Date__c>
                <xsl:value-of select="db:l_INVOICE_DATE"/>
              </client:Invoice_Creation_Date__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="db:l_INVOICE_STATUS=''">
              <client:fieldsToNull>Invoice_Status__c</client:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <client:Invoice_Status__c>
                <xsl:value-of select="db:l_INVOICE_STATUS"/>
              </client:Invoice_Status__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="db:l_PAYMENT_STATUS=''">
              <client:fieldsToNull>Payment_Status__c</client:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <client:Payment_Status__c>
                <xsl:value-of select="db:l_PAYMENT_STATUS"/>
              </client:Payment_Status__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="db:l_PO_DESCRIPTION=''">
              <client:fieldsToNull>PO_Description__c</client:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <client:PO_Description__c>
                <xsl:value-of select="db:l_PO_DESCRIPTION"/>
              </client:PO_Description__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="db:l_PAYMENT_NUMBER=''">
              <client:fieldsToNull>Payment_Remittance_Number__c</client:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <client:Payment_Remittance_Number__c>
                <xsl:value-of select="db:l_PAYMENT_NUMBER"/>
              </client:Payment_Remittance_Number__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="db:l_PO_LINE_STATUS=''">
              <client:fieldsToNull>PO_Line_Status__c</client:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <client:PO_Line_Status__c>
                <xsl:value-of select="db:l_PO_LINE_STATUS"/>
              </client:PO_Line_Status__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="db:SO_LINE_STATUS=''">
              <client:fieldsToNull>SO_Line_Status__c</client:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <client:SO_Line_Status__c>
                <xsl:value-of select="db:l_SO_LINE_STATUS"/>
              </client:SO_Line_Status__c>
            </xsl:otherwise>
          </xsl:choose>
        </client:sObject>
      </xsl:for-each>
    </client:upsert>
  </xsl:template>
</xsl:stylesheet>