<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/FetchEBSLeasePaymentDtls" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns0="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns9="http://www.sunpowercorp.com/Noun/Lease2Outbound/V1" xmlns:ns6="http://www.sunpowercorp.com/utilities/ID/xsd/v1" xmlns:ns2="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns7="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Lease2Outbound/Lease2OutboundSFDCProv/FetchEBSLeasePaymentDtls" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns8="http://www.sunpowercorp.com/Common/Lease2OutboundCommonTypes/V1" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessLease2Outbound/V1" xmlns:ns5="http://schemas.oracle.com/bpel/extension" xmlns:ns3="urn:partner.soap.sforce.com" xmlns:client="http://www.sunpowercorp.com/SunPowerApp/Lease2OutboundSFDCProv/Lease2OutboundSFDCProv_BPEL" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" xmlns:ns4="http://www.sunpowercorp.com/SunPowerApp/SFDCId" exclude-result-prefixes="xsi xsl ns0 plnk wsdl ns9 ns6 ns2 ns7 ns8 xsd ns1 ns5 ns3 client ns4 db tns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/Lease2OutboundSFDCProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessLease2Outbound" namespace="http://www.sunpowercorp.com/BOD/ProcessLease2Outbound/V1"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/FetchEBSLeasePaymentDtls.wsdl"/>
            <oracle-xsl-mapper:rootElement name="FetchEBSLeasePaymentDtlsInput" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/FetchEBSLeasePaymentDtls"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON OCT 10 16:52:09 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <db:FetchEBSLeasePaymentDtlsInput>      
      <db:HeaderId>
        <xsl:for-each select="/ns1:ProcessLease2Outbound/ns1:DataArea/ns9:LeaseOrder/ns9:Lease2OrderDetails">
            <!--xsl:value-of select="concat(&quot;'&quot;,ns8:SoHeaderId,&quot;'&quot;)"/--> 
            <xsl:value-of select="ns8:SoHeaderId"/> 
            <xsl:if test="position() != last()">
                <xsl:text disable-output-escaping="no">:</xsl:text>
            </xsl:if>
          </xsl:for-each>
      </db:HeaderId>
    </db:FetchEBSLeasePaymentDtlsInput>
  </xsl:template>
</xsl:stylesheet>