<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateStatusToEBS" xmlns:ns0="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns8="http://www.sunpowercorp.com/Noun/Lease2Outbound/V1" xmlns:ns6="http://www.sunpowercorp.com/utilities/ID/xsd/v1" xmlns:ns2="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:ens="urn:sobject.partner.soap.sforce.com" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns3="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:fns="urn:fault.partner.soap.sforce.com" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns7="http://www.sunpowercorp.com/Common/Lease2OutboundCommonTypes/V1" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessLease2Outbound/V1" xmlns:ns5="http://schemas.oracle.com/bpel/extension" xmlns:client="http://www.sunpowercorp.com/SunPowerApp/Lease2OutboundSFDCProv/Lease2OutboundSFDCProv_BPEL" xmlns:tns="urn:partner.soap.sforce.com" xmlns:ns9="http://xmlns.oracle.com/pcbpel/adapter/db/Lease2Outbound/Lease2OutboundSFDCProv/UpdateStatusToEBS" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" xmlns:ns4="http://www.sunpowercorp.com/SunPowerApp/SFDCId" exclude-result-prefixes="xsi xsl ns0 plnk soap wsdl ns8 ns6 ns2 ens ns3 fns ns7 xsd ns1 ns5 client tns ns4 top ns9 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/partner.wsdl"/>
            <oracle-xsl-mapper:rootElement name="queryResponse" namespace="urn:partner.soap.sforce.com"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/Lease2OutboundSFDCProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessLease2Outbound" namespace="http://www.sunpowercorp.com/BOD/ProcessLease2Outbound/V1"/>
            <oracle-xsl-mapper:param name="inputVariable.payload"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/UpdateStatusToEBS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="XxspwrLease2OutboundDetailsCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateStatusToEBS"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON OCT 10 16:52:09 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:key name="LeaseDistinct" match="ens:OracleOrderHeaderId__c" use="."/>
  <xsl:param name="inputVariable.payload"/>
  <xsl:template match="/">
    <top:XxspwrLease2OutboundDetailsCollection>
      <xsl:for-each select="/tns:queryResponse/tns:result/tns:records">
        <xsl:if test="false() or ens:OracleOrderHeaderId__c [key('LeaseDistinct',.)[2]]">
          <top:XxspwrLease2OutboundDetails>
            <xsl:variable name="LeaseVar" select="ens:OracleOrderHeaderId__c"/>
            <top:soNumber>
              <xsl:value-of select="$inputVariable.payload/ns1:ProcessLease2Outbound/ns1:DataArea/ns8:LeaseOrder/ns8:Lease2OrderDetails[ns7:SoHeaderId=$LeaseVar]/ns7:SoNumber"/>
            </top:soNumber>
            <top:soaStatus>
              <xsl:text disable-output-escaping="no">ERROR</xsl:text>
            </top:soaStatus>
            <top:errorMessage>
              <xsl:value-of select="concat(&quot;ERROR::Multiple Record Ids returned from SFDC for Lease Number--&quot;,$LeaseVar)"/>
            </top:errorMessage>
          </top:XxspwrLease2OutboundDetails>
        </xsl:if>
      </xsl:for-each>
      <xsl:for-each select="$inputVariable.payload/ns1:ProcessLease2Outbound/ns1:DataArea/ns8:LeaseOrder/ns8:Lease2OrderDetails">
        <xsl:variable name="count" select="count(.[ns7:SoHeaderId=/tns:queryResponse/tns:result/tns:records/ens:OracleOrderHeaderId__c])"/>
        <xsl:if test="$count = 0">
          <top:XxspwrLease2OutboundDetails>
            <top:soNumber>
              <xsl:value-of select="ns7:SoNumber"/>
            </top:soNumber>
            <top:soaStatus>
              <xsl:text disable-output-escaping="no">ERROR</xsl:text>
            </top:soaStatus>
            <top:errorMessage>
              <xsl:value-of select="concat(&quot;ERROR::Empty Record Id returned from SFDC for Lease Number--&quot;,ns7:LeaseNumber)"/>
            </top:errorMessage>
          </top:XxspwrLease2OutboundDetails>
        </xsl:if>
      </xsl:for-each>
    </top:XxspwrLease2OutboundDetailsCollection>
  </xsl:template>
</xsl:stylesheet>