<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
                xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
                xmlns:ns4="http://www.sunpowercorp.com/Common/Dealer_PartnerCreditINFOTypes/V1"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DealerPartnerCreditDetalis/SyncCreditLimitOracleReq/SelectCreditLimitInfo"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions"
                xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/SelectCreditLimitInfo"
                xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessDealer_PartnerCreditINFO/V1"
                xmlns:ns0="http://www.sunpowercorp.com/Noun/Dealer_PartnerCreditINFO/V1"
                xmlns:ns2="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ora="http://schemas.oracle.com/xpath/extension"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:ns3="http://www.sunpowercorp.com/Common/CommonDataTypes/V1"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath"
                xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath"
                xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:client="http://www.example.org/SyncCreditLimitPSWsdl"
                xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap"
                exclude-result-prefixes="xsi xsl tns db plt wsdl xsd ns4 ns1 ns0 ns2 soap ns3 client xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/SelectCreditLimitInfo.wsdl"/>
        <oracle-xsl-mapper:rootElement name="SelectCreditLimitInfoOutputCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SelectCreditLimitInfo"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7004/SyncCreditLimitEBS/Proxy/SyncCreditLimitPS?wsdl"/>
        <oracle-xsl-mapper:rootElement name="ProcessDealer_PartnerCreditINFO"
                                       namespace="http://www.sunpowercorp.com/BOD/ProcessDealer_PartnerCreditINFO/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <oracle-xsl-mapper:mapShowPrefixes type="true"/>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE OCT 11 11:33:55 CDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ns1:ProcessDealer_PartnerCreditINFO>
      <ns1:DataArea>
        <ns0:CreditLimit>
          <xsl:for-each select="/db:SelectCreditLimitInfoOutputCollection/db:SelectCreditLimitInfoOutput">
            <ns0:CreditLimitDetails>
              <ns4:AccountNumber>
                <xsl:value-of select="db:ACCOUNT_NUMBER"/>
              </ns4:AccountNumber>
              <ns4:AccountName>
                <xsl:value-of select="db:ACCOUNT_NAME"/>
              </ns4:AccountName>
              <ns4:CustAccountId>
                <xsl:value-of select="db:CUST_ACCOUNT_ID"/>
              </ns4:CustAccountId>
              <ns4:OverallCreditLimit>
                <xsl:value-of select="db:OVERALL_CREDIT_LIMIT"/>
              </ns4:OverallCreditLimit>
              <ns4:LastUpdateDate>
                <xsl:value-of select="db:LAST_UPDATE_DATE"/>
              </ns4:LastUpdateDate>
              <ns4:AvailableCreditLimit>
                <xsl:value-of select="db:Avaiable_CreditLimit"/>
              </ns4:AvailableCreditLimit>
              <ns4:AmountPastDue>
                <xsl:value-of select="db:AMOUNT_PAST_DUE"/>
              </ns4:AmountPastDue>
              <ns4:Netterm>
                <xsl:value-of select="db:NetTerm"/>
              </ns4:Netterm>
            </ns0:CreditLimitDetails>
          </xsl:for-each>
        </ns0:CreditLimit>
      </ns1:DataArea>
    </ns1:ProcessDealer_PartnerCreditINFO>
  </xsl:template>
</xsl:stylesheet>