<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:ns6="http://www.sunpowercorp.com/Common/SunPowerStoreONFToSFDCDetailsCommonTypes/V1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns0="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:client="http://www.sunpowercorp.com/SunPowerStoreONFToSFDC/SunPowerStoreSFDCProv/SunPowerStoreSFDCProv_BPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns4="http://www.sunpowercorp.com/SFDCIDs/xsd/v1" xmlns:ns2="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:ens="urn:sobject.partner.soap.sforce.com" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns5="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:fns="urn:fault.partner.soap.sforce.com" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns7="http://www.sunpowercorp.com/Noun/SunPowerStoreONFToSFDC/V1" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessSunPowerStoreONFToSFDC/V1" xmlns:ns3="urn:partner.soap.sforce.com" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns6 ns0 plnk soap client wsdl ns4 ns2 ens ns5 fns ns7 xsd ns1 ns3 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SunPowerStoreSFDCProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessSunPowerStoreONFToSFDC" namespace="http://www.sunpowercorp.com/BOD/ProcessSunPowerStoreONFToSFDC/V1"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/partner.wsdl"/>
            <oracle-xsl-mapper:rootElement name="queryResponse" namespace="urn:partner.soap.sforce.com"/>
            <oracle-xsl-mapper:param name="InvSFDCQuery_OV.parameters"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/partner.wsdl"/>
            <oracle-xsl-mapper:rootElement name="upsert" namespace="urn:partner.soap.sforce.com"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [FRI OCT 07 19:06:49 IST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="InvSFDCQuery_OV.parameters"/>
  <xsl:template match="/">
    <ns3:upsert>
      <ns3:externalIDFieldName>
        <xsl:text disable-output-escaping="no">Id</xsl:text>
      </ns3:externalIDFieldName>
      <xsl:for-each select="$InvSFDCQuery_OV.parameters/ns3:queryResponse/ns3:result/ns3:records">
        <xsl:variable name="SmartStoreID" select="ens:SmartStore_ID__c"/>
        <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]">
          <ns3:sObjects>
            <ens:type>
              <xsl:text disable-output-escaping="no">SmartStore_Details__c</xsl:text>
            </ens:type>
            <ens:Id>
              <xsl:text disable-output-escaping="no"/>
            </ens:Id>
            <ens:Name>
              <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ID"/>
            </ens:Name>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns6:CreateDate != &quot;&quot;">
              <ens:Order_Date__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns6:CreateDate"/>
              </ens:Order_Date__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:User/ns7:ID != &quot;&quot;">
              <ens:SmartStore_ID__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:User/ns7:ID"/>
              </ens:SmartStore_ID__c>
            </xsl:if>
            <xsl:if test="ens:Contact/ens:AccountId != &quot;&quot;">
              <ens:Account__c>
                <xsl:value-of select="ens:Contact/ens:AccountId"/>
              </ens:Account__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns6:OrderNumber != &quot;&quot;">
              <ens:Order_Number__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns6:OrderNumber"/>
              </ens:Order_Number__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns6:ProductName != &quot;&quot;">
              <ens:Product_Name__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns6:ProductName"/>
              </ens:Product_Name__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns7:SKU/ns7:ID != &quot;&quot;">
              <ens:SKU__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns7:SKU/ns7:ID"/>
              </ens:SKU__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns6:Quantity != &quot;&quot;">
              <ens:Qty_Ordered__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns6:Quantity"/>
              </ens:Qty_Ordered__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns7:Price/ns7:Cost/ns7:Customer != &quot;&quot;">
              <ens:Price__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns7:Price/ns7:Cost/ns7:Customer"/>
              </ens:Price__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns7:Price/ns7:Tax/ns7:DirectAcctSales != &quot;&quot;">
              <ens:Total_Tax__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns7:Price/ns7:Tax/ns7:DirectAcctSales"/>
              </ens:Total_Tax__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns7:Shipping/ns6:Method != &quot;&quot;">
              <ens:Shipping_Method__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns7:Shipping/ns6:Method"/>
              </ens:Shipping_Method__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns7:Shipping/ns6:TrackingNumber != &quot;&quot;">
              <ens:Tracking_Number__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns7:Shipping/ns6:TrackingNumber"/>
              </ens:Tracking_Number__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns7:Price/ns7:Cost/ns7:Shipping != &quot;&quot;">
              <ens:Shipping_Handling_Cost__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns7:Price/ns7:Cost/ns7:Shipping"/>
              </ens:Shipping_Handling_Cost__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns7:ClientStatus/ns6:Value != &quot;&quot;">
              <ens:Status__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns7:ClientStatus/ns6:Value"/>
              </ens:Status__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns6:OrderType != &quot;&quot;">
              <ens:Purchase_Type__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns6:OrderType"/>
              </ens:Purchase_Type__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns7:Price/ns7:Cost/ns7:Unit != &quot;&quot;">
              <ens:Unit_Price__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns7:Price/ns7:Cost/ns7:Unit"/>
              </ens:Unit_Price__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns7:SKU/ns6:Name != &quot;&quot;">
              <ens:SKU_Description__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns7:SKU/ns6:Name"/>
              </ens:SKU_Description__c>
            </xsl:if>
			
           <xsl:if test="string-length(/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns7:Shipping/ns6:Date) > 0">
              <ens:Ship_Date__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:OrderDetails/ns7:OrderDetail/ns7:Shipping/ns6:Date"/>
              </ens:Ship_Date__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:Description != &quot;&quot;">
              <ens:Ship_Address__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:Description"/>
              </ens:Ship_Address__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:Description != &quot;&quot;">
              <ens:Bill_Address__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:Description"/>
              </ens:Bill_Address__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:CompanyName != &quot;&quot;">
              <ens:Ship_Company__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:CompanyName"/>
              </ens:Ship_Company__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:Attn != &quot;&quot;">
              <ens:Ship_Attn__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:Attn"/>
              </ens:Ship_Attn__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:Address1 != &quot;&quot;">
              <ens:Ship_Addr1__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:Address1"/>
              </ens:Ship_Addr1__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:Address2 != &quot;&quot;">
              <ens:Ship_Addr2__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:Address2"/>
              </ens:Ship_Addr2__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:Address3 != &quot;&quot;">
              <ens:Ship_Addr3__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:Address3"/>
              </ens:Ship_Addr3__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:Address4 != &quot;&quot;">
              <ens:Ship_Addr4__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:Address4"/>
              </ens:Ship_Addr4__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:City != &quot;&quot;">
              <ens:Ship_City__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:City"/>
              </ens:Ship_City__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:State != &quot;&quot;">
              <ens:Ship_State__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:State"/>
              </ens:Ship_State__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:Zip != &quot;&quot;">
              <ens:Ship_Zip__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:Zip"/>
              </ens:Ship_Zip__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:Country != &quot;&quot;">
              <ens:Ship_Country__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:ShippingAddress/ns6:Country"/>
              </ens:Ship_Country__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:CompanyName != &quot;&quot;">
              <ens:Bill_Company__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:CompanyName"/>
              </ens:Bill_Company__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:Attn != &quot;&quot;">
              <ens:Bill_Attn__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:Attn"/>
              </ens:Bill_Attn__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:Address1 != &quot;&quot;">
              <ens:Bill_Addr1__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:Address1"/>
              </ens:Bill_Addr1__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:Address2 != &quot;&quot;">
              <ens:Bill_Addr2__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:Address2"/>
              </ens:Bill_Addr2__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:Address3 != &quot;&quot;">
              <ens:Bill_Addr3__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:Address3"/>
              </ens:Bill_Addr3__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:Address4 != &quot;&quot;">
              <ens:Bill_Addr4__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:Address4"/>
              </ens:Bill_Addr4__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:City != &quot;&quot;">
              <ens:Bill_City__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:City"/>
              </ens:Bill_City__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:State != &quot;&quot;">
              <ens:Bill_State__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:State"/>
              </ens:Bill_State__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:Zip != &quot;&quot;">
              <ens:Bill_Zip__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:Zip"/>
              </ens:Bill_Zip__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:Country != &quot;&quot;">
              <ens:Bill_Country__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:BillingAddress/ns6:Country"/>
              </ens:Bill_Country__c>
            </xsl:if>
            <xsl:if test="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:User/ns6:LoginID != &quot;&quot;">
              <ens:Purchaser_ID__c>
                <xsl:value-of select="/ns1:ProcessSunPowerStoreONFToSFDC/ns1:DataArea/ns7:SunPowerStoreONFToSFDC/ns7:SunPowerStoreONFToSFDCDetails/ns7:OrderResponse/ns7:Orders/ns7:Order[ns7:User/ns7:ID = $SmartStoreID]/ns7:User/ns6:LoginID"/>
              </ens:Purchaser_ID__c>
            </xsl:if>
          </ns3:sObjects>
        </xsl:if>
      </xsl:for-each>
    </ns3:upsert>
  </xsl:template>
</xsl:stylesheet>