<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessOracleSFDCItem/V1" xmlns:ns14="http://xmlns.oracle.com/SFDCUtilityService/SFDCUtilityService" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns5="http://www.sunpowercorp.com/Noun/OracleSFDCItem/V1" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:tns="http://xmlns.oracle.com/SFDCUtilityService/SFDCUtilityServiceMediator" xmlns:ns0="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns10="http://www.sunpowercorp.com/OracleIndexItems" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns4="http://www.sunpowercorp.com/Common/OracleSFDCItemCommonTypes/V1" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns2="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns11="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns12="http://www.sunpowercorp.com/SOAUtilityServices/CommonLoggingService/CommonLoggingService_BPEL" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns8="http://www.sunpowercorp.com/SFDCItems" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:client="http://www.sunpowercorp.com/OnlineOrderingItemOnlyOracleToSFDC/OracleSFDCItemPRODProv/OracleSFDCItemPRODProv_BPEL" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns9="http://schemas.oracle.com/bpel/extension" xmlns:ns6="http://www.sunpowercorp.com/OracleItems" xmlns:ns3="urn:partner.soap.sforce.com" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns1 ns5 ns0 plnk ns10 wsdl ns4 ns7 ns2 ns11 ns4 ns8 client xsd ns9 ns6 ns3 ns14 tns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:ns7="http://www.sunpowercorp.com/online/OracleSFDCItemProd/xsd/v1"
                xmlns:ns16="http://www.sunpowercorp.com/SunPowerDevelopment/utility/EmailContent/xsd/V1"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:ns13="http://www.sunpowercorp.com/MergedItems"
                xmlns:ns15="http://www.sunpowercorp.com/SunPowerDevelopment/DealerPartnerCreditINFO/EnqueSyncCreditHoldLimit/initParams/xsd/v1">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/OracleSFDCItemPRODProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessOracleSFDCItem" namespace="http://www.sunpowercorp.com/BOD/ProcessOracleSFDCItem/V1"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7003/soa-infra/services/default/SFDCUtilityService/SFDCUtilityServiceMediator.wsdl"/>
            <oracle-xsl-mapper:rootElement name="upsert" namespace="http://xmlns.oracle.com/SFDCUtilityService/SFDCUtilityService"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON OCT 10 17:27:41 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns14:upsert>
      <ns14:externalIDFieldName>
        <xsl:text disable-output-escaping="no">OraclePVSimId__c</xsl:text>
      </ns14:externalIDFieldName>
      <xsl:for-each select="/ns1:ProcessOracleSFDCItem/ns1:DataArea/ns5:OracleSFDCItem/ns5:OracleSFDCItemDetails">
            <ns14:sObject>
              <ns14:type>
                <xsl:text disable-output-escaping="no">Item__c</xsl:text>
              </ns14:type>
              <ns14:OraclePVSimId__c>
                <xsl:value-of select="ns4:ITEM_NUMBER"/>
              </ns14:OraclePVSimId__c>
              <ns14:Name>
                <xsl:value-of select="ns4:ITEM_NUMBER"/>
              </ns14:Name>
              <ns14:Active__c>
                <xsl:value-of select="dvm:lookupValue(&quot;ITEMSTATUS.dvm&quot;,&quot;Oracle&quot;,ns4:ITEM_STATUS_CODE,&quot;SFDC&quot;,&quot;false&quot;)"/>
              </ns14:Active__c>
              <ns14:Status__c>
                <xsl:value-of select="ns4:ITEM_STATUS_CODE"/>
              </ns14:Status__c>
              <ns14:Description__c>
                <xsl:value-of select="ns4:DESCRIPTION"/>
              </ns14:Description__c>
              <ns14:Item_ID__c>
                <xsl:value-of select="ns4:ITEM_NUMBER"/>
              </ns14:Item_ID__c>
              <ns14:Long_Description__c>
                <xsl:value-of select="ns4:LONG_DESCRIPTION"/>
              </ns14:Long_Description__c>
              <ns14:Item_Category_3__c>
                <xsl:value-of select="ns4:ITEM_CATEGORY3"/>
              </ns14:Item_Category_3__c>
              <ns14:Item_Category_2__c>
                <xsl:value-of select="ns4:ITEM_CATEGORY2"/>
              </ns14:Item_Category_2__c>
              <ns14:Item_Category_1__c>
                <xsl:value-of select="ns4:ITEM_CATEGORY1"/>
              </ns14:Item_Category_1__c>
              <ns14:Product_Type__c>
                <xsl:value-of select="ns4:PROD_TYPE"/>
              </ns14:Product_Type__c>
              <!-- <ns14:Item_Cost__c>
              <xsl:value-of select="ns4:ITEM_COST"/>
              </ns14:Item_Cost__c> -->
            </ns14:sObject>
      </xsl:for-each>
    </ns14:upsert>
  </xsl:template>
</xsl:stylesheet>