<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns0="http://www.sunpowercorp.com/SOAUtilityServices/CommonLoggingService/CommonLoggingService_BPEL" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:client="http://www.sunpowercorp.com/SunPowerApp/CommonErrorHandler/CommonErrorHandler_BPEL" xmlns:ns1="http://www.sunpowercorp.com/SunPowerDevelopment/utility/CommonErrorHandler/xsd/V1" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl plnk xsd wsdl client ns1 ns0 bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref ora socket ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../CommonErrorHandler_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CommonErrorHandlerInput" namespace="http://www.sunpowercorp.com/SunPowerDevelopment/utility/CommonErrorHandler/xsd/V1"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7003/soa-infra/services/default/CommonLoggingService/CommonLoggingService_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="process" namespace="http://www.sunpowercorp.com/SOAUtilityServices/CommonLoggingService/CommonLoggingService_BPEL"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE OCT 04 11:20:15 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns0:process>
      <xsl:value-of select="/ns1:CommonErrorHandlerInput"/>
      <ns0:faultmessage>
        <xsl:value-of select="/ns1:CommonErrorHandlerInput/ns1:Fault/ns1:FaultMessage"/>
      </ns0:faultmessage>
      <ns0:faultcode>
        <xsl:value-of select="/ns1:CommonErrorHandlerInput/ns1:Fault/ns1:FaultCode"/>
      </ns0:faultcode>
      <ns0:faulttime>
        <xsl:value-of select="/ns1:CommonErrorHandlerInput/ns1:Fault/ns1:FaultTime"/>
      </ns0:faulttime>
      <ns0:faultdescription>
        <xsl:value-of select="/ns1:CommonErrorHandlerInput/ns1:Fault/ns1:FaultDescription"/>
      </ns0:faultdescription>
      <ns0:correctiveaction>
        <xsl:value-of select="/ns1:CommonErrorHandlerInput/ns1:CorrectiveAction"/>
      </ns0:correctiveaction>
      <ns0:interfacenumber>
        <xsl:value-of select="/ns1:CommonErrorHandlerInput/ns1:InterfaceNumber"/>
      </ns0:interfacenumber>
      <ns0:interfacename>
        <xsl:value-of select="/ns1:CommonErrorHandlerInput/ns1:InterfaceName"/>
      </ns0:interfacename>
      <ns0:instancenumber>
        <xsl:value-of select="/ns1:CommonErrorHandlerInput/ns1:InstanceNumber"/>
      </ns0:instancenumber>
      <ns0:processname>
        <xsl:value-of select="/ns1:CommonErrorHandlerInput/ns1:ProcessName"/>
      </ns0:processname>
      <ns0:bopenserviceticket>
        <xsl:value-of select="/ns1:CommonErrorHandlerInput/ns1:bOpenServiceTicket"/>
      </ns0:bopenserviceticket>
      <ns0:severity>
        <xsl:value-of select="/ns1:CommonErrorHandlerInput/ns1:Severity"/>
      </ns0:severity>
      <ns0:faultsystemname>
        <xsl:value-of select="/ns1:CommonErrorHandlerInput/ns1:FaultSystemName"/>
      </ns0:faultsystemname>
      <ns0:status>
        <xsl:text disable-output-escaping="no">E</xsl:text>
      </ns0:status>
      <ns0:createddatetime>
        <xsl:value-of select="xp20:current-dateTime()"/>
      </ns0:createddatetime>
    </ns0:process>
  </xsl:template>
</xsl:stylesheet>