<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:ns5="http://www.sunpowercorp.com/Common/Dealer_PartnerCreditINFOTypes/V1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/DealerPartnerCreditDetalis/SyncCreditHoldOracleReq/SelectCreditHoldInfo" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessDealer_PartnerCreditINFO/V1" xmlns:ns2="http://www.sunpowercorp.com/Noun/Dealer_PartnerCreditINFO/V1" xmlns:ns3="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/SelectCreditHoldInfo" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns4="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://www.example.org/SyncCreditHoldPS/" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl tns plt wsdl db xsd ns5 ns1 ns2 ns3 soap ns4 ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SelectCreditHoldInfo.wsdl"/>
            <oracle-xsl-mapper:rootElement name="SelectCreditHoldInfoOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SelectCreditHoldInfo"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7004/SyncCreditHoldEBS/Proxy/SyncCreditHoldPS?wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessDealer_PartnerCreditINFO" namespace="http://www.sunpowercorp.com/BOD/ProcessDealer_PartnerCreditINFO/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE OCT 11 11:19:17 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns1:ProcessDealer_PartnerCreditINFO>
      <ns1:DataArea>
        <ns2:CreditLimit>
          <xsl:for-each select="/db:SelectCreditHoldInfoOutputCollection/db:SelectCreditHoldInfoOutput">
            <ns2:CreditLimitDetails>
              <ns5:AccountNumber>
                <xsl:value-of select="db:ACCOUNT_NUMBER"/>
              </ns5:AccountNumber>
              <ns5:AccountName>
                <xsl:value-of select="db:ACCOUNT_NAME"/>
              </ns5:AccountName>
              <ns5:CustAccountId>
                <xsl:value-of select="db:CUST_ACCOUNT_ID"/>
              </ns5:CustAccountId>
              <ns5:LastUpdateDate>
                <xsl:value-of select="db:LAST_UPDATE_DATE"/>
              </ns5:LastUpdateDate>
              <ns5:CreditHold>
                <xsl:value-of select="db:CREDIT_HOLD"/>
              </ns5:CreditHold>
              <ns5:CreditCheck>
                <xsl:value-of select="db:CREDIT_CHECKING"/>
              </ns5:CreditCheck>
              <ns5:Netterm>
                <xsl:value-of select="db:NetTerm"/>
              </ns5:Netterm>
            </ns2:CreditLimitDetails>
          </xsl:for-each>
        </ns2:CreditLimit>
      </ns1:DataArea>
    </ns1:ProcessDealer_PartnerCreditINFO>
  </xsl:template>
</xsl:stylesheet>