<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBJDEVResource/JDEVDBResources/UpdateAuditLogHeaders" name="UpdateAuditLogHeaders-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSBJDEVResource/JDEVDBResources/UpdateAuditLogHeaders" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBJDEVResource/JDEVDBResources/UpdateAuditLogHeaders" location="../JCAResources/UpdateAuditLogHeaders.wsdl"/>
  <binding name="UpdateAuditLogHeaders_ptt-binding" type="tns:UpdateAuditLogHeaders_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="update">
      <soap:operation soapAction="update"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="UpdateAuditLogHeaders-service">
    <port name="UpdateAuditLogHeaders-port" binding="tns:UpdateAuditLogHeaders_ptt-binding">
      <soap:address location="jca://eis/DB/SOACustom"/>
    </port>
  </service>
</definitions>