<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBJDEVResource/JDEVDBResources/ProcessAuditLogHeaders" name="ProcessAuditLogHeaders-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSBJDEVResource/JDEVDBResources/ProcessAuditLogHeaders" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBJDEVResource/JDEVDBResources/ProcessAuditLogHeaders" location="../JCAResources/ProcessAuditLogHeaders.wsdl"/>
  <binding name="ProcessAuditLogHeaders_ptt-binding" type="tns:ProcessAuditLogHeaders_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="insert">
      <soap:operation soapAction="insert"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="ProcessAuditLogHeaders-service">
    <port name="ProcessAuditLogHeaders-port" binding="tns:ProcessAuditLogHeaders_ptt-binding">
      <soap:address location="jca://eis/DB/SOACustom"/>
    </port>
  </service>
</definitions>