<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollVertexDataDetails" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns5="http://www.sunpowercorp.com/Noun/VertexDataFeed/V1" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns2="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessVertexDataFeedDetails/V1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns4="http://www.sunpowercorp.com/Common/VertexDataFeedDetailsCommonTypes/V1" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns3="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:ns0="http://www.sunpowercorp.com/OracleSFDCVertexDataLoadCanonical/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OracleSFDC_VertexDataLoad/OracleSFDCVertexDataLoadReq/PollVertexDataDetails" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl top plt wsdl tns xsd ns5 ns2 ns1 soap ns4 ns3 ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../PollVertexDataDetails.wsdl"/>
            <oracle-xsl-mapper:rootElement name="XxspwrGeoVertexStgCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollVertexDataDetails"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../OracleSFDCVertexDataLoadCanonical.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessVertexDataFeedDetails" namespace="http://www.sunpowercorp.com/BOD/ProcessVertexDataFeedDetails/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [WED OCT 05 18:56:11 IST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns1:ProcessVertexDataFeedDetails>
      <ns1:DataArea>
        <xsl:for-each select="/top:XxspwrGeoVertexStgCollection/top:XxspwrGeoVertexStg">
          <ns5:VertexDataFeedDetail>
            <ns4:GeoGRAPHY_ID>
              <xsl:value-of select="top:geographyId"/>
            </ns4:GeoGRAPHY_ID>
            <ns4:COUNTRY>
              <xsl:value-of select="top:country"/>
            </ns4:COUNTRY>
            <ns4:COUNTRY_CODE>
              <xsl:value-of select="top:countryCode"/>
            </ns4:COUNTRY_CODE>
            <ns4:CITY>
              <xsl:value-of select="top:city"/>
            </ns4:CITY>
            <ns4:COUNTY>
              <xsl:value-of select="top:county"/>
            </ns4:COUNTY>
            <ns4:STATE>
              <xsl:value-of select="top:state"/>
            </ns4:STATE>
            <ns4:POSTAL_CODE>
              <xsl:value-of select="top:postalCode"/>
            </ns4:POSTAL_CODE>
            <ns4:INTERFACE_STATUS>
              <xsl:value-of select="top:interfaceStatus"/>
            </ns4:INTERFACE_STATUS>
            <ns4:ERROR_MESSAGE>
              <xsl:value-of select="top:errorMessage"/>
            </ns4:ERROR_MESSAGE>
            <ns4:TRANSACTION_DATE>
              <xsl:value-of select="top:transactionDate"/>
            </ns4:TRANSACTION_DATE>
            <ns4:REQUEST_ID>
              <xsl:value-of select="top:requestId"/>
            </ns4:REQUEST_ID>
            <ns4:GEO_CREATED_BY>
              <xsl:value-of select="top:geoCreatedBy"/>
            </ns4:GEO_CREATED_BY>
            <ns4:GEO_CREATION_DATE>
              <xsl:value-of select="top:geoCreationDate"/>
            </ns4:GEO_CREATION_DATE>
            <ns4:GEO_LAST_UPDATED_BY>
              <xsl:value-of select="top:geoLastUpdatedBy"/>
            </ns4:GEO_LAST_UPDATED_BY>
            <ns4:GEO_LAST_UPDATE_DATE>
              <xsl:value-of select="top:geoLastUpdateDate"/>
            </ns4:GEO_LAST_UPDATE_DATE>
            <ns4:CREATED_BY>
              <xsl:value-of select="top:createdBy"/>
            </ns4:CREATED_BY>
            <ns4:CREATION_DATE>
              <xsl:value-of select="top:creationDate"/>
            </ns4:CREATION_DATE>
            <ns4:LAST_UPDATED_BY>
              <xsl:value-of select="top:lastUpdatedBy"/>
            </ns4:LAST_UPDATED_BY>
            <ns4:LAST_UPDATED_DATE>
              <xsl:value-of select="top:lastUpdateDate"/>
            </ns4:LAST_UPDATED_DATE>
          </ns5:VertexDataFeedDetail>
        </xsl:for-each>
      </ns1:DataArea>
    </ns1:ProcessVertexDataFeedDetails>
  </xsl:template>
</xsl:stylesheet>