<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns8="http://www.sunpowercorp.com/Common/ArenaOracleDataFeedDetailsCommonTypes/V1" xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:ns0="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesCanonical" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns1="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/SunPowerDevelopment/ArenaOracleItemsBOMSubstituesReq/getFilesFromSunExchange" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns2="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:imp1="http://www.sunpowercorp.com/ArenaOracleDataFeed/ProductDataeXchangePackage/xsd/v1" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:ns6="http://www.sunpowercorp.com/BOD/ProcessArenaOracleDataFeed/V1" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns7="http://www.sunpowercorp.com/Noun/ArenaOracleDataFeed/V1" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl pc plt wsdl tns imp1 jca xsd ns8 ns0 ns1 soap ns2 ns6 ns7 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../readFilesFromArenaDir.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProductDataeXchangePackage" namespace="http://www.sunpowercorp.com/ArenaOracleDataFeed/ProductDataeXchangePackage/xsd/v1"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7004/ArenaOracleItemsBOMSubstituesSvc/Proxy/ArenaOracleItemsBOMSubstituesPS?wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessArenaOracleDataFeed" namespace="http://www.sunpowercorp.com/BOD/ProcessArenaOracleDataFeed/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE OCT 04 15:40:35 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="ProductDataeXchangePackage">
    <ns6:ProcessArenaOracleDataFeed>
      <ns1:ApplicationArea>
        <ns1:FileInfo>
          <ns1:sourceFileName>
            <xsl:text disable-output-escaping="no"/>
          </ns1:sourceFileName>
          <ns1:TargetFileName>
            <xsl:text disable-output-escaping="no"/>
          </ns1:TargetFileName>
          <ns1:InboundDir>
            <xsl:text disable-output-escaping="no"/>
          </ns1:InboundDir>
          <ns1:SuccessDir>
            <xsl:text disable-output-escaping="no"/>
          </ns1:SuccessDir>
          <ns1:ErrorDir>
            <xsl:text disable-output-escaping="no"/>
          </ns1:ErrorDir>
        </ns1:FileInfo>
      </ns1:ApplicationArea>
      <ns6:DataArea>
        <ns7:ArenaOracleDataFeed>
          <ns7:ArenaOracleDataFeedDetails>
            <xsl:attribute name="ns8:thisDocumentIdentifier">
              <xsl:value-of select="./@thisDocumentIdentifier"/>
            </xsl:attribute>            
             <xsl:attribute name="ns8:thisDocumentGenerationDateTime">
              <xsl:value-of select="./@thisDocumentGenerationDateTime"/>
            </xsl:attribute>
            <xsl:attribute name="ns8:thisDocumentModificationDateTime">
              <xsl:value-of select="./@thisDocumentModificationDateTime"/>
            </xsl:attribute>
            <xsl:attribute name="ns8:originatedByContactName">
              <xsl:value-of select="./@originatedByContactName"/>
            </xsl:attribute>
            <xsl:attribute name="ns8:packageType">
              <xsl:value-of select="./@packageType"/>
            </xsl:attribute>
            <xsl:attribute name="ns8:dataSource">
              <xsl:value-of select="./@dataSource"/>
            </xsl:attribute>
            <xsl:attribute name="ns8:thisDocumentCopyright">
              <xsl:value-of select="./@thisDocumentCopyright"/>
            </xsl:attribute>
            <ns7:Items>
              <xsl:for-each select="./Items/Item">
                <ns7:Item>
                  <xsl:if test="@itemIdentifier">
                    <xsl:attribute name="itemIdentifier">
                      <xsl:value-of select="@itemIdentifier"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@itemUniqueIdentifier">
                    <xsl:attribute name="ns8:itemUniqueIdentifier">
                      <xsl:value-of select="@itemUniqueIdentifier"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@globalLifeCyclePhaseCode">
                    <xsl:attribute name="ns8:globalLifeCyclePhaseCode">
                      <xsl:value-of select="@globalLifeCyclePhaseCode"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@globalLifeCyclePhaseCodeOther">
                    <xsl:attribute name="ns8:globalLifeCyclePhaseCodeOther">
                      <xsl:value-of select="@globalLifeCyclePhaseCodeOther"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@revisionIdentifier">
                    <xsl:attribute name="ns8:revisionIdentifier">
                      <xsl:value-of select="@revisionIdentifier"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@proprietaryProductFamily">
                    <xsl:attribute name="ns8:proprietaryProductFamily">
                      <xsl:value-of select="@proprietaryProductFamily"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@category">
                    <xsl:attribute name="ns8:category">
                      <xsl:value-of select="@category"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@globalProductUnitOfMeasureCode">
                    <xsl:attribute name="ns8:globalProductUnitOfMeasureCode">
                      <xsl:value-of select="@globalProductUnitOfMeasureCode"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@revisionReleasedDate">
                    <xsl:attribute name="ns8:revisionReleasedDate">
                      <xsl:value-of select="@revisionReleasedDate"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@ownerName">
                    <xsl:attribute name="ns8:ownerName">
                      <xsl:value-of select="@ownerName"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@isTopLevel">
                    <xsl:attribute name="ns8:isTopLevel">
                      <xsl:value-of select="@isTopLevel"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@description">
                    <xsl:attribute name="ns8:description">
                      <xsl:value-of select="@description"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:for-each select="AdditionalAttributes">
                    <ns7:AdditionalAttributes>
                      <xsl:if test="@groupLabel">
                        <xsl:attribute name="groupLabel">
                          <xsl:value-of select="@groupLabel"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:for-each select="AdditionalAttribute">
                        <ns7:AdditionalAttribute>
                          <xsl:if test="@name">
                            <xsl:attribute name="ns8:name">
                              <xsl:value-of select="@name"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="@value">
                            <xsl:attribute name="ns8:value">
                              <xsl:value-of select="@value"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="@dataType">
                            <xsl:attribute name="ns8:dataType">
                              <xsl:value-of select="@dataType"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="@dimension">
                            <xsl:attribute name="ns8:dimension">
                              <xsl:value-of select="@dimension"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="@description">
                            <xsl:attribute name="ns8:description">
                              <xsl:value-of select="@description"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:value-of select="."/>
                        </ns7:AdditionalAttribute>
                      </xsl:for-each>
                    </ns7:AdditionalAttributes>
                  </xsl:for-each>
                  <xsl:if test="BillOfMaterial">
                    <ns7:BillOfMaterial>
                      <xsl:for-each select="BillOfMaterial/BillOfMaterialItem">
                        <ns7:BillOfMaterialItem>
                          <xsl:if test="@revisionIdentifier">
                            <xsl:attribute name="ns8:revisionIdentifier">
                              <xsl:value-of select="@revisionIdentifier"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="@billOfMaterialItemIdentifier">
                            <xsl:attribute name="ns8:billOfMaterialItemIdentifier">
                              <xsl:value-of select="@billOfMaterialItemIdentifier"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="@billOfMaterialItemUniqueIdentifier">
                            <xsl:attribute name="ns8:billOfMaterialItemUniqueIdentifier">
                              <xsl:value-of select="@billOfMaterialItemUniqueIdentifier"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="@itemQuantity">
                            <xsl:attribute name="ns8:itemQuantity">
                              <xsl:value-of select="@itemQuantity"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="@globalProductQuantityTypeCode">
                            <xsl:attribute name="ns8:globalProductQuantityTypeCode">
                              <xsl:value-of select="@globalProductQuantityTypeCode"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="@globalProductQuantityTypeCodeOther">
                            <xsl:attribute name="ns8:globalProductQuantityTypeCodeOther">
                              <xsl:value-of select="@globalProductQuantityTypeCodeOther"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="@notes">
                            <xsl:attribute name="ns8:notes">
                              <xsl:value-of select="@notes"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="@description">
                            <xsl:attribute name="ns8:description">
                              <xsl:value-of select="@description"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="@proprietarySequenceIdentifier">
                            <xsl:attribute name="ns8:proprietarySequenceIdentifier">
                              <xsl:value-of select="@proprietarySequenceIdentifier"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="AlternateItems">
                            <ns7:AlternateItems>
                              <xsl:for-each select="AlternateItems/AlternateItem">
                                <ns7:AlternateItem>
                                  <xsl:if test="@itemIdentifier">
                                    <xsl:attribute name="ns8:itemIdentifier">
                                      <xsl:value-of select="@itemIdentifier"/>
                                    </xsl:attribute>
                                  </xsl:if>
                                  <xsl:if test="@itemUniqueIdentifier">
                                    <xsl:attribute name="ns8:itemUniqueIdentifier">
                                      <xsl:value-of select="@itemUniqueIdentifier"/>
                                    </xsl:attribute>
                                  </xsl:if>
                                  <xsl:if test="@globalPreferredStatusCode">
                                    <xsl:attribute name="ns8:globalPreferredStatusCode">
                                      <xsl:value-of select="@globalPreferredStatusCode"/>
                                    </xsl:attribute>
                                  </xsl:if>
                                  <ns7:AdditionalAttributes>
                                    <xsl:if test="AdditionalAttributes/@groupLabel">
                                      <xsl:attribute name="groupLabel">
                                        <xsl:value-of select="AdditionalAttributes/@groupLabel"/>
                                      </xsl:attribute>
                                    </xsl:if>
                                    <xsl:for-each select="AdditionalAttributes/AdditionalAttribute">
                                      <ns7:AdditionalAttribute>
                                        <xsl:if test="@name">
                                          <xsl:attribute name="ns8:name">
                                            <xsl:value-of select="@name"/>
                                          </xsl:attribute>
                                        </xsl:if>
                                        <xsl:if test="@value">
                                          <xsl:attribute name="ns8:value">
                                            <xsl:value-of select="@value"/>
                                          </xsl:attribute>
                                        </xsl:if>
                                        <xsl:if test="@dataType">
                                          <xsl:attribute name="ns8:dataType">
                                            <xsl:value-of select="@dataType"/>
                                          </xsl:attribute>
                                        </xsl:if>
                                        <xsl:value-of select="."/>
                                      </ns7:AdditionalAttribute>
                                    </xsl:for-each>
                                  </ns7:AdditionalAttributes>
                                </ns7:AlternateItem>
                              </xsl:for-each>
                            </ns7:AlternateItems>
                          </xsl:if>
                          <xsl:for-each select="AdditionalAttributes">
                            <ns7:AdditionalAttributes>
                              <xsl:if test="@groupLabel">
                                <xsl:attribute name="groupLabel">
                                  <xsl:value-of select="@groupLabel"/>
                                </xsl:attribute>
                              </xsl:if>
                              <xsl:for-each select="AdditionalAttribute">
                                <ns7:AdditionalAttribute>
                                  <xsl:if test="@name">
                                    <xsl:attribute name="ns8:name">
                                      <xsl:value-of select="@name"/>
                                    </xsl:attribute>
                                  </xsl:if>
                                  <xsl:if test="@value">
                                    <xsl:attribute name="ns8:value">
                                      <xsl:value-of select="@value"/>
                                    </xsl:attribute>
                                  </xsl:if>
                                  <xsl:if test="@dataType">
                                    <xsl:attribute name="ns8:dataType">
                                      <xsl:value-of select="@dataType"/>
                                    </xsl:attribute>
                                  </xsl:if>
                                  <xsl:value-of select="."/>
                                </ns7:AdditionalAttribute>
                              </xsl:for-each>
                            </ns7:AdditionalAttributes>
                          </xsl:for-each>
                        </ns7:BillOfMaterialItem>
                      </xsl:for-each>
                    </ns7:BillOfMaterial>
                  </xsl:if>
                  <xsl:if test="ApprovedManufacturerList">
                    <ns7:ApprovedManufacturerList>
                      <xsl:for-each select="ApprovedManufacturerList/ApprovedManufacturerListItem">
                        <ns7:ApprovedManufacturerListItem>
                          <xsl:if test="@manufacturerPartIdentifier">
                            <xsl:attribute name="ns8:manufacturerPartIdentifier">
                              <xsl:value-of select="@manufacturerPartIdentifier"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="@manufacturerPartUniqueIdentifier">
                            <xsl:attribute name="ns8:manufacturerPartUniqueIdentifier">
                              <xsl:value-of select="@manufacturerPartUniqueIdentifier"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="@manufacturerContactUniqueIdentifier">
                            <xsl:attribute name="ns8:manufacturerContactUniqueIdentifier">
                              <xsl:value-of select="@manufacturerContactUniqueIdentifier"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="@globalManufacturerPartStatusCode">
                            <xsl:attribute name="ns8:globalManufacturerPartStatusCode">
                              <xsl:value-of select="@globalManufacturerPartStatusCode"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="@description">
                            <xsl:attribute name="ns8:description">
                              <xsl:value-of select="@description"/>
                            </xsl:attribute>
                          </xsl:if>
                          <xsl:if test="@manufacturedBy">
                            <xsl:attribute name="ns8:manufacturedBy">
                              <xsl:value-of select="@manufacturedBy"/>
                            </xsl:attribute>
                          </xsl:if>
                          <ns7:AdditionalAttributes>
                            <xsl:if test="AdditionalAttributes/@groupLabel">
                              <xsl:attribute name="groupLabel">
                                <xsl:value-of select="AdditionalAttributes/@groupLabel"/>
                              </xsl:attribute>
                            </xsl:if>
                            <xsl:for-each select="AdditionalAttributes/AdditionalAttribute">
                              <ns7:AdditionalAttribute>
                                <xsl:attribute name="ns8:name">
                                  <xsl:value-of select="@name"/>
                                </xsl:attribute>
                                <xsl:attribute name="ns8:value">
                                  <xsl:value-of select="@value"/>
                                </xsl:attribute>
                                <xsl:if test="../../ApprovedManufacturerList/ApprovedManufacturerListItem/AdditionalAttributes/AdditionalAttribute/@dataType">
                                  <xsl:attribute name="ns8:dataType">
                                    <xsl:value-of select="../../ApprovedManufacturerList/ApprovedManufacturerListItem/AdditionalAttributes/AdditionalAttribute/@dataType"/>
                                  </xsl:attribute>
                                </xsl:if>
                                <xsl:if test="@dimension">
                                  <xsl:attribute name="ns8:dimension">
                                    <xsl:value-of select="@dimension"/>
                                  </xsl:attribute>
                                </xsl:if>
                                <xsl:if test="@description">
                                  <xsl:attribute name="ns8:description">
                                    <xsl:value-of select="@description"/>
                                  </xsl:attribute>
                                </xsl:if>
                                <xsl:value-of select="../../ApprovedManufacturerList/ApprovedManufacturerListItem/AdditionalAttributes/AdditionalAttribute"/>
                              </ns7:AdditionalAttribute>
                            </xsl:for-each>
                          </ns7:AdditionalAttributes>
                        </ns7:ApprovedManufacturerListItem>
                      </xsl:for-each>
                    </ns7:ApprovedManufacturerList>
                  </xsl:if>
                </ns7:Item>
              </xsl:for-each>
            </ns7:Items>
            <ns7:ManufacturerParts>
              <xsl:for-each select="./ManufacturerParts/ManufacturerPart">
                <ns7:ManufacturerPart>
                  <xsl:if test="@manufacturerPartIdentifier">
                    <xsl:attribute name="ns8:manufacturerPartIdentifier">
                      <xsl:value-of select="@manufacturerPartIdentifier"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@manufacturerPartUniqueIdentifier">
                    <xsl:attribute name="ns8:manufacturerPartUniqueIdentifier">
                      <xsl:value-of select="@manufacturerPartUniqueIdentifier"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@manufacturerName">
                    <xsl:attribute name="ns8:manufacturerName">
                      <xsl:value-of select="@manufacturerName"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@manufacturerContactUniqueIdentifier">
                    <xsl:attribute name="ns8:manufacturerContactUniqueIdentifier">
                      <xsl:value-of select="@manufacturerContactUniqueIdentifier"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@referenceNotes">
                    <xsl:attribute name="ns8:referenceNotes">
                      <xsl:value-of select="@referenceNotes"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@manufacturerPartType">
                    <xsl:attribute name="ns8:manufacturerPartType">
                      <xsl:value-of select="@manufacturerPartType"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@description">
                    <xsl:attribute name="ns8:description">
                      <xsl:value-of select="@description"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@isTopLevel">
                    <xsl:attribute name="ns8:isTopLevel">
                      <xsl:value-of select="@isTopLevel"/>
                    </xsl:attribute>
                  </xsl:if>
                  <ns7:ApprovedSupplierList>
                    <xsl:for-each select="ApprovedSupplierList/ApprovedSupplierListItem">
                      <ns7:ApprovedSupplierListItem>
                        <xsl:if test="@supplierPartIdentifier">
                          <xsl:attribute name="ns8:supplierPartIdentifier">
                            <xsl:value-of select="@supplierPartIdentifier"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="@supplierPartUniqueIdentifier">
                          <xsl:attribute name="ns8:supplierPartUniqueIdentifier">
                            <xsl:value-of select="@supplierPartUniqueIdentifier"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="@supplierPartContactUniqueIdentifier">
                          <xsl:attribute name="ns8:supplierPartContactUniqueIdentifier">
                            <xsl:value-of select="@supplierPartContactUniqueIdentifier"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="@globalSupplierPartStatusCode">
                          <xsl:attribute name="ns8:globalSupplierPartStatusCode">
                            <xsl:value-of select="@globalSupplierPartStatusCode"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="@comments">
                          <xsl:attribute name="ns8:comments">
                            <xsl:value-of select="@comments"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:if test="@suppliedBy">
                          <xsl:attribute name="ns8:suppliedBy">
                            <xsl:value-of select="@suppliedBy"/>
                          </xsl:attribute>
                        </xsl:if>
                        <xsl:value-of select="."/>
                      </ns7:ApprovedSupplierListItem>
                    </xsl:for-each>
                  </ns7:ApprovedSupplierList>
                </ns7:ManufacturerPart>
              </xsl:for-each>
            </ns7:ManufacturerParts>
            <ns7:SupplierParts>
              <xsl:for-each select="./SupplierParts/SupplierPart">
                <ns7:SupplierPart>
                  <xsl:if test="@supplierPartIdentifier">
                    <xsl:attribute name="ns8:supplierPartIdentifier">
                      <xsl:value-of select="@supplierPartIdentifier"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@supplierPartUniqueIdentifier">
                    <xsl:attribute name="ns8:supplierPartUniqueIdentifier">
                      <xsl:value-of select="@supplierPartUniqueIdentifier"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@supplierName">
                    <xsl:attribute name="ns8:supplierName">
                      <xsl:value-of select="@supplierName"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@supplierContactUniqueIdentifier">
                    <xsl:attribute name="ns8:supplierContactUniqueIdentifier">
                      <xsl:value-of select="@supplierContactUniqueIdentifier"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@referenceNotes">
                    <xsl:attribute name="ns8:referenceNotes">
                      <xsl:value-of select="@referenceNotes"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@supplierPartType">
                    <xsl:attribute name="ns8:supplierPartType">
                      <xsl:value-of select="@supplierPartType"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@description">
                    <xsl:attribute name="ns8:description">
                      <xsl:value-of select="@description"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@isTopLevel">
                    <xsl:attribute name="ns8:isTopLevel">
                      <xsl:value-of select="@isTopLevel"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="."/>
                </ns7:SupplierPart>
              </xsl:for-each>
            </ns7:SupplierParts>
            <ns7:Contacts>
              <xsl:for-each select="./Contacts/Contact">
                <ns7:Contact>
                  <xsl:if test="@contactIdentifier">
                    <xsl:attribute name="ns8:contactIdentifier">
                      <xsl:value-of select="@contactIdentifier"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@contactUniqueIdentifier">
                    <xsl:attribute name="ns8:contactUniqueIdentifier">
                      <xsl:value-of select="@contactUniqueIdentifier"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@contactName">
                    <xsl:attribute name="ns8:contactName">
                      <xsl:value-of select="@contactName"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@addressLine2">
                    <xsl:attribute name="ns8:addressLine2">
                      <xsl:value-of select="@addressLine2"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@cityName">
                    <xsl:attribute name="ns8:cityName">
                      <xsl:value-of select="@cityName"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@regionName">
                    <xsl:attribute name="ns8:regionName">
                      <xsl:value-of select="@regionName"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@globalCountryCode">
                    <xsl:attribute name="ns8:globalCountryCode">
                      <xsl:value-of select="@globalCountryCode"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@nationalPostalCode">
                    <xsl:attribute name="ns8:nationalPostalCode">
                      <xsl:value-of select="@nationalPostalCode"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@telephoneNumber">
                    <xsl:attribute name="ns8:telephoneNumber">
                      <xsl:value-of select="@telephoneNumber"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@facsimileNumber">
                    <xsl:attribute name="ns8:facsimileNumber">
                      <xsl:value-of select="@facsimileNumber"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@department">
                    <xsl:attribute name="ns8:department">
                      <xsl:value-of select="@department"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@businessName">
                    <xsl:attribute name="ns8:businessName">
                      <xsl:value-of select="@businessName"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@emailAddress">
                    <xsl:attribute name="ns8:emailAddress">
                      <xsl:value-of select="@emailAddress"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@universalResourceIdentifier">
                    <xsl:attribute name="ns8:universalResourceIdentifier">
                      <xsl:value-of select="@universalResourceIdentifier"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@contactStatus">
                    <xsl:attribute name="ns8:contactStatus">
                      <xsl:value-of select="@contactStatus"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@isTopLevel">
                    <xsl:attribute name="ns8:isTopLevel">
                      <xsl:value-of select="@isTopLevel"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="@addressLine1">
                    <xsl:attribute name="ns8:addressLine1">
                      <xsl:value-of select="@addressLine1"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="."/>
                </ns7:Contact>
              </xsl:for-each>
            </ns7:Contacts>
          </ns7:ArenaOracleDataFeedDetails>
        </ns7:ArenaOracleDataFeed>
      </ns6:DataArea>
    </ns6:ProcessArenaOracleDataFeed>
  </xsl:template>
</xsl:stylesheet>