<wsdl:definitions name="CreateSalesOrderOracleProv" targetNamespace="http://xmlns.oracle.com/OnLineSalesOrder/CreateSalesOrderOracleProv/CreateSalesOrderOracleProv" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessOracleSFDCNoItemOrders/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:client="http://xmlns.oracle.com/OnLineSalesOrder/CreateSalesOrderOracleProv/CreateSalesOrderOracleProv" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
       <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://www.sunpowercorp.com/BOD/ProcessOracleSFDCNoItemOrders/V1" schemaLocation="../xsd/CDM/BOD/Nouns/OracleSFDCNoItemOrders/V1/ProcessOracleSFDCNoItemOrders.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="CreateSalesOrderOracleProvRequestMessage">
        <wsdl:part name="payload" element="ns1:ProcessOracleSFDCNoItemOrdersReq"/>
    </wsdl:message>
    <wsdl:portType name="CreateSalesOrderOracleProv">
        <wsdl:operation name="process">
            <wsdl:input message="client:CreateSalesOrderOracleProvRequestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CreateSalesOrderOracleProvBinding" type="client:CreateSalesOrderOracleProv">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="createsalesorderoracleprov_client_ep">
        <wsdl:port name="CreateSalesOrderOracleProv_pt" binding="client:CreateSalesOrderOracleProvBinding">
            <soap:address location="http://dev-fusappdca02.sunpowercorp.com:7003/soa-infra/services/online/CreateSalesOrderOracleProv/createsalesorderoracleprov_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>