<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ns0="http://www.sunpowercorp.com/Noun/ACBClaimToSFDC/V1" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns6="http://www.sunpowercorp.com/ACBAccountClaimToSFDCDetails" xmlns:ns8="http://www.sunpowercorp.com/Common/ACBClaimToSFDCCommonTypes/V1" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns9="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessACBClaimToSFDC/V1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns7="http://www.sunpowercorp.com/SunPowerDevelopment/DealerPartnerCreditINFO/EnqueSyncCreditHoldLimit/initParams/xsd/v1" xmlns:ns2="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:ens="urn:sobject.partner.soap.sforce.com" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns3="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns5="http://www.sunpowercorp.com/ACBClaimToSFDCMergeDetails" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:fns="urn:fault.partner.soap.sforce.com" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns4="http://www.sunpowercorp.com/ACBClaimToSFDCDetails" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:client="http://www.sunpowercorp.com/MarketingNTrainingActAppClmACBToSFDC/ACBGetAllClaimsmergeProv/ACBGetAllClaimsmergeProv_BPEL" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="urn:partner.soap.sforce.com" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns0 ns6 ns8 ns9 plnk ns1 soap wsdl ns7 ns2 ens ns3 ns5 fns ns4 client xsd tns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/partner.wsdl"/>
            <oracle-xsl-mapper:rootElement name="queryResponse" namespace="urn:partner.soap.sforce.com"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/ACBGetAllClaimsmergeProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ACBAccountClaimToSFDCRows" namespace="http://www.sunpowercorp.com/ACBAccountClaimToSFDCDetails"/>
            <oracle-xsl-mapper:param name="ACBAccountClaim"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/partner.wsdl"/>
            <oracle-xsl-mapper:rootElement name="upsert" namespace="urn:partner.soap.sforce.com"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [FRI OCT 07 17:20:42 IST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="ACBAccountClaim"/>
  <xsl:template match="/">
    <tns:upsert>
      <tns:externalIDFieldName>
        <xsl:text disable-output-escaping="no">Id</xsl:text>
      </tns:externalIDFieldName>
      <xsl:for-each select="$ACBAccountClaim/ns6:ACBAccountClaimToSFDCRows/ns6:row">
        <xsl:variable name="InputRow" select="."/>
        <xsl:for-each select="/tns:queryResponse/tns:result/tns:records">
          <xsl:variable name="SFDCRow" select="."/>
          <xsl:if test="$InputRow/ns6:ACB_Paranet_ID__c = ens:ACBParanet_ID__c">
            <tns:sObjects>
              <ens:type>
                <xsl:text disable-output-escaping="no">MDTF_Claim__c</xsl:text>
              </ens:type>
              <ens:Account__c>
                <xsl:value-of select="ens:Id"/>
              </ens:Account__c>
              <ens:Promotion__c>
                <xsl:value-of select="$InputRow/ns6:Promotion__c"/>
              </ens:Promotion__c>
              <ens:Process_Date__c>
                <xsl:value-of select="$InputRow/ns6:Process_Date__c"/>
              </ens:Process_Date__c>
              <xsl:choose>
                <xsl:when test="$InputRow/ns6:Pre_Approval_Number__c = &quot;&quot;">
                  <ens:Pre_Approval_Number__c>
                    <xsl:text disable-output-escaping="no">0</xsl:text>
                  </ens:Pre_Approval_Number__c>
                </xsl:when>
                <xsl:otherwise>
                  <ens:Pre_Approval_Number__c>
                    <xsl:value-of select="$InputRow/ns6:Pre_Approval_Number__c"/>
                  </ens:Pre_Approval_Number__c>
                </xsl:otherwise>
              </xsl:choose>
              <ens:Claim_Number__c>
                <xsl:value-of select="$InputRow/ns6:Claim_Number__c"/>
              </ens:Claim_Number__c>
              <ens:Activity_Description__c>
                <xsl:value-of select="$InputRow/ns6:Acitivity_Description__c"/>
              </ens:Activity_Description__c>
              <ens:Activity_from_Date__c>
                <xsl:value-of select="$InputRow/ns6:Activity_from_Date__c"/>
              </ens:Activity_from_Date__c>
              <ens:Activity_to_Date__c>
                <xsl:value-of select="$InputRow/ns6:Activity_to_Date__c"/>
              </ens:Activity_to_Date__c>
              <xsl:choose>
                <xsl:when test="$InputRow/ns6:Claimed_Amt__c = &quot;&quot;">
                  <ens:Claimed_Amt__c>
                    <xsl:text disable-output-escaping="no">0</xsl:text>
                  </ens:Claimed_Amt__c>
                </xsl:when>
                <xsl:otherwise>
                  <ens:Claimed_Amt__c>
                    <xsl:value-of select="$InputRow/ns6:Claimed_Amt__c"/>
                  </ens:Claimed_Amt__c>
                </xsl:otherwise>
              </xsl:choose>
              <xsl:choose>
                <xsl:when test="$InputRow/ns6:Approved_Amt__c = &quot;&quot;">
                  <ens:Approved_Amt__c>
                    <xsl:text disable-output-escaping="no">0</xsl:text>
                  </ens:Approved_Amt__c>
                </xsl:when>
                <xsl:otherwise>
                  <ens:Approved_Amt__c>
                    <xsl:value-of select="$InputRow/ns6:Approved_Amt__c"/>
                  </ens:Approved_Amt__c>
                </xsl:otherwise>
              </xsl:choose>
              <xsl:choose>
                <xsl:when test="$InputRow/ns6:Paid_Amt__c = &quot;&quot;">
                  <ens:Paid_Amt__c>
                    <xsl:text disable-output-escaping="no">0</xsl:text>
                  </ens:Paid_Amt__c>
                </xsl:when>
                <xsl:otherwise>
                  <ens:Paid_Amt__c>
                    <xsl:value-of select="$InputRow/ns6:Paid_Amt__c"/>
                  </ens:Paid_Amt__c>
                </xsl:otherwise>
              </xsl:choose>
              <ens:Credit_Memo__c>
                <xsl:value-of select="$InputRow/ns6:Credit_Memo__c"/>
              </ens:Credit_Memo__c>
              <ens:Comment__c>
                <xsl:value-of select="$InputRow/ns6:Comment__c"/>
              </ens:Comment__c>
              <ens:ACBParanet_ID__c>
                <xsl:value-of select="ens:ACBParanet_ID__c"/>
              </ens:ACBParanet_ID__c>
            </tns:sObjects>
          </xsl:if>
        </xsl:for-each>
      </xsl:for-each>
    </tns:upsert>
  </xsl:template>
</xsl:stylesheet>