<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:ns3="http://www.sunpowercorp.com/Noun/SyncAccCustomers/V1" xmlns:ns6="http://xmlns.oracle.com/SFDCUtilityService/SFDCUtilityService" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:tns="http://xmlns.oracle.com/SFDCUtilityService/SFDCUtilityServiceMediator" xmlns:ns0="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:client="http://xmlns.oracle.com/TPOSOACustomerSync/CreateUpdateCustomerOracleProv/CreateUpdateCustomerOracleProv" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns4="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns2="http://www.sunpowercorp.com/SFDCSyncLeaseCustomerReq/xsd/v1" xmlns:ns5="http://www.sunpowercorp.com/Common/SyncAccCustCommonTypes/V1" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessSFDCSyncCust/V1" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns3 ns0 plnk wsdl client ns4 ns2 ns5 xsd ns1 ns6 tns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/CreateUpdateCustomerOracleProv.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessSFDCSyncCust" namespace="http://www.sunpowercorp.com/BOD/ProcessSFDCSyncCust/V1"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7003/soa-infra/services/default/SFDCUtilityService!1.0/SFDCUtilityServiceMediator.wsdl"/>
            <oracle-xsl-mapper:rootElement name="update" namespace="http://xmlns.oracle.com/SFDCUtilityService/SFDCUtilityService"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [FRI OCT 07 15:38:37 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns6:update>
      <ns6:CallingServiceName>
        <xsl:text disable-output-escaping="no">CreateUpdateCustomerOracleProv</xsl:text>
      </ns6:CallingServiceName>
      <xsl:for-each select="/ns1:ProcessSFDCSyncCust/ns1:DataArea/ns3:SyncAccCustomers/ns3:Accounts/ns3:Account[(ns5:TRANSACTION_STATUS != 'SKIP')]">
        <ns6:sObject>
          <ns6:type>
            <xsl:text disable-output-escaping="no">Account</xsl:text>
          </ns6:type>
          <ns6:Id>
            <xsl:value-of select="ns5:SFDC_ACCOUNT_ID"/>
          </ns6:Id>
          <ns6:Interface_Status__c>
            <xsl:text disable-output-escaping="no">Sent to Oracle</xsl:text>
          </ns6:Interface_Status__c>
        </ns6:sObject>
      </xsl:for-each>
      <xsl:for-each select="/ns1:ProcessSFDCSyncCust/ns1:DataArea/ns3:SyncAccCustomers/ns3:Accounts/ns3:Account/ns3:CustSites/ns3:CustSite[(ns5:SITE_USAGE = &quot;BILL_TO&quot;) and (ns5:SFDC_BILLTO_SITE_ID != &quot;&quot;) and (ns5:TRANSACTION_STATUS != &quot;SKIP&quot;)]">
        <ns6:sObject>
          <ns6:type>
            <xsl:text disable-output-escaping="no">Bill_To_Site__c</xsl:text>
          </ns6:type>
          <ns6:Id>
            <xsl:value-of select="ns5:SFDC_BILLTO_SITE_ID"/>
          </ns6:Id>
          <ns6:Interface_Status__c>
            <xsl:text disable-output-escaping="no">Sent to Oracle</xsl:text>
          </ns6:Interface_Status__c>
        </ns6:sObject>
      </xsl:for-each>
      <xsl:for-each select="/ns1:ProcessSFDCSyncCust/ns1:DataArea/ns3:SyncAccCustomers/ns3:Accounts/ns3:Account/ns3:CustSites/ns3:CustSite[(ns5:SITE_USAGE = 'SHIP_TO') and (ns5:SFDC_SHIPTO_SITE_ID != '') and (ns5:TRANSACTION_STATUS != 'SKIP')]">
        <ns6:sObject>
          <ns6:type>
            <xsl:text disable-output-escaping="no">Ship_to_Site__c</xsl:text>
          </ns6:type>
          <ns6:Id>
            <xsl:value-of select="ns5:SFDC_SHIPTO_SITE_ID"/>
          </ns6:Id>
          <ns6:Interface_Status__c>
            <xsl:text disable-output-escaping="no">Sent to Oracle</xsl:text>
          </ns6:Interface_Status__c>
        </ns6:sObject>
      </xsl:for-each>
      <xsl:for-each select="/ns1:ProcessSFDCSyncCust/ns1:DataArea/ns3:SyncAccCustomers/ns3:Accounts/ns3:Account/ns3:Contacts/ns3:Contact[(ns5:TRANSACTION_STATUS != 'SKIP')]">
        <ns6:sObject>
          <ns6:type>
            <xsl:text disable-output-escaping="no">Contact</xsl:text>
          </ns6:type>
          <ns6:Id>
            <xsl:value-of select="ns5:SFDC_CONTACT_ID"/>
          </ns6:Id>
          <ns6:Interface_Status__c>
            <xsl:text disable-output-escaping="no">Sent to Oracle</xsl:text>
          </ns6:Interface_Status__c>
        </ns6:sObject>
      </xsl:for-each>
      <xsl:for-each select="/ns1:ProcessSFDCSyncCust/ns1:DataArea/ns3:SyncAccCustomers/ns3:CustSites/ns3:CustSite[(ns5:SITE_USAGE = &quot;BILL_TO&quot;) and (ns5:SFDC_BILLTO_SITE_ID != &quot;&quot;) and (ns5:TRANSACTION_STATUS != &quot;SKIP&quot;)]">
        <ns6:sObject>
          <ns6:type>
            <xsl:text disable-output-escaping="no">Bill_To_Site__c</xsl:text>
          </ns6:type>
          <ns6:Id>
            <xsl:value-of select="ns5:SFDC_BILLTO_SITE_ID"/>
          </ns6:Id>
          <ns6:Interface_Status__c>
            <xsl:text disable-output-escaping="no">Sent to Oracle</xsl:text>
          </ns6:Interface_Status__c>
        </ns6:sObject>
      </xsl:for-each>
      <xsl:for-each select="/ns1:ProcessSFDCSyncCust/ns1:DataArea/ns3:SyncAccCustomers/ns3:CustSites/ns3:CustSite[(ns5:SITE_USAGE = 'SHIP_TO') and (ns5:SFDC_SHIPTO_SITE_ID != '') and (ns5:TRANSACTION_STATUS != 'SKIP')]">
        <ns6:sObject>
          <ns6:type>
            <xsl:text disable-output-escaping="no">Ship_to_Site__c</xsl:text>
          </ns6:type>
          <ns6:Id>
            <xsl:value-of select="ns5:SFDC_SHIPTO_SITE_ID"/>
          </ns6:Id>
          <ns6:Interface_Status__c>
            <xsl:text disable-output-escaping="no">Sent to Oracle</xsl:text>
          </ns6:Interface_Status__c>
        </ns6:sObject>
      </xsl:for-each>
      <xsl:for-each select="/ns1:ProcessSFDCSyncCust/ns1:DataArea/ns3:SyncAccCustomers/ns3:Contacts/ns3:Contact[(ns5:TRANSACTION_STATUS != 'SKIP')]">
        <ns6:sObject>
          <ns6:type>
            <xsl:text disable-output-escaping="no">Contact</xsl:text>
          </ns6:type>
          <ns6:Id>
            <xsl:value-of select="ns5:SFDC_CONTACT_ID"/>
          </ns6:Id>
          <ns6:Interface_Status__c>
            <xsl:text disable-output-escaping="no">Sent to Oracle</xsl:text>
          </ns6:Interface_Status__c>
        </ns6:sObject>
      </xsl:for-each>
    </ns6:update>
  </xsl:template>
</xsl:stylesheet>