<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="SunPowerStoreSFDCProv_BPEL"
     targetNamespace="http://www.sunpowercorp.com/SunPowerStoreONFToSFDC/SunPowerStoreSFDCProv/SunPowerStoreSFDCProv_BPEL"
     xmlns:ns2="http://schemas.xmlsoap.org/ws/2003/03/addressing"
     xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessSunPowerStoreONFToSFDC/V1"
     xmlns:ns4="http://www.sunpowercorp.com/SFDCIDs/xsd/v1"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:ns3="urn:partner.soap.sforce.com"
     xmlns:client="http://www.sunpowercorp.com/SunPowerStoreONFToSFDC/SunPowerStoreSFDCProv/SunPowerStoreSFDCProv_BPEL"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="SunPowerStoreSFDCProv_BPEL">
        <plnk:role name="SunPowerStoreSFDCProv_BPELProvider">
            <plnk:portType name="client:SunPowerStoreSFDCProv_BPEL"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="urn:partner.soap.sforce.com" location="partner.wsdl"/>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://www.sunpowercorp.com/BOD/ProcessSunPowerStoreONFToSFDC/V1"
                 schemaLocation="../Schemas/CDM/BOD/Nouns/SunPowerStoreONFToSFDC/V1/ProcessSunPowerStoreONFToSFDC.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                        schemaLocation="../Schemas/wsaaddress.xsd"/>
        </xsd:schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.sunpowercorp.com/SFDCIDs/xsd/v1" schemaLocation="../Schemas/SFDCIDs.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="SunPowerStoreSFDCProv_BPELRequestMessage">
        <wsdl:part name="payload" element="ns1:ProcessSunPowerStoreONFToSFDC"/>
    </wsdl:message>
    <wsdl:portType name="SunPowerStoreSFDCProv_BPEL">
        <wsdl:operation name="process">
            <wsdl:input message="client:SunPowerStoreSFDCProv_BPELRequestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
