<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/OSG/PublishARSupplPaymntReversalsOracleToOSG/WriteOSGSupplPaymntReversalsFeedToLocal" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:imp1="http://TargetNamespace.com/WriteOSGSupplPaymntReversalsFeedToLocal" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:client="http://xmlns.oracle.com/OSG/PublishARSupplPaymntReversalsOracleToOSG/PublishARSupplPaymntReversalsOracleToOSG_BPEL" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl plnk xsd wsdl client tns jca imp1 bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref ora socket ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/PublishARSupplPaymntReversalsOracleToOSG_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="process" namespace="http://xmlns.oracle.com/OSG/PublishARSupplPaymntReversalsOracleToOSG/PublishARSupplPaymntReversalsOracleToOSG_BPEL"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/WriteOSGSupplPaymntReversalsFeedToLocal.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OSGSupplPaymntReversals" namespace="http://TargetNamespace.com/WriteOSGSupplPaymntReversalsFeedToLocal"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU OCT 06 19:31:45 IST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <imp1:OSGSupplPaymntReversals>
      <imp1:OSGSupplPaymntReversalsFeed>
        <imp1:ACCOUNT_NUMBER>
          <xsl:text disable-output-escaping="no">ACCOUNT_NUMBER</xsl:text>
        </imp1:ACCOUNT_NUMBER>
        <imp1:TRX_NUMBER>
          <xsl:text disable-output-escaping="no">TRX_NUMBER</xsl:text>
        </imp1:TRX_NUMBER>
         <imp1:RECEIPT_AMOUNT>
          <xsl:text disable-output-escaping="no">RECEIPT_AMOUNT</xsl:text>
        </imp1:RECEIPT_AMOUNT>
        <imp1:REVERSAL_DATE>
          <xsl:text disable-output-escaping="no">REVERSAL_DATE</xsl:text>
        </imp1:REVERSAL_DATE>       
      </imp1:OSGSupplPaymntReversalsFeed>
    </imp1:OSGSupplPaymntReversals>
  </xsl:template>
</xsl:stylesheet>