<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SunPowerDevelopment/Lease2OutboundEBSReq/EBSPollDBAdapter" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateStatusToEBS" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/Lease2Outbound/Lease2OutboundEBSReq/UpdateStatusToEBS" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/EBSPollDBAdapter" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl tns top plt xsd wsdl ns1 ns0 bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref ora socket ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/EBSPollDBAdapter.wsdl"/>
            <oracle-xsl-mapper:rootElement name="XxspwrLease2OutboundDetailsCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/EBSPollDBAdapter"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../UpdateStatusToEBS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="XxspwrLease2OutboundDetailsCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateStatusToEBS"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON OCT 10 17:00:25 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns1:XxspwrLease2OutboundDetailsCollection>
      <xsl:for-each select="/top:XxspwrLease2OutboundDetailsCollection/top:XxspwrLease2OutboundDetails">
        <ns1:XxspwrLease2OutboundDetails>
          <xsl:if test="top:leaseNumber">
            <ns1:leaseNumber>
              <xsl:value-of select="top:leaseNumber"/>
            </ns1:leaseNumber>
          </xsl:if>
          <xsl:if test="top:soNumber">
            <ns1:soNumber>
              <xsl:value-of select="top:soNumber"/>
            </ns1:soNumber>
          </xsl:if>
          <ns1:soHeaderId>
            <xsl:value-of select="top:soHeaderId"/>
          </ns1:soHeaderId>
          <ns1:soaStatus>
            <xsl:text disable-output-escaping="no">ERROR</xsl:text>
          </ns1:soaStatus>
          <ns1:errorMessage>
            <xsl:text disable-output-escaping="no">SOA SYSTEM_FAULT</xsl:text>
          </ns1:errorMessage>
        </ns1:XxspwrLease2OutboundDetails>
      </xsl:for-each>
    </ns1:XxspwrLease2OutboundDetailsCollection>
  </xsl:template>
</xsl:stylesheet>