<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SunPowerApp/Lease2OutboundEBSReq/EBSPollDBAdapter" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns2="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/EBSPollDBAdapter" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns5="http://www.sunpowercorp.com/Noun/Lease2Outbound/V1" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns3="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns4="http://www.sunpowercorp.com/Common/Lease2OutboundCommonTypes/V1" xmlns:ns6="http://xmlns.oracle.com/pcbpel/adapter/db/SunPowerDevelopment/Lease2OutboundEBSReq/EBSPollDBAdapter" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessLease2Outbound/V1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns0="http://www.sunpowercorp.com/Lease2OutboundCanonical/" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl plt top wsdl ns6 xsd ns2 soap ns5 ns3 ns4 ns1 ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/EBSPollDBAdapter.wsdl"/>
            <oracle-xsl-mapper:rootElement name="XxspwrLease2OutboundDetailsCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/EBSPollDBAdapter"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/Lease2OutboundCanonical.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessLease2Outbound" namespace="http://www.sunpowercorp.com/BOD/ProcessLease2Outbound/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON OCT 10 17:00:25 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns1:ProcessLease2Outbound>
      <ns1:DataArea>
        <ns5:LeaseOrder>
          <xsl:for-each select="/top:XxspwrLease2OutboundDetailsCollection/top:XxspwrLease2OutboundDetails">
            <ns5:Lease2OrderDetails>
              <ns4:SoNumber>
                <xsl:value-of select="top:soNumber"/>
              </ns4:SoNumber>
              <ns4:SoHeaderId>
                <xsl:value-of select="top:soHeaderId"/>
              </ns4:SoHeaderId>
              <ns4:LeaseNumber>
                <xsl:value-of select="top:leaseNumber"/>
              </ns4:LeaseNumber>
              <xsl:if test="top:schDelivDatePv != &quot;&quot;">
                <ns4:SchDelivDatePv>
                  <xsl:value-of select="top:schDelivDatePv"/>
                </ns4:SchDelivDatePv>
              </xsl:if>
              <xsl:if test="top:schDelivDateInv != &quot;&quot;">
                <ns4:SchDelivDateInv>
                  <xsl:value-of select="top:schDelivDateInv"/>
                </ns4:SchDelivDateInv>
              </xsl:if>
              <xsl:if test="top:schDelivDateMount != &quot;&quot;">
                <ns4:SchDelivDateMount>
                  <xsl:value-of select="top:schDelivDateMount"/>
                </ns4:SchDelivDateMount>
              </xsl:if>
              <xsl:if test="top:delivDatePv != &quot;&quot;">
                <ns4:DelivDatePv>
                  <xsl:value-of select="top:delivDatePv"/>
                </ns4:DelivDatePv>
              </xsl:if>
              <xsl:if test="top:delivDateInv != &quot;&quot;">
                <ns4:DelivDateInv>
                  <xsl:value-of select="top:delivDateInv"/>
                </ns4:DelivDateInv>
              </xsl:if>
              <xsl:if test="top:delivDateMount != &quot;&quot;">
                <ns4:DelivDateMount>
                  <xsl:value-of select="top:delivDateMount"/>
                </ns4:DelivDateMount>
              </xsl:if>
              <xsl:if test="top:poNumberOrig != &quot;&quot;">
                <ns4:PONumberOrig>
                  <xsl:value-of select="top:poNumberOrig"/>
                </ns4:PONumberOrig>
              </xsl:if>
              <xsl:if test="top:poNumberInstall != &quot;&quot;">
                <ns4:PONumberInstall>
                  <xsl:value-of select="top:poNumberInstall"/>
                </ns4:PONumberInstall>
              </xsl:if>
              <xsl:if test="top:poNumberInter != &quot;&quot;">
                <ns4:PONumberInter>
                  <xsl:value-of select="top:poNumberInter"/>
                </ns4:PONumberInter>
              </xsl:if>
              <xsl:if test="top:poCreationDateOrig != &quot;&quot;">
                <ns4:POCreationDateOrig>
                  <xsl:value-of select="top:poCreationDateOrig"/>
                </ns4:POCreationDateOrig>
              </xsl:if>
              <xsl:if test="top:poCreationDateInstall != &quot;&quot;">
                <ns4:POCreationDateInstall>
                  <xsl:value-of select="top:poCreationDateInstall"/>
                </ns4:POCreationDateInstall>
              </xsl:if>
              <xsl:if test="top:poCreationDateInter != &quot;&quot;">
                <ns4:POCreationDateInter>
                  <xsl:value-of select="top:poCreationDateInter"/>
                </ns4:POCreationDateInter>
              </xsl:if>
              <xsl:if test="top:poAmountOrig != &quot;&quot;">
                <ns4:POAmountOrig>
                  <xsl:value-of select="top:poAmountOrig"/>
                </ns4:POAmountOrig>
              </xsl:if>
              <xsl:if test="top:poAmountInstall != &quot;&quot;">
                <ns4:POAmountInstall>
                  <xsl:value-of select="top:poAmountInstall"/>
                </ns4:POAmountInstall>
              </xsl:if>
              <xsl:if test="top:poAmountInter != &quot;&quot;">
                <ns4:POAmountInter>
                  <xsl:value-of select="top:poAmountInter"/>
                </ns4:POAmountInter>
              </xsl:if>
              <xsl:if test="top:poReceiptDateOrigination != &quot;&quot;">
                <ns4:POReceiptDateOrigination>
                  <xsl:value-of select="top:poReceiptDateOrigination"/>
                </ns4:POReceiptDateOrigination>
              </xsl:if>
              <xsl:if test="top:poReceiptDateInstallation != &quot;&quot;">
                <ns4:POReceiptDateInstallation>
                  <xsl:value-of select="top:poReceiptDateInstallation"/>
                </ns4:POReceiptDateInstallation>
              </xsl:if>
              <xsl:if test="top:poReceiptDateInterconnect != &quot;&quot;">
                <ns4:POReceiptDateInterConnect>
                  <xsl:value-of select="top:poReceiptDateInterconnect"/>
                </ns4:POReceiptDateInterConnect>
              </xsl:if>
              <xsl:if test="top:supInvNumOrigination != &quot;&quot;">
                <ns4:SupInvNumOrigination>
                  <xsl:value-of select="top:supInvNumOrigination"/>
                </ns4:SupInvNumOrigination>
              </xsl:if>
              <xsl:if test="top:supInvNumInstallation != &quot;&quot;">
                <ns4:SupInvNumInstallation>
                  <xsl:value-of select="top:supInvNumInstallation"/>
                </ns4:SupInvNumInstallation>
              </xsl:if>
              <xsl:if test="top:supInvNumInterconnect != &quot;&quot;">
                <ns4:SupInvNumInterConnect>
                  <xsl:value-of select="top:supInvNumInterconnect"/>
                </ns4:SupInvNumInterConnect>
              </xsl:if>
              <xsl:if test="top:supInvAmtOrigination != &quot;&quot;">
                <ns4:SupInvAmtOrigination>
                  <xsl:value-of select="top:supInvAmtOrigination"/>
                </ns4:SupInvAmtOrigination>
              </xsl:if>
              <xsl:if test="top:supInvAmtInstallation != &quot;&quot;">
                <ns4:SupInvAmtInstallation>
                  <xsl:value-of select="top:supInvAmtInstallation"/>
                </ns4:SupInvAmtInstallation>
              </xsl:if>
              <xsl:if test="top:supInvAmtInterconnect != &quot;&quot;">
                <ns4:SupInvAmtInterConnect>
                  <xsl:value-of select="top:supInvAmtInterconnect"/>
                </ns4:SupInvAmtInterConnect>
              </xsl:if>
              <xsl:if test="top:paymentAmtOrigination != &quot;&quot;">
                <ns4:PaymentAmtOrigination>
                  <xsl:value-of select="top:paymentAmtOrigination"/>
                </ns4:PaymentAmtOrigination>
              </xsl:if>
              <xsl:if test="top:paymentAmtInstallation != &quot;&quot;">
                <ns4:PaymentAmtInstallation>
                  <xsl:value-of select="top:paymentAmtInstallation"/>
                </ns4:PaymentAmtInstallation>
              </xsl:if>
              <xsl:if test="top:paymentAmtInterconnect != &quot;&quot;">
                <ns4:PaymentAmtInterConnect>
                  <xsl:value-of select="top:paymentAmtInterconnect"/>
                </ns4:PaymentAmtInterConnect>
              </xsl:if>
              <xsl:if test="top:paymentDateOrigination != &quot;&quot;">
                <ns4:PaymentDateOrigination>
                  <xsl:value-of select="top:paymentDateOrigination"/>
                </ns4:PaymentDateOrigination>
              </xsl:if>
              <xsl:if test="top:paymentDateInstallation != &quot;&quot;">
                <ns4:PaymentDateInstallation>
                  <xsl:value-of select="top:paymentDateInstallation"/>
                </ns4:PaymentDateInstallation>
              </xsl:if>
              <xsl:if test="top:paymentDateInterconnect != &quot;&quot;">
                <ns4:PaymentDateInterConnect>
                  <xsl:value-of select="top:paymentDateInterconnect"/>
                </ns4:PaymentDateInterConnect>
              </xsl:if>
              <xsl:if test="top:schedulePayDateOrig != &quot;&quot;">
                <ns4:SchedulePayDateOrig>
                  <xsl:value-of select="top:schedulePayDateOrig"/>
                </ns4:SchedulePayDateOrig>
              </xsl:if>
              <xsl:if test="top:schedulePayDateInstall != &quot;&quot;">
                <ns4:SchedulePayDateInstall>
                  <xsl:value-of select="top:schedulePayDateInstall"/>
                </ns4:SchedulePayDateInstall>
              </xsl:if>
              <xsl:if test="top:schedulePayDateInter != &quot;&quot;">
                <ns4:SchedulePayDateInter>
                  <xsl:value-of select="top:schedulePayDateInter"/>
                </ns4:SchedulePayDateInter>
              </xsl:if>
              <xsl:if test="top:custReqDatePv != &quot;&quot;">
                <ns4:CustReqDatePv>
                  <xsl:value-of select="top:custReqDatePv"/>
                </ns4:CustReqDatePv>
              </xsl:if>
              <xsl:if test="top:custReqDateInv != &quot;&quot;">
                <ns4:CustReqDateInv>
                  <xsl:value-of select="top:custReqDateInv"/>
                </ns4:CustReqDateInv>
              </xsl:if>
              <xsl:if test="top:custReqDateMount != &quot;&quot;">
                <ns4:CustReqDateMount>
                  <xsl:value-of select="top:custReqDateMount"/>
                </ns4:CustReqDateMount>
              </xsl:if>
              <xsl:if test="top:custPromiseDatePv != &quot;&quot;">
                <ns4:CustPromiseDatePv>
                  <xsl:value-of select="top:custPromiseDatePv"/>
                </ns4:CustPromiseDatePv>
              </xsl:if>
              <xsl:if test="top:custPromiseDateInv != &quot;&quot;">
                <ns4:CustPromiseDateInv>
                  <xsl:value-of select="top:custPromiseDateInv"/>
                </ns4:CustPromiseDateInv>
              </xsl:if>
              <xsl:if test="top:custPromiseDateMount != &quot;&quot;">
                <ns4:CustPromiseDateMount>
                  <xsl:value-of select="top:custPromiseDateMount"/>
                </ns4:CustPromiseDateMount>
              </xsl:if>
              <xsl:if test="top:attribute1 != &quot;&quot;">
                <ns4:Attribute1>
                  <xsl:value-of select="top:attribute1"/>
                </ns4:Attribute1>
              </xsl:if>
              <xsl:if test="top:attribute2 != &quot;&quot;">
                <ns4:Attribute2>
                  <xsl:value-of select="top:attribute2"/>
                </ns4:Attribute2>
              </xsl:if>
              <xsl:if test="top:attribute3 != &quot;&quot;">
                <ns4:Attribute3>
                  <xsl:value-of select="top:attribute3"/>
                </ns4:Attribute3>
              </xsl:if>
              <xsl:if test="top:attribute4 != &quot;&quot;">
                <ns4:Attribute4>
                  <xsl:value-of select="top:attribute4"/>
                </ns4:Attribute4>
              </xsl:if>
              <xsl:if test="top:attribute5 != &quot;&quot;">
                <ns4:Attribute5>
                  <xsl:value-of select="top:attribute5"/>
                </ns4:Attribute5>
              </xsl:if>
              <xsl:if test="top:attribute6 != &quot;&quot;">
                <ns4:Attribute6>
                  <xsl:value-of select="top:attribute6"/>
                </ns4:Attribute6>
              </xsl:if>
              <xsl:if test="top:attribute7 != &quot;&quot;">
                <ns4:Attribute7>
                  <xsl:value-of select="top:attribute7"/>
                </ns4:Attribute7>
              </xsl:if>
              <xsl:if test="top:attribute8 != &quot;&quot;">
                <ns4:Attribute8>
                  <xsl:value-of select="top:attribute8"/>
                </ns4:Attribute8>
              </xsl:if>
              <xsl:if test="top:attribute9 != &quot;&quot;">
                <ns4:Attribute9>
                  <xsl:value-of select="top:attribute9"/>
                </ns4:Attribute9>
              </xsl:if>
              <xsl:if test="top:attribute10 != &quot;&quot;">
                <ns4:Attribute10>
                  <xsl:value-of select="top:attribute10"/>
                </ns4:Attribute10>
              </xsl:if>
              <xsl:if test="top:soaStatus != &quot;&quot;">
                <ns4:SOA_STATUS>
                  <xsl:value-of select="top:soaStatus"/>
                </ns4:SOA_STATUS>
              </xsl:if>
              <xsl:if test="top:leaseCost != &quot;&quot;">
                <ns4:LEASE_COST>
                  <xsl:value-of select="top:leaseCost"/>
                </ns4:LEASE_COST>
              </xsl:if>
              <xsl:if test="top:leaseCloseStatus != &quot;&quot;">
                <ns4:LEASE_CLOSE_STATUS>
                  <xsl:value-of select="top:leaseCloseStatus"/>
                </ns4:LEASE_CLOSE_STATUS>
              </xsl:if>
              <xsl:if test="top:leaseCloseDate != &quot;&quot;">
                <ns4:LEASE_CLOSE_DATE>
                  <xsl:value-of select="top:leaseCloseDate"/>
                </ns4:LEASE_CLOSE_DATE>
              </xsl:if>
              <xsl:if test="top:leaseCloseReqId != &quot;&quot;">
                <ns4:LEASE_CLOSE_REQ_ID>
                  <xsl:value-of select="top:leaseCloseReqId"/>
                </ns4:LEASE_CLOSE_REQ_ID>
              </xsl:if>
              <xsl:if test="top:creationDate != &quot;&quot;">
                <ns4:CreationDate>
                  <xsl:value-of select="top:creationDate"/>
                </ns4:CreationDate>
              </xsl:if>
              <xsl:if test="top:createdBy != &quot;&quot;">
                <ns4:CreatedBy>
                  <xsl:value-of select="top:createdBy"/>
                </ns4:CreatedBy>
              </xsl:if>
              <xsl:if test="top:lastUpdateDate != &quot;&quot;">
                <ns4:LastUpdateDate>
                  <xsl:value-of select="top:lastUpdateDate"/>
                </ns4:LastUpdateDate>
              </xsl:if>
              <xsl:if test="top:lastUpdatedBy != &quot;&quot;">
                <ns4:LastUpdatedBy>
                  <xsl:value-of select="top:lastUpdatedBy"/>
                </ns4:LastUpdatedBy>
              </xsl:if>
              <ns4:PV_COST>
                <xsl:value-of select="top:pvCost"/>
              </ns4:PV_COST>
              <ns4:INVERTER_COST>
                <xsl:value-of select="top:inverterCost"/>
              </ns4:INVERTER_COST>
              <ns4:MONITORING_COST>
                <xsl:value-of select="top:monitoringCost"/>
              </ns4:MONITORING_COST>
              <ns4:BOS_COST>
                <xsl:value-of select="top:bosCost"/>
              </ns4:BOS_COST>
              <ns4:RACKING_COST_INTERNAL>
                <xsl:value-of select="top:rackingCostInternal"/>
              </ns4:RACKING_COST_INTERNAL>
              <ns4:MISC_COST_INTERNAL>
                <xsl:value-of select="top:miscCostInternal"/>
              </ns4:MISC_COST_INTERNAL>
              <ns4:RACKING_COST_INSTALLER>
                <xsl:value-of select="top:rackingCostInstaller"/>
              </ns4:RACKING_COST_INSTALLER>
              <ns4:MISC_COST_INSTALLER>
                <xsl:value-of select="top:miscCostInstaller"/>
              </ns4:MISC_COST_INSTALLER>
              <ns4:TOTAL_SPWR_SUPP_MATERIAL>
                <xsl:value-of select="top:totalSpwrSuppMaterial"/>
              </ns4:TOTAL_SPWR_SUPP_MATERIAL>
              <ns4:TOTAL_DEALER_SUPP_MATERIAL>
                <xsl:value-of select="top:totalDealerSuppMaterial"/>
              </ns4:TOTAL_DEALER_SUPP_MATERIAL>
              <ns4:TOTAL_MATERIAL_COST>
                <xsl:value-of select="top:totalMaterialCost"/>
              </ns4:TOTAL_MATERIAL_COST>
              <ns4:TOTAL_SERVICE_COST>
                <xsl:value-of select="top:totalServiceCost"/>
              </ns4:TOTAL_SERVICE_COST>
              <ns4:TAX_AMOUNT>
                <xsl:value-of select="top:taxAmount"/>
              </ns4:TAX_AMOUNT>
              <ns4:NET_DEALER_SERVICE_COST>
                <xsl:value-of select="top:netDealerServiceCost"/>
              </ns4:NET_DEALER_SERVICE_COST>
              <ns4:ORDER_STATUS>
                <xsl:value-of select="top:orderStatus"/>
              </ns4:ORDER_STATUS>
              <ns4:TAX_IDENTIFIER>
                <xsl:value-of select="top:taxIdentifier"/>
              </ns4:TAX_IDENTIFIER>
              <ns4:ERROR_MESSAGE>
                <xsl:value-of select="top:errorMessage"/>
              </ns4:ERROR_MESSAGE>
            </ns5:Lease2OrderDetails>
          </xsl:for-each>
        </ns5:LeaseOrder>
      </ns1:DataArea>
    </ns1:ProcessLease2Outbound>
  </xsl:template>
</xsl:stylesheet>