<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="EnqueOracleSFDCNoItemOperatingUnit_BPEL" targetNamespace="http://www.sunpowercorp.com/OnlineOrderingNoItemOracleToSFDC/EnqueOracleSFDCNoItemOperatingUnit/EnqueOracleSFDCNoItemOperatingUnit_BPEL" xmlns:ns1="http://www.sunpowercorp.com/SunPowerDevelopment/indexInputParams/xsd/v1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:client="http://www.sunpowercorp.com/OnlineOrderingNoItemOracleToSFDC/EnqueOracleSFDCNoItemOperatingUnit/EnqueOracleSFDCNoItemOperatingUnit_BPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="EnqueOracleSFDCNoItemOperatingUnit_BPEL">
      <plnk:role name="EnqueOracleSFDCNoItemOperatingUnit_BPELProvider">
         <plnk:portType name="client:EnqueOracleSFDCNoItemOperatingUnit_BPEL"/>
      </plnk:role>
   </plnk:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://www.sunpowercorp.com/OnlineOrderingNoItemOracleToSFDC/EnqueOracleSFDCNoItemOperatingUnit/EnqueOracleSFDCNoItemOperatingUnit_BPEL"
                 schemaLocation="Schemas/EnqueOracleSFDCNoItemOperatingUnit_BPEL.xsd"/>
      </schema>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
         <xsd:import namespace="http://www.sunpowercorp.com/SunPowerDevelopment/indexInputParams/xsd/v1"
                     schemaLocation="Schemas/inputParams.xsd"/>
      </xsd:schema>
   </wsdl:types>
   <wsdl:message name="EnqueOracleSFDCNoItemOperatingUnit_BPELRequestMessage">
      <wsdl:part name="payload" element="client:process"/>
   </wsdl:message>
   <wsdl:portType name="EnqueOracleSFDCNoItemOperatingUnit_BPEL">
      <wsdl:operation name="process">
         <wsdl:input message="client:EnqueOracleSFDCNoItemOperatingUnit_BPELRequestMessage"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
