<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="selecteNoItemOperatingUnitFromEBS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OnlineOrderingNoItemOracleToSFDC/EnqueOracleSFDCNoItemOperatingUnit/selecteNoItemOperatingUnitFromEBS" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/selecteNoItemOperatingUnitFromEBS" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OnlineOrderingNoItemOracleToSFDC/EnqueOracleSFDCNoItemOperatingUnit/selecteNoItemOperatingUnitFromEBS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
   <plt:partnerLinkType name="selecteNoItemOperatingUnitFromEBS_plt">
      <plt:role name="selecteNoItemOperatingUnitFromEBS_role">
         <plt:portType name="tns:selecteNoItemOperatingUnitFromEBS_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/selecteNoItemOperatingUnitFromEBS"
                 schemaLocation="Schemas/selecteNoItemOperatingUnitFromEBS.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="selecteNoItemOperatingUnitFromEBSInput_msg">
      <wsdl:part name="selecteNoItemOperatingUnitFromEBSInput_msg" element="db:selecteNoItemOperatingUnitFromEBSInput"/>
   </wsdl:message>
   <wsdl:message name="selecteNoItemOperatingUnitFromEBSOutputCollection_msg">
      <wsdl:part name="selecteNoItemOperatingUnitFromEBSOutputCollection" element="db:selecteNoItemOperatingUnitFromEBSOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="selecteNoItemOperatingUnitFromEBS_ptt">
      <wsdl:operation name="selecteNoItemOperatingUnitFromEBS">
         <wsdl:input message="tns:selecteNoItemOperatingUnitFromEBSInput_msg"/>
         <wsdl:output message="tns:selecteNoItemOperatingUnitFromEBSOutputCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
