<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollFDSRecrdDB" xmlns:ns0="http://www.sunpowercorp.com/WarrantyFDSToSFDCCanonical/" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns3="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessWarratyFDSToSFDC/V1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/WarrantyRegistrationFDSToSFDC/WarrantyFDSToSFDCReq/PollFDSRecrdDB" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns4="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:ns2="http://www.sunpowercorp.com/Common/WarrantyFDSToSFDCCommonTypes/V1" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns6="http://schemas.oracle.com/bpel/extension" xmlns:ns5="http://www.sunpowercorp.com/Noun/WarrantyFDSToSFDC/V1" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl top plt wsdl tns xsd ns6 ns0 ns3 ns1 soap ns4 ns2 ns5 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/PollFDSRecrdDB.wsdl"/>
            <oracle-xsl-mapper:rootElement name="WarrantyViewFlushCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollFDSRecrdDB"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/WarrantyFDSToSFDCCanonical.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessWarrantyFDSToSFDC" namespace="http://www.sunpowercorp.com/BOD/ProcessWarratyFDSToSFDC/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [FRI OCT 07 14:02:03 IST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns1:ProcessWarrantyFDSToSFDC>
      <ns1:DataArea>
        <ns5:WRFDS2SFDC>
          <xsl:for-each select="/top:WarrantyViewFlushCollection/top:WarrantyViewFlush">
            <ns5:WRFDSToSFDCDetails>
              <ns2:ID>
                <xsl:value-of select="top:id"/>
              </ns2:ID>
              <ns2:manufacturer>
                <xsl:value-of select="top:manufacturer"/>
              </ns2:manufacturer>
              <ns2:product_type>
                <xsl:value-of select="top:productType"/>
              </ns2:product_type>
              <ns2:serial_number>
                <xsl:value-of select="top:serialNumber"/>
              </ns2:serial_number>
              <ns2:packing_list_no>
                <xsl:value-of select="top:packingListNo"/>
              </ns2:packing_list_no>
              <ns2:trad_ship_date>
                <xsl:value-of select="top:trdShipDate"/>
              </ns2:trad_ship_date>
              <ns2:dealer_name>
                <xsl:value-of select="top:dealerName"/>
              </ns2:dealer_name>
              <ns2:third_party_logistics_name>
                <xsl:value-of select="top:thirdPartyLogisticsName"/>
              </ns2:third_party_logistics_name>
              <ns2:product_group>
                <xsl:value-of select="top:productGroup"/>
              </ns2:product_group>
              <ns2:last_updated_stamp>
                <xsl:value-of select="top:lastUpdatedStamp"/>
              </ns2:last_updated_stamp>
            </ns5:WRFDSToSFDCDetails>
          </xsl:for-each>
        </ns5:WRFDS2SFDC>
      </ns1:DataArea>
    </ns1:ProcessWarrantyFDSToSFDC>
  </xsl:template>
</xsl:stylesheet>