<?binding.jca InsertCommonLogDataDB_db.jca?>
<wsdl:definitions name="InsertCommonLogDataDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SOAUtilityServices/CommonLoggingService/InsertCommonLogDataDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOAUtilityServices/CommonLoggingService/InsertCommonLogDataDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertCommonLogDataDB">
    <plt:partnerLinkType name="InsertCommonLogDataDB_plt">
        <plt:role name="InsertCommonLogDataDB_role">
            <plt:portType name="tns:InsertCommonLogDataDB_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertCommonLogDataDB"
                    schemaLocation="../Schemas/InsertCommonLogDataDB_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="MiddlewareErrorLogCollection_msg">
        <wsdl:part name="MiddlewareErrorLogCollection" element="top:MiddlewareErrorLogCollection"/>
    </wsdl:message>
    <wsdl:portType name="InsertCommonLogDataDB_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:MiddlewareErrorLogCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
