<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ACBClaimAll"
     targetNamespace="http://www.sunpowercorp.com/ACBClaimAll/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:WL5G3N2="http://www.sunpowercorp.com/ACBClaimAll/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="ACBGetAllActivitesmergeOSB">
        <plnk:role name="ACBClaimAll">
            <plnk:portType name="WL5G3N2:ACBClaimAll"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.sunpowercorp.com/ACBClaimAll/" location="http://dev-fusappdca02.sunpowercorp.com:7004/ACBGetAllActivitesmergeSvc/Proxy/ACBGetAllActivitesmergeSvcPS?wsdl"/>
</wsdl:definitions>
