<?binding.jca CreateUpdateCustSiteCustomer_db.jca?>
<wsdl:definitions name="CreateUpdateCustSiteCustomer" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TPOSOACustomerSync/CreateUpdateCustomerOracleProv/CreateUpdateCustSiteCustomer" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/TPOSOACustomerSync/CreateUpdateCustomerOracleProv/CreateUpdateCustSiteCustomer" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CreateUpdateCustSiteCustomer">
    <plt:partnerLinkType name="CreateUpdateCustSiteCustomer_plt">
        <plt:role name="CreateUpdateCustSiteCustomer_role">
            <plt:portType name="tns:CreateUpdateCustSiteCustomer_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CreateUpdateCustSiteCustomer"
                    schemaLocation="../Schemas/CreateUpdateCustSiteCustomer_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="XxspwrSforaCustSitesCollection_msg">
        <wsdl:part name="XxspwrSforaCustSitesCollection" element="top:XxspwrSforaCustSitesCollection"/>
    </wsdl:message>
    <wsdl:portType name="CreateUpdateCustSiteCustomer_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:XxspwrSforaCustSitesCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
