<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/DEVELOPMENT_CODE/DeptFeedHyperion2Oracle/InsertDeptHyperionFeed" xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns1="http://www.sunpowercorp.com/SunPowerDevelopment/initParams/xsd/v1" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertDeptHyperionFeed" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:imp1="http://www.sunpowercorp.com/PoolDeptFeedHyperionFile" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/Test/DeptFeedHyperion2Oracle/PollDeptHyperionFeedFile" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl pc plt wsdl ns1 imp1 tns jca xsd ns0 top xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../PollDeptHyperionFeedFile.wsdl"/>
            <oracle-xsl-mapper:rootElement name="DeptFeed" namespace="http://www.sunpowercorp.com/PoolDeptFeedHyperionFile"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../PollDeptHyperionFeedFile.wsdl"/>
            <oracle-xsl-mapper:rootElement name="InitParams" namespace="http://www.sunpowercorp.com/SunPowerDevelopment/initParams/xsd/v1"/>
            <oracle-xsl-mapper:param name="initParams"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../InsertDeptHyperionFeed.wsdl"/>
            <oracle-xsl-mapper:rootElement name="XxspwrHypDeptBuMapTabCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertDeptHyperionFeed"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU OCT 13 11:16:52 IST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="initParams"/>
  <xsl:template match="/">
    <top:XxspwrHypDeptBuMapTabCollection>
      <xsl:variable name="i" select="number($initParams/ns1:InitParams/ns1:i)"/>
      <top:XxspwrHypDeptBuMapTab>
        <top:execOwnerName>
          <xsl:value-of select="/imp1:DeptFeed/imp1:DeptFeedHyperion[$i]/imp1:EXEC_OWNER_NAME"/>
        </top:execOwnerName>
        <top:execOwnerEmpId>
          <xsl:value-of select="/imp1:DeptFeed/imp1:DeptFeedHyperion[$i]/imp1:EXEC_OWNER_EMP_ID"/>
        </top:execOwnerEmpId>
        <top:deptNum>
          <xsl:value-of select="/imp1:DeptFeed/imp1:DeptFeedHyperion[$i]/imp1:DEPT_NUM"/>
        </top:deptNum>
        <top:deptAlias>
          <xsl:value-of select="/imp1:DeptFeed/imp1:DeptFeedHyperion[$i]/imp1:DEPT_ALIAS"/>
        </top:deptAlias>
        <top:deptSubBu>
          <xsl:value-of select="/imp1:DeptFeed/imp1:DeptFeedHyperion[$i]/imp1:DEPT_SUB_BU"/>
        </top:deptSubBu>
        <top:deptBu>
          <xsl:value-of select="/imp1:DeptFeed/imp1:DeptFeedHyperion[$i]/imp1:DEPT_BU"/>
        </top:deptBu>
        <top:deptCogsOpex>
          <xsl:value-of select="/imp1:DeptFeed/imp1:DeptFeedHyperion[$i]/imp1:DEPT_COGS_OPEX"/>
        </top:deptCogsOpex>
        <top:status>
          <xsl:text disable-output-escaping="no">U</xsl:text>
        </top:status>
      </top:XxspwrHypDeptBuMapTab>
    </top:XxspwrHypDeptBuMapTabCollection>
  </xsl:template>
</xsl:stylesheet>