<?binding.jca PollVertexDataDetails_db.jca?>
<wsdl:definitions name="PollVertexDataDetails" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OracleSFDC_VertexDataLoad/OracleSFDCVertexDataLoadReq/PollVertexDataDetails" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OracleSFDC_VertexDataLoad/OracleSFDCVertexDataLoadReq/PollVertexDataDetails" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollVertexDataDetails">
    <plt:partnerLinkType name="PollVertexDataDetails_plt">
        <plt:role name="PollVertexDataDetails_role">
            <plt:portType name="tns:PollVertexDataDetails_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollVertexDataDetails"
                    schemaLocation="Schemas/PollVertexDataDetails_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="XxspwrGeoVertexStgCollection_msg">
        <wsdl:part name="XxspwrGeoVertexStgCollection" element="top:XxspwrGeoVertexStgCollection"/>
    </wsdl:message>
    <wsdl:portType name="PollVertexDataDetails_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:XxspwrGeoVertexStgCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
