<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns0="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns6="http://www.sunpowercorp.com/Common/SyncOEOrdersCommonTypes/V1" xmlns:ns7="http://www.sunpowercorp.com/SunPowerDevelopment/initParams/xsd/v1" xmlns:ns2="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessSyncOEOrders/V1" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns4="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/fetchOracleOraderLines" xmlns:ns8="http://www.sunpowercorp.com/SunPowerDevelopment/utility/BatchEmailUtilityService/xsd/V1" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns5="http://www.sunpowercorp.com/Noun/SyncOEOrders/V1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SyncOEOrdersOracleToSFDC/SyncOEOrdersOracleReq/fetchOracleOraderLines" xmlns:client="http://www.sunpowercorp.com/SyncOEOrdersOracleToSFDC/SyncOEOrdersSFDCProv/SyncOEOrdersSFDCProv_BPEL" xmlns:ns3="urn:partner.soap.sforce.com" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl plt wsdl db xsd tns ns0 ns6 ns7 ns2 ns1 ns4 ns8 ns5 client ns3 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/fetchOracleOraderLines.wsdl"/>
            <oracle-xsl-mapper:rootElement name="fetchOracleOraderLinesOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/fetchOracleOraderLines"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7003/soa-infra/services/online/SyncOEOrdersSFDCProv/SyncOEOrdersSFDCProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessSyncOEOrders" namespace="http://www.sunpowercorp.com/BOD/ProcessSyncOEOrders/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE OCT 11 15:42:52 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns1:ProcessSyncOEOrders>
      <ns1:DataArea>
        <ns0:process>
          <xsl:text disable-output-escaping="no"/>
        </ns0:process>
        <ns5:SyncOEOrders>
          <xsl:for-each select="/db:fetchOracleOraderLinesOutputCollection/db:fetchOracleOraderLinesOutput">
            <ns5:SyncOEOrderLineDetails>
              <ns6:SFDC_ID>
                <xsl:value-of select="db:c_SFDC_ID"/>
              </ns6:SFDC_ID>
              <ns6:Order_SFDC_ID>
                <xsl:value-of select="db:b_SFDC_ID"/>
              </ns6:Order_SFDC_ID>
              <ns6:LINE_NUMBER>
                <xsl:value-of select="db:c_LINE_NUMBER"/>
              </ns6:LINE_NUMBER>
              <ns6:ORACLE_REQUEST_ID>
                <xsl:value-of select="db:c_ORACLE_REQUEST_ID"/>
              </ns6:ORACLE_REQUEST_ID>
              <ns6:SFDC_REQUEST_ID>
                <xsl:value-of select="db:c_SFDC_REQUEST_ID"/>
              </ns6:SFDC_REQUEST_ID>
              <ns6:SFDC_REQUEST_STATUS>
                <xsl:value-of select="db:c_SFDC_REQUEST_STATUS"/>
              </ns6:SFDC_REQUEST_STATUS>
              <ns6:HEADER_ID>
                <xsl:value-of select="db:c_HEADER_ID"/>
              </ns6:HEADER_ID>
              <ns6:LINE_ID>
                <xsl:value-of select="db:c_LINE_ID"/>
              </ns6:LINE_ID>
              <ns6:INVENTORY_ITEM_ID>
                <xsl:value-of select="db:c_INVENTORY_ITEM_ID"/>
              </ns6:INVENTORY_ITEM_ID>
              <ns6:ITEM_NUMBER>
                <xsl:value-of select="db:c_ITEM_NUMBER"/>
              </ns6:ITEM_NUMBER>
              <ns6:ITEM_DESCRIPTION>
                <xsl:value-of select="db:c_ITEM_DESCRIPTION"/>
              </ns6:ITEM_DESCRIPTION>
              <ns6:REQUESTED_QTY>
                <xsl:value-of select="db:c_REQUESTED_QTY"/>
              </ns6:REQUESTED_QTY>
              <ns6:UOM>
                <xsl:value-of select="db:c_UOM"/>
              </ns6:UOM>
              <ns6:UNIT_PRICE>
                <xsl:value-of select="db:c_UNIT_PRICE"/>
              </ns6:UNIT_PRICE>
              <ns6:ORDER_LINE_TYPE>
                <xsl:value-of select="db:c_ORDER_LINE_TYPE"/>
              </ns6:ORDER_LINE_TYPE>
              <ns6:LINE_STATUS>
                <xsl:value-of select="db:c_LINE_STATUS"/>
              </ns6:LINE_STATUS>
              <ns6:PACKING_SLIP_NUMBER>
                <xsl:value-of select="db:c_PACKING_SLIP_NUMBER"/>
              </ns6:PACKING_SLIP_NUMBER>
              <ns6:PRODUCT_TYPE>
                <xsl:value-of select="db:c_PRODUCT_TYPE"/>
              </ns6:PRODUCT_TYPE>
              <ns6:WATTAGE_TYPE>
                <xsl:value-of select="db:c_WATTAGE_TYPE"/>
              </ns6:WATTAGE_TYPE>
              <ns6:ITEM_TYPE>
                <xsl:value-of select="db:c_ITEM_TYPE"/>
              </ns6:ITEM_TYPE>
              <ns6:LINE_REQUEST_DATE>
                <xsl:value-of select="db:c_LINE_REQUEST_DATE"/>
              </ns6:LINE_REQUEST_DATE>
              <ns6:LINE_SCH_SHIP_DATE>
                <xsl:value-of select="db:c_LINE_SCH_SHIP_DATE"/>
              </ns6:LINE_SCH_SHIP_DATE>
              <ns6:SCHEDULED_ARRIVAL_DATE>
                <xsl:value-of select="db:c_SCHEDULED_ARRIVAL_DATE"/>
              </ns6:SCHEDULED_ARRIVAL_DATE>
              <ns6:PROMISED_DATE>
                <xsl:value-of select="db:c_PROMISED_DATE"/>
              </ns6:PROMISED_DATE>
              <ns6:SHIP_FROM_ORG_ID>
                <xsl:value-of select="db:c_SHIP_FROM_ORG_ID"/>
              </ns6:SHIP_FROM_ORG_ID>
              <ns6:BILL_TO_SITE_ID>
                <xsl:value-of select="db:c_BILL_TO_SITE_ID"/>
              </ns6:BILL_TO_SITE_ID>
              <ns6:BILL_ADDRESS_LINE_1>
                <xsl:value-of select="db:c_BILL_ADDRESS_LINE_1"/>
              </ns6:BILL_ADDRESS_LINE_1>
              <ns6:BILL_ADDRESS_LINE_2>
                <xsl:value-of select="db:c_BILL_ADDRESS_LINE_2"/>
              </ns6:BILL_ADDRESS_LINE_2>
              <ns6:BILL_ADDRESS_LINE_3>
                <xsl:value-of select="db:c_BILL_ADDRESS_LINE_3"/>
              </ns6:BILL_ADDRESS_LINE_3>
              <ns6:BILL_CITY>
                <xsl:value-of select="db:c_BILL_CITY"/>
              </ns6:BILL_CITY>
              <ns6:BILL_STATE>
                <xsl:value-of select="db:c_BILL_STATE"/>
              </ns6:BILL_STATE>
              <ns6:BILL_COUNTRY>
                <xsl:value-of select="db:c_BILL_COUNTRY"/>
              </ns6:BILL_COUNTRY>
              <ns6:BILL_POSTAL_CODE>
                <xsl:value-of select="db:c_BILL_POSTAL_CODE"/>
              </ns6:BILL_POSTAL_CODE>
              <ns6:DELIVER_TO_ORG_ID>
                <xsl:value-of select="db:c_DELIVER_TO_ORG_ID"/>
              </ns6:DELIVER_TO_ORG_ID>
              <ns6:DELIVER_ADDRESS_LINE_1>
                <xsl:value-of select="db:c_DELIVER_ADDRESS_LINE_1"/>
              </ns6:DELIVER_ADDRESS_LINE_1>
              <ns6:DELIVER_ADDRESS_LINE_2>
                <xsl:value-of select="db:c_DELIVER_ADDRESS_LINE_2"/>
              </ns6:DELIVER_ADDRESS_LINE_2>
              <ns6:DELIVER_ADDRESS_LINE_3>
                <xsl:value-of select="db:c_DELIVER_ADDRESS_LINE_3"/>
              </ns6:DELIVER_ADDRESS_LINE_3>
              <ns6:DELIVER_CITY>
                <xsl:value-of select="db:c_DELIVER_CITY"/>
              </ns6:DELIVER_CITY>
              <ns6:DELIVER_STATE>
                <xsl:value-of select="db:c_DELIVER_STATE"/>
              </ns6:DELIVER_STATE>
              <ns6:DELIVER_COUNTRY>
                <xsl:value-of select="db:c_DELIVER_COUNTRY"/>
              </ns6:DELIVER_COUNTRY>
              <ns6:DELIVER_POSTAL_CODE>
                <xsl:value-of select="db:c_DELIVER_POSTAL_CODE"/>
              </ns6:DELIVER_POSTAL_CODE>
              <ns6:SHIP_TO_SITE_ID>
                <xsl:value-of select="db:c_SHIP_TO_SITE_ID"/>
              </ns6:SHIP_TO_SITE_ID>
              <ns6:ADDRESS_LINE_1>
                <xsl:value-of select="db:c_ADDRESS_LINE_1"/>
              </ns6:ADDRESS_LINE_1>
              <ns6:ADDRESS_LINE_2>
                <xsl:value-of select="db:c_ADDRESS_LINE_2"/>
              </ns6:ADDRESS_LINE_2>
              <ns6:ADDRESS_LINE_3>
                <xsl:value-of select="db:c_ADDRESS_LINE_3"/>
              </ns6:ADDRESS_LINE_3>
              <ns6:CITY>
                <xsl:value-of select="db:c_CITY"/>
              </ns6:CITY>
              <ns6:STATE>
                <xsl:value-of select="db:c_STATE"/>
              </ns6:STATE>
              <ns6:COUNTRY>
                <xsl:value-of select="db:c_COUNTRY"/>
              </ns6:COUNTRY>
              <ns6:POSTAL_CODE>
                <xsl:value-of select="db:c_POSTAL_CODE"/>
              </ns6:POSTAL_CODE>
              <ns6:CONTACT_PHONE1>
                <xsl:value-of select="db:c_CONTACT_PHONE1"/>
              </ns6:CONTACT_PHONE1>
              <ns6:CONTACT_PHONE2>
                <xsl:value-of select="db:c_CONTACT_PHONE2"/>
              </ns6:CONTACT_PHONE2>
              <ns6:CONTACT_PERSON_NAME>
                <xsl:value-of select="db:c_CONTACT_PERSON_NAME"/>
              </ns6:CONTACT_PERSON_NAME>
              <ns6:CONTACT_EMAIL>
                <xsl:value-of select="db:c_CONTACT_EMAIL"/>
              </ns6:CONTACT_EMAIL>
              <ns6:CONTACT_FAX>
                <xsl:value-of select="db:c_CONTACT_FAX"/>
              </ns6:CONTACT_FAX>
              <ns6:SHIP_TO_CONTACT_ID>
                <xsl:value-of select="db:c_SHIP_TO_CONTACT_ID"/>
              </ns6:SHIP_TO_CONTACT_ID>
              <ns6:SHIPPING_METHOD>
                <xsl:value-of select="db:c_SHIPPING_METHOD"/>
              </ns6:SHIPPING_METHOD>
              <ns6:SPECIAL_INSTRUCTIONS>
                <xsl:value-of select="db:c_SPECIAL_INSTRUCTIONS"/>
              </ns6:SPECIAL_INSTRUCTIONS>
              <ns6:SHIPPING_INSTRUCTIONS>
                <xsl:value-of select="db:c_SHIPPING_INSTRUCTIONS"/>
              </ns6:SHIPPING_INSTRUCTIONS>
              <ns6:PACKING_INSTRUCTIONS>
                <xsl:value-of select="db:c_PACKING_INSTRUCTIONS"/>
              </ns6:PACKING_INSTRUCTIONS>
              <ns6:TAX_FLAG>
                <xsl:value-of select="db:c_TAX_FLAG"/>
              </ns6:TAX_FLAG>
              <ns6:REQUESTED_DELIVERY_DATE>
                <xsl:value-of select="db:c_REQUESTED_DELIVERY_DATE"/>
              </ns6:REQUESTED_DELIVERY_DATE>
              <ns6:DATE_DELIVERED>
                <xsl:value-of select="db:c_DATE_DELIVERED"/>
              </ns6:DATE_DELIVERED>
              <ns6:LAST_UPDATE_DATE>
                <xsl:value-of select="/db:fetchOracleOraderLinesOutputCollection/db:fetchOracleOraderLinesOutput/db:c_LAST_UPDATE_DATE"/>
              </ns6:LAST_UPDATE_DATE>
              <ns6:LAST_UPDATED_BY>
                <xsl:value-of select="/db:fetchOracleOraderLinesOutputCollection/db:fetchOracleOraderLinesOutput/db:c_LAST_UPDATED_BY"/>
              </ns6:LAST_UPDATED_BY>
              <ns6:CREATION_DATE>
                <xsl:value-of select="/db:fetchOracleOraderLinesOutputCollection/db:fetchOracleOraderLinesOutput/db:c_CREATION_DATE"/>
              </ns6:CREATION_DATE>
              <ns6:CREATED_BY>
                <xsl:value-of select="/db:fetchOracleOraderLinesOutputCollection/db:fetchOracleOraderLinesOutput/db:c_CREATED_BY"/>
              </ns6:CREATED_BY>
              <ns6:SOA_FLAG>
                <xsl:value-of select="/db:fetchOracleOraderLinesOutputCollection/db:fetchOracleOraderLinesOutput/db:c_SOA_FLAG"/>
              </ns6:SOA_FLAG>
              <ns6:SOA_ERRORMSG>
                <xsl:value-of select="/db:fetchOracleOraderLinesOutputCollection/db:fetchOracleOraderLinesOutput/db:c_SOA_ERRORMSG"/>
              </ns6:SOA_ERRORMSG>
              <ns6:PROCESS_FLAG>
                <xsl:value-of select="db:c_PROCESS_FLAG"/>
              </ns6:PROCESS_FLAG>
              <ns6:PROCESS_MESSAGE>
                <xsl:value-of select="db:c_PROCESS_MESSAGE"/>
              </ns6:PROCESS_MESSAGE>
              <ns6:OPEN_QTY>
                <xsl:value-of select="db:c_OPEN_QTY"/>
              </ns6:OPEN_QTY>
              <ns6:INVOICE_REFERENCE>
                <xsl:value-of select="db:c_INVOICE_REFERENCE"/>
              </ns6:INVOICE_REFERENCE>
              <ns6:INVENTORY_FLAG>
                <xsl:value-of select="db:c_INVENTORY_FLAG"/>
              </ns6:INVENTORY_FLAG>
              <ns6:CURRENCY_CODE>
                <xsl:value-of select="db:b_CURRENCY_CODE"/>
              </ns6:CURRENCY_CODE>
            </ns5:SyncOEOrderLineDetails>
          </xsl:for-each>
        </ns5:SyncOEOrders>
      </ns1:DataArea>
    </ns1:ProcessSyncOEOrders>
  </xsl:template>
</xsl:stylesheet>