<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:tns="http://soap.sforce.com/schemas/class/OrderIntegrationService" xmlns:ns3="http://www.sunpowercorp.com/order/Verb/VerbCommonTypes/V1" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://www.example.org/CreateSalesOrderEBSWSDL" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns6="http://www.sunpowercorp.com/Noun/OracleSFDCNoItemOrders/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns7="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns4="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:ns2="http://www.sunpowercorp.com/SFDCSyncLeaseCustomerReq/xsd/v1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:client="http://xmlns.oracle.com/OnLineSalesOrder/CreateSalesOrderSFDCReq/CreateSalesOrderSFDCReq" xmlns:ns5="http://www.sunpowercorp.com/Common/OracleSFDCNoItemOrdersCommonTypes/V1" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessOracleSFDCNoItemOrders/V1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl tns plnk soap wsdl ns7 ns2 client xsd ns3 ns0 ns6 ns4 ns5 ns1 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/GetNewOrder.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetNewOrdersResponse" namespace="http://soap.sforce.com/schemas/class/OrderIntegrationService"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/CreateSalesOrderSFDCReq.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Inputparam" namespace="http://www.sunpowercorp.com/SFDCSyncLeaseCustomerReq/xsd/v1"/>
            <oracle-xsl-mapper:param name="Inputparam"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7004/CreateSalesOrderEBS/Proxy/CreateSalesOrderEBSPS?wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessOracleSFDCNoItemOrdersReq" namespace="http://www.sunpowercorp.com/BOD/ProcessOracleSFDCNoItemOrders/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [FRI OCT 07 15:33:07 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="Inputparam"/>
  <xsl:template match="/">
    <ns1:ProcessOracleSFDCNoItemOrdersReq>
      <ns1:DataArea>
        <ns3:process>
          <xsl:text disable-output-escaping="no">SFDC</xsl:text>
        </ns3:process>
        <ns3:callService>
          <xsl:value-of select="$Inputparam/ns2:Inputparam/ns2:finalLoop"/>
        </ns3:callService>
        <xsl:variable name="Index" select="number($Inputparam/ns2:Inputparam/ns2:iteration)"/>
        <ns6:OracleSFDCNoItemOrderHeader>
          <xsl:for-each select="/tns:GetNewOrdersResponse/tns:result/tns:orders[$Index]/tns:orderHeader">
            <ns6:OracleSFDCNoItemOrderDetailsHeader>
              <ns5:SFDC_ID>
                <xsl:value-of select="tns:OrderId"/>
              </ns5:SFDC_ID>
              <ns5:SFDC_SHIPTO>
                <xsl:value-of select="tns:ShipToSiteID"/>
              </ns5:SFDC_SHIPTO>
              <ns5:SFDC_BILLTO>
                <xsl:value-of select="tns:BillToSiteID"/>
              </ns5:SFDC_BILLTO>
              <ns5:SFDC_SHIPTO_CONTACT_ID>
                <xsl:value-of select="tns:ShipToContactID"/>
              </ns5:SFDC_SHIPTO_CONTACT_ID>
              <ns5:SFDC_BILLTO_CONTACT_ID>
                <xsl:value-of select="tns:BillToContactID"/>
              </ns5:SFDC_BILLTO_CONTACT_ID>
              <ns5:SFDC_PARTNER_ID>
                <xsl:value-of select="tns:PartnerId"/>
              </ns5:SFDC_PARTNER_ID>
              <ns5:SFDC_HOMEOWNER_ID>
                <xsl:value-of select="tns:HomeownerId"/>
              </ns5:SFDC_HOMEOWNER_ID>
              <ns5:SFDC_TPO_ID>
                <xsl:value-of select="tns:ThirdPartyOwnerId"/>
              </ns5:SFDC_TPO_ID>
              <ns5:ADJUSTED_AMOUNT>
                <xsl:value-of select="tns:DeliveryCharges"/>
              </ns5:ADJUSTED_AMOUNT>
              <ns5:ORDER_NUMBER>
                <xsl:value-of select="tns:OracleOrderNumber"/>
              </ns5:ORDER_NUMBER>
              <ns5:DSR_EMAIL_ID>
                <xsl:value-of select="tns:PrimaryPSREmail"/>
              </ns5:DSR_EMAIL_ID>
              <ns5:CUST_PO_NUMBER>
                <xsl:value-of select="tns:PONumber"/>
              </ns5:CUST_PO_NUMBER>
              <ns5:SHIPPING_METHOD>
                <xsl:value-of select="tns:ShippingMethod"/>
              </ns5:SHIPPING_METHOD>
              <ns5:SPECIAL_INSTRUCTIONS>
                <xsl:value-of select="tns:SpecialInstructions"/>
              </ns5:SPECIAL_INSTRUCTIONS>
              <ns5:TAX_FLAG>
                <xsl:value-of select="tns:IsTaxibleOrder"/>
              </ns5:TAX_FLAG>
              <ns5:ORDER_CURRENCY_CODE>
                <xsl:value-of select="tns:CurrencyISOCode"/>
              </ns5:ORDER_CURRENCY_CODE>
              <ns5:REQUESTED_DELIVERY_DATE>
                <xsl:value-of select="tns:RequestedDeliveryDate"/>
              </ns5:REQUESTED_DELIVERY_DATE>
              <ns5:SMARTPACK_FLAG>
                <xsl:value-of select="tns:IsSmartPack"/>
              </ns5:SMARTPACK_FLAG>
              <ns5:ORDER_STATUS>
                <xsl:value-of select="tns:OrderStatus"/>
              </ns5:ORDER_STATUS>
              <ns5:NEW_ORDER_CLASS>
                <xsl:value-of select="tns:SmartPackMountingType"/>
              </ns5:NEW_ORDER_CLASS>
              <ns5:INVERTER_TYPE>
                <xsl:value-of select="tns:SmartPackInverterType"/>
              </ns5:INVERTER_TYPE>
              <ns5:VENDOR_NUMBER>
                <xsl:value-of select="tns:OracleVendorNumber"/>
              </ns5:VENDOR_NUMBER>
              <ns5:VENDOR_SITE_CODE>
                <xsl:value-of select="tns:OracleVendorSiteCode"/>
              </ns5:VENDOR_SITE_CODE>
              <ns5:LEASE_NUMBER>
                <xsl:value-of select="tns:LeaseNumber"/>
              </ns5:LEASE_NUMBER>
              <ns5:CUSTOMER_SYNC>
                <xsl:text disable-output-escaping="no">P</xsl:text>
              </ns5:CUSTOMER_SYNC>
              <xsl:variable name="salesType" select="tns:SalesType"/>
              <ns5:SALES_TYPE>
                <xsl:value-of select="dvm:lookupValue(&quot;CUSTOMER_SITES_STATUS.dvm&quot;,&quot;SFDC&quot;,$salesType,&quot;Ebiz&quot;,&quot;&quot;)"/>
              </ns5:SALES_TYPE>
              <ns5:CUSTOMER_ORDER_LINK_ID>
                <xsl:value-of select="$Inputparam/ns2:Inputparam/ns2:orderAccountLinkId"/>
              </ns5:CUSTOMER_ORDER_LINK_ID>
              <ns5:TRANSACTION_STATUS>
                <xsl:value-of select="tns:TransactionStatus"/>
              </ns5:TRANSACTION_STATUS>
              <xsl:variable name="channelType" select="tns:ChannelType"/>
              <ns5:CHANNEL_TYPE>
                <xsl:value-of select="dvm:lookupValue(&quot;CUSTOMER_SITES_STATUS.dvm&quot;,&quot;SFDC&quot;,$channelType,&quot;Ebiz&quot;,&quot;&quot;)"/>
              </ns5:CHANNEL_TYPE>
              <ns5:PAYMENT_TYPE>
                <xsl:value-of select="tns:PaymentType"/>
              </ns5:PAYMENT_TYPE>
              <ns5:TAX_IDENTIFIER>
                <xsl:value-of select="tns:TaxIdentifier"/>
              </ns5:TAX_IDENTIFIER>
              <ns5:OK_TO_SHIP_FLAG>
              <xsl:value-of select="tns:OkToShip"/>
              </ns5:OK_TO_SHIP_FLAG>
                <ns5:SYSTEM_COUNT>
              <xsl:value-of select="tns:NumberOfSystems"/>
              </ns5:SYSTEM_COUNT>            
              <ns5:RACKING_INCLUDED>
               <xsl:value-of select="tns:RackingOptOut"/>
              </ns5:RACKING_INCLUDED>
           <ns5:MONITORING_SYSTEM_OPT_OUT>
               <xsl:value-of select="tns:MonitoringOptOut"/>
              </ns5:MONITORING_SYSTEM_OPT_OUT>
              
              <xsl:for-each select="tns:allLineItem">
                <ns6:OracleSFDCNoItemOrderDetailsLine>
                  <ns5:SFDC_ID>
                    <xsl:value-of select="tns:OrderId"/>
                  </ns5:SFDC_ID>
                  <ns5:SFDC_ORDER_LINE_ID>
                    <xsl:value-of select="tns:OrderLineId"/>
                  </ns5:SFDC_ORDER_LINE_ID>
                  <ns5:LINE_NUMBER>
                    <xsl:value-of select="tns:OrderLineNumber"/>
                  </ns5:LINE_NUMBER>
                  <ns5:INVENTORY_ITEM_ID>
                    <xsl:value-of select="tns:ItemID"/>
                  </ns5:INVENTORY_ITEM_ID>
                  <ns5:REQUESTED_QTY>
                    <xsl:value-of select="tns:Quantity"/>
                  </ns5:REQUESTED_QTY>
                  <ns5:UNIT_PRICE>
                    <xsl:value-of select="tns:UnitPrice"/>
                  </ns5:UNIT_PRICE>
                  <ns5:ORDER_LINE_TYPE>
                    <xsl:value-of select="tns:OracleLineType"/>
                  </ns5:ORDER_LINE_TYPE>
                  <ns5:PRODUCT_TYPE>
                    <xsl:value-of select="tns:SmartPackItem"/>
                  </ns5:PRODUCT_TYPE>
                  <ns5:ITEM_TYPE>
                    <xsl:value-of select="tns:ItemType"/>
                  </ns5:ITEM_TYPE>
                  <ns5:VENDORNUMBER>
                    <xsl:value-of select="tns:OracleVendorNumber"/>
                  </ns5:VENDORNUMBER>
                  <ns5:VENDORSITECODE>
                    <xsl:value-of select="tns:OracleVendorSiteCode"/>
                  </ns5:VENDORSITECODE>
                  <ns5:LINE_REQUEST_DATE>
                    <xsl:value-of select="tns:RequestedDeliveryDate"/>
                  </ns5:LINE_REQUEST_DATE>
                   <ns5:VENDOR_TYPE>
                    <xsl:value-of select="tns:VendorRole"/>
                  </ns5:VENDOR_TYPE>
                </ns6:OracleSFDCNoItemOrderDetailsLine>
              </xsl:for-each>
            </ns6:OracleSFDCNoItemOrderDetailsHeader>
          </xsl:for-each>
        </ns6:OracleSFDCNoItemOrderHeader>
      </ns1:DataArea>
    </ns1:ProcessOracleSFDCNoItemOrdersReq>
  </xsl:template>
</xsl:stylesheet>