<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ns3="http://www.sunpowercorp.com/order/Verb/VerbCommonTypes/V1" xmlns:client="http://xmlns.oracle.com/OnLineSalesOrder/UpdateSalesOrderResponseOracleReq/UpdateSalesOrderResponseOracleReq" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns6="http://www.sunpowercorp.com/Noun/OracleSFDCNoItemOrders/V1" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/SelectSalesOrderEBS" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OnLineSalesOrder/UpdateSalesOrderResponseOracleReq/SelectSalesOrderEBS" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns4="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:ns1="http://www.sunpowercorp.com/SFDCSyncLeaseCustomerReq/xsd/v1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns5="http://www.sunpowercorp.com/Common/OracleSFDCNoItemOrdersCommonTypes/V1" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns2="http://www.sunpowercorp.com/BOD/ProcessOracleSFDCNoItemOrders/V1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns0="http://www.example.org/UpdateSalesOrderResponseWSDL" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl client db plnk wsdl tns ns1 xsd ns3 ns6 soap ns4 ns5 ns2 ns0 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/UpdateSalesOrderResponseOracleReq.wsdl"/>
            <oracle-xsl-mapper:rootElement name="process" namespace="http://xmlns.oracle.com/OnLineSalesOrder/UpdateSalesOrderResponseOracleReq/UpdateSalesOrderResponseOracleReq"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SelectSalesOrderEBS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="SelectSalesOrderEBSOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SelectSalesOrderEBS"/>
            <oracle-xsl-mapper:param name="InvSelectSalesOrderEBS_OV.SelectSalesOrderEBSOutputCollection"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7004/UpdateSalesOrderResponseEBS/Proxy/UpdateSalesOrderResponsePS?wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessOracleSFDCNoItemOrdersRes" namespace="http://www.sunpowercorp.com/BOD/ProcessOracleSFDCNoItemOrders/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON OCT 10 15:26:18 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="InvSelectSalesOrderEBS_OV.SelectSalesOrderEBSOutputCollection"/>
  <xsl:template match="/">
    <ns2:ProcessOracleSFDCNoItemOrdersRes>
      <ns2:DataArea>
        <ns3:process>
          <xsl:value-of select="/client:process/client:input"/>
        </ns3:process>
        <ns6:OracleSFDCNoItemOrder>
          <xsl:for-each select="$InvSelectSalesOrderEBS_OV.SelectSalesOrderEBSOutputCollection/db:SelectSalesOrderEBSOutputCollection/db:SelectSalesOrderEBSOutput">
            <ns6:OracleSFDCNoItemOrderDetails>
              <ns5:SFDC_ID>
                <xsl:value-of select="db:SFDC_ID"/>
              </ns5:SFDC_ID>
              <ns5:ORDER_STATUS>
                <xsl:value-of select="db:ORDER_STATUS"/>
              </ns5:ORDER_STATUS>
              <ns5:INTERFACE_MESSAGE>
                <xsl:value-of select="db:INTERFACE_MESSAGE"/>
              </ns5:INTERFACE_MESSAGE>
              <ns5:ORDER_NUMBER>
                <xsl:value-of select="db:ORDER_NUMBER"/>
              </ns5:ORDER_NUMBER>
              <ns5:CREATION_DATE>
                <xsl:value-of select="db:CREATION_DATE"/>
              </ns5:CREATION_DATE>
              <ns5:LAST_UPDATE_DATE>
                <xsl:value-of select="db:LAST_UPDATE_DATE"/>
              </ns5:LAST_UPDATE_DATE>
              <ns5:POSITION>
                <xsl:value-of select="position()"/>
              </ns5:POSITION>
            </ns6:OracleSFDCNoItemOrderDetails>
          </xsl:for-each>
        </ns6:OracleSFDCNoItemOrder>
      </ns2:DataArea>
    </ns2:ProcessOracleSFDCNoItemOrdersRes>
  </xsl:template>
</xsl:stylesheet>