<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:tns="http://www.onfulfillment.com/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:ns3="http://www.sunpowercorp.com/Common/SunPowerStoreONFToSFDCDetailsCommonTypes/V1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns0="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:client="http://www.sunpowercorp.com/SunPowerStoreONFToSFDC/SunPowerStoreSvc/SunPowerStoreCanonical" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:s1="http://www.onfulfillment.com" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns2="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns4="http://www.sunpowercorp.com/Noun/SunPowerStoreONFToSFDC/V1" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessSunPowerStoreONFToSFDC/V1" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl tns tm soap12 soapenc soap wsdl mime s1 http xsd ns3 ns0 client ns2 ns4 ns1 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/Onlinefulfillment.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetOrdersByDateResponse" namespace="http://www.onfulfillment.com/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7004/SunpowerStoreSvc/Proxy/SunpowerStorePS?wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessSunPowerStoreONFToSFDC" namespace="http://www.sunpowercorp.com/BOD/ProcessSunPowerStoreONFToSFDC/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [FRI OCT 07 19:42:23 IST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns1:ProcessSunPowerStoreONFToSFDC>
      <ns1:DataArea>
        <ns4:SunPowerStoreONFToSFDC>
          <ns4:SunPowerStoreONFToSFDCDetails>
            <xsl:if test="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/@version">
              <xsl:attribute name="ns3:version">
                <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/@version"/>
              </xsl:attribute>
            </xsl:if>
            <ns4:OrderResponse>
              <ns4:Summary>
                <ns4:DateRange>
                  <ns4:Start>
                    <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Summary/s1:DateRange/s1:Start"/>
                  </ns4:Start>
                  <ns4:End>
                    <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Summary/s1:DateRange/s1:End"/>
                  </ns4:End>
                </ns4:DateRange>
                <ns3:RequestIdentifier>
                  <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Summary/s1:RequestIdentifier"/>
                </ns3:RequestIdentifier>
              </ns4:Summary>
              <ns4:Orders>
                <xsl:for-each select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order">
                  <xsl:variable name="pos" select="position()"/>
                  <ns4:Order>
                    <xsl:if test="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:ID">
                      <ns4:ID>
                        <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:ID"/>
                      </ns4:ID>
                    </xsl:if>
                    <ns3:OrderNumber>
                      <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:OrderNumber"/>
                    </ns3:OrderNumber>
                    <ns3:CreateDate>
                      <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:CreateDate"/>
                    </ns3:CreateDate>
                    <ns4:User>
                      <xsl:if test="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:User">
                        <ns4:ID>
                          <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:User/s1:ID"/>
                        </ns4:ID>
                      </xsl:if>
                      <ns3:LoginID>
                        <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:User/s1:LoginID"/>
                      </ns3:LoginID>
                    </ns4:User>
                    <xsl:if test="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:BillingAddress">
                      <ns4:BillingAddress>
                        <xsl:if test="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:BillingAddress/s1:ID">
                          <ns4:ID>
                            <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:BillingAddress/s1:ID"/>
                          </ns4:ID>
                        </xsl:if>
                        <ns3:Description>
                          <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:BillingAddress/s1:Description"/>
                        </ns3:Description>
                        <ns3:Address1>
                          <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:BillingAddress/s1:Address1"/>
                        </ns3:Address1>
                        <ns3:Address2>
                          <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:BillingAddress/s1:Address2"/>
                        </ns3:Address2>
                        <ns3:Address3>
                          <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:BillingAddress/s1:Address3"/>
                        </ns3:Address3>
                        <ns3:Address4>
                          <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:BillingAddress/s1:Address4"/>
                        </ns3:Address4>
                        <ns3:City>
                          <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:BillingAddress/s1:City"/>
                        </ns3:City>
                        <ns3:State>
                          <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:BillingAddress/s1:State"/>
                        </ns3:State>
                        <ns3:Zip>
                          <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:BillingAddress/s1:Zip"/>
                        </ns3:Zip>
                        <ns3:Country>
                          <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:BillingAddress/s1:Country"/>
                        </ns3:Country>
                        <ns3:CompanyName>
                          <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:BillingAddress/s1:CompanyName"/>
                        </ns3:CompanyName>
                        <ns3:Attn>
                          <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:BillingAddress/s1:Attn"/>
                        </ns3:Attn>
                      </ns4:BillingAddress>
                    </xsl:if>
                    <ns4:ShippingAddress>
                      <ns3:Description>
                        <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:ShippingAddress/s1:Description"/>
                      </ns3:Description>
                      <ns3:Address1>
                        <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:ShippingAddress/s1:Address1"/>
                      </ns3:Address1>
                      <ns3:Address2>
                        <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:ShippingAddress/s1:Address2"/>
                      </ns3:Address2>
                      <ns3:Address3>
                        <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:ShippingAddress/s1:Address3"/>
                      </ns3:Address3>
                      <ns3:Address4>
                        <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:ShippingAddress/s1:Address4"/>
                      </ns3:Address4>
                      <ns3:City>
                        <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:ShippingAddress/s1:City"/>
                      </ns3:City>
                      <ns3:State>
                        <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:ShippingAddress/s1:State"/>
                      </ns3:State>
                      <ns3:Zip>
                        <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:ShippingAddress/s1:Zip"/>
                      </ns3:Zip>
                      <ns3:Country>
                        <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:ShippingAddress/s1:Country"/>
                      </ns3:Country>
                      <ns3:PhoneNumber>
                        <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:ShippingAddress/s1:PhoneNumber"/>
                      </ns3:PhoneNumber>
                      <ns3:CompanyName>
                        <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:ShippingAddress/s1:CompanyName"/>
                      </ns3:CompanyName>
                      <ns3:Attn>
                        <xsl:value-of select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:ShippingAddress/s1:Attn"/>
                      </ns3:Attn>
                    </ns4:ShippingAddress>
                    <xsl:if test="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:OrderDetails">
                      <ns4:OrderDetails>
                        <xsl:for-each select="/tns:GetOrdersByDateResponse/tns:GetOrdersByDateResult/s1:GetOrdersResponse/s1:Orders/s1:Order[$pos]/s1:OrderDetails/s1:OrderDetail">
                          <ns4:OrderDetail>
                            <ns3:OrderType>
                              <xsl:value-of select="s1:OrderType"/>
                            </ns3:OrderType>
                            <ns3:ProductName>
                              <xsl:value-of select="s1:ProductName"/>
                            </ns3:ProductName>
                            <xsl:if test="s1:SKU">
                              <ns4:SKU>
                                <xsl:if test="s1:SKU/s1:ID">
                                  <ns4:ID>
                                    <xsl:value-of select="s1:SKU/s1:ID"/>
                                  </ns4:ID>
                                </xsl:if>
                                <ns3:Name>
                                  <xsl:value-of select="s1:SKU/s1:Name"/>
                                </ns3:Name>
                              </ns4:SKU>
                            </xsl:if>
                            <xsl:if test="s1:Quantity !=''">
                              <ns3:Quantity>
                                <xsl:value-of select="s1:Quantity"/>
                              </ns3:Quantity>
                            </xsl:if>
                            <xsl:if test="s1:Price">
                              <ns4:Price>
                                <ns4:Cost>
                                  <xsl:if test="s1:Price/s1:Cost/s1:Customer">
                                    <ns4:Customer>
                                      <xsl:if test="s1:Price/s1:Cost/s1:Customer/@Currency">
                                        <xsl:attribute name="ns3:Currency">
                                          <xsl:value-of select="s1:Price/s1:Cost/s1:Customer/@Currency"/>
                                        </xsl:attribute>
                                      </xsl:if>
                                      <xsl:value-of select="s1:Price/s1:Cost/s1:Customer"/>
                                    </ns4:Customer>
                                  </xsl:if>
                                  <xsl:if test="s1:Price/s1:Cost/s1:Seller">
                                    <ns4:Seller>
                                      <xsl:if test="s1:Price/s1:Cost/s1:Seller/@Currency">
                                        <xsl:attribute name="ns3:Currency">
                                          <xsl:value-of select="s1:Price/s1:Cost/s1:Seller/@Currency"/>
                                        </xsl:attribute>
                                      </xsl:if>
                                      <xsl:value-of select="s1:Price/s1:Cost/s1:Seller"/>
                                    </ns4:Seller>
                                  </xsl:if>
                                  <xsl:if test="s1:Price/s1:Cost/s1:Shipping">
                                    <ns4:Shipping>
                                      <xsl:if test="s1:Price/s1:Cost/s1:Shipping/@Currency">
                                        <xsl:attribute name="ns3:Currency">
                                          <xsl:value-of select="s1:Price/s1:Cost/s1:Shipping/@Currency"/>
                                        </xsl:attribute>
                                      </xsl:if>
                                      <xsl:value-of select="s1:Price/s1:Cost/s1:Shipping"/>
                                    </ns4:Shipping>
                                  </xsl:if>
                                  <xsl:if test="s1:Price/s1:Cost/s1:Unit!=''">
                                    <ns4:Unit>
                                      <xsl:if test="s1:Price/s1:Cost/s1:Unit/@Currency">
                                        <xsl:attribute name="ns3:Currency">
                                          <xsl:value-of select="s1:Price/s1:Cost/s1:Unit/@Currency"/>
                                        </xsl:attribute>
                                      </xsl:if>
                                      <xsl:value-of select="s1:Price/s1:Cost/s1:Unit"/>
                                    </ns4:Unit>
                                  </xsl:if>
                                  <xsl:if test="s1:Price/s1:Cost/s1:SellerMisc!=''">
                                    <ns4:SellerMisc>
                                      <xsl:if test="s1:Price/s1:Cost/s1:SellerMisc/@Currency">
                                        <xsl:attribute name="ns3:Currency">
                                          <xsl:value-of select="s1:Price/s1:Cost/s1:SellerMisc/@Currency"/>
                                        </xsl:attribute>
                                      </xsl:if>
                                      <xsl:value-of select="s1:Price/s1:Cost/s1:SellerMisc"/>
                                    </ns4:SellerMisc>
                                  </xsl:if>
                                  <xsl:if test="s1:Price/s1:Cost/s1:SellerStoreDiscount!=''">
                                    <ns4:SellerStoreDiscount>
                                      <xsl:if test="s1:Price/s1:Cost/s1:SellerStoreDiscount/@Currency">
                                        <xsl:attribute name="ns3:Currency">
                                          <xsl:value-of select="s1:Price/s1:Cost/s1:SellerStoreDiscount/@Currency"/>
                                        </xsl:attribute>
                                      </xsl:if>
                                      <xsl:value-of select="s1:Price/s1:Cost/s1:SellerStoreDiscount"/>
                                    </ns4:SellerStoreDiscount>
                                  </xsl:if>
                                  <xsl:if test="s1:Price/s1:Cost/s1:SellerShipping!=''">
                                    <ns4:SellerShipping>
                                      <xsl:if test="s1:Price/s1:Cost/s1:SellerShipping/@Currency">
                                        <xsl:attribute name="ns3:Currency">
                                          <xsl:value-of select="s1:Price/s1:Cost/s1:SellerShipping/@Currency"/>
                                        </xsl:attribute>
                                      </xsl:if>
                                      <xsl:value-of select="s1:Price/s1:Cost/s1:SellerShipping"/>
                                    </ns4:SellerShipping>
                                  </xsl:if>
                                  <xsl:if test="s1:Price/s1:Cost/s1:CustomerStoreDiscount!=''">
                                    <ns4:CustomerStoreDiscount>
                                      <xsl:if test="s1:Price/s1:Cost/s1:CustomerStoreDiscount/@Currency">
                                        <xsl:attribute name="ns3:Currency">
                                          <xsl:value-of select="s1:Price/s1:Cost/s1:CustomerStoreDiscount/@Currency"/>
                                        </xsl:attribute>
                                      </xsl:if>
                                      <xsl:value-of select="s1:Price/s1:Cost/s1:CustomerStoreDiscount"/>
                                    </ns4:CustomerStoreDiscount>
                                  </xsl:if>
                                  <xsl:if test="s1:Price/s1:Cost/s1:Postage!=''">
                                    <ns4:Postage>
                                      <xsl:if test="s1:Price/s1:Cost/s1:Postage/@Currency">
                                        <xsl:attribute name="ns3:Currency">
                                          <xsl:value-of select="s1:Price/s1:Cost/s1:Postage/@Currency"/>
                                        </xsl:attribute>
                                      </xsl:if>
                                      <xsl:value-of select="s1:Price/s1:Cost/s1:Postage"/>
                                    </ns4:Postage>
                                  </xsl:if>
                                  <xsl:if test="s1:Price/s1:Cost/s1:CustomerMisc!=''">
                                    <ns4:CustomerMisc>
                                      <xsl:if test="s1:Price/s1:Cost/s1:CustomerMisc/@Currency">
                                        <xsl:attribute name="ns3:Currency">
                                          <xsl:value-of select="s1:Price/s1:Cost/s1:CustomerMisc/@Currency"/>
                                        </xsl:attribute>
                                      </xsl:if>
                                      <xsl:value-of select="s1:Price/s1:Cost/s1:CustomerMisc"/>
                                    </ns4:CustomerMisc>
                                  </xsl:if>
                                </ns4:Cost>
                                <xsl:if test="s1:Price/s1:Tax">
                                  <ns4:Tax>
                                    <xsl:if test="s1:Price/s1:Tax/s1:CustomerSales!=''">
                                      <ns4:CustomerSales>
                                        <xsl:if test="s1:Price/s1:Tax/s1:CustomerSales/@Currency">
                                          <xsl:attribute name="ns3:Currency">
                                            <xsl:value-of select="s1:Price/s1:Tax/s1:CustomerSales/@Currency"/>
                                          </xsl:attribute>
                                        </xsl:if>
                                        <xsl:value-of select="s1:Price/s1:Tax/s1:CustomerSales"/>
                                      </ns4:CustomerSales>
                                    </xsl:if>
                                    <xsl:if test="s1:Price/s1:Tax/s1:DirectAcctSales!=''">
                                      <ns4:DirectAcctSales>
                                        <xsl:if test="s1:Price/s1:Tax/s1:DirectAcctSales/@Currency">
                                          <xsl:attribute name="ns3:Currency">
                                            <xsl:value-of select="s1:Price/s1:Tax/s1:DirectAcctSales/@Currency"/>
                                          </xsl:attribute>
                                        </xsl:if>
                                        <xsl:value-of select="s1:Price/s1:Tax/s1:DirectAcctSales"/>
                                      </ns4:DirectAcctSales>
                                    </xsl:if>
                                  </ns4:Tax>
                                </xsl:if>
                              </ns4:Price>
                            </xsl:if>
                            <ns4:Shipping>
                              <ns3:Date>
                                <xsl:value-of select="s1:Shipping/s1:Date"/>
                              </ns3:Date>
                              <ns3:Method>
                                <xsl:value-of select="s1:Shipping/s1:Method"/>
                              </ns3:Method>
                              <ns3:TrackingNumber>
                                <xsl:value-of select="s1:Shipping/s1:TrackingNumber"/>
                              </ns3:TrackingNumber>
                            </ns4:Shipping>
                            <ns4:ClientStatus>
                              <ns3:Value>
                                <xsl:value-of select="s1:ClientStatus/s1:Value"/>
                              </ns3:Value>
                            </ns4:ClientStatus>
                          </ns4:OrderDetail>
                        </xsl:for-each>
                      </ns4:OrderDetails>
                    </xsl:if>
                  </ns4:Order>
                </xsl:for-each>
              </ns4:Orders>
            </ns4:OrderResponse>
          </ns4:SunPowerStoreONFToSFDCDetails>
        </ns4:SunPowerStoreONFToSFDC>
      </ns1:DataArea>
    </ns1:ProcessSunPowerStoreONFToSFDC>
  </xsl:template>
</xsl:stylesheet>