<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
    
     targetNamespace="http://soap.sforce.com/schemas/class/OrderIntegrationService"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://soap.sforce.com/schemas/class/OrderIntegrationService"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="GetNewOrder">
        <plnk:role name="OrderIntegrationServicePortType">
            <plnk:portType name="tns:OrderIntegrationServicePortType"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://soap.sforce.com/schemas/class/OrderIntegrationService"
                 location="GetNewOrder.wsdl"/>
</wsdl:definitions>
