
  CREATE TABLE "SOACUSTOM"."OSB_ERROR_LOG" 
   (	"INSTANCE_NUMBER" NUMBER NOT NULL ENABLE, 
	"INTERFACE_NUMBER" VARCHAR2(20 BYTE), 
	"PROCESS_NAME" VARCHAR2(200 BYTE), 
	"COMPONENT_NAME" VARCHAR2(200 BYTE), 
	"UNIQUE_IDENTIFIER" VARCHAR2(200 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"FAULT_SYSTEMNAME" VARCHAR2(20 BYTE), 
	"FAULT_CODE" VARCHAR2(20 BYTE), 
	"FAULT_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"FAULT_MESSAGE" VARCHAR2(4000 BYTE), 
	"FAULTED_DATE_TIME" DATE, 
	"SEVERITY" VARCHAR2(20 BYTE), 
	"CORRECTIVE_ACTION" VARCHAR2(4000 BYTE), 
	"EMAIL_SENT" VARCHAR2(20 BYTE), 
	"OPEN_SERVICE_TICKET" VARCHAR2(20 BYTE), 
	"ATTRIBUTE1" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE2" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE3" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE4" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST_SCHEMA" ;
