
  CREATE TABLE "SOACUSTOM"."OSB_AUDIT_LOG_HEADER" 
   (	"INSTANCE_ID" NUMBER NOT NULL ENABLE, 
	"INTERFACE_NUMBER" VARCHAR2(200 BYTE), 
	"PROCESS_NAME" VARCHAR2(200 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"UNIQ_IDENTIFIER" VARCHAR2(200 BYTE), 
	"PARENT_ID" VARCHAR2(20 BYTE), 
	"COMPONENT_NAME" VARCHAR2(200 BYTE), 
	"PROCESS_STATUS" VARCHAR2(200 BYTE), 
	"PAYLOAD" BLOB, 
	"CREATED_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"FAULT_MESSAGE" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE1" VARCHAR2(2000 BYTE), 
	"ATTRIBUTE2" VARCHAR2(2000 BYTE), 
	"ATTRIBUTE3" VARCHAR2(2000 BYTE), 
	"ATTRIBUTE4" VARCHAR2(2000 BYTE), 
	"ATTRIBUTE5" VARCHAR2(2000 BYTE), 
	"ATTRIBUTE6" VARCHAR2(4000 BYTE), 
	"ATTRIBUTE7" NUMBER, 
	"ATTRIBUTE8" NUMBER, 
	 CONSTRAINT "OSB_AUDIT_LOG_HEADER_PK" PRIMARY KEY ("INSTANCE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST_SCHEMA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEST_SCHEMA" 
 LOB ("PAYLOAD") STORE AS BASICFILE (
  TABLESPACE "TEST_SCHEMA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
