<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessOracleSFDCItem/V1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns14="http://www.sunpowercorp.com/Noun/OracleSFDCItem/V1" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns0="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns10="http://www.sunpowercorp.com/OracleIndexItems" xmlns:ns13="http://www.sunpowercorp.com/Common/OracleSFDCItemCommonTypes/V1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns7="http://www.sunpowercorp.com/SunPowerDevelopment/DealerPartnerCreditINFO/EnqueSyncCreditHoldLimit/initParams/xsd/v1" xmlns:ns5="http://www.sunpowercorp.com/MergedItems" xmlns:ns2="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns12="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns4="http://www.sunpowercorp.com/SOAUtilityServices/CommonLoggingService/CommonLoggingService_BPEL" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns8="http://www.sunpowercorp.com/SFDCItems" xmlns:ns11="http://www.sunpowercorp.com/SunPowerDevelopment/utility/EmailContent/xsd/V1" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:client="http://www.sunpowercorp.com/OnlineOrderingItemOnlyOracleToSFDC/OracleSFDCItemPRODProv/OracleSFDCItemPRODProv_BPEL" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns9="http://schemas.oracle.com/bpel/extension" xmlns:ns6="http://www.sunpowercorp.com/OracleItems" xmlns:ns3="urn:partner.soap.sforce.com" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns1 ns14 ns0 plnk ns10 ns13 wsdl ns7 ns5 ns2 ns12 ns4 ns8 ns11 client xsd ns9 ns6 ns3 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/OracleSFDCItemPRODProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessOracleSFDCItem" namespace="http://www.sunpowercorp.com/BOD/ProcessOracleSFDCItem/V1"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/OracleSFDCItemPRODProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="EmailContent" namespace="http://www.sunpowercorp.com/SunPowerDevelopment/utility/EmailContent/xsd/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON OCT 10 17:27:41 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns11:EmailContent>
      <ns11:Subject>
        <xsl:text disable-output-escaping="no">ALERT: Invalid Item Status Received from Oracle</xsl:text>
      </ns11:Subject>
      <xsl:variable name="tableHeader" select="&quot;&lt;table border='1'>&lt;tr>&lt;th bgcolor='#C0C0C0'>&lt;b>Item No&lt;/b>&lt;/th> &lt;th bgcolor='#C0C0C0'>&lt;b>Item Status&lt;/b>&lt;/th>&lt;/th> &lt;/tr> &quot;"/>
      <xsl:variable name="tableBody">
        <xsl:for-each select="/ns1:ProcessOracleSFDCItem/ns1:DataArea/ns14:OracleSFDCItem/ns14:OracleSFDCItemDetails">
          <xsl:if test="dvm:lookupValue(&quot;ITEMSTATUS.dvm&quot;,&quot;Oracle&quot;,ns13:ITEM_STATUS_CODE,&quot;SFDC&quot;,&quot;ERROR&quot;) = &quot;ERROR&quot;">
            <xsl:value-of select="concat(&quot;&lt;tr>&lt;td>&quot;,ns13:ITEM_NUMBER,&quot;&lt;/td>&lt;td>&quot;,ns13:ITEM_STATUS_CODE,&quot;&lt;/td>&lt;/tr>&quot;)"/>
          </xsl:if>
        </xsl:for-each>
      </xsl:variable>
      <xsl:if test="$tableBody !=''">
        <ns11:body>
          <xsl:value-of select="concat(&quot;Dear Team &lt;br/> The following invalid item status codes received from Oracle for the respective items as mentioned in below table. All of these has been updated to salesforce as inactive i.e active__c=false &lt;br/> &lt;b>Interface Name: &lt;/b> OracleSFDCItemPROD &lt;br/>&quot;,$tableHeader,$tableBody,&quot;&lt;/table> &lt;br/> &lt;i> Note: This message was automatically generated, please do not reply to it &lt;/i> &lt;br/>&lt;br/>&lt;b>Thanks &amp; Regards&lt;/b>&lt;br/>System Admin&quot;)"/>
        </ns11:body>
      </xsl:if>
    </ns11:EmailContent>
  </xsl:template>
</xsl:stylesheet>