<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="2.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns6="http://TargetNamespace.com/SFDCLMSFlatFile" xmlns:ns9="http://www.sunpowercorp.com/MergeLmsRows" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns10="http://www.sunpowercorp.com/SunPowerDevelopment/DealerPartnerCreditINFO/EnqueSyncCreditHoldLimit/initParams/xsd/v1" xmlns:ns7="http://xmlns.oracle.com/testingapplication/CommonSFDCErrorLogService/CallCommSFDCErrMediator" xmlns:ns3="http://www.sunpowercorp.com/PlateauHRConectorFFData" xmlns:ns1="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:ens="urn:sobject.partner.soap.sforce.com" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:fns="urn:fault.partner.soap.sforce.com" xmlns:ns4="http://www.sunpowercorp.com/PlateauHRConectorFFAccountData" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:client="http://www.sunpowercorp.com/UserFeedOracleSFDCToLMS/SFDCLMSUsersDataLoadInterface/SFDCLMSUsersDataLoadInterface_BPEL" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns5="http://www.sunpowercorp.com/MergedRows" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns8="http://schemas.oracle.com/bpel/extension" xmlns:tns="urn:partner.soap.sforce.com" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl soap ens fns xsd tns plnk ns6 ns9 wsdl ns10 ns7 ns3 ns1 ns4 client ns5 ns8 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/partner.wsdl"/>
            <oracle-xsl-mapper:rootElement name="queryResponse" namespace="urn:partner.soap.sforce.com"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SFDCLMSUsersDataLoadInterface_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="MergeLmsRowsCollection" namespace="http://www.sunpowercorp.com/MergeLmsRows"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <oracle-xsl-mapper:named-template-schema>
         <oracle-xsl-mapper:template name="Tokenize">
            <oracle-xsl-mapper:mapSources/>
         </oracle-xsl-mapper:template>
      </oracle-xsl-mapper:named-template-schema>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [SAT OCT 08 16:55:14 IST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns9:MergeLmsRowsCollection>
      <xsl:for-each select="/tns:queryResponse/tns:result/tns:records">
        <xsl:variable name="pos" select="position()"/>
        <xsl:variable name="Tokens">
          <xsl:call-template name="Tokenize">
            <xsl:with-param name="input" select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:LMS_Job_ID__c"/>
          </xsl:call-template>
        </xsl:variable>
        <ns9:MergeLmsRowsItems>
          <xsl:choose>
          <xsl:when test="(((/tns:queryResponse/tns:result/tns:records[$pos]/ens:Portal_User_Type__c = &quot;LMS Only User&quot;) and (/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:Terminated__c = &quot;true&quot;))or            ((/tns:queryResponse/tns:result/tns:records[$pos]/ens:Portal_User_Type__c = &quot;SFDC User&quot;) and (/tns:queryResponse/tns:result/tns:records[$pos]/ens:IsActive = &quot;false&quot;)) or (/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:Account/ens:Status__c = &quot;Terminated&quot;))">
              <ns9:not_active>
                <xsl:text disable-output-escaping="no">Y</xsl:text>
              </ns9:not_active>
               </xsl:when>
           <xsl:when test="(((/tns:queryResponse/tns:result/tns:records[$pos]/ens:Portal_User_Type__c = &quot;LMS Only User&quot;) and (/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:Terminated__c = &quot;false&quot;)) or             ((/tns:queryResponse/tns:result/tns:records[$pos]/ens:Portal_User_Type__c = &quot;SFDC User&quot;) and (/tns:queryResponse/tns:result/tns:records[$pos]/ens:IsActive = &quot;true&quot;)))">
              <ns9:not_active>
                <xsl:text disable-output-escaping="no">N</xsl:text>
              </ns9:not_active>
            </xsl:when>
                 </xsl:choose>
          <!--
                    <xsl:when test='/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:Account/ens:Status__c = "Terminated"'>
              <ns9:not_active>
                <xsl:text disable-output-escaping="no">Y</xsl:text>
              </ns9:not_active>
            </xsl:when>
            <xsl:when test='(/tns:queryResponse/tns:result/tns:records[$pos]/ens:Portal_User_Type__c = "LMS Only User") and (/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:Terminated__c = "true")'>
              <ns9:not_active>
                <xsl:text disable-output-escaping="no">Y</xsl:text>
              </ns9:not_active>
               </xsl:when>
               <xsl:when test='(/tns:queryResponse/tns:result/tns:records[$pos]/ens:Portal_User_Type__c = "LMS Only User") and (/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:Terminated__c = "false")'>
              <ns9:not_active>
                <xsl:text disable-output-escaping="no">N</xsl:text>
              </ns9:not_active>
            </xsl:when>
            <xsl:when test='(/tns:queryResponse/tns:result/tns:records[$pos]/ens:Portal_User_Type__c = "SFDC User") and (/tns:queryResponse/tns:result/tns:records[$pos]/ens:IsActive = "false")'>
              <ns9:not_active>
                <xsl:text disable-output-escaping="no">Y</xsl:text>
              </ns9:not_active>
            </xsl:when>
            <xsl:when test='(/tns:queryResponse/tns:result/tns:records[$pos]/ens:Portal_User_Type__c = "SFDC User") and (/tns:queryResponse/tns:result/tns:records[$pos]/ens:IsActive = "true")'>
              <ns9:not_active>
                <xsl:text disable-output-escaping="no">N</xsl:text>
              </ns9:not_active>
            </xsl:when>
            -->
      
      
          
          <ns9:user_id>
            <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:Plateau_Id__c"/>
          </ns9:user_id>
          <ns9:first_name>
            <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:FirstName"/>
          </ns9:first_name>
          <ns9:last_name>
            <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:LastName"/>
          </ns9:last_name>
          <ns9:job_position_id>
            <xsl:value-of select="$Tokens/ns9:Tag[1.0]"/>
          </ns9:job_position_id>
          <ns9:job_position_description>
            <xsl:value-of select="$Tokens/ns9:Tag[1.0]"/>
          </ns9:job_position_description>
          <ns9:role>
            <xsl:text disable-output-escaping="no">VAR USER</xsl:text>
          </ns9:role>
          <ns9:domain_id>
            <xsl:value-of select="dvm:lookupValue(&quot;DomainID.dvm&quot;,&quot;KeyColumn&quot;,/tns:queryResponse/tns:result/tns:records[$pos]/ens:Country_Domain__c,&quot;ValueColumn&quot;,&quot;VAR-NA&quot;)"/>
          </ns9:domain_id>
          <ns9:organization_id>
            <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:Account/ens:AccountNumber"/>
          </ns9:organization_id>
          <ns9:organization_description>
            <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:Account/ens:Name"/>
          </ns9:organization_description>
          <ns9:state>
            <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:Account/ens:BillingState"/>
          </ns9:state>
          <ns9:country>
            <xsl:value-of select="dvm:lookupValue(&quot;Country.dvm&quot;,&quot;SFDC&quot;,/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:Account/ens:BillingCountry,&quot;LMS&quot;,&quot;&quot;)"/>
          </ns9:country>
          <ns9:region_id>
            <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:Account/ens:Territory__c"/>
          </ns9:region_id>
          <ns9:region_description>
            <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:Account/ens:Territory__c"/>
          </ns9:region_description>
          <ns9:email_address>
            <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:Email"/>
          </ns9:email_address>
          <ns9:hired_date>
            <xsl:value-of select="xp20:format-dateTime(/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:Account/ens:Authorized_Partner_Date__c,&quot;[MN,*-3]-[D01]-[Y0001] [H01]:[m01]:[s01]&quot;)"/>
          </ns9:hired_date>
          <ns9:supervisor>
            <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:LMS_Supervisor_ID__c"/>
          </ns9:supervisor>
          <ns9:account_code>
            <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:Account/ens:Integration_ID__c"/>
          </ns9:account_code>
          <ns9:phone_number_i>
            <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:Phone"/>
          </ns9:phone_number_i>
          <ns9:phone_number_description_i>
            <xsl:text disable-output-escaping="no">Primary</xsl:text>
          </ns9:phone_number_description_i>
          <ns9:phone_number_ii>
            <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:MobilePhone"/>
          </ns9:phone_number_ii>
          <ns9:phone_number_description_ii>
            <xsl:text disable-output-escaping="no">mobile</xsl:text>
          </ns9:phone_number_description_ii>
          <ns9:phone_number_iii>
            <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:HomePhone"/>
          </ns9:phone_number_iii>
          <ns9:phone_number_description_iii>
            <xsl:text disable-output-escaping="no">home</xsl:text>
          </ns9:phone_number_description_iii>
          <ns9:alternate_job_position_id>
            <xsl:value-of select="$Tokens/ns9:Tag[2.0]"/>
          </ns9:alternate_job_position_id>
          <ns9:shopping_account_type>
            <xsl:text disable-output-escaping="no">EXTERNAL</xsl:text>
          </ns9:shopping_account_type>
          <ns9:enable_shopping_account>
            <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:LMS_Role__c"/>
          </ns9:enable_shopping_account>
          <ns9:custom_column_100>
            <xsl:value-of select="dvm:lookupValue(&quot;Authorize100.dvm&quot;,&quot;KeyColumn&quot;,/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:Account/ens:Type,&quot;ValueColumn&quot;,&quot;&quot;)"/>
          </ns9:custom_column_100>
          <ns9:custom_column_110>
            <xsl:value-of select="dvm:lookupValue(&quot;Combo100.dvm&quot;,&quot;KeyColumn&quot;,/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:Account/ens:Type,&quot;ValueColumn&quot;,&quot;&quot;)"/>
          </ns9:custom_column_110>
          <ns9:custom_column_120>
            <xsl:value-of select="dvm:lookupValue(&quot;LMSRoleMap.dvm&quot;,&quot;KeyColumn&quot;,/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:LMS_Role__c,&quot;ValueColumn&quot;,&quot;&quot;)"/>
          </ns9:custom_column_120>
          <ns9:timezone>
            <xsl:value-of select="dvm:lookupValue(&quot;TimeZone.dvm&quot;,&quot;KeyColumn&quot;,/tns:queryResponse/tns:result/tns:records[$pos]/ens:Country_Domain__c,&quot;ValueColumn&quot;,&quot;&quot;)"/>
          </ns9:timezone>
          <ns9:language_id>
            <xsl:value-of select="dvm:lookupValue(&quot;LMSLanguages.dvm&quot;,&quot;KeyColumn&quot;,substring(/tns:queryResponse/tns:result/tns:records[$pos]/ens:LanguageLocaleKey,0.0,3.0),&quot;ValueColumn&quot;,&quot;English&quot;)"/>
          </ns9:language_id>
          <ns9:alt_job_position_id2>
            <xsl:value-of select="$Tokens/ns9:Tag[3.0]"/>
          </ns9:alt_job_position_id2>
          <ns9:alt_job_position_id3>
            <xsl:value-of select="$Tokens/ns9:Tag[4.0]"/>
          </ns9:alt_job_position_id3>
          <ns9:alt_job_position_id4>
            <xsl:value-of select="$Tokens/ns9:Tag[5.0]"/>
          </ns9:alt_job_position_id4>
          <ns9:alt_job_position_id5>
            <xsl:value-of select="$Tokens/ns9:Tag[5.0]"/>
          </ns9:alt_job_position_id5>
          <ns9:alt_job_position_id6>
            <xsl:value-of select="$Tokens/ns9:Tag[6.0]"/>
          </ns9:alt_job_position_id6>
          <ns9:end_of_row>
            <xsl:value-of select="/tns:queryResponse/tns:result/tns:records[$pos]/ens:Contact/ens:AccountId"/>
          </ns9:end_of_row>
        </ns9:MergeLmsRowsItems>
      </xsl:for-each>
    </ns9:MergeLmsRowsCollection>
  </xsl:template>
  <!--  User Defined Templates  -->
  <xsl:template name="Tokenize">
    <xsl:param name="input"/>
    <xsl:choose>
      <xsl:when test="contains($input,';')">
        <ns9:Tag>
          <xsl:value-of select="substring-before($input,';')"/>
        </ns9:Tag>
        <xsl:call-template name="Tokenize">
          <xsl:with-param name="input" select="substring-after($input,';')"/>
        </xsl:call-template>
      </xsl:when>
      <xsl:otherwise>
        <ns9:Tag>
          <xsl:value-of select="$input"/>
        </ns9:Tag>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>
</xsl:stylesheet>