<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:tns="http://www.sunpowercorp.com/PlateauHRConectorFFData" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns0="http://www.sunpowercorp.com/PlateauHRConectorFFAccountData" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.sunpowercorp.com/MergeLmsRows" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl tns ns0 xsd ns1 bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref ora socket ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/PlateauHRConectorFFData.xsd"/>
            <oracle-xsl-mapper:rootElement name="PlateauHRConectorFFDataCollection" namespace="http://www.sunpowercorp.com/PlateauHRConectorFFData"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/PlateauHRConectorFFAccountData.xsd"/>
            <oracle-xsl-mapper:rootElement name="PlateauHRConectorFFAccountDataCollection" namespace="http://www.sunpowercorp.com/PlateauHRConectorFFAccountData"/>
            <oracle-xsl-mapper:param name="PlateauHRFFAccountData"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/MergedLMSData.xsd"/>
            <oracle-xsl-mapper:rootElement name="MergeLmsRowsCollection" namespace="http://www.sunpowercorp.com/MergeLmsRows"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [SAT OCT 08 16:55:14 IST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="PlateauHRFFAccountData"/>
  <xsl:template match="/">
    <ns1:MergeLmsRowsCollection>
      <xsl:for-each select="$PlateauHRFFAccountData/ns0:PlateauHRConectorFFAccountDataCollection/ns0:PlateauHRConectorFFAccountDataItems">
        <xsl:variable name="AccountRow" select="."/>
        <xsl:for-each select="/tns:PlateauHRConectorFFDataCollection/tns:PlateauHRConectorFFDataItems">
          <xsl:variable name="UserFFRow" select="."/>
          <ns1:MergeLmsRowsItems>
            <ns1:not_active>
              <xsl:value-of select="tns:not_active"/>
            </ns1:not_active>
            <ns1:user_id>
              <xsl:value-of select="tns:user_id"/>
            </ns1:user_id>
            <ns1:first_name>
              <xsl:value-of select="tns:first_name"/>
            </ns1:first_name>
            <ns1:last_name>
              <xsl:value-of select="tns:last_name"/>
            </ns1:last_name>
            <ns1:middle_initial>
              <xsl:value-of select="tns:middle_initial"/>
            </ns1:middle_initial>
            <ns1:gender>
              <xsl:value-of select="tns:gender"/>
            </ns1:gender>
            <ns1:job_position_id>
              <xsl:value-of select="tns:job_position_id"/>
            </ns1:job_position_id>
            <ns1:job_position_description>
              <xsl:value-of select="tns:job_position_description"/>
            </ns1:job_position_description>
            <ns1:job_title>
              <xsl:value-of select="tns:job_title"/>
            </ns1:job_title>
            <ns1:role>
              <xsl:value-of select="tns:role"/>
            </ns1:role>
            <ns1:job_location_id>
              <xsl:value-of select="tns:job_location_id"/>
            </ns1:job_location_id>
            <ns1:job_location_description>
              <xsl:value-of select="tns:job_location_description"/>
            </ns1:job_location_description>
            <ns1:domain_id>
              <xsl:value-of select="tns:domain_id"/>
            </ns1:domain_id>
            <ns1:organization_id>
              <xsl:value-of select="$AccountRow/ns0:organization_id"/>
            </ns1:organization_id>
            <ns1:organization_description>
              <xsl:value-of select="$AccountRow/ns0:organization_description"/>
            </ns1:organization_description>
            <ns1:employee_type_id>
              <xsl:value-of select="tns:employee_type_id"/>
            </ns1:employee_type_id>
            <ns1:employee_type_description>
              <xsl:value-of select="tns:employee_type_description"/>
            </ns1:employee_type_description>
            <ns1:employee_status_id>
              <xsl:value-of select="tns:employee_status_id"/>
            </ns1:employee_status_id>
            <ns1:employee_status_description>
              <xsl:value-of select="tns:employee_status_description"/>
            </ns1:employee_status_description>
            <ns1:main_address>
              <xsl:value-of select="tns:main_address"/>
            </ns1:main_address>
            <ns1:city>
              <xsl:value-of select="tns:city"/>
            </ns1:city>
            <ns1:state>
              <xsl:value-of select="$AccountRow/ns0:state"/>
            </ns1:state>
            <ns1:postal_code>
              <xsl:value-of select="tns:postal_code"/>
            </ns1:postal_code>
            <ns1:country>
              <xsl:value-of select="tns:country"/>
            </ns1:country>
            <ns1:region_id>
              <xsl:value-of select="$AccountRow/ns0:region_id"/>
            </ns1:region_id>
            <ns1:region_description>
              <xsl:value-of select="$AccountRow/ns0:region_description"/>
            </ns1:region_description>
            <ns1:email_address>
              <xsl:value-of select="tns:email_address"/>
            </ns1:email_address>
            <ns1:hired_date>
              <xsl:value-of select="$AccountRow/ns0:hired_date"/>
            </ns1:hired_date>
            <ns1:terminated_date>
              <xsl:value-of select="tns:terminated_date"/>
            </ns1:terminated_date>
            <ns1:supervisor>
              <xsl:value-of select="tns:supervisor"/>
            </ns1:supervisor>
            <ns1:resume>
              <xsl:value-of select="tns:resume"/>
            </ns1:resume>
            <ns1:comments>
              <xsl:value-of select="tns:comments"/>
            </ns1:comments>
            <ns1:account_code>
              <xsl:value-of select="$AccountRow/ns0:account_code"/>
            </ns1:account_code>
            <ns1:account_code_description>
              <xsl:value-of select="tns:account_code_description"/>
            </ns1:account_code_description>
            <ns1:phone_number_i>
              <xsl:value-of select="tns:phone_number_i"/>
            </ns1:phone_number_i>
            <ns1:phone_number_description_i>
              <xsl:value-of select="tns:phone_number_description_i"/>
            </ns1:phone_number_description_i>
            <ns1:phone_number_ii>
              <xsl:value-of select="tns:phone_number_ii"/>
            </ns1:phone_number_ii>
            <ns1:phone_number_description_ii>
              <xsl:value-of select="tns:phone_number_description_ii"/>
            </ns1:phone_number_description_ii>
            <ns1:phone_number_iii>
              <xsl:value-of select="tns:phone_number_iii"/>
            </ns1:phone_number_iii>
            <ns1:phone_number_description_iii>
              <xsl:value-of select="tns:phone_number_description_iii"/>
            </ns1:phone_number_description_iii>
            <ns1:alternate_job_position_id>
              <xsl:value-of select="tns:alternate_job_position_id"/>
            </ns1:alternate_job_position_id>
            <ns1:shopping_account_type>
              <xsl:value-of select="tns:shopping_account_type"/>
            </ns1:shopping_account_type>
            <ns1:enable_shopping_account>
              <xsl:value-of select="tns:enable_shopping_account"/>
            </ns1:enable_shopping_account>
            <ns1:custom_column_100>
              <xsl:value-of select="$AccountRow/ns0:custom_column_100"/>
            </ns1:custom_column_100>
            <ns1:custom_column_110>
              <xsl:value-of select="$AccountRow/ns0:custom_column_110"/>
            </ns1:custom_column_110>
            <ns1:custom_column_120>
              <xsl:value-of select="tns:custom_column_120"/>
            </ns1:custom_column_120>
            <ns1:custom_column_130>
              <xsl:value-of select="tns:custom_column_130"/>
            </ns1:custom_column_130>
            <ns1:custom_column_140>
              <xsl:value-of select="tns:custom_column_140"/>
            </ns1:custom_column_140>
            <ns1:custom_column_150>
              <xsl:value-of select="tns:custom_column_150"/>
            </ns1:custom_column_150>
            <ns1:custom_column_160>
              <xsl:value-of select="tns:custom_column_160"/>
            </ns1:custom_column_160>
            <ns1:custom_column_170>
              <xsl:value-of select="tns:custom_column_170"/>
            </ns1:custom_column_170>
            <ns1:custom_column_180>
              <xsl:value-of select="tns:custom_column_180"/>
            </ns1:custom_column_180>
            <ns1:custom_column_190>
              <xsl:value-of select="tns:custom_column_190"/>
            </ns1:custom_column_190>
            <ns1:timezone>
              <xsl:value-of select="tns:timezone"/>
            </ns1:timezone>
            <ns1:language_id>
              <xsl:value-of select="tns:language_id"/>
            </ns1:language_id>
            <ns1:Organization_Account_Code>
              <xsl:value-of select="tns:Organization_Account_Code"/>
            </ns1:Organization_Account_Code>
            <ns1:currency_id>
              <xsl:value-of select="tns:currency_id"/>
            </ns1:currency_id>
            <ns1:alt_job_position_id2>
              <xsl:value-of select="tns:alt_job_position_id2"/>
            </ns1:alt_job_position_id2>
            <ns1:alt_job_position_id3>
              <xsl:value-of select="tns:alt_job_position_id3"/>
            </ns1:alt_job_position_id3>
            <ns1:alt_job_position_id4>
              <xsl:value-of select="tns:alt_job_position_id4"/>
            </ns1:alt_job_position_id4>
            <ns1:alt_job_position_id5>
              <xsl:value-of select="tns:alt_job_position_id5"/>
            </ns1:alt_job_position_id5>
            <ns1:alt_job_position_id6>
              <xsl:value-of select="tns:alt_job_position_id6"/>
            </ns1:alt_job_position_id6>
            <ns1:end_of_row>
              <xsl:value-of select="tns:end_of_row"/>
            </ns1:end_of_row>
          </ns1:MergeLmsRowsItems>
        </xsl:for-each>
      </xsl:for-each>
    </ns1:MergeLmsRowsCollection>
  </xsl:template>
</xsl:stylesheet>