<?binding.jca CreateUpdateContactCustomer_db.jca?>
<wsdl:definitions name="CreateUpdateContactCustomer" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TPOSOACustomerSync/CreateUpdateCustomerOracleProv/CreateUpdateContactCustomer" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/TPOSOACustomerSync/CreateUpdateCustomerOracleProv/CreateUpdateContactCustomer" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/CreateUpdateContactCustomer">
    <plt:partnerLinkType name="CreateUpdateContactCustomer_plt">
        <plt:role name="CreateUpdateContactCustomer_role">
            <plt:portType name="tns:CreateUpdateContactCustomer_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/CreateUpdateContactCustomer"
                    schemaLocation="../Schemas/CreateUpdateContactCustomer_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="XxspwrCustContactsCollection_msg">
        <wsdl:part name="XxspwrCustContactsCollection" element="top:XxspwrCustContactsCollection"/>
    </wsdl:message>
    <wsdl:portType name="CreateUpdateContactCustomer_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:XxspwrCustContactsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
