<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns5="http://www.sunpowercorp.com/MergedOracleSFDC" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns6="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns2="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns8="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns10="http://www.sunpowercorp.com/MergedOracleAttachmentSFDC" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:client="http://www.sunpowercorp.com/PDFFTPSalesforceT0042/SOAPDFMETASyncProv/SOAPDFMETASyncProv_BPEL" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:ns0="http://www.sunpowercorp.com/Common/PDFFTPSalesForceCommonTypes/V1" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:ns9="http://www.sunpowercorp.com/MergedAttachmentSFDC" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns7="http://www.sunpowercorp.com/Noun/PDFFTPSalesForce/V1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns3="http://schemas.oracle.com/bpel/extension" xmlns:ns4="http://www.sunpowercorp.com/MergedSFDC" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessPDFFTPSalesForce/V1" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns5 ns6 plnk wsdl ns2 ns8 ns10 client ns0 ns9 ns7 xsd ns3 ns4 ns1 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../SOAPDFMETASyncProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="MergedSFDCRows" namespace="http://www.sunpowercorp.com/MergedSFDC"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../SOAPDFMETASyncProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessPDFFTPSalesForce" namespace="http://www.sunpowercorp.com/BOD/ProcessPDFFTPSalesForce/V1"/>
            <oracle-xsl-mapper:param name="inputVariable.payload"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../SOAPDFMETASyncProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="MergedOracleSFDCRows" namespace="http://www.sunpowercorp.com/MergedOracleSFDC"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU OCT 06 10:31:19 IST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="inputVariable.payload"/>
  <xsl:template match="/">
    <ns5:MergedOracleSFDCRows>
      <xsl:for-each select="$inputVariable.payload/ns1:ProcessPDFFTPSalesForce/ns1:DataArea/ns7:PDFSalesForce/ns7:PDFSalesForceDetails">
        <xsl:variable name="InputRow" select="."/>
        <xsl:for-each select="/ns4:MergedSFDCRows/ns4:row">
          <xsl:variable name="SFDCRow" select="."/>
          <xsl:if test="$InputRow/ns0:CUSTOMER_NUMBER = ns4:CUSOMER_NUMBER">
            <ns5:row>
              <ns5:BILL_TO_CUSTOMER_ID>
                <xsl:value-of select="$InputRow/ns0:BILL_TO_CUSTOMER_ID"/>
              </ns5:BILL_TO_CUSTOMER_ID>
              <ns5:CUSOMER_NUMBER>
                <xsl:value-of select="$InputRow/ns0:CUSTOMER_NUMBER"/>
              </ns5:CUSOMER_NUMBER>
              <ns5:TRX_STATUS>
                <xsl:value-of select="$InputRow/ns0:TRX_STATUS"/>
              </ns5:TRX_STATUS>
              <ns5:TRX_DATE>
                <xsl:value-of select="$InputRow/ns0:TRX_DATE"/>
              </ns5:TRX_DATE>
              <ns5:TRX_CREATION_DATE>
                <xsl:value-of select="$InputRow/ns0:TRX_CREATION_DATE"/>
              </ns5:TRX_CREATION_DATE>
              <ns5:TRX_TYPE>
                <xsl:value-of select="$InputRow/ns0:TRX_TYPE"/>
              </ns5:TRX_TYPE>
              <ns5:TRX_TYPE_NAME>
                <xsl:value-of select="$InputRow/ns0:TRX_TYPE_NAME"/>
              </ns5:TRX_TYPE_NAME>
              <ns5:TRX_TYPE_DESC>
                <xsl:value-of select="$InputRow/ns0:TRX_TYPE_DESC"/>
              </ns5:TRX_TYPE_DESC>
              <ns5:OPERATING_UNIT_NAME>
                <xsl:value-of select="$InputRow/ns0:OPERATING_UNIT_NAME"/>
              </ns5:OPERATING_UNIT_NAME>
              <ns5:CURRENCY_CODE>
                <xsl:value-of select="$InputRow/ns0:CURRENCY_CODE"/>
              </ns5:CURRENCY_CODE>
              <ns5:TRANSACTION_CURRENCY_CODE>
                <xsl:value-of select="$InputRow/ns0:TRANSACTION_CURRENCY_CODE"/>
              </ns5:TRANSACTION_CURRENCY_CODE>
              <ns5:LAST_UPDATE_DATE>
                <xsl:value-of select="$InputRow/ns0:LAST_UPDATE_DATE"/>
              </ns5:LAST_UPDATE_DATE>
              <ns5:CREATED_BY>
                <xsl:value-of select="$InputRow/ns0:CREATED_BY"/>
              </ns5:CREATED_BY>
              <ns5:LAST_UPDATED_BY>
                <xsl:value-of select="$InputRow/ns0:LAST_UPDATED_BY"/>
              </ns5:LAST_UPDATED_BY>
              <ns5:LAST_UPDATED_LOGIN>
                <xsl:value-of select="$InputRow/ns0:LAST_UPDATED_LOGIN"/>
              </ns5:LAST_UPDATED_LOGIN>
              <ns5:RECORD_STATUS>
                <xsl:value-of select="$InputRow/ns0:RECORD_STATUS"/>
              </ns5:RECORD_STATUS>
              <ns5:RECORD_ID>
                <xsl:value-of select="$InputRow/ns0:RECORD_ID"/>
              </ns5:RECORD_ID>
              <ns5:ERROR_MESSAGE>
                <xsl:value-of select="$InputRow/ns0:ERROR_MESSAGE"/>
              </ns5:ERROR_MESSAGE>
              <ns5:PDF_FILE_NAME>
                <xsl:value-of select="substring-before($InputRow/ns0:PDF_FILE_NAME,&quot;.s&quot;)"/>
              </ns5:PDF_FILE_NAME>
              <ns5:TRX_LAST_UPDATED_DATE>
                <xsl:value-of select="$InputRow/ns0:TRX_LAST_UPDATED_DATE"/>
              </ns5:TRX_LAST_UPDATED_DATE>
              <ns5:T_CREATION_DATE>
                <xsl:value-of select="$InputRow/ns0:T_CREATION_DATE"/>
              </ns5:T_CREATION_DATE>
              <ns5:SFDC_ACCOUNT_ID>
                <xsl:value-of select="ns4:SFDC_ACCOUNT_ID"/>
              </ns5:SFDC_ACCOUNT_ID>
              <ns5:SFDC_ACCOUNT_NAME>
                <xsl:value-of select="ns4:SFDC_ACCOUNT_NAME"/>
              </ns5:SFDC_ACCOUNT_NAME>
              <ns5:SFDC_USER_ID>
                <xsl:value-of select="ns4:SFDC_USER_ID"/>
              </ns5:SFDC_USER_ID>
              <ns5:SFDC_ATTACHMENT_ID>
                <xsl:value-of select="$InputRow/ns0:SFDC_ATTACHMENT_ID"/>
              </ns5:SFDC_ATTACHMENT_ID>
              <ns5:TRX_TYPE_MEANING>
                <xsl:value-of select="$InputRow/ns0:TRX_TYPE_MEANING"/>
              </ns5:TRX_TYPE_MEANING>
              <ns5:ORG_ID>
                <xsl:value-of select="$InputRow/ns0:ORG_ID"/>
              </ns5:ORG_ID>
            </ns5:row>
          </xsl:if>
        </xsl:for-each>
      </xsl:for-each>
    </ns5:MergedOracleSFDCRows>
  </xsl:template>
</xsl:stylesheet>