<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="CallCommSFDCErrMediator"
     targetNamespace="http://xmlns.oracle.com/testingapplication/CommonSFDCErrorLogService/CallCommSFDCErrMediator"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:tns="http://xmlns.oracle.com/testingapplication/CommonSFDCErrorLogService/CallCommSFDCErrMediator"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="CommonSFDCErrorLogService">
        <plnk:role name="execute_ptt" portType="tns:execute_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/testingapplication/CommonSFDCErrorLogService/CallCommSFDCErrMediator"
         location="http://dev-fusappdca02.sunpowercorp.com:7003/soa-infra/services/default/CommonSFDCErrorLogService!1.0/WSDLs/CallCommSFDCErrMediator.wsdl"/>
</wsdl:definitions>
