<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="SyncCreditLimitPSWsdl"
     targetNamespace="http://www.example.org/SyncCreditLimitPSWsdl"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:WL5G3N2="http://www.example.org/SyncCreditLimitPSWsdl"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="SyncCreditLimitEBS">
        <plnk:role name="SyncCreditLimitSFDCLimit">
            <plnk:portType name="WL5G3N2:SyncCreditLimitSFDCLimit"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.example.org/SyncCreditLimitPSWsdl" location="http://dev-fusappdca02.sunpowercorp.com:7004/SyncCreditLimitEBS/Proxy/SyncCreditLimitPS?wsdl"/>
</wsdl:definitions>
