<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:tns="http://www.acbcoop.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns4="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessACBClaimToSFDC/V1" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns6="http://www.sunpowercorp.com/Noun/ACBActivitiesToSFDC/V1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://www.sunpowercorp.com/ACBClaimAll/" xmlns:ns2="http://www.sunpowercorp.com/BOD/ProcessACBActivitiesToSFDC/V1" xmlns:ns3="http://www.sunpowercorp.com/Common/ACBActivitiesToSFDCCommonTypes/V1" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns5="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl tm tns soap12 soapenc soap wsdl mime xsd http ns4 ns1 ns6 ns0 ns2 ns3 ns5 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/ACBGetActivitiesAll.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetAllFundDetailsResponse" namespace="http://www.acbcoop.com/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7004/ACBGetAllActivitesmergeSvc/Proxy/ACBGetAllActivitesmergeSvcPS?wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessACBActivitiesToSFDC" namespace="http://www.sunpowercorp.com/BOD/ProcessACBActivitiesToSFDC/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [FRI OCT 07 16:29:19 IST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns2:ProcessACBActivitiesToSFDC>
      <ns2:DataArea>
        <ns6:ACBActivitiesToSFDC>
          <xsl:for-each select="/tns:GetAllFundDetailsResponse/tns:GetAllFundDetailsResult/tns:WebServiceFundDetails">
            <ns6:ACBActivitiesToSFDCDetails>
              <ns3:Promotion__c>
                <xsl:value-of select="tns:Promotion"/>
              </ns3:Promotion__c>
              <ns3:Promotion_Description__c>
                <xsl:value-of select="tns:PromotionDescription"/>
              </ns3:Promotion_Description__c>
              <ns3:Transaction_Type__c>
                <xsl:value-of select="tns:TransactionType"/>
              </ns3:Transaction_Type__c>
              <ns3:Transaction_Month__c>
                <xsl:value-of select="tns:TransactionMonth"/>
              </ns3:Transaction_Month__c>
              <ns3:Transaction_Year__c>
                <xsl:value-of select="tns:TransactionYear"/>
              </ns3:Transaction_Year__c>
              <ns3:Sum_of_Transaction_Amt__c>
                <xsl:value-of select="tns:TransactionAmount"/>
              </ns3:Sum_of_Transaction_Amt__c>
              <ns3:Comment__c>
                <xsl:value-of select="tns:Comment"/>
              </ns3:Comment__c>
              <ns3:Promotion_Year__c>
                <xsl:value-of select="tns:PromotionYear"/>
              </ns3:Promotion_Year__c>
              <ns3:Record_Number__c>
                <xsl:value-of select="tns:RecordNumber"/>
              </ns3:Record_Number__c>
              <ns3:ACBParanet_ID__C>
                <xsl:value-of select="tns:DlrNum"/>
              </ns3:ACBParanet_ID__C>
            </ns6:ACBActivitiesToSFDCDetails>
          </xsl:for-each>
        </ns6:ACBActivitiesToSFDC>
      </ns2:DataArea>
    </ns2:ProcessACBActivitiesToSFDC>
  </xsl:template>
</xsl:stylesheet>