<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="enqueOracleSFDCNoItemOperatingUnit" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/jms/OnlineOrderingNoItemOracleToSFDC/EnqueOracleSFDCNoItemOperatingUnit/enqueOracleSFDCNoItemOperatingUnit" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/jms/OnlineOrderingNoItemOracleToSFDC/EnqueOracleSFDCNoItemOperatingUnit/enqueOracleSFDCNoItemOperatingUnit" xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:imp1="http://xmlns.oracle.com/pcbpel/adapter/db/selecteNoItemOperatingUnitFromEBS" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
   <plt:partnerLinkType name="Produce_Message_plt">
      <plt:role name="Produce_Message_role">
         <plt:portType name="tns:Produce_Message_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/selecteNoItemOperatingUnitFromEBS"
                 schemaLocation="Schemas/selecteNoItemOperatingUnitFromEBS.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="Produce_Message_msg">
      <wsdl:part name="body" element="imp1:selecteNoItemOperatingUnitFromEBSOutputCollection"/>
   </wsdl:message>
   <wsdl:portType name="Produce_Message_ptt">
      <wsdl:operation name="Produce_Message">
         <wsdl:input message="tns:Produce_Message_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
