<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns0="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:client="http://www.sunpowercorp.com/CRDSFDCToOracle/SyncOEHeadersOracleProv/SyncOEHeadersOracleProv_BPEL" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns4="http://www.sunpowercorp.com/Common/SyncOEOrdersCommonTypes/V1" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessSyncOEOrders/V1" xmlns:ens="urn:sobject.partner.soap.sforce.com" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns2="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:fns="urn:fault.partner.soap.sforce.com" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns6="http://www.sunpowercorp.com/SunPowerDevelopment/utility/BatchEmailUtilityService/xsd/V1" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns3="http://www.sunpowercorp.com/Noun/SyncOEOrders/V1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns5="http://schemas.oracle.com/bpel/extension" xmlns:tns="urn:partner.soap.sforce.com" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl soap ens fns xsd tns ns0 plnk client wsdl ns4 ns1 ns2 ns6 ns3 ns5 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/partner.wsdl"/>
            <oracle-xsl-mapper:rootElement name="queryMoreResponse" namespace="urn:partner.soap.sforce.com"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7003/soa-infra/services/online/SyncOEHeadersOracleProv/SyncOEHeadersOracleProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessSyncOEOrders" namespace="http://www.sunpowercorp.com/BOD/ProcessSyncOEOrders/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE OCT 11 14:08:58 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns1:ProcessSyncOEOrders>
      <ns0:ApplicationArea>
        <ns0:SFDCTimeStamp>
          <xsl:text disable-output-escaping="no"/>
        </ns0:SFDCTimeStamp>
      </ns0:ApplicationArea>
      <ns1:DataArea>
        <ns0:process>
          <xsl:text disable-output-escaping="no"/>
        </ns0:process>
        <ns3:SyncOEOrders>
          <xsl:for-each select="/tns:queryMoreResponse/tns:result/tns:records">
            <ns3:SyncOEOrderHeaderDetails>
              <ns4:SFDC_ID>
                <xsl:value-of select="ens:Id"/>
              </ns4:SFDC_ID>
              <ns4:OPERATING_UNIT>
                <xsl:value-of select="ens:OPERATING_UNIT__c"/>
              </ns4:OPERATING_UNIT>
              <ns4:HEADER_ID>
                <xsl:value-of select="ens:HEADER_ID__c"/>
              </ns4:HEADER_ID>
              <ns4:ORDER_NUMBER>
                <xsl:value-of select="ens:ORDER_NUMBER__c"/>
              </ns4:ORDER_NUMBER>
              <ns4:ORACLE_REQUEST_ID>
                <xsl:value-of select="ens:ORACLE_REQUEST_ID__c"/>
              </ns4:ORACLE_REQUEST_ID>
              <ns4:SFDC_REQUEST_ID>
                <xsl:value-of select="ens:SFDC_REQUEST_ID__c"/>
              </ns4:SFDC_REQUEST_ID>
              <ns4:SFDC_REQUEST_STATUS>
                <xsl:value-of select="ens:SFDC_REQUEST_STATUS__c"/>
              </ns4:SFDC_REQUEST_STATUS>
              <ns4:EMAIL_ID>
                <xsl:value-of select="ens:EMAIL_ID__c"/>
              </ns4:EMAIL_ID>
              <ns4:ORACLE_USER_ID>
                <xsl:value-of select="ens:ORACLE_USER_ID__c"/>
              </ns4:ORACLE_USER_ID>
              <ns4:CUST_ACCT_NUMBER>
                <xsl:value-of select="ens:CUST_ACCT_NUMBER__c"/>
              </ns4:CUST_ACCT_NUMBER>
              <ns4:CREDIT_LIMIT>
                <xsl:value-of select="ens:CREDIT_LIMIT__c"/>
              </ns4:CREDIT_LIMIT>
              <ns4:TRANSACTION_DATE>
                <xsl:value-of select="ens:TRANSACTION_DATE__c"/>
              </ns4:TRANSACTION_DATE>
              <ns4:DUE_DATE>
                <xsl:value-of select="ens:DUE_DATE__c"/>
              </ns4:DUE_DATE>
              <ns4:AMOUNT>
                <xsl:value-of select="ens:AMOUNT__c"/>
              </ns4:AMOUNT>
              <ns4:AMOUNT_OPEN>
                <xsl:value-of select="ens:AMOUNT_OPEN__c"/>
              </ns4:AMOUNT_OPEN>
              <ns4:PAYMENT_SCHEDULE_ID>
                <xsl:value-of select="ens:PAYMENT_SCHEDULE_ID__c"/>
              </ns4:PAYMENT_SCHEDULE_ID>
              <ns4:BALANCE>
                <xsl:value-of select="ens:BALANCE__c"/>
              </ns4:BALANCE>
              <ns4:LOCATION_NUMBER>
                <xsl:value-of select="ens:LOCATION_NUMBER__c"/>
              </ns4:LOCATION_NUMBER>
              <ns4:REFERENCE>
                <xsl:value-of select="ens:REFERENCE__c"/>
              </ns4:REFERENCE>
              <ns4:TRASACTION_TYPE>
                <xsl:value-of select="ens:TRASACTION_TYPE__c"/>
              </ns4:TRASACTION_TYPE>
              <ns4:QAD_CUSTOMER_NUMBER>
                <xsl:value-of select="ens:QAD_CUSTOMER_NUMBER__c"/>
              </ns4:QAD_CUSTOMER_NUMBER>
              <ns4:CUSTOMER_NAME>
                <xsl:value-of select="ens:CUSTOMER_NAME__c"/>
              </ns4:CUSTOMER_NAME>
              <ns4:REGION>
                <xsl:value-of select="ens:REGION__c"/>
              </ns4:REGION>
              <ns4:INVOICE_REFERENCE>
                <xsl:value-of select="ens:INVOICE_REFERENCE__c"/>
              </ns4:INVOICE_REFERENCE>
              <ns4:SITE_STATUS>
                <xsl:value-of select="ens:SITE_STATUS__c"/>
              </ns4:SITE_STATUS>
              <ns4:ORG_ID>
                <xsl:value-of select="ens:ORG_ID__c"/>
              </ns4:ORG_ID>
              <ns4:PO_SUBMIT_DATE>
                <xsl:value-of select="ens:PO_SUBMIT_DATE__c"/>
              </ns4:PO_SUBMIT_DATE>
              <ns4:SHIP_FROM_ORG_ID>
                <xsl:value-of select="ens:SHIP_FROM_ORG_ID__c"/>
              </ns4:SHIP_FROM_ORG_ID>
              <ns4:BILL_TO_SITE_ID>
                <xsl:value-of select="ens:BILL_TO_SITE_ID__c"/>
              </ns4:BILL_TO_SITE_ID>
              <ns4:SHIP_TO_SITE_ID>
                <xsl:value-of select="ens:SHIP_TO_SITE_ID__c"/>
              </ns4:SHIP_TO_SITE_ID>
              <ns4:BILL_ADDRESS_LINE_1>
                <xsl:value-of select="ens:BILL_ADDRESS_LINE_1__c"/>
              </ns4:BILL_ADDRESS_LINE_1>
              <ns4:BILL_ADDRESS_LINE_2>
                <xsl:value-of select="ens:BILL_ADDRESS_LINE_2__c"/>
              </ns4:BILL_ADDRESS_LINE_2>
              <ns4:BILL_ADDRESS_LINE_3>
                <xsl:value-of select="ens:BILL_ADDRESS_LINE_3__c"/>
              </ns4:BILL_ADDRESS_LINE_3>
              <ns4:BILL_CITY>
                <xsl:value-of select="ens:BILL_CITY__c"/>
              </ns4:BILL_CITY>
              <ns4:BILL_STATE>
                <xsl:value-of select="ens:BILL_STATE__c"/>
              </ns4:BILL_STATE>
              <ns4:BILL_COUNTRY>
                <xsl:value-of select="ens:BILL_COUNTRY__c"/>
              </ns4:BILL_COUNTRY>
              <ns4:BILL_POSTAL_CODE>
                <xsl:value-of select="ens:BILL_POSTAL_CODE__c"/>
              </ns4:BILL_POSTAL_CODE>
              <ns4:ADDRESS_LINE_1>
                <xsl:value-of select="ens:ADDRESS_LINE_1__c"/>
              </ns4:ADDRESS_LINE_1>
              <ns4:ADDRESS_LINE_2>
                <xsl:value-of select="ens:ADDRESS_LINE_2__c"/>
              </ns4:ADDRESS_LINE_2>
              <ns4:ADDRESS_LINE_3>
                <xsl:value-of select="ens:ADDRESS_LINE_3__c"/>
              </ns4:ADDRESS_LINE_3>
              <ns4:CITY>
                <xsl:value-of select="ens:Ship_To_City__c"/>
              </ns4:CITY>
              <ns4:STATE>
                <xsl:value-of select="ens:STATE__c"/>
              </ns4:STATE>
              <ns4:COUNTRY>
                <xsl:value-of select="ens:COUNTRY__c"/>
              </ns4:COUNTRY>
              <ns4:POSTAL_CODE>
                <xsl:value-of select="ens:POSTAL_CODE__c"/>
              </ns4:POSTAL_CODE>
              <ns4:CONTACT_PHONE1>
                <xsl:value-of select="ens:CONTACT_PHONE1__c"/>
              </ns4:CONTACT_PHONE1>
              <ns4:CONTACT_PHONE2>
                <xsl:value-of select="ens:CONTACT_PHONE2__c"/>
              </ns4:CONTACT_PHONE2>
              <ns4:CONTACT_PERSON_NAME>
                <xsl:value-of select="ens:CONTACT_PERSON_NAME__c"/>
              </ns4:CONTACT_PERSON_NAME>
              <ns4:CONTACT_EMAIL>
                <xsl:value-of select="ens:CONTACT_EMAIL__c"/>
              </ns4:CONTACT_EMAIL>
              <ns4:CONTACT_FAX>
                <xsl:value-of select="ens:CONTACT_FAX__c"/>
              </ns4:CONTACT_FAX>
              <ns4:SHIP_TO_CONTACT_ID>
                <xsl:value-of select="ens:SHIP_TO_CONTACT_ID__c"/>
              </ns4:SHIP_TO_CONTACT_ID>
              <ns4:SHIPPING_METHOD>
                <xsl:value-of select="ens:Shipping_Method__c"/>
              </ns4:SHIPPING_METHOD>
              <ns4:SPECIAL_INSTRUCTIONS>
                <xsl:value-of select="ens:SPECIAL_INSTRUCTIONS__c"/>
              </ns4:SPECIAL_INSTRUCTIONS>
              <ns4:SHIPPING_INSTRUCTIONS>
                <xsl:value-of select="ens:SHIPPING_INSTRUCTIONS__c"/>
              </ns4:SHIPPING_INSTRUCTIONS>
              <ns4:PACKING_INSTRUCTIONS>
                <xsl:value-of select="ens:PACKING_INSTRUCTIONS__c"/>
              </ns4:PACKING_INSTRUCTIONS>
              <!--
              <ns4:REQUESTED_DELIVERY_DATE>
                <xsl:value-of select="ens:REQUESTED_DELIVERY_DATE__c"/>
              </ns4:REQUESTED_DELIVERY_DATE>
              -->
               <xsl:choose>
                <xsl:when test="ens:CRD_SFDC__c = &quot;&quot;">
                  <ns4:REQUESTED_DELIVERY_DATE>
                    <xsl:value-of select="ens:REQUESTED_DELIVERY_DATE__c"/>
                  </ns4:REQUESTED_DELIVERY_DATE>
                </xsl:when>
                <xsl:otherwise>
                  <ns4:REQUESTED_DELIVERY_DATE>
                    <xsl:value-of select="ens:CRD_SFDC__c"/>
                  </ns4:REQUESTED_DELIVERY_DATE>
                </xsl:otherwise>
                  </xsl:choose>
              <ns4:ADJUSTED_AMOUNT>
                <xsl:value-of select="ens:ADJUSTED_AMOUNT__c"/>
              </ns4:ADJUSTED_AMOUNT>
              <ns4:SMARTPACK_FLAG>
                <xsl:value-of select="ens:SMARTPACK_FLAG__c"/>
              </ns4:SMARTPACK_FLAG>
              <ns4:ORDER_STATUS>
                <xsl:value-of select="ens:ORDER_STATUS__c"/>
              </ns4:ORDER_STATUS>
              <ns4:LAST_UPDATE_DATE>
                <xsl:value-of select="ens:LAST_UPDATE_DATE__c"/>
              </ns4:LAST_UPDATE_DATE>
              <ns4:LAST_UPDATED_BY>
                <xsl:value-of select="ens:LAST_UPDATED_BY__c"/>
              </ns4:LAST_UPDATED_BY>
              <ns4:CREATION_DATE>
                <xsl:value-of select="ens:CREATION_DATE__c"/>
              </ns4:CREATION_DATE>
              <ns4:CREATED_BY>
                <xsl:value-of select="ens:CREATED_BY__c"/>
              </ns4:CREATED_BY>
              <ns4:ORDER_TYPE>
                <xsl:value-of select="ens:ORDER_TYPE__c"/>
              </ns4:ORDER_TYPE>
              <ns4:LEASE_VALUE>
                <xsl:value-of select="ens:LEASE_VALUE__c"/>
              </ns4:LEASE_VALUE>
              <ns4:VENDOR_NUMBER>
                <xsl:value-of select="ens:Vendor_Number__c"/>
              </ns4:VENDOR_NUMBER>
              <ns4:VENDOR_SITE_CODE>
                <xsl:value-of select="ens:VENDOR_SITE_CODE__c"/>
              </ns4:VENDOR_SITE_CODE>
              <ns4:PARTNER_NAME>
                <xsl:value-of select="ens:Partner_Name_Formula__c"/>
              </ns4:PARTNER_NAME>
              <ns4:LEASE_FLAG>
                <xsl:value-of select="ens:LEASE_FLAG__c"/>
              </ns4:LEASE_FLAG>
              <ns4:LEASE_NUMBER>
                <xsl:value-of select="ens:LEASE_NUMBER__c"/>
              </ns4:LEASE_NUMBER>
              <ns4:ORDER_RECORD_TYPE>
                <xsl:value-of select="ens:RecordType/ens:Id[1]"/>
              </ns4:ORDER_RECORD_TYPE>
              <ns4:FINANCIER>
                <xsl:value-of select="ens:FINANCIER__c"/>
              </ns4:FINANCIER>
              <ns4:PARTNER_ACC_NUMBER>
                <xsl:value-of select="ens:PARTNER_ACC_NUMBER__c"/>
              </ns4:PARTNER_ACC_NUMBER>
              <ns4:SOA_FLAG>
                <xsl:value-of select="ens:SOA_FLAG__c"/>
              </ns4:SOA_FLAG>
              <ns4:SOA_ERRORMSG>
                <xsl:value-of select="ens:SOA_ERRORMSG__c"/>
              </ns4:SOA_ERRORMSG>
              <ns4:PROCESS_FLAG>
                <xsl:value-of select="ens:PROCESS_FLAG__c"/>
              </ns4:PROCESS_FLAG>
              <ns4:PROCESS_MESSAGE>
                <xsl:value-of select="ens:PROCESS_MESSAGE__c"/>
              </ns4:PROCESS_MESSAGE>
              <ns4:SHIP_TO_COUNTY>
                <xsl:value-of select="ens:Ship_To_County__c"/>
              </ns4:SHIP_TO_COUNTY>
              <ns4:Bill_To_COUNTY>
                <xsl:value-of select="ens:Bill_To_County__c"/>
              </ns4:Bill_To_COUNTY>
              <ns4:CUSTOMER_PROMISE_DATE>
                <xsl:value-of select="ens:CPD__c"/>
              </ns4:CUSTOMER_PROMISE_DATE>
              <ns4:SYSTEM_SIZE>
                <xsl:value-of select="ens:System_Size__c"/>
              </ns4:SYSTEM_SIZE>
              <ns4:LastModifiedDate>
                <xsl:value-of select="xp20:format-dateTime(ens:LastModifiedDate,&quot;[Y0001]-[M01]-[D01] [H01]:[m01]:[s01]&quot;)"/>
              </ns4:LastModifiedDate>
              <ns4:PSR_NAME>
                <xsl:value-of select="ens:PSR_Name__c"/>
              </ns4:PSR_NAME>
              <ns4:PSR_EMAIL>
                <xsl:value-of select="ens:PSRemailId__c"/>
              </ns4:PSR_EMAIL>
                     <ns4:OK_TO_SHIP_FLAG>
                        <xsl:value-of select="ens:OK_TO_SHIP__c"/>
                     </ns4:OK_TO_SHIP_FLAG>
                     <ns4:CANCEL_FLAG>
                        <xsl:value-of select="ens:SFDC_CANCEL_STATUS__c"/>
                     </ns4:CANCEL_FLAG>
            </ns3:SyncOEOrderHeaderDetails>
          </xsl:for-each>
        </ns3:SyncOEOrders>
      </ns1:DataArea>
    </ns1:ProcessSyncOEOrders>
  </xsl:template>
</xsl:stylesheet>