<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:client="http://www.sunpowercorp.com/SOAUtilityServices/CommonSFDCErrorLogService/CommonSFDCErrorLogService_BPEL" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns1="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:ens="urn:sobject.partner.soap.sforce.com" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:fns="urn:fault.partner.soap.sforce.com" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="urn:partner.soap.sforce.com" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl client plnk wsdl ns1 xsd ns2 soap ens fns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/CommonSFDCErrorLogService_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CommonSFDCErrorLog" namespace="http://www.sunpowercorp.com/SOAUtilityServices/CommonSFDCErrorLogService/CommonSFDCErrorLogService_BPEL"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/partner.wsdl"/>
            <oracle-xsl-mapper:rootElement name="create" namespace="urn:partner.soap.sforce.com"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE OCT 04 11:26:20 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns2:create>
      <ns2:sObjects>
        <ens:type>
          <xsl:text disable-output-escaping="no">Middleware_Exception__c</xsl:text>
        </ens:type>
        <ens:Fault_Name__c>
          <xsl:value-of select="/client:CommonSFDCErrorLog/client:CommonErrorHandlerInputDetails/client:Fault/client:FaultMessage"/>
        </ens:Fault_Name__c>
        <ens:Fault_Time__c>
          <xsl:value-of select="/client:CommonSFDCErrorLog/client:CommonErrorHandlerInputDetails/client:Fault/client:FaultTime"/>
        </ens:Fault_Time__c>
        <ens:Job_Start_Time__c>
          <xsl:value-of select="/client:CommonSFDCErrorLog/client:CommonErrorHandlerInputDetails/client:createddatetime"/>
        </ens:Job_Start_Time__c>
        <ens:Message__c>
          <xsl:value-of select="/client:CommonSFDCErrorLog/client:CommonErrorHandlerInputDetails/client:Fault/client:FaultDescription"/>
        </ens:Message__c>
        <ens:Middleware_Job_ID__c>
          <xsl:value-of select="/client:CommonSFDCErrorLog/client:CommonErrorHandlerInputDetails/client:InstanceNumber"/>
        </ens:Middleware_Job_ID__c>
        <ens:Orchestration_Name__c>
          <xsl:value-of select="/client:CommonSFDCErrorLog/client:CommonErrorHandlerInputDetails/client:InterfaceName"/>
        </ens:Orchestration_Name__c>
        <ens:Project_Name__c>
          <xsl:value-of select="/client:CommonSFDCErrorLog/client:CommonErrorHandlerInputDetails/client:ProcessName"/>
        </ens:Project_Name__c>
        <ens:Related_Object_ID__c>
          <xsl:value-of select="/client:CommonSFDCErrorLog/client:CommonErrorHandlerInputDetails/client:Related_Object_ID__c"/>
        </ens:Related_Object_ID__c>
        <ens:Router_Host_Name__c>
          <xsl:value-of select="/client:CommonSFDCErrorLog/client:CommonErrorHandlerInputDetails/client:Router_Host_Name__c"/>
        </ens:Router_Host_Name__c>
        <ens:Salesforce_User_ID__c>
          <xsl:value-of select="/client:CommonSFDCErrorLog/client:CommonErrorHandlerInputDetails/client:Salesforce_User_ID__c"/>
        </ens:Salesforce_User_ID__c>
        <ens:Severity__c>
          <xsl:value-of select="/client:CommonSFDCErrorLog/client:CommonErrorHandlerInputDetails/client:Severity"/>
        </ens:Severity__c>
      </ns2:sObjects>
    </ns2:create>
  </xsl:template>
</xsl:stylesheet>