<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:client="http://www.sunpowercorp.com/SOAUtilityServices/CommonSFDCErrorLogService/CommonSFDCErrorLogService_BPEL" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertLoggingDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOAUtilityServices/CommonSFDCErrorLogService/InsertLoggingDB" xmlns:ns1="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="urn:partner.soap.sforce.com" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl client plnk wsdl ns1 xsd ns2 top tns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/CommonSFDCErrorLogService_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CommonSFDCErrorLog" namespace="http://www.sunpowercorp.com/SOAUtilityServices/CommonSFDCErrorLogService/CommonSFDCErrorLogService_BPEL"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/InsertLoggingDB.wsdl"/>
            <oracle-xsl-mapper:rootElement name="MiddlewareErrorLogCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertLoggingDB"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE OCT 04 11:26:20 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <top:MiddlewareErrorLogCollection>
      <xsl:for-each select="/client:CommonSFDCErrorLog/client:CommonErrorHandlerInputDetails/client:UniqueIdentNum">
        <top:MiddlewareErrorLog>
          <top:faultmessage>
            <xsl:value-of select="../client:Fault/client:FaultMessage"/>
          </top:faultmessage>
          <top:faultcode>
            <xsl:value-of select="../client:Fault/client:FaultCode"/>
          </top:faultcode>
          <top:faulttime>
            <xsl:value-of select="../client:Fault/client:FaultTime"/>
          </top:faulttime>
          <top:faultdescription>
            <xsl:value-of select="../client:Fault/client:FaultDescription"/>
          </top:faultdescription>
          <top:correctiveaction>
            <xsl:value-of select="../client:CorrectiveAction"/>
          </top:correctiveaction>
          <top:interfacenumber>
            <xsl:value-of select="../client:InterfaceNumber"/>
          </top:interfacenumber>
          <top:interfacename>
            <xsl:value-of select="../client:InterfaceName"/>
          </top:interfacename>
          <top:instancenumber>
            <xsl:value-of select="../client:InstanceNumber"/>
          </top:instancenumber>
          <top:processname>
            <xsl:value-of select="../client:ProcessName"/>
          </top:processname>
          <top:bopenserviceticket>
            <xsl:value-of select="../client:bOpenServiceTicket"/>
          </top:bopenserviceticket>
          <top:severity>
            <xsl:value-of select="../client:Severity"/>
          </top:severity>
          <top:faultsystemname>
            <xsl:value-of select="../client:FaultSystemName"/>
          </top:faultsystemname>
          <top:status>
            <xsl:value-of select="../client:status"/>
          </top:status>
          <top:createddatetime>
            <xsl:value-of select="../client:createddatetime"/>
          </top:createddatetime>
          <top:uniqueIdentifier>
            <xsl:value-of select="client:UniqueIdentifier"/>
          </top:uniqueIdentifier>
          <top:emailSent>
            <xsl:value-of select="../client:SendEmail"/>
          </top:emailSent>
        </top:MiddlewareErrorLog>
      </xsl:for-each>
    </top:MiddlewareErrorLogCollection>
  </xsl:template>
</xsl:stylesheet>