<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="UpdateSalesOrderResponseSFDCProv"
     targetNamespace="http://xmlns.oracle.com/OnLineSalesOrder/UpdateSalesOrderResponseSFDCProv/UpdateSalesOrderResponseSFDCProv"
     xmlns:ns2="http://www.sunpowercorp.com/SFDCSyncLeaseCustomerReq/xsd/v1"
     xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessOracleSFDCNoItemOrders/V1"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/OnLineSalesOrder/UpdateSalesOrderResponseSFDCProv/UpdateSalesOrderResponseSFDCProv"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="UpdateSalesOrderResponseSFDCProv">
        <plnk:role name="UpdateSalesOrderResponseSFDCProvProvider">
            <plnk:portType name="client:UpdateSalesOrderResponseSFDCProv"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://www.sunpowercorp.com/BOD/ProcessOracleSFDCNoItemOrders/V1"
                 schemaLocation="../Schemas/CDM/BOD/Nouns/OracleSFDCNoItemOrders/V1/ProcessOracleSFDCNoItemOrders.xsd"/>
        </schema>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.sunpowercorp.com/SFDCSyncLeaseCustomerReq/xsd/v1"
                        schemaLocation="../Schemas/inputparams.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="UpdateSalesOrderResponseSFDCProvRequestMessage">
        <wsdl:part name="payload" element="ns1:ProcessOracleSFDCNoItemOrdersRes"/>
    </wsdl:message>
    <wsdl:portType name="UpdateSalesOrderResponseSFDCProv">
        <wsdl:operation name="process">
            <wsdl:input message="client:UpdateSalesOrderResponseSFDCProvRequestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
