<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:client="http://xmlns.oracle.com/SFDCUtilityService/SFDCUtilityService" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns1="http://xmlns.oracle.com/SFDCUtilityService/SFDCUtilityServiceMediator" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/ftp/UserCertificatesLMS2SFDCProcess/UserCertificatesLMS2SFDC/PoolLMSUserCertificateFileFTP" xmlns:ens="urn:sobject.partner.soap.sforce.com" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:fns="urn:fault.partner.soap.sforce.com" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:imp1="http://sunpowercorp.com/PoolLMSUserCertificateFileFTP/xsd/v1" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns0="urn:partner.soap.sforce.com" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl pc plt soap wsdl tns ens fns jca imp1 xsd ns0 client ns1 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/PoolLMSUserCertificateFileFTP.wsdl"/>
            <oracle-xsl-mapper:rootElement name="LMSCertificate" namespace="http://sunpowercorp.com/PoolLMSUserCertificateFileFTP/xsd/v1"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/partner.wsdl"/>
            <oracle-xsl-mapper:rootElement name="queryResponse" namespace="urn:partner.soap.sforce.com"/>
            <oracle-xsl-mapper:param name="InvSFDC_query_OV.parameters"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7003/soa-infra/services/default/SFDCUtilityService/SFDCUtilityServiceMediator.wsdl"/>
            <oracle-xsl-mapper:rootElement name="upsert" namespace="http://xmlns.oracle.com/SFDCUtilityService/SFDCUtilityService"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <oracle-xsl-mapper:named-template-schema>
         <oracle-xsl-mapper:template name="FormatDate">
            <oracle-xsl-mapper:mapSources/>
         </oracle-xsl-mapper:template>
      </oracle-xsl-mapper:named-template-schema>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [SAT OCT 08 17:31:42 IST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="InvSFDC_query_OV.parameters"/>
  <xsl:template match="/">
    <client:upsert>
      <client:externalIDFieldName>
        <xsl:text disable-output-escaping="no">UniqueId__c</xsl:text>
      </client:externalIDFieldName>
      <xsl:for-each select="/imp1:LMSCertificate/imp1:LMSSuccessfactor">
        <xsl:variable name="userId" select="imp1:UserID"/>
        <client:sObject>
          <client:type>
            <xsl:text disable-output-escaping="no">Learning__c</xsl:text>
          </client:type>
          <client:UniqueId__c>
            <xsl:value-of select="concat(imp1:UserID,'|',imp1:ItemID)"/>
          </client:UniqueId__c>
          <client:Name>
            <xsl:value-of select="imp1:ItemID"/>
          </client:Name>
          <client:Title__c>
            <xsl:value-of select="imp1:Description"/>
          </client:Title__c>
          <client:Type__c>
            <xsl:value-of select="dvm:lookupValue(&quot;ItemType.dvm&quot;,&quot;SuccessFact&quot;,imp1:ItemType,&quot;SFDC&quot;,&quot;INVALID_CODE&quot;)"/>
          </client:Type__c>
          <client:Learning_Mode__c>
            <xsl:value-of select="dvm:lookupValue(&quot;Learning_Mode.dvm&quot;,&quot;SuccessFact&quot;,imp1:ItemType,&quot;SFDC&quot;,&quot;INVALID_CODE&quot;)"/>
          </client:Learning_Mode__c>
          <client:Status__c>
            <xsl:value-of select="dvm:lookupValue(&quot;CompletionStatus.dvm&quot;,&quot;SuccessFact&quot;,imp1:CompletionStatusID,&quot;SFDC&quot;,&quot;INVALID_CODE&quot;)"/>
          </client:Status__c>
          <client:Completion_Date__c>
            <xsl:call-template name="FormatDate">
              <xsl:with-param name="inputDate" select="substring-before(normalize-space(imp1:CompletionDate),&quot; &quot;)"/>
            </xsl:call-template>
          </client:Completion_Date__c>
          <client:Contact_Name__c>
            <xsl:value-of select="$InvSFDC_query_OV.parameters/ns0:queryResponse/ns0:result/ns0:records[(ens:Plateau_Id__c = $userId)]/ens:ContactId"/>
          </client:Contact_Name__c>
        </client:sObject>
      </xsl:for-each>
    </client:upsert>
  </xsl:template>
  <xsl:template name="FormatDate">
    <xsl:param name="inputDate"/>
    <xsl:variable name="mo">
      <xsl:value-of select="substring-before($inputDate,'/')"/>
    </xsl:variable>
    <xsl:variable name="DY">
      <xsl:value-of select="substring-after($inputDate,'/')"/>
    </xsl:variable>
    <xsl:variable name="date">
      <xsl:value-of select="substring-before($DY,'/')"/>
    </xsl:variable>
    <xsl:variable name="year">
      <xsl:value-of select="substring-after($DY,'/')"/>
    </xsl:variable>
    <xsl:value-of select="$year"/>
    <xsl:value-of select="'-'"/>
    <xsl:if test="(string-length($mo) &lt; 2)">
      <xsl:value-of select="0"/>
    </xsl:if>
    <xsl:value-of select="$mo"/>
    <xsl:value-of select="'-'"/>
    <xsl:if test="(string-length($date) &lt; 2)">
      <xsl:value-of select="0"/>
    </xsl:if>
    <xsl:value-of select="$date"/>
  </xsl:template>
</xsl:stylesheet>