<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:ns6="http://xmlns.oracle.com/pcbpel/adapter/db/EDICom/Publish856n204OracleToEDICOM/updateStatusToOracle" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/selectDetailsFromOracle" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/updateStatusToOracle" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/AQ/EDICom/Publish856n204OracleToEDICOM/DequeEDISignal" xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns4="http://www.sunpowercorp.com/utilities/indexparams/xsdV1" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:opaque="http://xmlns.oracle.com/pcbpel/adapter/opaque/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns5="http://www.sunpowercorp.com/Publish856n204OracleToEDICOM/EDI_204/xsd/v1" xmlns:ns3="http://www.sunpowercorp.com/utilities/xsd/OrgAssignments/V1" xmlns:ns1="http://www.sunpowercorp.com/Publish856n204OracleToEDICOM/EDIOutboundFileBunch/xsd/v1" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/EDICom/Publish856n204OracleToEDICOM/selectDetailsFromOracle" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns7="http://schemas.oracle.com/bpel/extension" xmlns:ns2="http://www.sunpowercorp.com/Publish856n204OracleToEDICOM/EDI/xsd/v1" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl db ns0 pc ns4 plt opaque wsdl ns5 ns3 ns1 jca tns xsd ns7 ns2 ns6 top xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../selectDetailsFromOracle.wsdl"/>
            <oracle-xsl-mapper:rootElement name="selectDetailsFromOracleOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/selectDetailsFromOracle"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../DequeEDISignal.wsdl"/>
            <oracle-xsl-mapper:rootElement name="params" namespace="http://www.sunpowercorp.com/utilities/indexparams/xsdV1"/>
            <oracle-xsl-mapper:param name="indexVariable"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../updateStatusToOracle.wsdl"/>
            <oracle-xsl-mapper:rootElement name="XxspwrEdicom856N204OutboundCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/updateStatusToOracle"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [WED OCT 05 15:31:17 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="indexVariable"/>
  <xsl:template match="/">
    <top:XxspwrEdicom856N204OutboundCollection>
      <xsl:for-each select="/db:selectDetailsFromOracleOutputCollection/db:selectDetailsFromOracleOutput">
        <top:XxspwrEdicom856N204Outbound>
          <top:comnDeliveryNumber>
            <xsl:if test="db:comn_delivery_number/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="db:comn_delivery_number/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="db:comn_delivery_number"/>
          </top:comnDeliveryNumber>
          <top:groupId>
            <xsl:if test="db:group_id/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="db:group_id/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="db:group_id"/>
          </top:groupId>
          <top:statusCode>
            <xsl:text disable-output-escaping="no">Failed in SOA</xsl:text>
          </top:statusCode>
          <top:errorMessage>
            <xsl:value-of select="$indexVariable/ns4:params/ns4:ErrorMessage"/>
          </top:errorMessage>
          <top:soaLastUpdateDate>
            <xsl:value-of select="xp20:current-dateTime()"/>
          </top:soaLastUpdateDate>
          <top:soaInstanceId>
            <xsl:value-of select="$indexVariable/ns4:params/ns4:InstanceNo"/>
          </top:soaInstanceId>
        </top:XxspwrEdicom856N204Outbound>
      </xsl:for-each>
    </top:XxspwrEdicom856N204OutboundCollection>
  </xsl:template>
</xsl:stylesheet>