<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/insertEDI846ToOracle" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns1="http://www.sunpowercorp.com/utilities/headerIDs/xsd/v1" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://www.sunpowercorp.com/utilities/inputparam/xsd/v1" xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/EDICom/pollEDI846FilesToOracle/insertEDI846ToOracle" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:imp1="http://sunpowercorp.com/846FlatFile/xsd/v1" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/EDICom/pollEDI846FilesToOracle/pollEDI846Files" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl pc ns1 plt wsdl ns0 jca imp1 tns xsd top ns2 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../pollEDI846Files.wsdl"/>
            <oracle-xsl-mapper:rootElement name="OrderDetails" namespace="http://sunpowercorp.com/846FlatFile/xsd/v1"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../pollEDI846Files.wsdl"/>
            <oracle-xsl-mapper:rootElement name="InputParams" namespace="http://www.sunpowercorp.com/utilities/inputparam/xsd/v1"/>
            <oracle-xsl-mapper:param name="inputParam"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../insertEDI846ToOracle.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Xxspwr3PlInvAdviceHdrCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/insertEDI846ToOracle"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <oracle-xsl-mapper:named-template-schema>
         <oracle-xsl-mapper:template name="convertDate">
            <oracle-xsl-mapper:mapSources/>
         </oracle-xsl-mapper:template>
      </oracle-xsl-mapper:named-template-schema>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU OCT 06 11:09:20 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="inputParam"/>
   <xsl:template match="/">
    <top:Xxspwr3PlInvAdviceHdrCollection>
      <xsl:for-each select="/imp1:OrderDetails/imp1:HEADER">
        <top:Xxspwr3PlInvAdviceHdr>
          <top:batchId>
            <xsl:value-of select="$inputParam/ns0:InputParams/ns0:instanceID"/>
          </top:batchId>
          <top:headerId>
            <xsl:value-of select="oraext:sequence-next-val(&quot;xxspwr.xxspwr_3pl_inv_header_seq&quot;,$inputParam/ns0:InputParams/ns0:JNDI)"/>
          </top:headerId>
          <top:signalType>
            <xsl:value-of select="imp1:Signal_Type"/>
          </top:signalType>
          <top:signalReceivedDate>
            <xsl:call-template name="convertDate">
              <xsl:with-param name="date" select="/imp1:OrderDetails/imp1:HEADER/imp1:Snapshot_Date"/>
            </xsl:call-template>
          </top:signalReceivedDate>
          <top:warehouseIdentifier>
            <xsl:value-of select="imp1:warehouse_Identifier"/>
          </top:warehouseIdentifier>
          <top:tplOrganizationName>
            <xsl:value-of select="imp1:Warehouse_Name"/>
          </top:tplOrganizationName>
          <top:tplOrganizationCode>
            <xsl:value-of select="imp1:Warehouse_Code"/>
          </top:tplOrganizationCode>
          <top:address1>
            <xsl:value-of select="imp1:Address_1"/>
          </top:address1>
          <top:address2>
            <xsl:value-of select="imp1:Address_2"/>
          </top:address2>
          <top:city>
            <xsl:value-of select="imp1:City"/>
          </top:city>
          <top:stateProvinceCode>
            <xsl:value-of select="imp1:StateProvince_Code"/>
          </top:stateProvinceCode>
          <top:postalCode>
            <xsl:value-of select="imp1:Postal_Code"/>
          </top:postalCode>
          <top:countryCode>
            <xsl:value-of select="imp1:Country_Code"/>
          </top:countryCode>
          <top:soaStatus>
            <xsl:text disable-output-escaping="no">N</xsl:text>
          </top:soaStatus>
          <top:creationDate>
            <xsl:value-of select="xp20:current-dateTime()"/>
          </top:creationDate>
          <top:lastUpdateDate>
            <xsl:value-of select="xp20:current-dateTime()"/>
          </top:lastUpdateDate>
          <top:createdBy>
            <xsl:text disable-output-escaping="no">-1</xsl:text>
          </top:createdBy>
          <top:processFlag>
            <xsl:text disable-output-escaping="no">N</xsl:text>
          </top:processFlag>
          <top:xxspwr3PlInvAdviceLineCollection>
            <xsl:for-each select="imp1:LinesList">
              <top:Xxspwr3PlInvAdviceLine>
                <top:lineId>
                  <xsl:value-of select="position()"/>
                </top:lineId>
                <top:batchId>
                  <xsl:value-of select="$inputParam/ns0:InputParams/ns0:instanceID"/>
                </top:batchId>
                <top:tplItemNumber>
                  <xsl:value-of select="imp1:WH_Item_Number"/>
                </top:tplItemNumber>
                <top:spwrItemNumber>
                  <xsl:value-of select="imp1:SPWR_Item_Number"/>
                </top:spwrItemNumber>
                <top:refQualifier>
                  <xsl:value-of select="imp1:REF_Qualifier"/>
                </top:refQualifier>
                <top:holdSubinvCode>
                  <xsl:value-of select="imp1:Hold_Subinv_Code"/>
                </top:holdSubinvCode>
                <top:tplOnhandQuantity>
                  <xsl:value-of select="imp1:On_Hand_Quantity"/>
                </top:tplOnhandQuantity>
                <top:primaryUomCode>
                  <xsl:value-of select="imp1:Unit_Of_Measure"/>
                </top:primaryUomCode>
                <top:creationDate>
                  <xsl:value-of select="xp20:current-dateTime()"/>
                </top:creationDate>
                <top:lastUpdateDate>
                  <xsl:value-of select="xp20:current-dateTime()"/>
                </top:lastUpdateDate>
                <top:createdBy>
                  <xsl:text disable-output-escaping="no">-1</xsl:text>
                </top:createdBy>
                <top:processFlag>
                  <xsl:text disable-output-escaping="no">N</xsl:text>
                </top:processFlag>
                <top:holdAdditionalRef>
                  <xsl:value-of select="imp1:Attribute2"/>
                </top:holdAdditionalRef>
              </top:Xxspwr3PlInvAdviceLine>
            </xsl:for-each>
          </top:xxspwr3PlInvAdviceLineCollection>
        </top:Xxspwr3PlInvAdviceHdr>
      </xsl:for-each>
    </top:Xxspwr3PlInvAdviceHdrCollection>
  </xsl:template> <!--  User Defined Templates  --> <xsl:template name="convertDate">
    <xsl:param name="date"/>
    <xsl:value-of select="substring($date,1,4)"/>
    <xsl:value-of select="'-'"/>
    <xsl:value-of select="substring($date,5,2)"/>
    <xsl:value-of select="'-'"/>
    <xsl:value-of select="substring($date,7,2)"/>
    <xsl:value-of select="'T'"/>
    <xsl:value-of select="substring($date,9,2)"/>
    <xsl:value-of select="':'"/>
    <xsl:value-of select="substring($date,11,2)"/>
    <xsl:value-of select="':'"/>
    <xsl:value-of select="substring($date,13,2)"/>
  </xsl:template>
</xsl:stylesheet>