<?binding.jca EBSPollDBAdapter_db.jca?>
<wsdl:definitions name="EBSPollDBAdapter" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Lease2Outbound/Lease2OutboundEBSReq/EBSPollDBAdapter" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Lease2Outbound/Lease2OutboundEBSReq/EBSPollDBAdapter" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/EBSPollDBAdapter">
    <plt:partnerLinkType name="EBSPollDBAdapter_plt">
        <plt:role name="EBSPollDBAdapter_role">
            <plt:portType name="tns:EBSPollDBAdapter_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/EBSPollDBAdapter"
                    schemaLocation="../Schemas/EBSPollDBAdapter_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="XxspwrLease2OutboundDetailsCollection_msg">
        <wsdl:part name="XxspwrLease2OutboundDetailsCollection" element="top:XxspwrLease2OutboundDetailsCollection"/>
    </wsdl:message>
    <wsdl:portType name="EBSPollDBAdapter_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:XxspwrLease2OutboundDetailsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
