<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="Lease2OutboundCanonical"
     targetNamespace="http://www.sunpowercorp.com/Lease2OutboundCanonical/"
     xmlns:ns1="http://www.sunpowercorp.com/Lease2OutboundCanonical/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="Lease2OutboundCanonical_PL">
        <plnk:role name="Lease2OutboundCanonical_Role">
            <plnk:portType name="ns1:Lease2OutboundCanonical"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.sunpowercorp.com/Lease2OutboundCanonical/"
                 location="Lease2OutboundCanonical.wsdl"/>
</wsdl:definitions>
