<?binding.jca PollOracleEBSDataDB_db.jca?>
<wsdl:definitions name="PollOracleEBSDataDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/WarrantyRegistrationOracleToSFDC/WarrantyORACLEToSFDCReq/PollOracleEBSDataDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/WarrantyRegistrationOracleToSFDC/WarrantyORACLEToSFDCReq/PollOracleEBSDataDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollOracleEBSDataDB">
    <plt:partnerLinkType name="PollOracleEBSDataDB_plt">
        <plt:role name="PollOracleEBSDataDB_role">
            <plt:portType name="tns:PollOracleEBSDataDB_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollOracleEBSDataDB"
                    schemaLocation="Schemas/PollOracleEBSDataDB_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="SalesOrdDetCollection_msg">
        <wsdl:part name="SalesOrdDetCollection" element="top:SalesOrdDetCollection"/>
    </wsdl:message>
    <wsdl:portType name="PollOracleEBSDataDB_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:SalesOrdDetCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
