<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="EBIBrokerWebServiceV2"
     targetNamespace="http://com.edicom.broker.adapter.services"
     xmlns:ns1="http://com.edicom.broker.adapter.services"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="EBIBrokerWebServiceV2">
        <plnk:role name="EBIBrokerWebServiceV2">
            <plnk:portType name="ns1:EBIBrokerWebServiceV2"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://com.edicom.broker.adapter.services" location="EBIBrokerWebServiceV2ImplService.wsdl"/>
</wsdl:definitions>
