<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns="http://com.reval.webservices/params" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns0="http://TargetNamespace.com/RevalFileRead" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/file/054_RevalConnect/RevalConnect_FileUpload_2Reval/RevalFileRead"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:client="http://xmlns.oracle.com/054_RevalConnect/RevalConnect_FileUpload_2Reval/RevalConnect_FileUpload_2Reval"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/file/054_RevalConnect/RevalConnect_FileUpload_2Reval/RevalFileRead">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/RevalFileRead.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Root-Element" namespace="http://TargetNamespace.com/RevalFileRead"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/RevalConnect_FileUpload_2Reval.wsdl"/>
            <oracle-xsl-mapper:rootElement name="RevalParams" namespace="http://com.reval.webservices/params"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU APR 20 23:52:47 IST 2017].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
      <RevalParams>
        <Data>
          <Descr>
            <xsl:text disable-output-escaping="no">ABCD</xsl:text>
          </Descr>
          <QJobSysId>
            <xsl:text disable-output-escaping="no">ABCD</xsl:text>
          </QJobSysId>
        </Data>
         <Param ProcessName="">
            <FileName>
                <xsl:text disable-output-escaping="no"></xsl:text>
            </FileName>
            <CSVData>
               <xsl:for-each select="/ns0:Root-Element/ns0:RevalData">
                  <line>
                     <xsl:value-of select="ns0:Line"/>
                  </line>
               </xsl:for-each>
            </CSVData>
            <uiData>
               <ProcessSubType>
                <xsl:text disable-output-escaping="no"></xsl:text>
               </ProcessSubType>
               <ITSServiceFunction>
                <xsl:text disable-output-escaping="no"></xsl:text>
               </ITSServiceFunction>
               <ITSServiceID>
                <xsl:text disable-output-escaping="no"></xsl:text>
               </ITSServiceID>
            </uiData>
         </Param>
      </RevalParams>
   </xsl:template>
</xsl:stylesheet>
