<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/WarrantyRegistrationOracleToSFDC/WarrantyORACLEToSFDCReq/PollOracleEBSDataDB" xmlns:ns5="http://www.sunpowercorp.com/Common/WarrantyOracleToSFDCCommonTypes/V1" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns2="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessWarrantyOracleToSFDC/V1" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollOracleEBSDataDB" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns3="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns0="http://www.sunpowercorp.com/WarrantyOracleToSFDCCanonical/" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns4="http://www.sunpowercorp.com/Noun/WarrantyOracleToSFDC/V1" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl tns plt wsdl top xsd ns5 ns2 soap ns1 ns3 ns0 ns4 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../PollOracleEBSDataDB.wsdl"/>
            <oracle-xsl-mapper:rootElement name="SalesOrdDetCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollOracleEBSDataDB"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7004/WarrantyORACLEToSFDCSvc/Proxy/WarrantyORACLEToSFDCSvcPS?wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessWarrantyOracleToSFDC" namespace="http://www.sunpowercorp.com/BOD/ProcessWarrantyOracleToSFDC/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU OCT 06 10:15:41 IST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns1:ProcessWarrantyOracleToSFDC>
      <ns1:DataArea>
        <ns4:WROracleToSFDC>
          <xsl:for-each select="/top:SalesOrdDetCollection/top:SalesOrdDet">
            <xsl:variable name="pos" select="position()"/>
          <ns4:WRORACLEToSFDCDetails>
            <ns5:No>
              <xsl:value-of select="/top:SalesOrdDetCollection/top:SalesOrdDet[$pos]/top:no"/>
            </ns5:No>
            <ns5:Quantity_Ordered>
              <xsl:value-of select="/top:SalesOrdDetCollection/top:SalesOrdDet[$pos]/top:quantityOrdered"/>
            </ns5:Quantity_Ordered>
            <ns5:Delivery_No>
              <xsl:value-of select="/top:SalesOrdDetCollection/top:SalesOrdDet[$pos]/top:deliveryNo"/>
            </ns5:Delivery_No>
            <ns5:Customer_Number>
              <xsl:value-of select="/top:SalesOrdDetCollection/top:SalesOrdDet[$pos]/top:customerNumber"/>
            </ns5:Customer_Number>
            <ns5:ORDER_CREATION_DATE>
              <xsl:value-of select="/top:SalesOrdDetCollection/top:SalesOrdDet[$pos]/top:orderCreationDate"/>
            </ns5:ORDER_CREATION_DATE>
            <ns5:CUSTOMER_NAME>
              <xsl:value-of select="/top:SalesOrdDetCollection/top:SalesOrdDet[$pos]/top:customerName"/>
            </ns5:CUSTOMER_NAME>
            <ns5:PURCHASE_ORDER>
              <xsl:value-of select="/top:SalesOrdDetCollection/top:SalesOrdDet[$pos]/top:purchaseOrder"/>
            </ns5:PURCHASE_ORDER>
            <ns5:SALES_ORDER>
              <xsl:value-of select="/top:SalesOrdDetCollection/top:SalesOrdDet[$pos]/top:salesOrder"/>
            </ns5:SALES_ORDER>
            <ns5:Theater>
              <xsl:value-of select="/top:SalesOrdDetCollection/top:SalesOrdDet[$pos]/top:theater"/>
            </ns5:Theater>
            <ns5:Packing_SLIP>
              <xsl:value-of select="/top:SalesOrdDetCollection/top:SalesOrdDet[$pos]/top:packingSlip"/>
            </ns5:Packing_SLIP>
          </ns4:WRORACLEToSFDCDetails>
            </xsl:for-each>
        </ns4:WROracleToSFDC>
      </ns1:DataArea>
    </ns1:ProcessWarrantyOracleToSFDC>
  </xsl:template>
</xsl:stylesheet>