<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="PDFFTPCanonical"
     targetNamespace="http://www.sunpowercorp.com/PDFFTPCanonical/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:WL5G3N2="http://www.sunpowercorp.com/PDFFTPCanonical/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="PDFFTPOSBService">
        <plnk:role name="PDFFTPCanonical">
            <plnk:portType name="WL5G3N2:PDFFTPCanonical"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.sunpowercorp.com/PDFFTPCanonical/" location="http://dev-fusappdca02.sunpowercorp.com:7004/SOAPDFMETASyncSvc/Proxy/SOAPDFMETASyncSvcPS?wsdl"/>
</wsdl:definitions>
