<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ns0="http://www.sunpowercorp.com/order/Verb/VerbCommonTypes/V1" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:ns6="http://xmlns.oracle.com/SFDCUtilityService/SFDCUtilityService" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateOrderEBS" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns5="http://www.sunpowercorp.com/Noun/OracleSFDCNoItemOrders/V1" xmlns:tns="http://xmlns.oracle.com/SFDCUtilityService/SFDCUtilityServiceMediator" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns2="http://www.sunpowercorp.com/SFDCSyncLeaseCustomerReq/xsd/v1" xmlns:ns3="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns4="http://www.sunpowercorp.com/Common/OracleSFDCNoItemOrdersCommonTypes/V1" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:client="http://xmlns.oracle.com/OnLineSalesOrder/UpdateSalesOrderResponseSFDCProv/UpdateSalesOrderResponseSFDCProv" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessOracleSFDCNoItemOrders/V1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns7="http://xmlns.oracle.com/pcbpel/adapter/db/OnLineSalesOrder/UpdateSalesOrderResponseSFDCProv/UpdateOrderEBS" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns0 ns6 ns5 tns plnk wsdl ns2 ns3 ns4 client ns1 xsd top ns7 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/UpdateSalesOrderResponseSFDCProv.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessOracleSFDCNoItemOrdersRes" namespace="http://www.sunpowercorp.com/BOD/ProcessOracleSFDCNoItemOrders/V1"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7003/soa-infra/services/default/SFDCUtilityService!1.0/SFDCUtilityServiceMediator.wsdl"/>
            <oracle-xsl-mapper:rootElement name="updateResponse" namespace="http://xmlns.oracle.com/SFDCUtilityService/SFDCUtilityService"/>
            <oracle-xsl-mapper:param name="ReceiveSFDCUtilityService_OV.payload"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/UpdateSalesOrderResponseSFDCProv.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Inputparam" namespace="http://www.sunpowercorp.com/SFDCSyncLeaseCustomerReq/xsd/v1"/>
            <oracle-xsl-mapper:param name="InstanceId"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../UpdateOrderEBS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="XxspwrDsrSoHeaderCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateOrderEBS"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <oracle-xsl-mapper:named-template-schema>
         <oracle-xsl-mapper:template name="OrdersEBSResp">
            <oracle-xsl-mapper:mapSources/>
         </oracle-xsl-mapper:template>
      </oracle-xsl-mapper:named-template-schema>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON OCT 10 15:20:58 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="ReceiveSFDCUtilityService_OV.payload"/>
  <xsl:param name="InstanceId"/>
  <xsl:template match="/">
    <top:XxspwrDsrSoHeaderCollection>
      <xsl:for-each select="/ns1:ProcessOracleSFDCNoItemOrdersRes/ns1:DataArea/ns5:OracleSFDCNoItemOrder/ns5:OracleSFDCNoItemOrderDetails">
        <xsl:call-template name="OrdersEBSResp">
          <xsl:with-param name="ordersCnt" select="ns4:POSITION"/>
          <xsl:with-param name="orders" select="."/>
        </xsl:call-template>
      </xsl:for-each>
    </top:XxspwrDsrSoHeaderCollection>
  </xsl:template>
  <!--  User Defined Templates   -->
  <xsl:template name="OrdersEBSResp">
    <xsl:param name="ordersCnt"/>
    <xsl:param name="orders"/>
    <top:XxspwrDsrSoHeader>
      <top:sfdcId>
        <xsl:value-of select="$orders/ns4:SFDC_ID"/>
      </top:sfdcId>
      <xsl:choose>
        <xsl:when test="$ReceiveSFDCUtilityService_OV.payload/ns6:updateResponse/ns6:result[position()=$ordersCnt]/ns6:success='true'">
          <top:sfdcSynced>
            <xsl:value-of select="'S'"/>
          </top:sfdcSynced>
        </xsl:when>
        <xsl:otherwise>
          <top:sfdcSynced>
            <xsl:value-of select="'E'"/>
          </top:sfdcSynced>
          <top:soaErrorMessage>
            <xsl:value-of select="$ReceiveSFDCUtilityService_OV.payload/ns6:updateResponse/ns6:result[position()=$ordersCnt]/ns6:errors/ns6:message"/>
          </top:soaErrorMessage>
        </xsl:otherwise>
      </xsl:choose>
      <top:soaO2SId>
        <xsl:value-of select="$InstanceId/ns2:Inputparam/ns2:instanceid"/>
      </top:soaO2SId>
    </top:XxspwrDsrSoHeader>
  </xsl:template>
</xsl:stylesheet>