<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessOracleSFDCItem/V1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns5="http://www.sunpowercorp.com/Noun/OracleSFDCItem/V1" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns2="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns0="http://www.sunpowercorp.com/OracleSFDCItemCanonical/" xmlns:ns4="http://www.sunpowercorp.com/Common/OracleSFDCItemCommonTypes/V1" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OnlineOrderingItemOnlyOracleToSFDC/OracleSFDCItemPRODReq/FetchOrcEbizDataDB" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns3="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/FetchOrcEbizDataDB" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl plt wsdl tns xsd db ns1 ns5 ns2 soap ns0 ns4 ns3 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/FetchOrcEbizDataDB.wsdl"/>
            <oracle-xsl-mapper:rootElement name="FetchOrcEbizDataDBOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/FetchOrcEbizDataDB"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7004/OracleSFDCItemPRODSvc/Proxy/OracleSFDCItemPRODSvcPS?wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessOracleSFDCItem" namespace="http://www.sunpowercorp.com/BOD/ProcessOracleSFDCItem/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [MON OCT 10 17:45:04 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns1:ProcessOracleSFDCItem>
      <ns1:DataArea>
        <ns5:OracleSFDCItem>
          <xsl:for-each select="/db:FetchOrcEbizDataDBOutputCollection/db:FetchOrcEbizDataDBOutput">
            <ns5:OracleSFDCItemDetails>
              <ns4:ITEM_NUMBER>
                <xsl:value-of select="db:ITEM_NUMBER"/>
              </ns4:ITEM_NUMBER>
              <ns4:DESCRIPTION>
                <xsl:value-of select="db:DESCRIPTION"/>
              </ns4:DESCRIPTION>
              <ns4:LONG_DESCRIPTION>
                <xsl:value-of select="db:LONG_DESCRIPTION"/>
              </ns4:LONG_DESCRIPTION>
              <ns4:INVENTORY_ITEM_ID>
                <xsl:value-of select="db:INVENTORY_ITEM_ID"/>
              </ns4:INVENTORY_ITEM_ID>
              <ns4:ITEM_CATEGORY1>
                <xsl:value-of select="db:Item_category1"/>
              </ns4:ITEM_CATEGORY1>
              <ns4:ITEM_CATEGORY2>
                <xsl:value-of select="db:Item_category2"/>
              </ns4:ITEM_CATEGORY2>
              <ns4:ITEM_CATEGORY3>
                <xsl:value-of select="db:Item_Category3"/>
              </ns4:ITEM_CATEGORY3>
              <ns4:PROD_TYPE>
                <xsl:value-of select="db:PROD_TYPE"/>
              </ns4:PROD_TYPE>
              <ns4:ITEM_STATUS_CODE>
                <xsl:value-of select="db:ITEM_STATUS_CODE"/>
              </ns4:ITEM_STATUS_CODE>
            </ns5:OracleSFDCItemDetails>
          </xsl:for-each>
        </ns5:OracleSFDCItem>
      </ns1:DataArea>
    </ns1:ProcessOracleSFDCItem>
  </xsl:template>
</xsl:stylesheet>