<?binding.jca DeleteToDSRSOLinesEBS_db.jca?>
<wsdl:definitions name="DeleteToDSRSOLinesEBS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OnLineSalesOrder/CreateSalesOrderOracleProv/DeleteToDSRSOLinesEBS" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DeleteToDSRSOLinesEBS" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OnLineSalesOrder/CreateSalesOrderOracleProv/DeleteToDSRSOLinesEBS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="DeleteToDSRSOLinesEBS_plt">
        <plt:role name="DeleteToDSRSOLinesEBS_role">
            <plt:portType name="tns:DeleteToDSRSOLinesEBS_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DeleteToDSRSOLinesEBS"
                    schemaLocation="Schemas/DeleteToDSRSOLinesEBS.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="DeleteToDSRSOLinesEBSInput_msg">
        <wsdl:part name="DeleteToDSRSOLinesEBSInput_msg" element="db:DeleteToDSRSOLinesEBSInput"/>
    </wsdl:message>
    <wsdl:portType name="DeleteToDSRSOLinesEBS_ptt">
        <wsdl:operation name="DeleteToDSRSOLinesEBS">
            <wsdl:input message="tns:DeleteToDSRSOLinesEBSInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
