<?binding.jca UpdateCustSiteEBS_db.jca?>
<wsdl:definitions name="UpdateCustSiteEBS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TPOSOACustomerSync/UpdateCustomerSFDCProv/UpdateCustSiteEBS" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/TPOSOACustomerSync/UpdateCustomerSFDCProv/UpdateCustSiteEBS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateCustSiteEBS">
    <plt:partnerLinkType name="UpdateCustSiteEBS_plt">
        <plt:role name="UpdateCustSiteEBS_role">
            <plt:portType name="tns:UpdateCustSiteEBS_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateCustSiteEBS"
                    schemaLocation="../Schemas/UpdateCustSiteEBS_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="XxspwrSforaCustSitesCollection_msg">
        <wsdl:part name="XxspwrSforaCustSitesCollection" element="top:XxspwrSforaCustSitesCollection"/>
    </wsdl:message>
    <wsdl:portType name="UpdateCustSiteEBS_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:XxspwrSforaCustSitesCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
