<?binding.jca UpdateAccountEBS_db.jca?>
<wsdl:definitions name="UpdateAccountEBS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TPOSOACustomerSync/UpdateCustomerSFDCProv/UpdateAccountEBS" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/TPOSOACustomerSync/UpdateCustomerSFDCProv/UpdateAccountEBS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateAccountEBS">
    <plt:partnerLinkType name="UpdateAccountEBS_plt">
        <plt:role name="UpdateAccountEBS_role">
            <plt:portType name="tns:UpdateAccountEBS_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateAccountEBS"
                    schemaLocation="../Schemas/UpdateAccountEBS_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="XxspwrSforaCustomersCollection_msg">
        <wsdl:part name="XxspwrSforaCustomersCollection" element="top:XxspwrSforaCustomersCollection"/>
    </wsdl:message>
    <wsdl:portType name="UpdateAccountEBS_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:XxspwrSforaCustomersCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
