<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:client="http://www.sunpowercorp.com/SOAUtilityServices/CommonLoggingService/CommonLoggingService_BPEL" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOAUtilityServices/CommonLoggingService/InsertLoggingDataDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertLoggingDataDB" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl client plnk xsd wsdl tns top bpws xp20 mhdr bpel oraext dvm hwf med ids bpm xdk xref ora socket ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/CommonLoggingService_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="process" namespace="http://www.sunpowercorp.com/SOAUtilityServices/CommonLoggingService/CommonLoggingService_BPEL"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../../InsertLoggingDataDB.wsdl"/>
            <oracle-xsl-mapper:rootElement name="MidddlewareErrorLogCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertLoggingDataDB"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE OCT 04 11:22:08 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <top:MidddlewareErrorLogCollection>
      <top:MidddlewareErrorLog>
        <top:faultmessage>
          <xsl:value-of select="/client:process/client:faultmessage"/>
        </top:faultmessage>
        <top:faultcode>
          <xsl:value-of select="/client:process/client:faultcode"/>
        </top:faultcode>
        <top:faulttime>
          <xsl:value-of select="/client:process/client:faulttime"/>
        </top:faulttime>
        <top:faultdescription>
          <xsl:value-of select="/client:process/client:faultdescription"/>
        </top:faultdescription>
        <top:correctiveaction>
          <xsl:value-of select="/client:process/client:correctiveaction"/>
        </top:correctiveaction>
        <top:interfacenumber>
          <xsl:value-of select="/client:process/client:interfacenumber"/>
        </top:interfacenumber>
        <top:interfacename>
          <xsl:value-of select="/client:process/client:interfacename"/>
        </top:interfacename>
        <top:instancenumber>
          <xsl:value-of select="/client:process/client:instancenumber"/>
        </top:instancenumber>
        <top:processname>
          <xsl:value-of select="/client:process/client:processname"/>
        </top:processname>
        <top:bopenserviceticket>
          <xsl:value-of select="/client:process/client:bopenserviceticket"/>
        </top:bopenserviceticket>
        <top:severity>
          <xsl:value-of select="/client:process/client:severity"/>
        </top:severity>
        <top:faultsystemname>
          <xsl:value-of select="/client:process/client:faultsystemname"/>
        </top:faultsystemname>
        <top:status>
          <xsl:value-of select="/client:process/client:status"/>
        </top:status>
        <top:createddatetime>
          <xsl:value-of select="/client:process/client:createddatetime"/>
        </top:createddatetime>
      </top:MidddlewareErrorLog>
    </top:MidddlewareErrorLogCollection>
  </xsl:template>
</xsl:stylesheet>