<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/GetFTPDataDetailsDB" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns3="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/PDFFTPSalesforceT0042/SOAPDFMETASyncReq/GetFTPDataDetailsDB" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns5="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:ns2="http://www.sunpowercorp.com/Common/PDFFTPSalesForceCommonTypes/V1" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns0="http://www.sunpowercorp.com/PDFFTPCanonical/" xmlns:ns4="http://www.sunpowercorp.com/Noun/PDFFTPSalesForce/V1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessPDFFTPSalesForce/V1" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl db plt wsdl tns xsd ns3 soap ns5 ns2 ns0 ns4 ns1 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../GetFTPDataDetailsDB.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetFTPDataDetailsDBOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/GetFTPDataDetailsDB"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7004/SOAPDFMETASyncSvc/Proxy/SOAPDFMETASyncSvcPS?wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessPDFFTPSalesForce" namespace="http://www.sunpowercorp.com/BOD/ProcessPDFFTPSalesForce/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU OCT 06 10:31:06 IST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns1:ProcessPDFFTPSalesForce>
      <ns1:DataArea>
        <ns4:PDFSalesForce>
          <ns4:PDFSalesForceDetails>
            <ns2:TRX_NUMBER>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:TRX_NUMBER"/>
            </ns2:TRX_NUMBER>
            <ns2:BILL_TO_CUSTOMER_ID>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:BILL_TO_CUSTOMER_ID"/>
            </ns2:BILL_TO_CUSTOMER_ID>
            <ns2:CUSTOMER_NUMBER>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:CUSTOMER_NUMBER"/>
            </ns2:CUSTOMER_NUMBER>
            <ns2:TRX_STATUS>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:TRX_STATUS"/>
            </ns2:TRX_STATUS>
            <ns2:TRX_DATE>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:TRX_DATE"/>
            </ns2:TRX_DATE>
            <ns2:TRX_CREATION_DATE>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:TRX_CREATION_DATE"/>
            </ns2:TRX_CREATION_DATE>
            <ns2:TRX_TYPE>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:TRX_TYPE"/>
            </ns2:TRX_TYPE>
            <ns2:TRX_TYPE_NAME>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:TRX_TYPE_NAME"/>
            </ns2:TRX_TYPE_NAME>
            <ns2:TRX_TYPE_DESC>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:TRX_TYPE_DESC"/>
            </ns2:TRX_TYPE_DESC>
            <ns2:OPERATING_UNIT_NAME>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:OPERATING_UNIT_NAME"/>
            </ns2:OPERATING_UNIT_NAME>
            <ns2:CURRENCY_CODE>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:CURRENCY_CODE"/>
            </ns2:CURRENCY_CODE>
            <ns2:TRANSACTION_CURRENCY_CODE>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:TRANSACTION_CURRENCY_CODE"/>
            </ns2:TRANSACTION_CURRENCY_CODE>
            <ns2:LAST_UPDATE_DATE>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:LAST_UPDATE_DATE"/>
            </ns2:LAST_UPDATE_DATE>
            <ns2:CREATED_BY>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:CREATED_BY"/>
            </ns2:CREATED_BY>
            <ns2:LAST_UPDATED_BY>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:LAST_UPDATED_BY"/>
            </ns2:LAST_UPDATED_BY>
            <ns2:LAST_UPDATED_LOGIN>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:LAST_UPDATED_LOGIN"/>
            </ns2:LAST_UPDATED_LOGIN>
            <ns2:RECORD_STATUS>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:RECORD_STATUS"/>
            </ns2:RECORD_STATUS>
            <ns2:RECORD_ID>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:RECORD_ID"/>
            </ns2:RECORD_ID>
            <ns2:ERROR_MESSAGE>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:ERROR_MESSAGE"/>
            </ns2:ERROR_MESSAGE>
            <ns2:PDF_FILE_NAME>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:PDF_FILE_NAME"/>
            </ns2:PDF_FILE_NAME>
            <ns2:TRX_LAST_UPDATED_DATE>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:TRX_LAST_UPDATED_DATE"/>
            </ns2:TRX_LAST_UPDATED_DATE>
            <ns2:T_CREATION_DATE>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:T_CREATION_DATE"/>
            </ns2:T_CREATION_DATE>
            <ns2:TRX_TYPE_MEANING>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:TRX_TYPE_MEANING"/>
            </ns2:TRX_TYPE_MEANING>
            <ns2:ORG_ID>
              <xsl:value-of select="/db:GetFTPDataDetailsDBOutputCollection/db:GetFTPDataDetailsDBOutput/db:ORG_ID"/>
            </ns2:ORG_ID>
            <ns2:Body>
              <xsl:text disable-output-escaping="no"/>
            </ns2:Body>
            <ns2:SourceDirectoryPath>
              <xsl:text disable-output-escaping="no"/>
            </ns2:SourceDirectoryPath>
          </ns4:PDFSalesForceDetails>
        </ns4:PDFSalesForce>
      </ns1:DataArea>
    </ns1:ProcessPDFFTPSalesForce>
  </xsl:template>
</xsl:stylesheet>