<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="http://www.sunpowercorp.com/SunPowerDevelopment/BulkEmailServiceProvider/initParams/xsd/v1" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/SOAUtilityServices/BulkEmailServiceProvider/updateEmailStatusToDB" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/updateEmailStatusToDB" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:client="http://xmlns.oracle.com/SOAUtilityServices/BulkEmailServiceProvider/BulkEmailServiceProviderBPEL" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOAUtilityServices/BulkEmailServiceProvider/selectRecordsFromDB" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/selectRecordsFromDB" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:ns2="http://www.sunpowercorp.com/SunPowerDevelopment/utility/BatchEmailUtilityService/xsd/V1" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns1 plt wsdl client tns db ns2 xsd ns0 top xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/selectRecordsFromDB.wsdl"/>
            <oracle-xsl-mapper:rootElement name="selectRecordsFromDBOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/selectRecordsFromDB"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/BulkEmailServiceProviderBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="InitParams" namespace="http://www.sunpowercorp.com/SunPowerDevelopment/BulkEmailServiceProvider/initParams/xsd/v1"/>
            <oracle-xsl-mapper:param name="initParams"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/updateEmailStatusToDB.wsdl"/>
            <oracle-xsl-mapper:rootElement name="MiddlewareErrorLogCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/updateEmailStatusToDB"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE OCT 04 10:54:07 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="initParams"/>
  <xsl:template match="/">
    <top:MiddlewareErrorLogCollection>
      <xsl:for-each select="/db:selectRecordsFromDBOutputCollection/db:selectRecordsFromDBOutput">
        <top:MiddlewareErrorLog>
          <top:interfacenumber>
            <xsl:value-of select="$initParams/ns1:InitParams/ns1:interfaceNo"/>
          </top:interfacenumber>
          <top:instancenumber>
            <xsl:value-of select="db:INSTANCENUMBER"/>
          </top:instancenumber>
          <top:uniqueIdentifier>
            <xsl:if test="db:UNIQUE_IDENTIFIER/@xsi:nil">
              <xsl:attribute name="xsi:nil">
                <xsl:value-of select="db:UNIQUE_IDENTIFIER/@xsi:nil"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="db:UNIQUE_IDENTIFIER"/>
          </top:uniqueIdentifier>
          <top:emailSent>
            <xsl:text disable-output-escaping="no">Y</xsl:text>
          </top:emailSent>
        </top:MiddlewareErrorLog>
      </xsl:for-each>
    </top:MiddlewareErrorLogCollection>
  </xsl:template>
</xsl:stylesheet>