<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="2.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="http://www.sunpowercorp.com/SunPowerDevelopment/BulkEmailServiceProvider/initParams/xsd/v1" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:client="http://xmlns.oracle.com/SOAUtilityServices/BulkEmailServiceProvider/BulkEmailServiceProviderBPEL" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SOAUtilityServices/BulkEmailServiceProvider/selectRecordsFromDB" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/selectRecordsFromDB" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:ns2="http://www.sunpowercorp.com/SunPowerDevelopment/utility/BatchEmailUtilityService/xsd/V1" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns1 plt wsdl client tns db ns2 xsd xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/selectRecordsFromDB.wsdl"/>
            <oracle-xsl-mapper:rootElement name="selectRecordsFromDBOutputCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/selectRecordsFromDB"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/BulkEmailServiceProviderBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="InitParams" namespace="http://www.sunpowercorp.com/SunPowerDevelopment/BulkEmailServiceProvider/initParams/xsd/v1"/>
            <oracle-xsl-mapper:param name="initParams"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/BulkEmailServiceProviderBPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="EmailContent" namespace="http://www.sunpowercorp.com/SunPowerDevelopment/utility/BatchEmailUtilityService/xsd/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE OCT 04 10:54:07 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="initParams"/>
  <xsl:template match="/">
    <xsl:variable name="StartIndex" select="$initParams/ns1:InitParams/ns1:startIndex"/>
    <xsl:variable name="EndIndex" select="$initParams/ns1:InitParams/ns1:endIndex"/>
    <ns2:EmailContent>
    
      <ns2:To>
        <xsl:value-of select="dvm:lookupValue(&quot;EmailDistributionList.dvm&quot;,&quot;InterfaceNumber&quot;,$initParams/ns1:InitParams/ns1:interfaceNo,&quot;emailDistrubtionList&quot;,&quot;SOASupport@sunpowercorp.com&quot;)"/>
      </ns2:To>
      
      <ns2:Subject>
        <xsl:value-of select="concat(&quot;Exception raised while processing &quot;,/db:selectRecordsFromDBOutputCollection/db:selectRecordsFromDBOutput[1]/db:INTERFACENAME)"/>
      </ns2:Subject>
      <xsl:variable name="tableHeader" select="concat(&quot;Dear Admin &lt;br/> Following errors occurred for service &quot;,/db:selectRecordsFromDBOutputCollection/db:selectRecordsFromDBOutput[1]/db:INTERFACENAME,&quot; with Interface Number &quot;,$initParams/ns1:InitParams/ns1:interfaceNo,&quot;&lt;br/>&lt;br/>&lt;table border='1'>&lt;tr>&lt;th bgcolor='#C0C0C0'>&lt;b>ProcessName&lt;/b>&lt;/th> &lt;th bgcolor='#C0C0C0'>&lt;b>FaultCode&lt;/b>&lt;/th> &lt;th bgcolor='#C0C0C0'>&lt;b>FaultDescription&lt;/b>&lt;/th> &lt;th bgcolor='#C0C0C0'>&lt;b>FaultTime&lt;/b>&lt;/th> &lt;th bgcolor='#C0C0C0'>&lt;b>UniqueIdentifier&lt;/b>&lt;/th> &lt;th bgcolor='#C0C0C0'>&lt;b>Instance Number&lt;/b>&lt;/th>&lt;/tr> &quot;)"/>
      <xsl:variable name="tableBody">
        <xsl:for-each select="$StartIndex to $EndIndex">
          <xsl:variable name="index" select="."/>
          <xsl:value-of select="concat(&quot;&lt;tr>&lt;td>&quot;,/db:selectRecordsFromDBOutputCollection/db:selectRecordsFromDBOutput[$index]/db:PROCESSNAME,&quot;&lt;/td>&lt;td>&quot;,/db:selectRecordsFromDBOutputCollection/db:selectRecordsFromDBOutput[$index]/db:FAULTCODE,&quot;&lt;/td>&lt;td>&quot;,/db:selectRecordsFromDBOutputCollection/db:selectRecordsFromDBOutput[$index]/db:FAULTDESCRIPTION,&quot;&lt;/td>&lt;td>&quot;,/db:selectRecordsFromDBOutputCollection/db:selectRecordsFromDBOutput[$index]/db:FAULTTIME,&quot;&lt;/td>&lt;td>&quot;,/db:selectRecordsFromDBOutputCollection/db:selectRecordsFromDBOutput[$index]/db:UNIQUE_IDENTIFIER,&quot;&lt;/td>&lt;td>&quot;,/db:selectRecordsFromDBOutputCollection/db:selectRecordsFromDBOutput[$index]/db:INSTANCENUMBER,&quot;&lt;/td>&lt;/tr>&quot;)"/>
        </xsl:for-each>
      </xsl:variable>
      <ns2:body>
        <xsl:value-of select="concat($tableHeader,$tableBody,&quot;&lt;/table> &lt;br/> &lt;i> Note: This message was automatically generated, please do not reply to it &lt;/i> &lt;br/>&lt;br/>&lt;b>Thanks &amp; Regards&lt;/b>&lt;br/>System Admin&quot;)"/>
      </ns2:body>
    </ns2:EmailContent>
  </xsl:template>
</xsl:stylesheet>