<?binding.jca updateStatusToDB_db.jca?>
<wsdl:definitions name="updateStatusToDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/EDICom/pollEDI997FilesToOracle/updateStatusToDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/EDICom/pollEDI997FilesToOracle/updateStatusToDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/updateStatusToDB">
    <plt:partnerLinkType name="updateStatusToDB_plt">
        <plt:role name="updateStatusToDB_role">
            <plt:portType name="tns:updateStatusToDB_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/updateStatusToDB"
                    schemaLocation="Schemas/updateStatusToDB_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="XxspwrEdicomInboundTrackCollection_msg">
        <wsdl:part name="XxspwrEdicomInboundTrackCollection" element="top:XxspwrEdicomInboundTrackCollection"/>
    </wsdl:message>
    <wsdl:portType name="updateStatusToDB_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:XxspwrEdicomInboundTrackCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
