<definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBJDEVResource/JDEVDBResources/ProcessOSBErrorLogs" name="ProcessOSBErrorLogs-concrete" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSBJDEVResource/JDEVDBResources/ProcessOSBErrorLogs" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSBJDEVResource/JDEVDBResources/ProcessOSBErrorLogs" location="../JCAResources/ProcessOSBErrorLogs.wsdl"/>
  <binding name="ProcessOSBErrorLogs_ptt-binding" type="tns:ProcessOSBErrorLogs_ptt">
    <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
    <operation name="insert">
      <soap:operation soapAction="insert"/>
      <input>
        <soap:body use="literal"/>
      </input>
    </operation>
  </binding>
  <service name="ProcessOSBErrorLogs-service">
    <port name="ProcessOSBErrorLogs-port" binding="tns:ProcessOSBErrorLogs_ptt-binding">
      <soap:address location="jca://eis/DB/SunPower_DEV"/>
    </port>
  </service>
</definitions>