<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns5="http://www.sunpowercorp.com/ACBAccountClaimToSFDCDetails" xmlns:client="http://www.sunpowercorp.com/MarketingNTrainingActAppClmACBToSFDC/ACBGetAllActivitesmergeProv/ACBGetAllActivitesmergeProv_BPEL" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns8="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessACBClaimToSFDC/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns10="http://www.sunpowercorp.com/Noun/ACBActivitiesToSFDC/V1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns7="http://www.sunpowercorp.com/SunPowerDevelopment/DealerPartnerCreditINFO/EnqueSyncCreditHoldLimit/initParams/xsd/v1" xmlns:ns2="http://www.sunpowercorp.com/BOD/ProcessACBActivitiesToSFDC/V1" xmlns:ns0="http://www.sunpowercorp.com/Common/ACBActivitiesToSFDCCommonTypes/V1" xmlns:ns3="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns9="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns6="http://www.sunpowercorp.com/ACBClaimToSFDCMergeDetails" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns4="urn:partner.soap.sforce.com" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns5 client ns8 ns1 plnk ns10 wsdl ns7 ns2 ns0 ns3 ns9 ns6 xsd ns4 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/ACBGetAllActivitesmergeProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessACBActivitiesToSFDC" namespace="http://www.sunpowercorp.com/BOD/ProcessACBActivitiesToSFDC/V1"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/ACBGetAllActivitesmergeProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ACBAccountClaimToSFDCRows" namespace="http://www.sunpowercorp.com/ACBAccountClaimToSFDCDetails"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [FRI OCT 07 16:21:33 IST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns5:ACBAccountClaimToSFDCRows>
      <xsl:for-each select="/ns2:ProcessACBActivitiesToSFDC/ns2:DataArea/ns10:ACBActivitiesToSFDC/ns10:ACBActivitiesToSFDCDetails">
        <ns5:row>
          <ns5:Promotion__c>
            <xsl:value-of select="ns0:Promotion__c"/>
          </ns5:Promotion__c>
          <ns5:Promotion_Description__c>
            <xsl:value-of select="ns0:Promotion_Description__c"/>
          </ns5:Promotion_Description__c>
          <ns5:Transaction_Type__c>
            <xsl:value-of select="ns0:Transaction_Type__c"/>
          </ns5:Transaction_Type__c>
          <ns5:Transaction_Year__c>
            <xsl:value-of select="ns0:Transaction_Month__c"/>
          </ns5:Transaction_Year__c>
          <ns5:Transaction_Month__c>
            <xsl:value-of select="ns0:Transaction_Year__c"/>
          </ns5:Transaction_Month__c>
          <ns5:Sum_of_Transaction_Amt__c>
            <xsl:value-of select="ns0:Sum_of_Transaction_Amt__c"/>
          </ns5:Sum_of_Transaction_Amt__c>
          <ns5:Comment__c>
            <xsl:value-of select="ns0:Comment__c"/>
          </ns5:Comment__c>
          <ns5:Promotion_Year__c>
            <xsl:value-of select="ns0:Promotion_Year__c"/>
          </ns5:Promotion_Year__c>
          <ns5:Record_Number__c>
            <xsl:value-of select="ns0:Record_Number__c"/>
          </ns5:Record_Number__c>
          <ns5:ACBParanet_ID__C>
            <xsl:value-of select="ns0:ACBParanet_ID__C"/>
          </ns5:ACBParanet_ID__C>
        </ns5:row>
      </xsl:for-each>
    </ns5:ACBAccountClaimToSFDCRows>
  </xsl:template>
</xsl:stylesheet>