<?binding.jca UpdateContactEBS_db.jca?>
<wsdl:definitions name="UpdateContactEBS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TPOSOACustomerSync/UpdateCustomerSFDCProv/UpdateContactEBS" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/TPOSOACustomerSync/UpdateCustomerSFDCProv/UpdateContactEBS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateContactEBS">
    <plt:partnerLinkType name="UpdateContactEBS_plt">
        <plt:role name="UpdateContactEBS_role">
            <plt:portType name="tns:UpdateContactEBS_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateContactEBS"
                    schemaLocation="../Schemas/UpdateContactEBS_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="XxspwrCustContactsCollection_msg">
        <wsdl:part name="XxspwrCustContactsCollection" element="top:XxspwrCustContactsCollection"/>
    </wsdl:message>
    <wsdl:portType name="UpdateContactEBS_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:XxspwrCustContactsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
