<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns5="http://www.sunpowercorp.com/MergedOracleSFDC" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns10="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns2="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns0="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns7="http://www.sunpowercorp.com/MergedOracleAttachmentSFDC" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:client="http://www.sunpowercorp.com/PDFFTPSalesforceT0042/SOAPDFMETASyncProv/SOAPDFMETASyncProv_BPEL" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:ns8="http://www.sunpowercorp.com/Common/PDFFTPSalesForceCommonTypes/V1" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:ns6="http://www.sunpowercorp.com/MergedAttachmentSFDC" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns9="http://www.sunpowercorp.com/Noun/PDFFTPSalesForce/V1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns3="http://schemas.oracle.com/bpel/extension" xmlns:ns4="http://www.sunpowercorp.com/MergedSFDC" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessPDFFTPSalesForce/V1" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns5 ns10 plnk wsdl ns2 ns0 ns7 client ns8 ns6 ns9 xsd ns3 ns4 ns1 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:ns11="http://www.pdf_meta_sync_params.org">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../SOAPDFMETASyncProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="MergedOracleSFDCRows" namespace="http://www.sunpowercorp.com/MergedOracleSFDC"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../SOAPDFMETASyncProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="MergedAttachmentSFDCRows" namespace="http://www.sunpowercorp.com/MergedAttachmentSFDC"/>
            <oracle-xsl-mapper:param name="MergeAttachSFDC"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../SOAPDFMETASyncProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="MergedOracleAttachmentSFDCRows" namespace="http://www.sunpowercorp.com/MergedOracleAttachmentSFDC"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU OCT 06 10:31:19 IST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="MergeAttachSFDC"/>
  <xsl:template match="/">
    <ns7:MergedOracleAttachmentSFDCRows>
      <xsl:for-each select="$MergeAttachSFDC/ns6:MergedAttachmentSFDCRows/ns6:row">
        <xsl:variable name="InputRow" select="."/>
        <xsl:for-each select="/ns5:MergedOracleSFDCRows/ns5:row">
          <xsl:variable name="SFDCRow" select="."/>
          <xsl:if test="($InputRow/ns6:SFDC_ACCOUNT_ID = ns5:SFDC_ACCOUNT_ID) and ($InputRow/ns6:PDF_FILE_NAME = ns5:PDF_FILE_NAME)">
            <ns7:row>
              <ns7:TRX_NUMBER>
                <xsl:value-of select="ns5:TRX_NUMBER"/>
              </ns7:TRX_NUMBER>
              <ns7:BILL_TO_CUSTOMER_ID>
                <xsl:value-of select="ns5:BILL_TO_CUSTOMER_ID"/>
              </ns7:BILL_TO_CUSTOMER_ID>
              <ns7:CUSOMER_NAME>
                <xsl:value-of select="ns5:CUSOMER_NAME"/>
              </ns7:CUSOMER_NAME>
              <ns7:CUSOMER_NUMBER>
                <xsl:value-of select="ns5:CUSOMER_NUMBER"/>
              </ns7:CUSOMER_NUMBER>
              <ns7:TRX_STATUS>
                <xsl:value-of select="ns5:TRX_STATUS"/>
              </ns7:TRX_STATUS>
              <ns7:TRX_DATE>
                <xsl:value-of select="ns5:TRX_DATE"/>
              </ns7:TRX_DATE>
              <ns7:TRX_CREATION_DATE>
                <xsl:value-of select="ns5:TRX_CREATION_DATE"/>
              </ns7:TRX_CREATION_DATE>
              <ns7:TRX_TYPE>
                <xsl:value-of select="ns5:TRX_TYPE"/>
              </ns7:TRX_TYPE>
              <ns7:TRX_TYPE_NAME>
                <xsl:value-of select="ns5:TRX_TYPE_NAME"/>
              </ns7:TRX_TYPE_NAME>
              <ns7:TRX_TYPE_DESC>
                <xsl:value-of select="ns5:TRX_TYPE_DESC"/>
              </ns7:TRX_TYPE_DESC>
              <ns7:OPERATING_UNIT_NAME>
                <xsl:value-of select="ns5:OPERATING_UNIT_NAME"/>
              </ns7:OPERATING_UNIT_NAME>
              <ns7:CURRENCY_CODE>
                <xsl:value-of select="ns5:CURRENCY_CODE"/>
              </ns7:CURRENCY_CODE>
              <ns7:TRANSACTION_CURRENCY_CODE>
                <xsl:value-of select="ns5:TRANSACTION_CURRENCY_CODE"/>
              </ns7:TRANSACTION_CURRENCY_CODE>
              <ns7:LAST_UPDATE_DATE>
                <xsl:value-of select="ns5:LAST_UPDATE_DATE"/>
              </ns7:LAST_UPDATE_DATE>
              <ns7:CREATED_BY>
                <xsl:value-of select="ns5:CREATED_BY"/>
              </ns7:CREATED_BY>
              <ns7:LAST_UPDATED_BY>
                <xsl:value-of select="ns5:LAST_UPDATED_BY"/>
              </ns7:LAST_UPDATED_BY>
              <ns7:LAST_UPDATED_LOGIN>
                <xsl:value-of select="ns5:LAST_UPDATED_LOGIN"/>
              </ns7:LAST_UPDATED_LOGIN>
              <ns7:RECORD_STATUS>
                <xsl:value-of select="ns5:RECORD_STATUS"/>
              </ns7:RECORD_STATUS>
              <ns7:RECORD_ID>
                <xsl:value-of select="ns5:RECORD_ID"/>
              </ns7:RECORD_ID>
              <ns7:ERROR_MESSAGE>
                <xsl:value-of select="ns5:ERROR_MESSAGE"/>
              </ns7:ERROR_MESSAGE>
              <ns7:PDF_FILE_NAME>
                <xsl:value-of select="ns5:PDF_FILE_NAME"/>
              </ns7:PDF_FILE_NAME>
              <ns7:TRX_LAST_UPDATED_DATE>
                <xsl:value-of select="ns5:TRX_LAST_UPDATED_DATE"/>
              </ns7:TRX_LAST_UPDATED_DATE>
              <ns7:T_CREATION_DATE>
                <xsl:value-of select="ns5:T_CREATION_DATE"/>
              </ns7:T_CREATION_DATE>
              <ns7:SFDC_ACCOUNT_ID>
                <xsl:value-of select="ns5:SFDC_ACCOUNT_ID"/>
              </ns7:SFDC_ACCOUNT_ID>
              <ns7:SFDC_ACCOUNT_NAME>
                <xsl:value-of select="ns5:SFDC_ACCOUNT_NAME"/>
              </ns7:SFDC_ACCOUNT_NAME>
              <ns7:SFDC_USER_ID>
                <xsl:value-of select="ns5:SFDC_USER_ID"/>
              </ns7:SFDC_USER_ID>
              <ns7:SFDC_ATTACHMENT_ID>
                <xsl:value-of select="$InputRow/ns6:SFDC_ATTACHMENT_ID"/>
              </ns7:SFDC_ATTACHMENT_ID>
              <ns7:TRX_TYPE_MEANING>
                <xsl:value-of select="ns5:TRX_TYPE_MEANING"/>
              </ns7:TRX_TYPE_MEANING>
              <ns7:ORG_ID>
                <xsl:value-of select="ns5:ORG_ID"/>
              </ns7:ORG_ID>
            </ns7:row>
          </xsl:if>
        </xsl:for-each>
      </xsl:for-each>
    </ns7:MergedOracleAttachmentSFDCRows>
  </xsl:template>
</xsl:stylesheet>