<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:ns0="http://www.sunpowercorp.com/MergedOracleSFDC" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:tns="urn:partner.soap.sforce.com" xmlns:ns2="http://www.pdf_meta_sync_params.org" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessPDFFTPSalesForce/V1" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" exclude-result-prefixes=" xsd oracle-xsl-mapper xsi xsl ns0 ns2 ns1 tns mhdr oraext xp20 xref socket dvm oraxsl"
                xmlns:ns9="http://www.sunpowercorp.com/Common/CommonDataTypes/V1"
                xmlns:ns4="http://www.sunpowercorp.com/MergedSFDC"
                xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:ns6="http://www.sunpowercorp.com/MergedAttachmentSFDC"
                xmlns:client="http://www.sunpowercorp.com/PDFFTPSalesforceT0042/SOAPDFMETASyncProv/SOAPDFMETASyncProv_BPEL"
                xmlns:ns7="http://www.sunpowercorp.com/MergedOracleAttachmentSFDC"
                xmlns:ns8="http://www.sunpowercorp.com/Common/PDFFTPSalesForceCommonTypes/V1"
                xmlns:ns3="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                xmlns:ns5="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns10="http://www.sunpowercorp.com/Noun/PDFFTPSalesForce/V1"
                xmlns:ns11="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:fns="urn:fault.partner.soap.sforce.com"
                xmlns:ens="urn:sobject.partner.soap.sforce.com">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../SOAPDFMETASyncProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="MergedOracleSFDCRows" namespace="http://www.sunpowercorp.com/MergedOracleSFDC"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../SOAPDFMETASyncProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessPDFFTPSalesForce" namespace="http://www.sunpowercorp.com/BOD/ProcessPDFFTPSalesForce/V1"/>
            <oracle-xsl-mapper:param name="inputVariable.payload"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="XSD">
            <oracle-xsl-mapper:schema location="../Schemas/params.xsd"/>
            <oracle-xsl-mapper:rootElement name="params" namespace="http://www.pdf_meta_sync_params.org"/>
            <oracle-xsl-mapper:param name="params"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../partner.wsdl"/>
            <oracle-xsl-mapper:rootElement name="upsert" namespace="urn:partner.soap.sforce.com"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE APR 30 00:24:56 IST 2019].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="inputVariable.payload"/>
   <xsl:param name="params"/>
   <xsl:template match="/">
      <tns:upsert>
        <tns:externalIDFieldName>
          <xsl:text disable-output-escaping="no">Id</xsl:text>
         </tns:externalIDFieldName>
         <xsl:for-each select="/ns0:MergedOracleSFDCRows/ns0:row[position()=$params/ns2:params/ns2:loopCounter]">
            <tns:sObjects>
                <ens:type>
                  <xsl:text disable-output-escaping="no">Attachment</xsl:text>
                </ens:type>
               <ens:Body>
                  <xsl:value-of select="$inputVariable.payload/ns1:ProcessPDFFTPSalesForce/ns1:DataArea/ns10:PDFSalesForce/ns10:PDFSalesForceDetails/ns8:Body"/>
               </ens:Body>
               <ens:Name>
                  <xsl:value-of select="$inputVariable.payload/ns1:ProcessPDFFTPSalesForce/ns1:DataArea/ns10:PDFSalesForce/ns10:PDFSalesForceDetails/ns8:PDF_FILE_NAME"/>
               </ens:Name>
               <ens:ContentType>
            <xsl:text disable-output-escaping="no">application/pdf</xsl:text>
          </ens:ContentType>
               <ens:ParentId>
                  <xsl:value-of select="ns0:SFDC_ACCOUNT_ID"/>
               </ens:ParentId>
               <ens:OwnerId>
            <xsl:value-of select="ns0:SFDC_USER_ID"/>
          </ens:OwnerId>
            </tns:sObjects>
         </xsl:for-each>
      </tns:upsert>
   </xsl:template>
</xsl:stylesheet>
