<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ns3="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesProv/xsd/OrgAssignments/V1" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns6="http://www.sunpowercorp.com/Common/ArenaOracleDataFeedDetailsCommonTypes/V1" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns0="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns8="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesProv/xsd/Categories/V1" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:client="http://www.sunpowercorp.com/SunPowerDevelopment/ArenaOracleItemsBOMSubstituesProv/ArenaOracleItemsBOMSubstituesProv_BPEL" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns4="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesProv/xsd/ListOfVendorsArenaAsls/V1" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns5="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns2="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesProv/xsd/defaultParams/V1" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessArenaOracleDataFeed/V1" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns9="http://schemas.oracle.com/bpel/extension" xmlns:ns7="http://www.sunpowercorp.com/Noun/ArenaOracleDataFeed/V1" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns3 ns6 ns0 plnk wsdl ns8 client ns4 ns5 ns2 ns1 xsd ns9 ns7 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../ArenaOracleItemsBOMSubstituesProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Item" namespace="http://www.sunpowercorp.com/BOD/ProcessArenaOracleDataFeed/V1"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../ArenaOracleItemsBOMSubstituesProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessArenaOracleDataFeed" namespace="http://www.sunpowercorp.com/BOD/ProcessArenaOracleDataFeed/V1"/>
            <oracle-xsl-mapper:param name="inputVariable.payload"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../ArenaOracleItemsBOMSubstituesProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ListOfVendorsArenaAsls" namespace="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesProv/xsd/ListOfVendorsArenaAsls/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE OCT 04 15:42:23 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="inputVariable.payload"/>
   <xsl:template match="ns7:ApprovedManufacturerList">
    <ns4:ListOfVendorsArenaAsls>
      <xsl:for-each select="./ns7:ApprovedManufacturerListItem">
        <xsl:variable name="manufacturedBy">
          <xsl:value-of select="@ns6:manufacturedBy"/>
        </xsl:variable>
        <xsl:variable name="manufacturerPartIdentifier">
          <xsl:if test="ns7:AdditionalAttributes[@groupLabel = &quot;Supplier Item Type&quot;]">
            <xsl:value-of select="@ns6:manufacturerPartIdentifier"/>
          </xsl:if>
        </xsl:variable>
        <xsl:variable name="manufacturerPartUniqueIdentifier">
          <xsl:if test="ns7:AdditionalAttributes[@groupLabel = &quot;Supplier Item Type&quot;]">
            <xsl:value-of select="@ns6:manufacturerPartUniqueIdentifier"/>
          </xsl:if>
        </xsl:variable>
        <xsl:if test="($manufacturerPartIdentifier!='') and ($manufacturerPartUniqueIdentifier!='') ">
          <xsl:for-each select="$inputVariable.payload/ns1:ProcessArenaOracleDataFeed/ns1:DataArea/ns7:ArenaOracleDataFeed/ns7:ArenaOracleDataFeedDetails/ns7:ManufacturerParts/ns7:ManufacturerPart">
            <xsl:if test="(@ns6:manufacturerPartIdentifier=$manufacturerPartIdentifier) and (@ns6:manufacturerPartUniqueIdentifier=$manufacturerPartUniqueIdentifier)">
              <ns4:ListOfVendorArenaAsls>
                <ns4:ManufacturedBy>
                  <xsl:value-of select="$manufacturedBy"/>
                </ns4:ManufacturedBy>
                <xsl:for-each select="ns7:ApprovedSupplierList/ns7:ApprovedSupplierListItem">
                  <ns4:ARENA_ASLS>
                    <xsl:variable name="vendarName">
                      <xsl:value-of select="@ns6:suppliedBy"/>
                    </xsl:variable>
                    <ns4:Vendar_Name>
                      <xsl:value-of select="$vendarName"/>
                    </ns4:Vendar_Name>
                    <ns4:Vendar_Number>
                      <xsl:value-of select="$inputVariable.payload/ns1:ProcessArenaOracleDataFeed/ns1:DataArea/ns7:ArenaOracleDataFeed/ns7:ArenaOracleDataFeedDetails/ns7:Contacts/ns7:Contact[@ns6:contactName =$vendarName]/@ns6:contactIdentifier"/>
                    </ns4:Vendar_Number>
                    <ns4:Vendar_Item>
                       <xsl:value-of select="substring(@ns6:supplierPartIdentifier,1,25)"/>
                    </ns4:Vendar_Item>
                    <ns4:Vendar_Status>
                      <xsl:value-of select="@ns6:globalSupplierPartStatusCode"/>
                    </ns4:Vendar_Status>
                    <ns4:Vendar_Comment>
                      <xsl:value-of select="@ns6:comments"/>
                    </ns4:Vendar_Comment>
                  </ns4:ARENA_ASLS>
                </xsl:for-each>
              </ns4:ListOfVendorArenaAsls>
            </xsl:if>
          </xsl:for-each>
        </xsl:if>
      </xsl:for-each>
    </ns4:ListOfVendorsArenaAsls>
  </xsl:template>
</xsl:stylesheet>