<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:ns5="http://www.sunpowercorp.com/Common/ArenaOracleDataFeedDetailsCommonTypes/V1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns0="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:client="http://www.sunpowercorp.com/SunPowerDevelopment/ArenaOracleItemsBOMSubstituesProv/ArenaOracleItemsBOMSubstituesProv_BPEL" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns4="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns2="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesProv/xsd/defaultParams/V1" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessArenaOracleDataFeed/V1" xmlns:ns3="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesProv/xsd/OrgAssignments/V1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns6="http://www.sunpowercorp.com/Noun/ArenaOracleDataFeed/V1" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns5 ns0 plnk wsdl client ns4 ns2 ns1 ns3 xsd ns6 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:ns9="http://schemas.oracle.com/bpel/extension"
                xmlns:ns7="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesProv/xsd/ListOfVendorsArenaAsls/V1"
                xmlns:ns8="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesProv/xsd/Categories/V1">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../ArenaOracleItemsBOMSubstituesProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Item" namespace="http://www.sunpowercorp.com/BOD/ProcessArenaOracleDataFeed/V1"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../ArenaOracleItemsBOMSubstituesProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="params" namespace="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesProv/xsd/OrgAssignments/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE OCT 04 15:42:23 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="ns1:Item">
    <ns3:params>
      <xsl:if test="./ns6:AdditionalAttributes[@groupLabel='Arena Solutions Custom Attributes']">
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='China - JV']/@ns5:value !=''">                                                                                    
          <ns3:param>
            <ns3:Name>
              <xsl:text>China - JV</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='China - JV']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>       
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='China - SPWR']/@ns5:value !=''">                                                                                    
          <ns3:param>
            <ns3:Name>
              <xsl:text>SPSWCHN OU</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='China - SPWR']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if> 
         <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco Mobile PG']/@ns5:value !=''">                                                                                    
          <ns3:param>
            <ns3:Name>
              <xsl:text>Modco Mobile PG</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco Mobile PG']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>      
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='RLC BU']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>RLC BU</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='RLC BU']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Components BU']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Components BU</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Components BU']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='New Homes BU']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>New Homes BU</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='New Homes BU']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Systems BU']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Systems BU</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Systems BU']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPAU (OU) Australia']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>SPAU (OU) Australia</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPAU (OU) Australia']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPEB (OU) Projects USA']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>SPEB (OU) Projects USA</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPEB (OU) Projects USA']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPNA (OU) North America']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>SPNA (OU) North America</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPNA (OU) North America']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPSW (OU) Switzerland']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>SPSW (OU) Switzerland</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPSW (OU) Switzerland']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPES (OU) Spain']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>SPES (OU) Spain</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPES (OU) Spain']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPDE (OU) Germany']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>SPDE (OU) Germany</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPDE (OU) Germany']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPIT (OU) Italy']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>SPIT (OU) Italy</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPIT (OU) Italy']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPKR (OU) Korea']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>SPKR (OU) Korea</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPKR (OU) Korea']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPCN (OU) Canada']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>SPCN (OU) Canada</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPCN (OU) Canada']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPPT (OU) Portugal']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>SPPT (OU) Portugal</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPPT (OU) Portugal']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPFR (OU) France']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>SPFR (OU) France</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPFR (OU) France']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPGR (OU) Greece']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>SPGR (OU) Greece</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPGR (OU) Greece']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPML (OU) Phils']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>SPML (OU) Phils</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPML (OU) Phils']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Australia']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Australia</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Australia']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='USA']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>USA</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='USA']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Spain']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Spain</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Spain']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Germany']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Germany</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Germany']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Italy']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Italy</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Italy']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='France']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>France</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='France']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Portugal']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Portugal</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Portugal']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Greece']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Greece</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Greece']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Korea']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Korea</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Korea']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Canada']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Canada</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Canada']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='US O AND M']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>US O AND M</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='US O AND M']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='UK']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>UK</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='UK']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Belgium']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Belgium</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Belgium']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='North America - Non US']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>North America - Non US</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='North America - Non US']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='India']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>India</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='India']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Cell Fab 1 and 2']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Cell Fab 1 and 2</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Cell Fab 1 and 2']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Modco</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco SPMX']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Modco SPMX</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco SPMX']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco CM MX PL or CN']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Modco CM MX PL or CN</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco CM MX PL or CN']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco CM SW']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Modco CM SW</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco CM SW']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco CM CA']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Modco CM CA</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco CM CA']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco CM CN']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Modco CM CN</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco CM CN']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco CM MX']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Modco CM MX</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco CM MX']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco CM PL']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Modco CM PL</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco CM PL']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco SPDV']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Modco SPDV</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco SPDV']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>        
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco SPMX2']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Modco SPMX2</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco SPMX2']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        
        
        
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPTN BU']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>SPTN BU</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPTN BU']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco SPTM Tenesol']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Modco SPTM Tenesol</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco SPTM Tenesol']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco SPTT Tenesol']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Modco SPTT Tenesol</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco SPTT Tenesol']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco SPTT']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Modco SPTT</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco SPTT']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Israel']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Israel</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Israel']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPIL (OU) Israel']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>SPIL (OU) Israel</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='SPIL (OU) Israel']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <!-- added as part of the CR raised on 11th Oct 2013 -->
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Chile']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Chile</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Chile']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Switzerland']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Switzerland</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Switzerland']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Japan']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Japan</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Japan']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <!--         INC4732086 : Update SOA to Activate F35 org    -->
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Cell Fab 3']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Cell Fab 3</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Cell Fab 3']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <!--CHG0012266 Include "Mexico" & 'South Africa' -->
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='South Africa']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>South Africa</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='South Africa']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Mexico']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Mexico</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Mexico']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <!--         INC4892698  : Update SOA to Activate F38 org    -->
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Cell Fab 4']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Cell Fab 4</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Cell Fab 4']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <!--         INC4892698  : Update SOA to Activate F47 org    -->
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco SPSA']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>Modco SPSA</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Modco SPSA']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
             <!--         INC4892698  : Update SOA to Activate W51 org    -->
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='APAC Region']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>APAC Region</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='APAC Region']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='EMEA Region']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text>EMEA Region</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='EMEA Region']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
        <xsl:if test="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Americas Region']/@ns5:value !=''">
          <ns3:param>
            <ns3:Name>
              <xsl:text> Americas Region</xsl:text>
            </ns3:Name>
            <ns3:Value>
              <xsl:value-of select="./ns6:AdditionalAttributes/ns6:AdditionalAttribute[@ns5:name='Americas Region']/@ns5:value"/>
            </ns3:Value>
          </ns3:param>
        </xsl:if>
      </xsl:if>
    </ns3:params>
  </xsl:template>
</xsl:stylesheet>