
package com.oracle.xmlns._054_revalconnect.revalconnect_fileupload_2reval.revalconnect_fileupload_2reval;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "revalconnect_fileupload_2reval_client_ep",
                  targetNamespace =
                  "http://xmlns.oracle.com/054_RevalConnect/RevalConnect_FileUpload_2Reval/RevalConnect_FileUpload_2Reval",
                  wsdlLocation =
                  "http://dev-fusappdca02:7003/soa-infra/services/finance/RevalConnect_FileUpload_2Reval/revalconnect_fileupload_2reval_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2F054_RevalConnect%2FRevalConnect_FileUpload_2Reval%2FRevalConnect_FileUpload_2Reval%7Drevalconnect_fileupload_2reval_client_ep")
public class RevalconnectFileupload2RevalClientEp extends Service {

    private final static URL REVALCONNECTFILEUPLOAD2REVALCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException REVALCONNECTFILEUPLOAD2REVALCLIENTEP_EXCEPTION;
    private final static QName REVALCONNECTFILEUPLOAD2REVALCLIENTEP_QNAME =
        new QName("http://xmlns.oracle.com/054_RevalConnect/RevalConnect_FileUpload_2Reval/RevalConnect_FileUpload_2Reval",
                  "revalconnect_fileupload_2reval_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://dev-fusappdca02:7003/soa-infra/services/finance/RevalConnect_FileUpload_2Reval/revalconnect_fileupload_2reval_client_ep?WSDL#%7Bhttp%3A%2F%2Fxmlns.oracle.com%2F054_RevalConnect%2FRevalConnect_FileUpload_2Reval%2FRevalConnect_FileUpload_2Reval%7Drevalconnect_fileupload_2reval_client_ep");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        REVALCONNECTFILEUPLOAD2REVALCLIENTEP_WSDL_LOCATION = url;
        REVALCONNECTFILEUPLOAD2REVALCLIENTEP_EXCEPTION = e;
    }

    public RevalconnectFileupload2RevalClientEp() {
        super(__getWsdlLocation(), REVALCONNECTFILEUPLOAD2REVALCLIENTEP_QNAME);
    }

    public RevalconnectFileupload2RevalClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), REVALCONNECTFILEUPLOAD2REVALCLIENTEP_QNAME, features);
    }

    public RevalconnectFileupload2RevalClientEp(URL wsdlLocation) {
        super(wsdlLocation, REVALCONNECTFILEUPLOAD2REVALCLIENTEP_QNAME);
    }

    public RevalconnectFileupload2RevalClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, REVALCONNECTFILEUPLOAD2REVALCLIENTEP_QNAME, features);
    }

    public RevalconnectFileupload2RevalClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RevalconnectFileupload2RevalClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RevalConnectFileUpload2Reval
     */
    @WebEndpoint(name = "RevalConnect_FileUpload_2Reval_pt")
    public RevalConnectFileUpload2Reval getRevalConnectFileUpload2RevalPt() {
        return super.getPort(new QName("http://xmlns.oracle.com/054_RevalConnect/RevalConnect_FileUpload_2Reval/RevalConnect_FileUpload_2Reval",
                                       "RevalConnect_FileUpload_2Reval_pt"), RevalConnectFileUpload2Reval.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RevalConnectFileUpload2Reval
     */
    @WebEndpoint(name = "RevalConnect_FileUpload_2Reval_pt")
    public RevalConnectFileUpload2Reval getRevalConnectFileUpload2RevalPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/054_RevalConnect/RevalConnect_FileUpload_2Reval/RevalConnect_FileUpload_2Reval",
                                       "RevalConnect_FileUpload_2Reval_pt"), RevalConnectFileUpload2Reval.class,
                             features);
    }

    private static URL __getWsdlLocation() {
        if (REVALCONNECTFILEUPLOAD2REVALCLIENTEP_EXCEPTION != null) {
            throw REVALCONNECTFILEUPLOAD2REVALCLIENTEP_EXCEPTION;
        }
        return REVALCONNECTFILEUPLOAD2REVALCLIENTEP_WSDL_LOCATION;
    }

}
