<wsdl:definitions name="OracleSFDCVertexDataLoadProv_BPEL" targetNamespace="http://www.sunpowercorp.com/OracleSFDC_VertexDataLoad/OracleSFDCVertexDataLoadProv/OracleSFDCVertexDataLoadProv_BPEL" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessVertexDataFeedDetails/V1" xmlns:client="http://www.sunpowercorp.com/OracleSFDC_VertexDataLoad/OracleSFDCVertexDataLoadProv/OracleSFDCVertexDataLoadProv_BPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
     <wsdl:types>
     
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.sunpowercorp.com/BOD/ProcessVertexDataFeedDetails/V1" schemaLocation="../xsd/CDM/BOD/Nouns/VertexDataFeed/V1/ProcessVertexDataFeedDetails.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="OracleSFDCVertexDataLoadProv_BPELRequestMessage">
        <wsdl:part name="payload" element="ns1:ProcessVertexDataFeedDetails"/>
    </wsdl:message>
  
    <wsdl:portType name="OracleSFDCVertexDataLoadProv_BPEL">
        <wsdl:operation name="process">
            <wsdl:input message="client:OracleSFDCVertexDataLoadProv_BPELRequestMessage"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="OracleSFDCVertexDataLoadProv_BPELBinding" type="client:OracleSFDCVertexDataLoadProv_BPEL">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="oraclesfdcvertexdataloadprov_bpel_client_ep">
        <wsdl:port name="OracleSFDCVertexDataLoadProv_BPEL_pt" binding="client:OracleSFDCVertexDataLoadProv_BPELBinding">
            <soap:address location="http://dev-fusappdca02.sunpowercorp.com:7003/soa-infra/services/default/OracleSFDCVertexDataLoadProv/oraclesfdcvertexdataloadprov_bpel_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>