<?binding.jca UpdateEBS_db.jca?>
<wsdl:definitions name="UpdateEBS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OracleSFDC_VertexDataLoad/OracleSFDCVertexDataLoadProv/UpdateEBS" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OracleSFDC_VertexDataLoad/OracleSFDCVertexDataLoadProv/UpdateEBS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateEBS">
    <plt:partnerLinkType name="UpdateEBS_plt">
        <plt:role name="UpdateEBS_role">
            <plt:portType name="tns:UpdateEBS_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateEBS"
                    schemaLocation="Schemas/UpdateEBS_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="XxspwrGeoVertexStgCollection_msg">
        <wsdl:part name="XxspwrGeoVertexStgCollection" element="top:XxspwrGeoVertexStgCollection"/>
    </wsdl:message>
    <wsdl:portType name="UpdateEBS_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:XxspwrGeoVertexStgCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
