<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="CostCenterFeedOracle2SF_BPEL" targetNamespace="http://www.sunpowercorp.com/SuccessFactor/CostCenterFeedOracle2SF/CostCenterFeedOracle2SF_BPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:client="http://www.sunpowercorp.com/SuccessFactor/CostCenterFeedOracle2SF/CostCenterFeedOracle2SF_BPEL" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://www.sunpowercorp.com/SuccessFactor/CostCenterFeedOracle2SF/CostCenterFeedOracle2SF_BPEL" schemaLocation="../Schemas/CostCenterFeedOracle2SF_BPEL.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="CostCenterFeedOracle2SF_BPELRequestMessage">
      <wsdl:part name="payload" element="client:process"/>
   </wsdl:message>
   <wsdl:portType name="CostCenterFeedOracle2SF_BPEL">
      <wsdl:operation name="process">
         <wsdl:input message="client:CostCenterFeedOracle2SF_BPELRequestMessage"/>
      </wsdl:operation>
   </wsdl:portType>
   <plnk:partnerLinkType name="CostCenterFeedOracle2SF_BPEL">
      <plnk:role name="CostCenterFeedOracle2SF_BPELProvider">
         <plnk:portType name="client:CostCenterFeedOracle2SF_BPEL"/>
      </plnk:role>
   </plnk:partnerLinkType>
</wsdl:definitions>
