<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessOracleSFDCNoItemOperatingUnit/V1" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns0="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns9="http://www.sunpowercorp.com/SunPowerApp/CommonErrorHandler/CommonErrorHandler_BPEL" xmlns:ns3="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:ns5="http://www.sunpowercorp.com/Noun/OracleSFDCNoItemOperatingUnit/V1" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns6="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns7="http://www.sunpowercorp.com/Common/OracleSFDCNoItemOperatingUnitCommonTypes/V1" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:client="http://www.sunpowercorp.com/OnlineOrderingNoItemOracleToSFDC/OracleSFDCNoItemOperatingUnitProv/OracleSFDCNoItemOperatingUnitProv_BPEL" xmlns:ns10="http://www.sunpowercorp.com/SOAUtilityServices/CommonLoggingService/CommonLoggingService_BPEL" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:ns4="http://www.sunpowercorp.com/OnlineOrderingNoItemOracleToSFDC/OracleAccountNumbers/xsd/v1" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns2="urn:partner.soap.sforce.com" xmlns:ns8="http://www.sunpowercorp.com/SunPowerDevelopment/utility/CommonErrorHandler/xsd/V1" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns1 ns0 plnk wsdl ns9 ns3 ns5 ns6 ns7 client ns4 xsd ns2 ns8 ns10 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../OracleSFDCNoItemOperatingUnitProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessOracleSFDCNoItemOperatingUnit" namespace="http://www.sunpowercorp.com/BOD/ProcessOracleSFDCNoItemOperatingUnit/V1"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7003/soa-infra/services/default/CommonErrorHandler/CommonErrorHandler_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="CommonErrorHandlerInput" namespace="http://www.sunpowercorp.com/SunPowerDevelopment/utility/CommonErrorHandler/xsd/V1"/>
            <oracle-xsl-mapper:param name="InvCommonErrorHandler_IV.payload"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7003/soa-infra/services/default/CommonLoggingService/CommonLoggingService_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Process" namespace="http://www.sunpowercorp.com/SOAUtilityServices/CommonLoggingService/CommonLoggingService_BPEL"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [THU OCT 06 10:54:50 IST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="InvCommonErrorHandler_IV.payload"/>
  <xsl:template match="/">
    <ns10:Process>
      <xsl:for-each select="/ns1:ProcessOracleSFDCNoItemOperatingUnit/ns1:DataArea/ns5:OracleSFDCNoItemOperatingUnit/ns5:OracleSFDCNoItemOperatingUnitDetails">
        <ns10:ProcessLog>
          <ns10:faultmessage>
            <xsl:value-of select="$InvCommonErrorHandler_IV.payload/ns8:CommonErrorHandlerInput/ns8:Fault/ns8:FaultMessage"/>
          </ns10:faultmessage>
          <ns10:faultcode>
            <xsl:value-of select="$InvCommonErrorHandler_IV.payload/ns8:CommonErrorHandlerInput/ns8:Fault/ns8:FaultCode"/>
          </ns10:faultcode>
          <ns10:faulttime>
            <xsl:value-of select="$InvCommonErrorHandler_IV.payload/ns8:CommonErrorHandlerInput/ns8:Fault/ns8:FaultTime"/>
          </ns10:faulttime>
          <ns10:faultdescription>
            <xsl:value-of select="$InvCommonErrorHandler_IV.payload/ns8:CommonErrorHandlerInput/ns8:Fault/ns8:FaultDescription"/>
          </ns10:faultdescription>
          <ns10:correctiveaction>
            <xsl:value-of select="$InvCommonErrorHandler_IV.payload/ns8:CommonErrorHandlerInput/ns8:CorrectiveAction"/>
          </ns10:correctiveaction>
          <ns10:interfacenumber>
            <xsl:value-of select="$InvCommonErrorHandler_IV.payload/ns8:CommonErrorHandlerInput/ns8:InterfaceNumber"/>
          </ns10:interfacenumber>
          <ns10:interfacename>
            <xsl:value-of select="$InvCommonErrorHandler_IV.payload/ns8:CommonErrorHandlerInput/ns8:InterfaceName"/>
          </ns10:interfacename>
          <ns10:instancenumber>
            <xsl:value-of select="$InvCommonErrorHandler_IV.payload/ns8:CommonErrorHandlerInput/ns8:InstanceNumber"/>
          </ns10:instancenumber>
          <ns10:processname>
            <xsl:value-of select="$InvCommonErrorHandler_IV.payload/ns8:CommonErrorHandlerInput/ns8:ProcessName"/>
          </ns10:processname>
          <ns10:bopenserviceticket>
            <xsl:value-of select="$InvCommonErrorHandler_IV.payload/ns8:CommonErrorHandlerInput/ns8:bOpenServiceTicket"/>
          </ns10:bopenserviceticket>
          <ns10:severity>
            <xsl:value-of select="$InvCommonErrorHandler_IV.payload/ns8:CommonErrorHandlerInput/ns8:Severity"/>
          </ns10:severity>
          <ns10:faultsystemname>
            <xsl:value-of select="$InvCommonErrorHandler_IV.payload/ns8:CommonErrorHandlerInput/ns8:FaultSystemName"/>
          </ns10:faultsystemname>
          <ns10:status>
            <xsl:text disable-output-escaping="no">'E'</xsl:text>
          </ns10:status>
          <ns10:createddatetime>
            <xsl:value-of select="xp20:current-dateTime()"/>
          </ns10:createddatetime>
          <ns10:uniqueIdentifier>
            <xsl:value-of select="ns7:ORALCE_ACCOUNT_NUMBER"/>
          </ns10:uniqueIdentifier>
          <ns10:emailSent>
            <xsl:value-of select="$InvCommonErrorHandler_IV.payload/ns8:CommonErrorHandlerInput/ns8:SendEmail"/>
          </ns10:emailSent>
        </ns10:ProcessLog>
      </xsl:for-each>
    </ns10:Process>
  </xsl:template>
</xsl:stylesheet>