<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ns7="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesProv/xsd/OrgAssignments/V1" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns4="http://www.sunpowercorp.com/Common/ArenaOracleDataFeedDetailsCommonTypes/V1" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns0="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:ns8="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesProv/xsd/Categories/V1" xmlns:client="http://www.sunpowercorp.com/SunPowerDevelopment/ArenaOracleItemsBOMSubstituesProv/ArenaOracleItemsBOMSubstituesProv_BPEL" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns3="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesProv/xsd/ListOfVendorsArenaAsls/V1" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns2="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns6="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesProv/xsd/defaultParams/V1" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SunPowerDevelopment/ArenaOracleItemsBOMSubstituesProv/processItemtoEBS" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessArenaOracleDataFeed/V1" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns9="http://schemas.oracle.com/bpel/extension" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/processItemtoEBS" xmlns:ns5="http://www.sunpowercorp.com/Noun/ArenaOracleDataFeed/V1" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns7 ns4 ns0 plnk wsdl ns8 client ns3 ns2 ns6 ns1 xsd ns9 ns5 tns top xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java">
   <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../ArenaOracleItemsBOMSubstituesProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Item" namespace="http://www.sunpowercorp.com/BOD/ProcessArenaOracleDataFeed/V1"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../ArenaOracleItemsBOMSubstituesProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="defaultParams" namespace="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesProv/xsd/defaultParams/V1"/>
            <oracle-xsl-mapper:param name="defaultParams"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../processItemtoEBS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="XxspwrArenaItemsCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/processItemtoEBS"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE OCT 04 15:42:23 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="defaultParams"/>
  <xsl:template match="ns1:Item">
    <top:XxspwrArenaItemsCollection>
      <top:XxspwrArenaItems>
        <top:itemId>
          <xsl:value-of select="$defaultParams/ns6:defaultParams/ns6:itemId"/>
        </top:itemId>
        <top:lastUpdateDate>
          <xsl:value-of select="xp20:current-dateTime()"/>
        </top:lastUpdateDate>
        <top:lastUpdatedBy>
          <xsl:text disable-output-escaping="no">-9999</xsl:text>
        </top:lastUpdatedBy>
        <top:creationDate>
          <xsl:value-of select="xp20:current-dateTime()"/>
        </top:creationDate>
        <top:createdBy>
          <xsl:text disable-output-escaping="no">-9999</xsl:text>
        </top:createdBy>
        <top:documentIdentifier>
          <xsl:value-of select="$defaultParams/ns6:defaultParams/ns6:documentIdentifier"/>
        </top:documentIdentifier>
        <top:documentGenDate>
          <xsl:value-of select="$defaultParams/ns6:defaultParams/ns6:documentGenerationDateTime"/>
        </top:documentGenDate>
        <top:documentName>
          <xsl:value-of select="$defaultParams/ns6:defaultParams/ns6:filename"/>
        </top:documentName>
        <top:description>
          <xsl:value-of select="./@ns4:description"/>
        </top:description>
        <top:itemNumber>
          <xsl:value-of select="./@itemIdentifier"/>
        </top:itemNumber>
        <top:revision>
          <xsl:value-of select="substring(./@ns4:revisionIdentifier,1,3)"/>
        </top:revision>
        <top:setProcessId>
          <xsl:value-of select="$defaultParams/ns6:defaultParams/ns6:processId"/>
        </top:setProcessId>
        <top:revisionEffectivityDate>
          <xsl:value-of select="./@ns4:revisionReleasedDate"/>
        </top:revisionEffectivityDate>
        <top:ecoNumber>
          <xsl:value-of select="./ns5:AdditionalAttributes[@groupLabel = &quot;Version Information&quot;]/ns5:AdditionalAttribute[@ns4:name = &quot;Change Number&quot;]/@ns4:value"/>
        </top:ecoNumber>
        <xsl:if test="./ns5:AdditionalAttributes[@groupLabel = &quot;Category Information&quot;]">
          <top:arenaCategory>
            <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Category Name&quot;]/@ns4:value"/>
          </top:arenaCategory>
          <top:arenaCategoryPath>
            <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Category Path&quot;]/@ns4:value"/>
          </top:arenaCategoryPath>
        </xsl:if>
        <xsl:if test="./ns5:AdditionalAttributes[@groupLabel = &quot;Arena Solutions Custom Attributes&quot;]">
          <top:longDescription>
            <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Arena Solutions Description&quot;]/@ns4:value"/>
          </top:longDescription>
          <xsl:choose>
            <xsl:when test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Active Cost #1&quot;]/@ns4:value != &quot;&quot;">
              <top:materialCost>
                <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Active Cost #1&quot;]/@ns4:value"/>
              </top:materialCost>
            </xsl:when>
            <xsl:when test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Active Cost #2&quot;]/@ns4:value != &quot;&quot;">
              <top:materialCost>
                <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Active Cost #2&quot;]/@ns4:value"/>
              </top:materialCost>
            </xsl:when>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;List Price&quot;]/@ns4:value != &quot;&quot;">
              <top:listPricePerUnit>
                <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;List Price&quot;]/@ns4:value"/>
              </top:listPricePerUnit>
            </xsl:when>
            <xsl:when test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Active Cost #1&quot;]/@ns4:value != &quot;&quot;">
              <top:listPricePerUnit>
                <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Active Cost #1&quot;]/@ns4:value"/>
              </top:listPricePerUnit>
            </xsl:when>
            <xsl:when test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Active Cost #2&quot;]/@ns4:value != &quot;&quot;">
              <top:listPricePerUnit>
                <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Active Cost #2&quot;]/@ns4:value"/>
              </top:listPricePerUnit>
            </xsl:when>
          </xsl:choose>
          <xsl:if test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;BOM Item Type&quot;]/@ns4:value != &quot;&quot;">
            <top:bomItemType>
              <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;BOM Item Type&quot;]/@ns4:value"/>
            </top:bomItemType>
          </xsl:if>
          <xsl:variable name="CFlag">
            <xsl:choose>
              <xsl:when test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name='RLC BU' or @ns4:name='Components BU' or @ns4:name='New Homes BU' or @ns4:name='Systems BU' or @ns4:name='SPTN BU']/@ns4:value='Yes'">
                <xsl:value-of select="'Y'"/>
              </xsl:when>
              <xsl:otherwise>
                <xsl:value-of select="''"/>
              </xsl:otherwise>
            </xsl:choose>
          </xsl:variable>
          <top:customerOrderEnabledFlag>
            <xsl:value-of select="$CFlag"/>
          </top:customerOrderEnabledFlag>
          <xsl:variable name="SFlag">
            <xsl:choose>
              <xsl:when test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name='Shippable']/@ns4:value='Yes'">
                <xsl:value-of select="'Y'"/>
              </xsl:when>
              <xsl:otherwise>
                <xsl:value-of select="$CFlag"/>
              </xsl:otherwise>
            </xsl:choose>
          </xsl:variable>
          <top:shippableItemFlag>
            <xsl:value-of select="$SFlag"/>
          </top:shippableItemFlag>
          <xsl:variable name="VFlag">
            <xsl:choose>
              <xsl:when test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name='Use Approved Supplier']/@ns4:value='No'">
                <xsl:value-of select="'N'"/>
              </xsl:when>
              <xsl:otherwise>
                <xsl:value-of select="'Y'"/>
              </xsl:otherwise>
            </xsl:choose>
          </xsl:variable>
          <top:mustUseApprovedVendorFlag>
            <xsl:value-of select="$VFlag"/>
          </top:mustUseApprovedVendorFlag>
          <xsl:if test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Default Buyer&quot;]/@ns4:value != &quot;&quot;">
            <top:buyerId>
              <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Default Buyer&quot;]/@ns4:value"/>
            </top:buyerId>
          </xsl:if>
          <top:plannerCode>
            <xsl:text disable-output-escaping="no">DEFAULT</xsl:text>
          </top:plannerCode>
          <xsl:if test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Processing Lead Time&quot;]/@ns4:value != &quot;&quot;">
            <top:fullLeadTime>
              <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Processing Lead Time&quot;]/@ns4:value"/>
            </top:fullLeadTime>
          </xsl:if>
          <xsl:if test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Weight&quot;]/@ns4:value != &quot;&quot;">
            <top:unitWeight>
              <xsl:value-of select="translate(./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Weight&quot;]/@ns4:value,&quot;,&quot;,&quot;&quot;)"/>
            </top:unitWeight>
          </xsl:if>
          <xsl:if test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Weight UOM&quot;]/@ns4:value != &quot;&quot;">
            <top:weightUomCode>
              <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Weight UOM&quot;]/@ns4:value"/>
            </top:weightUomCode>
          </xsl:if>
          <xsl:if test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Volume UOM&quot;]/@ns4:value != &quot;&quot;">
            <top:volumeUomCode>
              <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Volume UOM&quot;]/@ns4:value"/>
            </top:volumeUomCode>
          </xsl:if>
          <xsl:if test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Volume&quot;]/@ns4:value != &quot;&quot;">
            <top:unitVolume>
              <xsl:value-of select="translate(./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Volume&quot;]/@ns4:value,&quot;,&quot;,&quot;&quot;)"/>
            </top:unitVolume>
          </xsl:if>
          <xsl:if test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Dimension UOM&quot;]/@ns4:value != &quot;&quot;">
            <top:dimensionUomCode>
              <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Dimension UOM&quot;]/@ns4:value"/>
            </top:dimensionUomCode>
          </xsl:if>
          <xsl:if test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Length&quot;]/@ns4:value != &quot;&quot;">
            <top:unitLength>
              <xsl:value-of select="translate(./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Length&quot;]/@ns4:value,&quot;,&quot;,&quot;&quot;)"/>
            </top:unitLength>
          </xsl:if>
          <xsl:if test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Width&quot;]/@ns4:value != &quot;&quot;">
            <top:unitWidth>
              <xsl:value-of select="translate(./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Width&quot;]/@ns4:value,&quot;,&quot;,&quot;&quot;)"/>
            </top:unitWidth>
          </xsl:if>
          <xsl:if test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Height&quot;]/@ns4:value != &quot;&quot;">
            <top:unitHeight>
              <xsl:value-of select="translate(./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Height&quot;]/@ns4:value,&quot;,&quot;,&quot;&quot;)"/>
            </top:unitHeight>
          </xsl:if>
          <xsl:if test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;WIP Supply Type&quot;]/@ns4:value != &quot;&quot;">
            <top:wipSupplyType>
              <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;WIP Supply Type&quot;]/@ns4:value"/>
            </top:wipSupplyType>
          </xsl:if>
          <top:arenaItemType>
            <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Non-Inventory Item Type&quot;]/@ns4:value"/>
          </top:arenaItemType>
          <top:partOfBom>
            <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name='Part of BOM']/@ns4:value"/>
          </top:partOfBom>
          <top:attribute1>
            <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Legacy Item Number&quot;]/@ns4:value"/>
          </top:attribute1>
          <top:attribute4>
            <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;HTS Code&quot;]/@ns4:value"/>
          </top:attribute4>
          <xsl:choose>
            <xsl:when test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Product Type&quot;]/@ns4:value = &quot;CELL&quot;">
              <top:attribute5>
                <xsl:value-of select="&quot;Y&quot;"/>
              </top:attribute5>
            </xsl:when>
            <xsl:otherwise>
              <top:attribute5>
                <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;OSP_IND_ITEM&quot;]/@ns4:value"/>
              </top:attribute5>
            </xsl:otherwise>
          </xsl:choose>
		  <top:attribute6>
            <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Tolerance Values&quot;]/@ns4:value"/>
          </top:attribute6>
          <top:attribute11>
            <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Reference Document Number(DMS)&quot;]/@ns4:value"/>
          </top:attribute11>
          <top:attribute15>
            <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Invoice UOM&quot;]/@ns4:value"/>
          </top:attribute15>
          <top:productType>
            <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name='Product Type']/@ns4:value"/>
          </top:productType>
          
          
          <top:moduleTechnology>
            <xsl:value-of select="$defaultParams/ns6:defaultParams/ns6:ModuleTechnology"/>
          </top:moduleTechnology>
        </xsl:if>
        <top:primaryUnitOfMeasure>
          <xsl:value-of select="./@ns4:globalProductUnitOfMeasureCode"/>
        </top:primaryUnitOfMeasure>
        <xsl:choose>
          <xsl:when test="./@ns4:globalLifeCyclePhaseCode = &quot;Other&quot;">
            <top:inventoryItemStatusCode>
              <xsl:value-of select="./@ns4:globalLifeCyclePhaseCodeOther"/>
            </top:inventoryItemStatusCode>
          </xsl:when>
          <xsl:otherwise>
            <top:inventoryItemStatusCode>
              <xsl:value-of select="./@ns4:globalLifeCyclePhaseCode"/>
            </top:inventoryItemStatusCode>
          </xsl:otherwise>
        </xsl:choose>           
         <xsl:choose>
              <xsl:when test="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name='Category Name']/@ns4:value='Phantom'">
               <top:planningMakeBuyCode>
          <xsl:text disable-output-escaping="no">1</xsl:text>
              </top:planningMakeBuyCode>
              </xsl:when>
               <xsl:otherwise>
             <top:planningMakeBuyCode>
          <xsl:text disable-output-escaping="no">2</xsl:text>
        </top:planningMakeBuyCode>
        </xsl:otherwise>
            </xsl:choose>
        <xsl:choose>
          <xsl:when test="(count(./ns5:BillOfMaterial/ns5:BillOfMaterialItem) >= 0.0) and (./@ns4:isTopLevel = &quot;Yes&quot;)">
            <top:processFlag>
              <xsl:text disable-output-escaping="no">-1</xsl:text>
            </top:processFlag>
          </xsl:when>
          <xsl:otherwise>
            <top:processFlag>
              <xsl:text disable-output-escaping="no">44</xsl:text>
            </top:processFlag>
          </xsl:otherwise>
        </xsl:choose>
            <top:bAttribute15>
            <xsl:value-of select="./ns5:AdditionalAttributes/ns5:AdditionalAttribute[@ns4:name = &quot;Product Family&quot;]/@ns4:value"/>
          </top:bAttribute15>
      </top:XxspwrArenaItems>
    </top:XxspwrArenaItemsCollection>
  </xsl:template>
</xsl:stylesheet>