<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns5="http://www.sunpowercorp.com/Common/ArenaOracleDataFeedDetailsCommonTypes/V1" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns0="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:client="http://www.sunpowercorp.com/SunPowerDevelopment/ArenaOracleItemsBOMSubstituesProv/ArenaOracleItemsBOMSubstituesProv_BPEL" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns4="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:ns2="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesProv/xsd/defaultParams/V1" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/processOrgAssigmentsToEBS" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessArenaOracleDataFeed/V1" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns3="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesProv/xsd/OrgAssignments/V1" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SunPowerDevelopment/ArenaOracleItemsBOMSubstituesProv/processOrgAssigmentsToEBS" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns6="http://www.sunpowercorp.com/Noun/ArenaOracleDataFeed/V1" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns5 ns0 plnk wsdl client ns4 ns2 ns1 ns3 xsd ns6 top tns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:ns9="http://schemas.oracle.com/bpel/extension"
                xmlns:ns7="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesProv/xsd/ListOfVendorsArenaAsls/V1"
                xmlns:ns8="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesProv/xsd/Categories/V1">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../ArenaOracleItemsBOMSubstituesProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="defaultParams" namespace="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesProv/xsd/defaultParams/V1"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../ArenaOracleItemsBOMSubstituesProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="params" namespace="http://www.sunpowercorp.com/ArenaOracleItemsBOMSubstituesProv/xsd/OrgAssignments/V1"/>
            <oracle-xsl-mapper:param name="initParams"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../processOrgAssigmentsToEBS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="XxspwrArenaOrgAssignmentsCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/processOrgAssigmentsToEBS"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE OCT 04 15:42:23 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="initParams"/>
  <xsl:template match="/">
    <top:XxspwrArenaOrgAssignmentsCollection>
      <xsl:for-each select="$initParams/ns3:params/ns3:param">
        <top:XxspwrArenaOrgAssignments>
          <top:itemId>
            <xsl:value-of select="/ns2:defaultParams/ns2:itemId"/>
          </top:itemId>
          <top:buOrOuName>
            <xsl:value-of select="ns3:Name"/>
          </top:buOrOuName>
          <top:buOrOuValue>
            <xsl:value-of select="ns3:Value"/>
          </top:buOrOuValue>
          <top:setProcessId>
            <xsl:value-of select="/ns2:defaultParams/ns2:processId"/>
          </top:setProcessId>
          <top:itemNumber>
            <xsl:value-of select="/ns2:defaultParams/ns2:itemNumber"/>
          </top:itemNumber>
        </top:XxspwrArenaOrgAssignments>
      </xsl:for-each>
    </top:XxspwrArenaOrgAssignmentsCollection>
  </xsl:template>
</xsl:stylesheet>