<?binding.jca updateHeaderStatusToDB_db.jca?>
<wsdl:definitions name="updateHeaderStatusToDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SyncOEOrdersOracleToSFDC/SyncOEOrdersOracleReq/updateHeaderStatusToDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SyncOEOrdersOracleToSFDC/SyncOEOrdersOracleReq/updateHeaderStatusToDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/updateHeaderStatusToDB">
    <plt:partnerLinkType name="updateHeaderStatusToDB_plt">
        <plt:role name="updateHeaderStatusToDB_role">
            <plt:portType name="tns:updateHeaderStatusToDB_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/updateHeaderStatusToDB"
                    schemaLocation="../Schemas/updateHeaderStatusToDB_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="XxspwrOmHeaderSyncCollection_msg">
        <wsdl:part name="XxspwrOmHeaderSyncCollection" element="top:XxspwrOmHeaderSyncCollection"/>
    </wsdl:message>
    <wsdl:portType name="updateHeaderStatusToDB_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:XxspwrOmHeaderSyncCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
