<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns0="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:client="http://www.sunpowercorp.com/CRDSFDCToOracle/SyncOEHeadersOracleProv/SyncOEHeadersOracleProv_BPEL" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateEBS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns4="http://www.sunpowercorp.com/Common/SyncOEOrdersCommonTypes/V1" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessSyncOEOrders/V1" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns2="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ns7="http://www.sunpowercorp.com/SunPowerDevelopment/utility/BatchEmailUtilityService/xsd/V1" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:ns6="http://www.sunpowercorp.com/CRD/SyncOEHeadersOracleProv/xsd/V1" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns3="http://www.sunpowercorp.com/Noun/SyncOEOrders/V1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns5="http://schemas.oracle.com/bpel/extension" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/CRDSFDCToOracle/SyncOEHeadersOracleProv/UpdateEBS" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns0 plnk client wsdl ns4 ns1 ns2 ns7 ns6 ns3 xsd ns5 top tns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SyncOEHeadersOracleProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessSyncOEOrders" namespace="http://www.sunpowercorp.com/BOD/ProcessSyncOEOrders/V1"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/UpdateEBS.wsdl"/>
            <oracle-xsl-mapper:rootElement name="XxspwrOmHeaderSyncCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateEBS"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE OCT 11 11:42:59 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <xsl:variable name="i" select="number(/ns1:ProcessSyncOEOrders/ns1:DataArea/ns0:process)"/>
    <top:XxspwrOmHeaderSyncCollection>
      <top:XxspwrOmHeaderSync>
        <top:sfdcId>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:SFDC_ID"/>
        </top:sfdcId>
        <top:operatingUnit>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:OPERATING_UNIT"/>
        </top:operatingUnit>
        <top:headerId>
          <xsl:value-of select="round(/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:HEADER_ID)"/>
        </top:headerId>
        <top:orderNumber>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:ORDER_NUMBER"/>
        </top:orderNumber>
        <top:oracleRequestId>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:ORACLE_REQUEST_ID"/>
        </top:oracleRequestId>
        <top:sfdcRequestId>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:SFDC_REQUEST_ID"/>
        </top:sfdcRequestId>
        <top:sfdcRequestStatus>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:SFDC_REQUEST_STATUS"/>
        </top:sfdcRequestStatus>
        <top:emailId>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:EMAIL_ID"/>
        </top:emailId>
        <top:oracleUserId>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:ORACLE_USER_ID"/>
        </top:oracleUserId>
        <top:custAcctNumber>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:CUST_ACCT_NUMBER"/>
        </top:custAcctNumber>
        <top:creditLimit>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:CREDIT_LIMIT"/>
        </top:creditLimit>
        <top:transactionDate>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:TRANSACTION_DATE"/>
        </top:transactionDate>
        <top:dueDate>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:DUE_DATE"/>
        </top:dueDate>
        <top:amount>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:AMOUNT"/>
        </top:amount>
        <top:amountOpen>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:AMOUNT_OPEN"/>
        </top:amountOpen>
        <top:paymentScheduleId>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:PAYMENT_SCHEDULE_ID"/>
        </top:paymentScheduleId>
        <top:balance>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:BALANCE"/>
        </top:balance>
        <top:locationNumber>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:LOCATION_NUMBER"/>
        </top:locationNumber>
        <top:reference>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:REFERENCE"/>
        </top:reference>
        <top:trasactionType>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:TRASACTION_TYPE"/>
        </top:trasactionType>
        <top:qadCustomerNumber>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:QAD_CUSTOMER_NUMBER"/>
        </top:qadCustomerNumber>
        <top:customerName>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:CUSTOMER_NAME"/>
        </top:customerName>
        <top:region>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:REGION"/>
        </top:region>
        <top:invoiceReference>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:INVOICE_REFERENCE"/>
        </top:invoiceReference>
        <top:siteStatus>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:SITE_STATUS"/>
        </top:siteStatus>
        <top:orgId>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:ORG_ID"/>
        </top:orgId>
        <top:poSubmitDate>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:PO_SUBMIT_DATE"/>
        </top:poSubmitDate>
        <top:shipFromOrgId>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:SHIP_FROM_ORG_ID"/>
        </top:shipFromOrgId>
        <top:billToSiteId>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:BILL_TO_SITE_ID"/>
        </top:billToSiteId>
        <top:shipToSiteId>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:SHIP_TO_SITE_ID"/>
        </top:shipToSiteId>
        <top:addressLine1>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:ADDRESS_LINE_1"/>
        </top:addressLine1>
        <top:addressLine2>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:ADDRESS_LINE_2"/>
        </top:addressLine2>
        <top:addressLine3>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:ADDRESS_LINE_3"/>
        </top:addressLine3>
        <top:city>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:CITY"/>
        </top:city>
        <top:state>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:STATE"/>
        </top:state>
        <top:country>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:COUNTRY"/>
        </top:country>
        <top:postalCode>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:POSTAL_CODE"/>
        </top:postalCode>
        <top:contactPhone1>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:CONTACT_PHONE1"/>
        </top:contactPhone1>
        <top:contactPhone2>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:CONTACT_PHONE2"/>
        </top:contactPhone2>
        <top:contactPersonName>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:CONTACT_PERSON_NAME"/>
        </top:contactPersonName>
        <top:contactEmail>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:CONTACT_EMAIL"/>
        </top:contactEmail>
        <top:contactFax>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:CONTACT_FAX"/>
        </top:contactFax>
        <top:shipToContactId>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:SHIP_TO_CONTACT_ID"/>
        </top:shipToContactId>
        <top:shippingMethod>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:SHIPPING_METHOD"/>
        </top:shippingMethod>
        <top:specialInstructions>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:SPECIAL_INSTRUCTIONS"/>
        </top:specialInstructions>
        <top:shippingInstructions>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:SHIPPING_INSTRUCTIONS"/>
        </top:shippingInstructions>
        <top:packingInstructions>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:PACKING_INSTRUCTIONS"/>
        </top:packingInstructions>
        <top:requestedDeliveryDate>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:REQUESTED_DELIVERY_DATE"/>
        </top:requestedDeliveryDate>
        <top:adjustedAmount>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:ADJUSTED_AMOUNT"/>
        </top:adjustedAmount>
        <top:smartpackFlag>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:SMARTPACK_FLAG"/>
        </top:smartpackFlag>
        <top:orderStatus>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:ORDER_STATUS"/>
        </top:orderStatus>
        <top:lastUpdatedBy>
          <xsl:text disable-output-escaping="no">-99</xsl:text>
        </top:lastUpdatedBy>
        <top:createdBy>
          <xsl:text disable-output-escaping="no">-99</xsl:text>
        </top:createdBy>
        <top:orderType>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:ORDER_TYPE"/>
        </top:orderType>
        <top:leaseValue>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:LEASE_VALUE"/>
        </top:leaseValue>
        <top:vendorNumber>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:VENDOR_NUMBER"/>
        </top:vendorNumber>
        <top:vendorSiteCode>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:VENDOR_SITE_CODE"/>
        </top:vendorSiteCode>
        <top:partnerName>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:PARTNER_NAME"/>
        </top:partnerName>
        <top:leaseFlag>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:LEASE_FLAG"/>
        </top:leaseFlag>
        <top:leaseNumber>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:LEASE_NUMBER"/>
        </top:leaseNumber>
        <top:financier>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:FINANCIER"/>
        </top:financier>
        <top:partnerAccNumber>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:PARTNER_ACC_NUMBER"/>
        </top:partnerAccNumber>
        <top:processFlag>
          <xsl:text disable-output-escaping="no">N</xsl:text>
        </top:processFlag>
        <top:processMessage>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:PROCESS_MESSAGE"/>
        </top:processMessage>
        <top:soaFlag>
          <xsl:text disable-output-escaping="no">U</xsl:text>
        </top:soaFlag>
        <top:soaErrormsg>
          <xsl:value-of select="&quot; &quot;"/>
        </top:soaErrormsg>
        <top:orderRecordType>
          <xsl:value-of select="dvm:lookupValue(&quot;oramds:/deployed-composites/online/SyncOEOrdersSFDCProv_rev1.0/RecordType.dvm&quot;,&quot;SFDC&quot;,/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:ORDER_RECORD_TYPE,&quot;Oracle&quot;,&quot;&quot;)"/>
        </top:orderRecordType>
        <!--
        <top:orderRecordType>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:ORDER_RECORD_TYPE"/>
        </top:orderRecordType>
        -->
        <top:systemSize>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:SYSTEM_SIZE"/>
        </top:systemSize>
        <top:billAddressLine1>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:BILL_ADDRESS_LINE_1"/>
        </top:billAddressLine1>
        <top:billAddressLine2>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:BILL_ADDRESS_LINE_2"/>
        </top:billAddressLine2>
        <top:billAddressLine3>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:BILL_ADDRESS_LINE_3"/>
        </top:billAddressLine3>
        <top:billCity>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:BILL_CITY"/>
        </top:billCity>
        <top:billState>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:BILL_STATE"/>
        </top:billState>
        <top:billCountry>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:BILL_COUNTRY"/>
        </top:billCountry>
        <top:billPostalCode>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:BILL_POSTAL_CODE"/>
        </top:billPostalCode>
        <top:customerPromiseDate>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:CUSTOMER_PROMISE_DATE"/>
        </top:customerPromiseDate>
        <top:shipToCounty>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:SHIP_TO_COUNTY"/>
        </top:shipToCounty>
        <top:billToCounty>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:Bill_To_COUNTY"/>
        </top:billToCounty>
        <top:soaLastUpdateDate>
          <xsl:value-of select="xp20:current-dateTime()"/>
        </top:soaLastUpdateDate>
        <top:okToShipFlag>
          <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:OK_TO_SHIP_FLAG"/>
        </top:okToShipFlag>
        <!--
         <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns3:SyncOEOrders/ns3:SyncOEOrderHeaderDetails[$i]/ns4:CANCEL_FLAG='true'">
               <top:cancelFlag>
                 <xsl:text disable-output-escaping="no">Y</xsl:text>
              </top:cancelFlag>
            </xsl:when>
            <xsl:otherwise>
              <top:cancelFlag>
                 <xsl:text disable-output-escaping="no">N</xsl:text>
              </top:cancelFlag>
            </xsl:otherwise>
          </xsl:choose>
          -->
      </top:XxspwrOmHeaderSync>
    </top:XxspwrOmHeaderSyncCollection>
  </xsl:template>
</xsl:stylesheet>