<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="2.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns0="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns7="http://www.sunpowercorp.com/Common/SyncOEOrdersCommonTypes/V1" xmlns:ns4="http://www.sunpowercorp.com/SunPowerDevelopment/initParams/xsd/v1" xmlns:ns2="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessSyncOEOrders/V1" xmlns:ens="urn:sobject.partner.soap.sforce.com" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns5="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:fns="urn:fault.partner.soap.sforce.com" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns6="http://www.sunpowercorp.com/Noun/SyncOEOrders/V1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:client="http://www.sunpowercorp.com/SyncOEOrdersOracleToSFDC/SyncOEOrdersSFDCProv/SyncOEOrdersSFDCProv_BPEL" xmlns:ns3="urn:partner.soap.sforce.com" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns0 plnk wsdl ns7 ns4 ns2 ns1 ns5 ns6 xsd client ns3 soap ens fns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SyncOEOrdersSFDCProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessSyncOEOrders" namespace="http://www.sunpowercorp.com/BOD/ProcessSyncOEOrders/V1"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SyncOEOrdersSFDCProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="InitParams" namespace="http://www.sunpowercorp.com/SunPowerDevelopment/initParams/xsd/v1"/>
            <oracle-xsl-mapper:param name="initParams"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../partner.wsdl"/>
            <oracle-xsl-mapper:rootElement name="upsert" namespace="urn:partner.soap.sforce.com"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE OCT 11 14:37:59 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="initParams"/>
  <xsl:template match="/">
    <ns3:upsert>
      <ns3:externalIDFieldName>
        <xsl:text disable-output-escaping="no">HEADER_ID__c</xsl:text>
      </ns3:externalIDFieldName>
      <xsl:variable name="StartIndex" select="$initParams/ns4:InitParams/ns4:startIndex"/>
      <xsl:variable name="EndIndex" select="$initParams/ns4:InitParams/ns4:endIndex"/>
      <xsl:for-each select="$StartIndex to $EndIndex">
        <xsl:variable name="Index" select="."/>
        <ns3:sObjects>
          <ens:type>
            <xsl:text disable-output-escaping="no">OE_ORDER_HEADERS__c</xsl:text>
          </ens:type>
          <ens:Id>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:SFDC_ID"/>
          </ens:Id>
          <ens:Name>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:ORDER_NUMBER"/>
          </ens:Name>
          <ens:OPERATING_UNIT__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:OPERATING_UNIT"/>
          </ens:OPERATING_UNIT__c>
          <ens:HEADER_ID__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:HEADER_ID"/>
          </ens:HEADER_ID__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:ORDER_NUMBER=''">
              <ens:fieldsToNull>ORDER_NUMBER__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:ORDER_NUMBER__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:ORDER_NUMBER"/>
              </ens:ORDER_NUMBER__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:SFDC_REQUEST_ID=''">
              <ens:fieldsToNull>SFDC_REQUEST_ID__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:SFDC_REQUEST_ID__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:SFDC_REQUEST_ID"/>
              </ens:SFDC_REQUEST_ID__c>
            </xsl:otherwise>
          </xsl:choose>
          <ens:SFDC_REQUEST_STATUS__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:SFDC_REQUEST_STATUS"/>
          </ens:SFDC_REQUEST_STATUS__c>
          <ens:EMAIL_ID__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:EMAIL_ID"/>
          </ens:EMAIL_ID__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:ORACLE_USER_ID=''">
              <ens:fieldsToNull>ORACLE_USER_ID__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:ORACLE_USER_ID__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:ORACLE_USER_ID"/>
              </ens:ORACLE_USER_ID__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:CUST_ACCT_NUMBER=''">
              <ens:fieldsToNull>CUST_ACCT_NUMBER__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:CUST_ACCT_NUMBER__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:CUST_ACCT_NUMBER"/>
              </ens:CUST_ACCT_NUMBER__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:CREDIT_LIMIT=''">
              <ens:fieldsToNull>CREDIT_LIMIT__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:CREDIT_LIMIT__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:CREDIT_LIMIT"/>
              </ens:CREDIT_LIMIT__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:TRANSACTION_DATE=''">
              <ens:fieldsToNull>TRANSACTION_DATE__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:TRANSACTION_DATE__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:TRANSACTION_DATE"/>
              </ens:TRANSACTION_DATE__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:DUE_DATE=''">
              <ens:fieldsToNull>DUE_DATE__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:DUE_DATE__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:DUE_DATE"/>
              </ens:DUE_DATE__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:AMOUNT=''">
              <ens:fieldsToNull>AMOUNT__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:AMOUNT__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:AMOUNT"/>
              </ens:AMOUNT__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:AMOUNT_OPEN=''">
              <ens:fieldsToNull>AMOUNT_OPEN__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:AMOUNT_OPEN__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:AMOUNT_OPEN"/>
              </ens:AMOUNT_OPEN__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:PAYMENT_SCHEDULE_ID=''">
              <ens:fieldsToNull>PAYMENT_SCHEDULE_ID__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:PAYMENT_SCHEDULE_ID__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:PAYMENT_SCHEDULE_ID"/>
              </ens:PAYMENT_SCHEDULE_ID__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:BALANCE=''">
              <ens:fieldsToNull>BALANCE__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:BALANCE__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:BALANCE"/>
              </ens:BALANCE__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:LOCATION_NUMBER=''">
              <ens:fieldsToNull>LOCATION_NUMBER__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:LOCATION_NUMBER__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:LOCATION_NUMBER"/>
              </ens:LOCATION_NUMBER__c>
            </xsl:otherwise>
          </xsl:choose>
          <ens:REFERENCE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:REFERENCE"/>
          </ens:REFERENCE__c>
          <ens:TRASACTION_TYPE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:TRASACTION_TYPE"/>
          </ens:TRASACTION_TYPE__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:QAD_CUSTOMER_NUMBER=''">
              <ens:fieldsToNull>QAD_CUSTOMER_NUMBER__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:QAD_CUSTOMER_NUMBER__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:QAD_CUSTOMER_NUMBER"/>
              </ens:QAD_CUSTOMER_NUMBER__c>
            </xsl:otherwise>
          </xsl:choose>
          <ens:CUSTOMER_NAME__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:CUSTOMER_NAME"/>
          </ens:CUSTOMER_NAME__c>
          <ens:REGION__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:REGION"/>
          </ens:REGION__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:INVOICE_REFERENCE=''">
              <ens:fieldsToNull>INVOICE_REFERENCE__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:INVOICE_REFERENCE__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:INVOICE_REFERENCE"/>
              </ens:INVOICE_REFERENCE__c>
            </xsl:otherwise>
          </xsl:choose>
          <ens:SITE_STATUS__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:SITE_STATUS"/>
          </ens:SITE_STATUS__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:ORG_ID=''">
              <ens:fieldsToNull>ORG_ID__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:ORG_ID__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:ORG_ID"/>
              </ens:ORG_ID__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:PO_SUBMIT_DATE=''">
              <ens:fieldsToNull>PO_SUBMIT_DATE__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:PO_SUBMIT_DATE__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:PO_SUBMIT_DATE"/>
              </ens:PO_SUBMIT_DATE__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:SHIP_FROM_ORG_ID=''">
              <ens:fieldsToNull>SHIP_FROM_ORG_ID__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:SHIP_FROM_ORG_ID__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:SHIP_FROM_ORG_ID"/>
              </ens:SHIP_FROM_ORG_ID__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:BILL_TO_SITE_ID=''">
              <ens:fieldsToNull>BILL_TO_SITE_ID__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:BILL_TO_SITE_ID__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:BILL_TO_SITE_ID"/>
              </ens:BILL_TO_SITE_ID__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:SHIP_TO_SITE_ID=''">
              <ens:fieldsToNull>SHIP_TO_SITE_ID__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:SHIP_TO_SITE_ID__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:SHIP_TO_SITE_ID"/>
              </ens:SHIP_TO_SITE_ID__c>
            </xsl:otherwise>
          </xsl:choose>
          <ens:ADDRESS_LINE_1__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:ADDRESS_LINE_1"/>
          </ens:ADDRESS_LINE_1__c>
          <ens:ADDRESS_LINE_2__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:ADDRESS_LINE_2"/>
          </ens:ADDRESS_LINE_2__c>
          <ens:ADDRESS_LINE_3__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:ADDRESS_LINE_3"/>
          </ens:ADDRESS_LINE_3__c>
          <ens:Ship_To_City__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:CITY"/>
          </ens:Ship_To_City__c>
          <ens:STATE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:STATE"/>
          </ens:STATE__c>
          <ens:COUNTRY__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:COUNTRY"/>
          </ens:COUNTRY__c>
          <ens:POSTAL_CODE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:POSTAL_CODE"/>
          </ens:POSTAL_CODE__c>
          <ens:CONTACT_PHONE1__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:CONTACT_PHONE1"/>
          </ens:CONTACT_PHONE1__c>
          <ens:CONTACT_PHONE2__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:CONTACT_PHONE2"/>
          </ens:CONTACT_PHONE2__c>
          <ens:CONTACT_PERSON_NAME__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:CONTACT_PERSON_NAME"/>
          </ens:CONTACT_PERSON_NAME__c>
          <ens:CONTACT_EMAIL__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:CONTACT_EMAIL"/>
          </ens:CONTACT_EMAIL__c>
          <ens:CONTACT_FAX__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:CONTACT_FAX"/>
          </ens:CONTACT_FAX__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:SHIP_TO_CONTACT_ID=''">
              <ens:fieldsToNull>SHIP_TO_CONTACT_ID__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:SHIP_TO_CONTACT_ID__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:SHIP_TO_CONTACT_ID"/>
              </ens:SHIP_TO_CONTACT_ID__c>
            </xsl:otherwise>
          </xsl:choose>
          <ens:SHIPPING_METHOD__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:SHIPPING_METHOD"/>
          </ens:SHIPPING_METHOD__c>
          <ens:SPECIAL_INSTRUCTIONS__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:SPECIAL_INSTRUCTIONS"/>
          </ens:SPECIAL_INSTRUCTIONS__c>
          <ens:SHIPPING_INSTRUCTIONS__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:SHIPPING_INSTRUCTIONS"/>
          </ens:SHIPPING_INSTRUCTIONS__c>
          <ens:PACKING_INSTRUCTIONS__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:PACKING_INSTRUCTIONS"/>
          </ens:PACKING_INSTRUCTIONS__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:REQUESTED_DELIVERY_DATE=''">
              <ens:fieldsToNull>REQUESTED_DELIVERY_DATE__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:REQUESTED_DELIVERY_DATE__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:REQUESTED_DELIVERY_DATE"/>
              </ens:REQUESTED_DELIVERY_DATE__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:ADJUSTED_AMOUNT=''">
              <ens:fieldsToNull>ADJUSTED_AMOUNT__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:ADJUSTED_AMOUNT__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:ADJUSTED_AMOUNT"/>
              </ens:ADJUSTED_AMOUNT__c>
            </xsl:otherwise>
          </xsl:choose>
          <ens:SMARTPACK_FLAG__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:SMARTPACK_FLAG"/>
          </ens:SMARTPACK_FLAG__c>
          <ens:ORDER_STATUS__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:ORDER_STATUS"/>
          </ens:ORDER_STATUS__c>
          <ens:LAST_UPDATED_BY__c>
            <xsl:text disable-output-escaping="no">-99</xsl:text>
          </ens:LAST_UPDATED_BY__c>
          <ens:ORDER_TYPE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:ORDER_TYPE"/>
          </ens:ORDER_TYPE__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:LEASE_VALUE=''">
              <ens:fieldsToNull>LEASE_VALUE__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:LEASE_VALUE__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:LEASE_VALUE"/>
              </ens:LEASE_VALUE__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:VENDOR_NUMBER=''">
              <ens:fieldsToNull>VENDOR_NUMBER__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:VENDOR_NUMBER__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:VENDOR_NUMBER"/>
              </ens:VENDOR_NUMBER__c>
            </xsl:otherwise>
          </xsl:choose>
          <ens:VENDOR_SITE_CODE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:VENDOR_SITE_CODE"/>
          </ens:VENDOR_SITE_CODE__c>
          <ens:PARTNER_NAME__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:PARTNER_NAME"/>
          </ens:PARTNER_NAME__c>
          <ens:LEASE_FLAG__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:LEASE_FLAG"/>
          </ens:LEASE_FLAG__c>
          <ens:LEASE_NUMBER__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:LEASE_NUMBER"/>
          </ens:LEASE_NUMBER__c>
          <ens:RecordTypeId>
            <xsl:value-of select="dvm:lookupValue(&quot;RecordType.dvm&quot;,&quot;Oracle&quot;,/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:ORDER_RECORD_TYPE,&quot;SFDC&quot;,&quot; &quot;)"/>
          </ens:RecordTypeId>
          <ens:FINANCIER__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:FINANCIER"/>
          </ens:FINANCIER__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:PARTNER_ACC_NUMBER=''">
              <ens:fieldsToNull>PARTNER_ACC_NUMBER__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:PARTNER_ACC_NUMBER__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:PARTNER_ACC_NUMBER"/>
              </ens:PARTNER_ACC_NUMBER__c>
            </xsl:otherwise>
          </xsl:choose>
          <ens:PROCESS_FLAG__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:PROCESS_FLAG"/>
          </ens:PROCESS_FLAG__c>
          <ens:PROCESS_MESSAGE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:PROCESS_MESSAGE"/>
          </ens:PROCESS_MESSAGE__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:ORACLE_REQUEST_ID=''">
              <ens:fieldsToNull>ORACLE_REQUEST_ID__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:ORACLE_REQUEST_ID__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:ORACLE_REQUEST_ID"/>
              </ens:ORACLE_REQUEST_ID__c>
            </xsl:otherwise>
          </xsl:choose>
          <ens:BILL_ADDRESS_LINE_1__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:BILL_ADDRESS_LINE_1"/>
          </ens:BILL_ADDRESS_LINE_1__c>
          <ens:BILL_ADDRESS_LINE_2__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:BILL_ADDRESS_LINE_2"/>
          </ens:BILL_ADDRESS_LINE_2__c>
          <ens:BILL_ADDRESS_LINE_3__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:BILL_ADDRESS_LINE_3"/>
          </ens:BILL_ADDRESS_LINE_3__c>
          <ens:BILL_CITY__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:BILL_CITY"/>
          </ens:BILL_CITY__c>
          <ens:BILL_STATE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:BILL_STATE"/>
          </ens:BILL_STATE__c>
          <ens:BILL_COUNTRY__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:BILL_COUNTRY"/>
          </ens:BILL_COUNTRY__c>
          <ens:BILL_POSTAL_CODE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:BILL_POSTAL_CODE"/>
          </ens:BILL_POSTAL_CODE__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:SYSTEM_SIZE=''">
              <ens:fieldsToNull>System_Size__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:System_Size__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:SYSTEM_SIZE"/>
              </ens:System_Size__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:CUSTOMER_PROMISE_DATE=''">
              <ens:fieldsToNull>CPD__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:CPD__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:CUSTOMER_PROMISE_DATE"/>
              </ens:CPD__c>
            </xsl:otherwise>
          </xsl:choose>
          <ens:Bill_To_County__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:BILL_TO_COUNTY"/>
          </ens:Bill_To_County__c>
          <ens:Ship_To_County__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:SHIP_TO_COUNTY"/>
          </ens:Ship_To_County__c>
          <ens:Oracle_Account_Number__c>
            <xsl:value-of select="dvm:lookupValue(&quot;RecordType.dvm&quot;,&quot;Oracle&quot;,&quot;Oracle_Account_Number&quot;,&quot;SFDC&quot;,&quot; &quot;)"/>
          </ens:Oracle_Account_Number__c>
          <ens:Parent_Account__c>
            <xsl:value-of select="dvm:lookupValue(&quot;RecordType.dvm&quot;,&quot;Oracle&quot;,&quot;Parent_Account&quot;,&quot;SFDC&quot;,&quot; &quot;)"/>
          </ens:Parent_Account__c>
          <ens:LAST_UPDATE_DATE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:LAST_UPDATE_DATE"/>
          </ens:LAST_UPDATE_DATE__c>
          <ens:CREATION_DATE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:CREATION_DATE"/>
          </ens:CREATION_DATE__c>
          <!--		  
              <ens:Hold_Status__c>
          <xsl:value-of select='dvm:lookupValue("Status.dvm","Oracle",/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:HOLD_STATUS,"SFDC","")'/>
              </ens:Hold_Status__c> 
			  -->
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:HOLD_STATUS=''">
              <ens:fieldsToNull>Hold_Status__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:Hold_Status__c>
                <xsl:value-of select="dvm:lookupValue(&quot;Status.dvm&quot;,&quot;Oracle&quot;,/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:HOLD_STATUS,&quot;SFDC&quot;,&quot;&quot;)"/>
              </ens:Hold_Status__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:CREDIT_CHECK_PAYMENT_DATE=''">
              <ens:fieldsToNull>ACTION_DUE_DATE__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:ACTION_DUE_DATE__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:CREDIT_CHECK_PAYMENT_DATE"/>
              </ens:ACTION_DUE_DATE__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:MIN_SCHEDULE_SHIP_DATE=''">
              <ens:fieldsToNull>MIN_SCHEDULE_SHIP_DATE__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:MIN_SCHEDULE_SHIP_DATE__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:MIN_SCHEDULE_SHIP_DATE"/>
              </ens:MIN_SCHEDULE_SHIP_DATE__c>
            </xsl:otherwise>
          </xsl:choose>
           <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:MIN_SCHEDULE_ARRIVAL_DATE=''">
              <ens:fieldsToNull>MIN_SCHEDULE_ARRIVAL_DATE__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:MIN_SCHEDULE_ARRIVAL_DATE__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:MIN_SCHEDULE_ARRIVAL_DATE"/>
              </ens:MIN_SCHEDULE_ARRIVAL_DATE__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:PARTNER_CONFIRM_DUE_DATE=''">
              <ens:fieldsToNull>OK_To_Ship_Action_Due_Date__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:OK_To_Ship_Action_Due_Date__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:PARTNER_CONFIRM_DUE_DATE"/>
              </ens:OK_To_Ship_Action_Due_Date__c>
            </xsl:otherwise>
          </xsl:choose>
           <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:CURRENCY_CODE=''">
              <ens:fieldsToNull>CurrencyIsoCode</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:CurrencyIsoCode>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns6:SyncOEOrders/ns6:SyncOEOrderHeaderDetails[$Index]/ns7:CURRENCY_CODE"/>
              </ens:CurrencyIsoCode>
            </xsl:otherwise>
          </xsl:choose>
        </ns3:sObjects>
      </xsl:for-each>
    </ns3:upsert>
  </xsl:template>
</xsl:stylesheet>