<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="2.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:aia="http://www.oracle.com/XSL/Transform/java/oracle.apps.aia.core.xpath.AIAFunctions" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns0="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns6="http://www.sunpowercorp.com/Common/SyncOEOrdersCommonTypes/V1" xmlns:ns4="http://www.sunpowercorp.com/SunPowerDevelopment/initParams/xsd/v1" xmlns:ns2="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:ens="urn:sobject.partner.soap.sforce.com" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessSyncOEOrders/V1" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns8="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:fns="urn:fault.partner.soap.sforce.com" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:ns5="http://www.sunpowercorp.com/Noun/SyncOEOrders/V1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:client="http://www.sunpowercorp.com/SyncOEOrdersOracleToSFDC/SyncOEOrdersSFDCProv/SyncOEOrdersSFDCProv_BPEL" xmlns:ns3="urn:partner.soap.sforce.com" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns0 plnk wsdl ns6 ns4 ns2 ns1 ns8 ns5 xsd client ns3 soap ens fns xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SyncOEOrdersSFDCProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessSyncOEOrders" namespace="http://www.sunpowercorp.com/BOD/ProcessSyncOEOrders/V1"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/SyncOEOrdersSFDCProv_BPEL.wsdl"/>
            <oracle-xsl-mapper:rootElement name="InitParams" namespace="http://www.sunpowercorp.com/SunPowerDevelopment/initParams/xsd/v1"/>
            <oracle-xsl-mapper:param name="initParams"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/partner.wsdl"/>
            <oracle-xsl-mapper:rootElement name="upsert" namespace="urn:partner.soap.sforce.com"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [TUE OCT 11 14:37:59 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="initParams"/>
  <xsl:template match="/">
    <ns3:upsert>
      <ns3:externalIDFieldName>
        <xsl:text disable-output-escaping="no">Id</xsl:text>
      </ns3:externalIDFieldName>
      <xsl:variable name="StartIndex" select="$initParams/ns4:InitParams/ns4:startIndex"/>
      <xsl:variable name="EndIndex" select="$initParams/ns4:InitParams/ns4:endIndex"/>
      <xsl:for-each select="$StartIndex to $EndIndex">
        <xsl:variable name="Index" select="."/>
        <ns3:sObjects>
          <ens:type>
            <xsl:text disable-output-escaping="no">OE_ORDER_LINES__c</xsl:text>
          </ens:type>
          <ens:Id>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:SFDC_ID"/>
          </ens:Id>
          <ens:HEADER_ID__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:HEADER_ID"/>
          </ens:HEADER_ID__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:Order_SFDC_ID=''">
              <ens:fieldsToNull>Order_SFDC_ID__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:Order_SFDC_ID__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:Order_SFDC_ID"/>
              </ens:Order_SFDC_ID__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:SFDC_REQUEST_ID=''">
              <ens:fieldsToNull>SFDC_REQUEST_ID__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:SFDC_REQUEST_ID__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:SFDC_REQUEST_ID"/>
              </ens:SFDC_REQUEST_ID__c>
            </xsl:otherwise>
          </xsl:choose>
          <ens:SFDC_REQUEST_STATUS__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:SFDC_REQUEST_STATUS"/>
          </ens:SFDC_REQUEST_STATUS__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:SHIP_FROM_ORG_ID=''">
              <ens:fieldsToNull>SHIP_FROM_ORG_ID__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:SHIP_FROM_ORG_ID__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:SHIP_FROM_ORG_ID"/>
              </ens:SHIP_FROM_ORG_ID__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:BILL_TO_SITE_ID=''">
              <ens:fieldsToNull>BILL_TO_SITE_ID__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:BILL_TO_SITE_ID__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:BILL_TO_SITE_ID"/>
              </ens:BILL_TO_SITE_ID__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:SHIP_TO_SITE_ID=''">
              <ens:fieldsToNull>SHIP_TO_SITE_ID__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:SHIP_TO_SITE_ID__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:SHIP_TO_SITE_ID"/>
              </ens:SHIP_TO_SITE_ID__c>
            </xsl:otherwise>
          </xsl:choose>
          <ens:ADDRESS_LINE_1__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:ADDRESS_LINE_1"/>
          </ens:ADDRESS_LINE_1__c>
          <ens:ADDRESS_LINE_2__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:ADDRESS_LINE_2"/>
          </ens:ADDRESS_LINE_2__c>
          <ens:ADDRESS_LINE_3__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:ADDRESS_LINE_3"/>
          </ens:ADDRESS_LINE_3__c>
          <ens:CITY__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:CITY"/>
          </ens:CITY__c>
          <ens:STATE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:STATE"/>
          </ens:STATE__c>
          <ens:COUNTRY__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:COUNTRY"/>
          </ens:COUNTRY__c>
          <ens:POSTAL_CODE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:POSTAL_CODE"/>
          </ens:POSTAL_CODE__c>
          <ens:CONTACT_PHONE1__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:CONTACT_PHONE1"/>
          </ens:CONTACT_PHONE1__c>
          <ens:CONTACT_PHONE2__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:CONTACT_PHONE2"/>
          </ens:CONTACT_PHONE2__c>
          <ens:CONTACT_PERSON_NAME__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:CONTACT_PERSON_NAME"/>
          </ens:CONTACT_PERSON_NAME__c>
          <ens:CONTACT_EMAIL__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:CONTACT_EMAIL"/>
          </ens:CONTACT_EMAIL__c>
          <ens:CONTACT_FAX__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:CONTACT_FAX"/>
          </ens:CONTACT_FAX__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:SHIP_TO_CONTACT_ID=''">
              <ens:fieldsToNull>SHIP_TO_CONTACT_ID__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:SHIP_TO_CONTACT_ID__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:SHIP_TO_CONTACT_ID"/>
              </ens:SHIP_TO_CONTACT_ID__c>
            </xsl:otherwise>
          </xsl:choose>
          <ens:SHIPPING_METHOD__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:SHIPPING_METHOD"/>
          </ens:SHIPPING_METHOD__c>
          <ens:SPECIAL_INSTRUCTIONS__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:SPECIAL_INSTRUCTIONS"/>
          </ens:SPECIAL_INSTRUCTIONS__c>
          <ens:SHIPPING_INSTRUCTIONS__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:SHIPPING_INSTRUCTIONS"/>
          </ens:SHIPPING_INSTRUCTIONS__c>
          <ens:PACKING_INSTRUCTIONS__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:PACKING_INSTRUCTIONS"/>
          </ens:PACKING_INSTRUCTIONS__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:REQUESTED_DELIVERY_DATE=''">
              <ens:fieldsToNull>REQUESTED_DELIVERY_DATE__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:REQUESTED_DELIVERY_DATE__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:REQUESTED_DELIVERY_DATE"/>
              </ens:REQUESTED_DELIVERY_DATE__c>
            </xsl:otherwise>
          </xsl:choose>
          <ens:LAST_UPDATED_BY__c>
            <xsl:text disable-output-escaping="no">-99</xsl:text>
          </ens:LAST_UPDATED_BY__c>
          <ens:PROCESS_FLAG__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:PROCESS_FLAG"/>
          </ens:PROCESS_FLAG__c>
          <ens:PROCESS_MESSAGE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:PROCESS_MESSAGE"/>
          </ens:PROCESS_MESSAGE__c>
          <ens:LINE_NUMBER__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:LINE_NUMBER"/>
          </ens:LINE_NUMBER__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:ORACLE_REQUEST_ID=''">
              <ens:fieldsToNull>ORACLE_REQUEST_ID__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:ORACLE_REQUEST_ID__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:ORACLE_REQUEST_ID"/>
              </ens:ORACLE_REQUEST_ID__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:LINE_ID=''">
              <ens:fieldsToNull>LINE_ID__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:LINE_ID__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:LINE_ID"/>
              </ens:LINE_ID__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:INVENTORY_ITEM_ID=''">
              <ens:fieldsToNull>INVENTORY_ITEM_ID__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:INVENTORY_ITEM_ID__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:INVENTORY_ITEM_ID"/>
              </ens:INVENTORY_ITEM_ID__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:ITEM_NUMBER=''">
              <ens:fieldsToNull>ITEM_NUMBER__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:ITEM_NUMBER__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:ITEM_NUMBER"/>
              </ens:ITEM_NUMBER__c>
            </xsl:otherwise>
          </xsl:choose>
          <ens:ITEM_DESCRIPTION__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:ITEM_DESCRIPTION"/>
          </ens:ITEM_DESCRIPTION__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:REQUESTED_QTY=''">
              <ens:fieldsToNull>REQUESTED_QTY__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:REQUESTED_QTY__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:REQUESTED_QTY"/>
              </ens:REQUESTED_QTY__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:UOM=''">
              <ens:fieldsToNull>UOM__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:UOM__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:UOM"/>
              </ens:UOM__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:UNIT_PRICE=''">
              <ens:fieldsToNull>UNIT_PRICE__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:UNIT_PRICE__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:UNIT_PRICE"/>
              </ens:UNIT_PRICE__c>
            </xsl:otherwise>
          </xsl:choose>
          <ens:ORDER_LINE_TYPE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:ORDER_LINE_TYPE"/>
          </ens:ORDER_LINE_TYPE__c>
          <ens:LINE_STATUS__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:LINE_STATUS"/>
          </ens:LINE_STATUS__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:PACKING_SLIP_NUMBER=''">
              <ens:fieldsToNull>PACKING_SLIP_NUMBER__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:PACKING_SLIP_NUMBER__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:PACKING_SLIP_NUMBER"/>
              </ens:PACKING_SLIP_NUMBER__c>
            </xsl:otherwise>
          </xsl:choose>
          <ens:PRODUCT_TYPE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:PRODUCT_TYPE"/>
          </ens:PRODUCT_TYPE__c>
          <ens:WATTAGE_TYPE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:WATTAGE_TYPE"/>
          </ens:WATTAGE_TYPE__c>
          <ens:ITEM_TYPE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:ITEM_TYPE"/>
          </ens:ITEM_TYPE__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:LINE_REQUEST_DATE=''">
              <ens:fieldsToNull>LINE_REQUEST_DATE__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:LINE_REQUEST_DATE__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:LINE_REQUEST_DATE"/>
              </ens:LINE_REQUEST_DATE__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:LINE_SCH_SHIP_DATE=''">
              <ens:fieldsToNull>LINE_SCH_SHIP_DATE__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:LINE_SCH_SHIP_DATE__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:LINE_SCH_SHIP_DATE"/>
              </ens:LINE_SCH_SHIP_DATE__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:SCHEDULED_ARRIVAL_DATE=''">
              <ens:fieldsToNull>SCHEDULED_ARRIVAL_DATE__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:SCHEDULED_ARRIVAL_DATE__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:SCHEDULED_ARRIVAL_DATE"/>
              </ens:SCHEDULED_ARRIVAL_DATE__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:PROMISED_DATE=''">
              <ens:fieldsToNull>PROMISED_DATE__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:PROMISED_DATE__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:PROMISED_DATE"/>
              </ens:PROMISED_DATE__c>
            </xsl:otherwise>
          </xsl:choose>
          <ens:BILL_ADDRESS_LINE_1__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:BILL_ADDRESS_LINE_1"/>
          </ens:BILL_ADDRESS_LINE_1__c>
          <ens:BILL_ADDRESS_LINE_2__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:BILL_ADDRESS_LINE_2"/>
          </ens:BILL_ADDRESS_LINE_2__c>
          <ens:BILL_ADDRESS_LINE_3__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:BILL_ADDRESS_LINE_3"/>
          </ens:BILL_ADDRESS_LINE_3__c>
          <ens:BILL_CITY__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:BILL_CITY"/>
          </ens:BILL_CITY__c>
          <ens:BILL_STATE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:BILL_STATE"/>
          </ens:BILL_STATE__c>
          <ens:BILL_COUNTRY__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:BILL_COUNTRY"/>
          </ens:BILL_COUNTRY__c>
          <ens:BILL_POSTAL_CODE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:BILL_POSTAL_CODE"/>
          </ens:BILL_POSTAL_CODE__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:DELIVER_TO_ORG_ID=''">
              <ens:fieldsToNull>DELIVER_TO_ORG_ID__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:DELIVER_TO_ORG_ID__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:DELIVER_TO_ORG_ID"/>
              </ens:DELIVER_TO_ORG_ID__c>
            </xsl:otherwise>
          </xsl:choose>
          <ens:DELIVER_ADDRESS_LINE_1__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:DELIVER_ADDRESS_LINE_1"/>
          </ens:DELIVER_ADDRESS_LINE_1__c>
          <ens:DELIVER_ADDRESS_LINE_2__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:DELIVER_ADDRESS_LINE_2"/>
          </ens:DELIVER_ADDRESS_LINE_2__c>
          <ens:DELIVER_ADDRESS_LINE_3__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:DELIVER_ADDRESS_LINE_3"/>
          </ens:DELIVER_ADDRESS_LINE_3__c>
          <ens:DELIVER_CITY__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:DELIVER_CITY"/>
          </ens:DELIVER_CITY__c>
          <ens:DELIVER_STATE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:DELIVER_STATE"/>
          </ens:DELIVER_STATE__c>
          <ens:DELIVER_COUNTRY__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:DELIVER_COUNTRY"/>
          </ens:DELIVER_COUNTRY__c>
          <ens:DELIVER_POSTAL_CODE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:DELIVER_POSTAL_CODE"/>
          </ens:DELIVER_POSTAL_CODE__c>
          <ens:TAX_FLAG__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:TAX_FLAG"/>
          </ens:TAX_FLAG__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:DATE_DELIVERED=''">
              <ens:fieldsToNull>DATE_DELIVERED__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:DATE_DELIVERED__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:DATE_DELIVERED"/>
              </ens:DATE_DELIVERED__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:OPEN_QTY=''">
              <ens:fieldsToNull>Qty_Open__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:Qty_Open__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:OPEN_QTY"/>
              </ens:Qty_Open__c>
            </xsl:otherwise>
          </xsl:choose>
          <ens:LAST_UPDATE_DATE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:LAST_UPDATE_DATE"/>
          </ens:LAST_UPDATE_DATE__c>
          <ens:CREATION_DATE__c>
            <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:CREATION_DATE"/>
          </ens:CREATION_DATE__c>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:INVOICE_REFERENCE=''">
              <ens:fieldsToNull>INVOICE_REFERENCE__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:INVOICE_REFERENCE__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:INVOICE_REFERENCE"/>
              </ens:INVOICE_REFERENCE__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:Delivery_Number=''">
              <ens:fieldsToNull>Delivery_Number__c</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:Delivery_Number__c>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:Delivery_Number"/>
              </ens:Delivery_Number__c>
            </xsl:otherwise>
          </xsl:choose>
           <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:INVENTORY_FLAG='Y'">
             <ens:INVENTORY__c>
                 <xsl:text disable-output-escaping="no">true</xsl:text>
              </ens:INVENTORY__c>
            </xsl:when>
            <xsl:otherwise>
              <ens:INVENTORY__c>
                 <xsl:text disable-output-escaping="no">false</xsl:text>
              </ens:INVENTORY__c>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:CURRENCY_CODE=''">
              <ens:fieldsToNull>CurrencyIsoCode</ens:fieldsToNull>
            </xsl:when>
            <xsl:otherwise>
              <ens:CurrencyIsoCode>
                <xsl:value-of select="/ns1:ProcessSyncOEOrders/ns1:DataArea/ns5:SyncOEOrders/ns5:SyncOEOrderLineDetails[$Index]/ns6:CURRENCY_CODE"/>
              </ens:CurrencyIsoCode>
            </xsl:otherwise>
          </xsl:choose>
        </ns3:sObjects>
      </xsl:for-each>
    </ns3:upsert>
  </xsl:template>
</xsl:stylesheet>