<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/file/EDICOMApplication/pollEDI214n861FilesToOracle/pollEDI214Files" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/insertEDI861Files" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns2="http://www.sunpowercorp.com/utilities/inputparam/xsd/v1" xmlns:ns1="http://www.sunpowercorp.com/214_FlatFile" xmlns:ns3="http://xmlns.oracle.com/pcbpel/adapter/db/EDICom/pollEDI214n861FilesToOracle/insertEDI861Files" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:imp1="http://www.sunpowercorp.com/861_FlatFile" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/file/EDICOMApplication/pollEDI214n861FilesToOracle/pollEDI861Files" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl ns0 pc plt wsdl ns2 ns1 jca imp1 xsd tns top ns3 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../pollEDI861Files.wsdl"/>
            <oracle-xsl-mapper:rootElement name="SalesOrderDetails" namespace="http://www.sunpowercorp.com/861_FlatFile"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../pollEDI214Files.wsdl"/>
            <oracle-xsl-mapper:rootElement name="InputParams" namespace="http://www.sunpowercorp.com/utilities/inputparam/xsd/v1"/>
            <oracle-xsl-mapper:param name="inputParam"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="../insertEDI861Files.wsdl"/>
            <oracle-xsl-mapper:rootElement name="XxspwrEdi861InboundStgCollection" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/insertEDI861Files"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [WED OCT 05 10:55:48 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="inputParam"/>
  <xsl:template match="/">
    <top:XxspwrEdi861InboundStgCollection>
      <xsl:for-each select="/imp1:SalesOrderDetails/imp1:HEADER">
        <top:XxspwrEdi861InboundStg>
          <top:trxId>
            <xsl:value-of select="oraext:sequence-next-val(&quot;XXSPWR.XXSPWR_EDI861_INBOUND_STG_S&quot;,$inputParam/ns2:InputParams/ns2:JNDI)"/>
          </top:trxId>
          <top:transactionSignal>
            <xsl:value-of select="imp1:TRANSACTION_SIGNAL"/>
          </top:transactionSignal>
          <top:transactionSetControlNumber>
            <xsl:value-of select="imp1:TRANSACTION_SET_CONTROL_NUMBER"/>
          </top:transactionSetControlNumber>
          <top:edisignalSentDate>
            <xsl:value-of select="imp1:EDISIGNAL_SENT_DATE"/>
          </top:edisignalSentDate>
          <top:transactionTransmitStatus>
            <xsl:value-of select="imp1:TRANSACTION_TRANSMIT_STATUS"/>
          </top:transactionTransmitStatus>
          <top:edi861FileName>
            <xsl:value-of select="$inputParam/ns2:InputParams/ns2:inputparam"/>
          </top:edi861FileName>
          <top:transactionDate>
            <xsl:value-of select="imp1:TRANSACTION_DATE"/>
          </top:transactionDate>
          <top:transactionType>
            <xsl:value-of select="imp1:TRANSACTION_TYPE"/>
          </top:transactionType>
          <top:receiptRouting>
            <xsl:value-of select="imp1:RECEIPT_ROUTING"/>
          </top:receiptRouting>
          <top:sourceDocumentCode>
            <xsl:value-of select="imp1:SOURCE_DOCUMENT_CODE"/>
          </top:sourceDocumentCode>
          <top:receiptNumber>
            <xsl:value-of select="imp1:RECEIPT_NUMBER"/>
          </top:receiptNumber>
          <top:shipmentNumber>
            <xsl:value-of select="imp1:SHIPMENT_NUMBER"/>
          </top:shipmentNumber>
          <top:shipmentLineNumber>
            <xsl:value-of select="imp1:SHIPMENT_LINE_NUMBER"/>
          </top:shipmentLineNumber>
          <top:operatingUnit>
            <xsl:value-of select="imp1:OPERATING_UNIT"/>
          </top:operatingUnit>
          <top:poIrNumber>
            <xsl:value-of select="imp1:PO_IR_NUMBER"/>
          </top:poIrNumber>
          <top:poIrLineNumber>
            <xsl:value-of select="imp1:PO_IR_LINE_NUMBER"/>
          </top:poIrLineNumber>
          <top:poIrUnitPrice>
            <xsl:value-of select="imp1:PO_IR_UNIT_PRICE"/>
          </top:poIrUnitPrice>
          <top:isoDeliveryNumber>
            <xsl:value-of select="imp1:ISO_DELIVERY_NUMBER"/>
          </top:isoDeliveryNumber>
          <top:quantity>
            <xsl:value-of select="imp1:QUANTITY"/>
          </top:quantity>
          <top:unitOfMeasure>
            <xsl:value-of select="imp1:UNIT_OF_MEASURE"/>
          </top:unitOfMeasure>
          <top:itemNumber>
            <xsl:value-of select="imp1:ITEM_NUMBER"/>
          </top:itemNumber>
          <top:itemDescription>
            <xsl:value-of select="imp1:ITEM_DESCRIPTION"/>
          </top:itemDescription>
          <top:uomCode>
            <xsl:value-of select="imp1:UOM_CODE"/>
          </top:uomCode>
          <top:currencyCode>
            <xsl:value-of select="imp1:CURRENCY_CODE"/>
          </top:currencyCode>
          <top:inspectionStatusCode>
            <xsl:value-of select="imp1:INSPECTION_STATUS_CODE"/>
          </top:inspectionStatusCode>
          <top:shipToOrganizationCode>
            <xsl:value-of select="imp1:SHIP_TO_ORGANIZATION_CODE"/>
          </top:shipToOrganizationCode>
          <top:toSubinventory>
            <xsl:value-of select="imp1:TO_SUBINVENTORY"/>
          </top:toSubinventory>
          <top:freightCarrierCode>
            <xsl:value-of select="imp1:FREIGHT_CARRIER_CODE"/>
          </top:freightCarrierCode>
          <top:billOfLading>
            <xsl:value-of select="imp1:BILL_OF_LADING"/>
          </top:billOfLading>
          <top:packingSlip>
            <xsl:value-of select="imp1:PACKING_SLIP"/>
          </top:packingSlip>
          <top:shippedDate>
            <xsl:value-of select="imp1:SHIPPED_DATE"/>
          </top:shippedDate>
          <top:receiptDate>
            <xsl:value-of select="imp1:RECEIPT_DATE"/>
          </top:receiptDate>
          <top:waybillAirbillNum>
            <xsl:value-of select="imp1:WAYBILL_AIRBILL_NUM"/>
          </top:waybillAirbillNum>
          <top:vendorName>
            <xsl:value-of select="imp1:VENDOR_NAME"/>
          </top:vendorName>
          <top:vendorNumber>
            <xsl:value-of select="imp1:VENDOR_NUMBER"/>
          </top:vendorNumber>
          <top:vendorItemNum>
            <xsl:value-of select="imp1:VENDOR_ITEM_NUM"/>
          </top:vendorItemNum>
          <top:comments>
            <xsl:value-of select="imp1:COMMENTS"/>
          </top:comments>
          <top:reasonCode>
            <xsl:value-of select="imp1:REASON_CODE"/>
          </top:reasonCode>
          <top:createdBy>
            <xsl:text disable-output-escaping="no">-1</xsl:text>
          </top:createdBy>
          <top:creationDate>
            <xsl:value-of select="xp20:current-dateTime()"/>
          </top:creationDate>
          <top:lastUpdatedBy>
            <xsl:text disable-output-escaping="no">-1</xsl:text>
          </top:lastUpdatedBy>
          <top:lastUpdateDate>
            <xsl:value-of select="xp20:current-dateTime()"/>
          </top:lastUpdateDate>
          <top:recordStatus>
            <xsl:text disable-output-escaping="no">Loaded</xsl:text>
          </top:recordStatus>
          <top:referenceIdentification>
            <xsl:value-of select="imp1:REFERENCE_IDENTIFICATION"/>
          </top:referenceIdentification>
          <top:referenceDescription>
            <xsl:value-of select="imp1:REFERENCE_DESCRIPTION"/>
          </top:referenceDescription>
          <top:xxspwrEdi861InboundSnStgCollection>
            <xsl:for-each select="imp1:LinesList">
              <top:XxspwrEdi861InboundSnStg>
                <top:serialId>
                  <xsl:value-of select="position()"/>
                </top:serialId>
                <top:item>
                  <xsl:value-of select="imp1:ITEM"/>
                </top:item>
                <top:serialNumber>
                  <xsl:value-of select="imp1:SERIAL_NUMBER"/>
                </top:serialNumber>
                <top:lpnNumber>
                  <xsl:value-of select="imp1:LPN_NUMBER"/>
                </top:lpnNumber>
                <top:lotNumber>
                  <xsl:value-of select="imp1:LOT_NUMBER"/>
                </top:lotNumber>
                <top:subinventory>
                  <xsl:value-of select="imp1:SUBINVENTORY"/>
                </top:subinventory>
                <top:creationDate>
                  <xsl:value-of select="xp20:current-dateTime()"/>
                </top:creationDate>
                <top:createdBy>
                  <xsl:text disable-output-escaping="no">-1</xsl:text>
                </top:createdBy>
                <top:lastUpdateDate>
                  <xsl:value-of select="xp20:current-dateTime()"/>
                </top:lastUpdateDate>
                <top:lastUpdatedBy>
                  <xsl:text disable-output-escaping="no">-1</xsl:text>
                </top:lastUpdatedBy>
                <top:attribute1>
                  <xsl:value-of select="imp1:ATTRIBUTE1"/>
                </top:attribute1>
                <top:attribute2>
                  <xsl:value-of select="imp1:ATTRIBUTE2"/>
                </top:attribute2>
                <top:attribute3>
                  <xsl:value-of select="imp1:ATTRIBUTE3"/>
                </top:attribute3>
                <top:attribute4>
                  <xsl:value-of select="imp1:ATTRIBUTE4"/>
                </top:attribute4>
                <top:attribute5>
                  <xsl:value-of select="imp1:ATTRIBUTE5"/>
                </top:attribute5>
              </top:XxspwrEdi861InboundSnStg>
            </xsl:for-each>
          </top:xxspwrEdi861InboundSnStgCollection>
        </top:XxspwrEdi861InboundStg>
      </xsl:for-each>
    </top:XxspwrEdi861InboundStgCollection>
  </xsl:template>
</xsl:stylesheet>