<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:ns4="http://www.sunpowercorp.com/Noun/SyncAccCustomers/V1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns3="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:ns5="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:ns2="http://www.sunpowercorp.com/SFDCSyncLeaseCustomerReq/xsd/v1" xmlns:client="http://xmlns.oracle.com/OnLineSalesOrder/CreateSalesOrderSFDCReq/CreateSalesOrderSFDCReq" xmlns:tns="http://soap.sforce.com/schemas/class/OrderIntegrationService" xmlns:ns6="http://www.sunpowercorp.com/Common/SyncAccCustCommonTypes/V1" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:ns0="http://www.example.org/CreateUpdatePS/" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessSFDCSyncCust/V1" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl plnk soap wsdl ns2 client tns xsd ns4 ns3 ns5 ns6 ns0 ns1 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/GetNewOrder.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetNewOrdersResponse" namespace="http://soap.sforce.com/schemas/class/OrderIntegrationService"/>
         </oracle-xsl-mapper:source>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/CreateSalesOrderSFDCReq.wsdl"/>
            <oracle-xsl-mapper:rootElement name="Inputparam" namespace="http://www.sunpowercorp.com/SFDCSyncLeaseCustomerReq/xsd/v1"/>
            <oracle-xsl-mapper:param name="Inputparam"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7004/CreateUpdateCustomerEBS/Proxy/CreateUpdateCustomerPS?WSDL"/>
            <oracle-xsl-mapper:rootElement name="ProcessSFDCSyncCust" namespace="http://www.sunpowercorp.com/BOD/ProcessSFDCSyncCust/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [FRI OCT 07 15:33:07 CDT 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:param name="Inputparam"/>
  <xsl:template match="/">
    <ns1:ProcessSFDCSyncCust>
      <ns1:DataArea>
        <ns3:process>
          <xsl:text disable-output-escaping="no">SFDC</xsl:text>
        </ns3:process>
        <ns3:callService>
          <xsl:value-of select="$Inputparam/ns2:Inputparam/ns2:finalLoop"/>
        </ns3:callService>
        <ns4:SyncAccCustomers>
          <xsl:variable name="Index" select="number($Inputparam/ns2:Inputparam/ns2:iteration)"/>
          <ns4:Accounts>
            <xsl:for-each select="/tns:GetNewOrdersResponse/tns:result/tns:orders[$Index]/tns:accountList/tns:account/tns:accountHeader">
              <xsl:variable name="TEMP_CUST_ID" select="oraext:sequence-next-val(&quot;XXSPWR.XXSPWR_SFORA_CUSTOMERS_S&quot;,$Inputparam/ns2:Inputparam/ns2:jndi)"/>
              <ns4:Account>
                <ns6:SFDC_ACCOUNT_ID>
                  <xsl:value-of select="tns:AccountId"/>
                </ns6:SFDC_ACCOUNT_ID>
                <ns6:ACCOUNT_NUMBER>
                  <xsl:value-of select="tns:OracleAccountNumber"/>
                </ns6:ACCOUNT_NUMBER>
                <ns6:PROCESS_FLAG>
                  <xsl:text disable-output-escaping="no">1</xsl:text>
                </ns6:PROCESS_FLAG>
                <ns6:TEMP_CUST_ID>
                  <xsl:value-of select="$TEMP_CUST_ID"/>
                </ns6:TEMP_CUST_ID>
                <ns6:CUSTOMER_NAME>
                  <xsl:value-of select="tns:Name"/>
                </ns6:CUSTOMER_NAME>
                <xsl:variable name="Status" select="tns:IsActive"/>
                <ns6:STATUS>
                  <xsl:value-of select="dvm:lookupValue(&quot;CUSTOMER_SITES_STATUS.dvm&quot;,&quot;SFDC&quot;,$Status,&quot;Ebiz&quot;,&quot;&quot;)"/>
                </ns6:STATUS>
                <xsl:variable name="accountType" select="tns:AccountType"/>
                <ns6:ACCOUNT_TYPE>
                  <xsl:value-of select="dvm:lookupValue(&quot;CUSTOMER_SITES_STATUS.dvm&quot;,&quot;SFDC&quot;,$accountType,&quot;Ebiz&quot;,&quot;&quot;)"/>
                </ns6:ACCOUNT_TYPE>
                <xsl:variable name="salesType" select="../../../tns:orderHeader/tns:SalesType"/>
                <ns6:SALES_TYPE>
                  <xsl:value-of select="dvm:lookupValue(&quot;CUSTOMER_SITES_STATUS.dvm&quot;,&quot;SFDC&quot;,$salesType,&quot;Ebiz&quot;,&quot;&quot;)"/>
                </ns6:SALES_TYPE>
                <ns6:CREATED_BY>
                  <xsl:text disable-output-escaping="no">-999</xsl:text>
                </ns6:CREATED_BY>
                <ns6:LAST_UPDATED_BY>
                  <xsl:text disable-output-escaping="no">-999</xsl:text>
                </ns6:LAST_UPDATED_BY>
                <ns6:CUSTOMER_ORDER_LINK_ID>
                  <xsl:value-of select="$Inputparam/ns2:Inputparam/ns2:orderAccountLinkId"/>
                </ns6:CUSTOMER_ORDER_LINK_ID>
                <ns6:TRANSACTION_STATUS>
                  <xsl:value-of select="tns:TransactionStatus"/>
                </ns6:TRANSACTION_STATUS>
                <ns6:DATA_SOURCE>
                  <xsl:text disable-output-escaping="no">SFDC</xsl:text>
                </ns6:DATA_SOURCE>
                <ns4:CustSites>
                  <xsl:for-each select="../tns:SiteList/tns:Sites">
                    <ns4:CustSite>
                      <ns6:TEMP_CUST_SITE_ID>
                        <xsl:value-of select="oraext:sequence-next-val(&quot;XXSPWR.XXSPWR_SFORA_CUST_SITES_S&quot;,$Inputparam/ns2:Inputparam/ns2:jndi)"/>
                      </ns6:TEMP_CUST_SITE_ID>
                      <ns6:PROCESS_FLAG>
                        <xsl:text disable-output-escaping="no">1</xsl:text>
                      </ns6:PROCESS_FLAG>
                      <ns6:CUST_ACCT_SITE_ID>
                        <xsl:value-of select="tns:OracleSiteId"/>
                      </ns6:CUST_ACCT_SITE_ID>
                      <ns6:SITE_USAGE>
                        <xsl:value-of select="tns:SiteType"/>
                      </ns6:SITE_USAGE>
                      <xsl:choose>
                        <xsl:when test="tns:SiteType = &quot;BILL_TO&quot;">
                          <ns6:SFDC_BILLTO_SITE_ID>
                            <xsl:value-of select="tns:SiteId"/>
                          </ns6:SFDC_BILLTO_SITE_ID>
                        </xsl:when>
                        <xsl:otherwise>
                          <ns6:SFDC_SHIPTO_SITE_ID>
                            <xsl:value-of select="tns:SiteId"/>
                          </ns6:SFDC_SHIPTO_SITE_ID>
                        </xsl:otherwise>
                      </xsl:choose>
                      <ns6:ADDRESS1>
                        <xsl:value-of select="tns:Address1"/>
                      </ns6:ADDRESS1>
                      <ns6:ADDRESS2>
                        <xsl:value-of select="tns:Address2"/>
                      </ns6:ADDRESS2>
                      <ns6:ADDRESS3>
                        <xsl:value-of select="tns:Address3"/>
                      </ns6:ADDRESS3>
                      <ns6:CITY>
                        <xsl:value-of select="tns:City"/>
                      </ns6:CITY>
                      <xsl:variable name="SiteStatus" select="xp20:upper-case(tns:IsActive)"/>
                      <ns6:STATUS>
                        <xsl:value-of select="dvm:lookupValue(&quot;CUSTOMER_SITES_STATUS.dvm&quot;,&quot;SFDC&quot;,$SiteStatus,&quot;Ebiz&quot;,&quot;&quot;)"/>
                      </ns6:STATUS>
                      <ns6:STATE>
                        <xsl:value-of select="tns:State"/>
                      </ns6:STATE>
                      <ns6:POSTAL_CODE>
                        <xsl:value-of select="tns:Postalcode"/>
                      </ns6:POSTAL_CODE>
                      <ns6:COUNTRY>
                        <xsl:value-of select="tns:Country"/>
                      </ns6:COUNTRY>
                      <ns6:COUNTY>
                        <xsl:value-of select="tns:County"/>
                      </ns6:COUNTY>
                      <xsl:choose>
                        <xsl:when test="tns:IsPrimary = &quot;true&quot;">
                          <ns6:PRIMARY_FLAG>
                            <xsl:value-of select="&quot;Y&quot;"/>
                          </ns6:PRIMARY_FLAG>
                        </xsl:when>
                        <xsl:otherwise>
                          <ns6:PRIMARY_FLAG>
                            <xsl:value-of select="&quot;N&quot;"/>
                          </ns6:PRIMARY_FLAG>
                        </xsl:otherwise>
                      </xsl:choose>
                      <ns6:TEMP_CUST_ID>
                        <xsl:value-of select="$TEMP_CUST_ID"/>
                      </ns6:TEMP_CUST_ID>
                      <ns6:PROVINCE>
                        <xsl:value-of select="tns:Province"/>
                      </ns6:PROVINCE>
                      <ns6:CREATED_BY>
                        <xsl:text disable-output-escaping="no">-999</xsl:text>
                      </ns6:CREATED_BY>
                      <ns6:LAST_UPDATED_BY>
                        <xsl:text disable-output-escaping="no">-999</xsl:text>
                      </ns6:LAST_UPDATED_BY>
                      <ns6:ACCOUNT_NUMBER>
                        <xsl:value-of select="tns:OracleAccountNumber"/>
                      </ns6:ACCOUNT_NUMBER>
                      <ns6:CUSTOMER_ORDER_LINK_ID>
                        <xsl:value-of select="$Inputparam/ns2:Inputparam/ns2:orderAccountLinkId"/>
                      </ns6:CUSTOMER_ORDER_LINK_ID>
                      <ns6:SFDC_ACCOUNT_ID>
                        <xsl:value-of select="tns:SiteAccountId"/>
                      </ns6:SFDC_ACCOUNT_ID>
                      <ns6:TRANSACTION_STATUS>
                        <xsl:value-of select="tns:TransactionStatus"/>
                      </ns6:TRANSACTION_STATUS>
                     <!-- <ns6:SITE_STATUS>
                        <xsl:value-of select="tns:SiteStatus"/>
                      </ns6:SITE_STATUS>-->
                      <xsl:variable name="salesTypeBillTo" select="/tns:GetNewOrdersResponse/tns:result/tns:orders[$Index]/tns:orderHeader/tns:SalesType"/>
                      <ns6:SALES_TYPE>
                        <xsl:value-of select="dvm:lookupValue(&quot;CUSTOMER_SITES_STATUS.dvm&quot;,&quot;SFDC&quot;,$salesTypeBillTo,&quot;Ebiz&quot;,&quot;&quot;)"/>
                      </ns6:SALES_TYPE>
                    </ns4:CustSite>
                  </xsl:for-each>
                </ns4:CustSites>
                <ns4:Contacts>
                  <xsl:for-each select="../tns:contactList/tns:contact">
                    <ns4:Contact>
                      <ns6:TEMP_CONTACT_ID>
                        <xsl:value-of select="oraext:sequence-next-val(&quot;XXSPWR.XXSPWR_CUST_CONTACTS_S&quot;,$Inputparam/ns2:Inputparam/ns2:jndi)"/>
                      </ns6:TEMP_CONTACT_ID>
                      <ns6:CUST_ACCOUNT_ROLE_ID>
                        <xsl:value-of select="tns:OracleContactId"/>
                      </ns6:CUST_ACCOUNT_ROLE_ID>
                      <ns6:SFDC_CONTACT_ID>
                        <xsl:value-of select="tns:ContactId"/>
                      </ns6:SFDC_CONTACT_ID>
                      <ns6:LAST_NAME>
                        <xsl:value-of select="tns:LastName"/>
                      </ns6:LAST_NAME>
                      <ns6:FIRST_NAME>
                        <xsl:value-of select="tns:FirstName"/>
                      </ns6:FIRST_NAME>
                      <ns6:RAW_PHONE_NUMBER>
                        <xsl:value-of select="tns:PhoneNumber"/>
                      </ns6:RAW_PHONE_NUMBER>
                      <ns6:FAX_NO>
                        <xsl:value-of select="tns:FaxNumber"/>
                      </ns6:FAX_NO>
                      <ns6:MOBILE_NO>
                        <xsl:value-of select="tns:MobileNumber"/>
                      </ns6:MOBILE_NO>
                      <ns6:EMAIL_ID>
                        <xsl:value-of select="tns:EmailAddress"/>
                      </ns6:EMAIL_ID>
                      <ns6:CREATED_BY>
                        <xsl:text disable-output-escaping="no">-999</xsl:text>
                      </ns6:CREATED_BY>
                      <ns6:LAST_UPDATED_BY>
                        <xsl:text disable-output-escaping="no">-999</xsl:text>
                      </ns6:LAST_UPDATED_BY>
                      <ns6:PROCESS_FLAG>
                        <xsl:text disable-output-escaping="no">1</xsl:text>
                      </ns6:PROCESS_FLAG>
                      <xsl:choose>
                        <xsl:when test="tns:IsPrimary = &quot;true&quot;">
                          <ns6:PRIMARY_FLAG>
                            <xsl:value-of select="&quot;Y&quot;"/>
                          </ns6:PRIMARY_FLAG>
                        </xsl:when>
                        <xsl:otherwise>
                          <ns6:PRIMARY_FLAG>
                            <xsl:value-of select="&quot;N&quot;"/>
                          </ns6:PRIMARY_FLAG>
                        </xsl:otherwise>
                      </xsl:choose>
                      <xsl:variable name="ContactStatus" select="tns:IsActive"/>
                      <ns6:STATUS>
                        <xsl:value-of select="dvm:lookupValue(&quot;CUSTOMER_SITES_STATUS.dvm&quot;,&quot;SFDC&quot;,$ContactStatus,&quot;Ebiz&quot;,&quot;&quot;)"/>
                      </ns6:STATUS>
                      <ns6:ACCOUNT_NUMBER>
                        <xsl:value-of select="tns:OracleAccountNumber"/>
                      </ns6:ACCOUNT_NUMBER>
                      <ns6:TEMP_CUST_ID>
                        <xsl:value-of select="$TEMP_CUST_ID"/>
                      </ns6:TEMP_CUST_ID>
                      <ns6:CUSTOMER_ORDER_LINK_ID>
                        <xsl:value-of select="$Inputparam/ns2:Inputparam/ns2:orderAccountLinkId"/>
                      </ns6:CUSTOMER_ORDER_LINK_ID>
                      <ns6:SFDC_ACCOUNT_ID>
                        <xsl:value-of select="tns:AccountId"/>
                      </ns6:SFDC_ACCOUNT_ID>
                      <ns6:TRANSACTION_STATUS>
                        <xsl:value-of select="tns:TransactionStatus"/>
                      </ns6:TRANSACTION_STATUS>
                      <xsl:variable name="salesTypeContact" select="/tns:GetNewOrdersResponse/tns:result/tns:orders[$Index]/tns:orderHeader/tns:SalesType"/>
                      <ns6:SALES_TYPE>
                        <xsl:value-of select="dvm:lookupValue(&quot;CUSTOMER_SITES_STATUS.dvm&quot;,&quot;SFDC&quot;,$salesTypeContact,&quot;Ebiz&quot;,&quot;&quot;)"/>
                      </ns6:SALES_TYPE>
                    </ns4:Contact>
                  </xsl:for-each>
                </ns4:Contacts>
              </ns4:Account>
            </xsl:for-each>
          </ns4:Accounts>
        </ns4:SyncAccCustomers>
      </ns1:DataArea>
    </ns1:ProcessSFDCSyncCust>
  </xsl:template>
</xsl:stylesheet>