<?binding.jca UpdateOrderEBS_db.jca?>
<wsdl:definitions name="UpdateOrderEBS" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OnLineSalesOrder/UpdateSalesOrderResponseSFDCProv/UpdateOrderEBS" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OnLineSalesOrder/UpdateSalesOrderResponseSFDCProv/UpdateOrderEBS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateOrderEBS">
    <plt:partnerLinkType name="UpdateOrderEBS_plt">
        <plt:role name="UpdateOrderEBS_role">
            <plt:portType name="tns:UpdateOrderEBS_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateOrderEBS"
                    schemaLocation="Schemas/UpdateOrderEBS_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="XxspwrDsrSoHeaderCollection_msg">
        <wsdl:part name="XxspwrDsrSoHeaderCollection" element="top:XxspwrDsrSoHeaderCollection"/>
    </wsdl:message>
    <wsdl:portType name="UpdateOrderEBS_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:XxspwrDsrSoHeaderCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
