<wsdl:definitions name="CreateSalesOrderEBSWSDL" targetNamespace="http://www.example.org/CreateSalesOrderEBSWSDL" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessOracleSFDCNoItemOrders/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:client="http://www.example.org/CreateSalesOrderEBSWSDL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
       <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://www.sunpowercorp.com/BOD/ProcessOracleSFDCNoItemOrders/V1" schemaLocation="../xsd/CDM/BOD/Nouns/OracleSFDCNoItemOrders/V1/ProcessOracleSFDCNoItemOrders.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="CreateSalesOrderOracleRequestMessage">
        <wsdl:part name="payload" element="ns1:ProcessOracleSFDCNoItemOrdersReq"/>
    </wsdl:message>
    <wsdl:portType name="CreateSalesOrderOracle">
        <wsdl:operation name="process">
            <wsdl:input message="client:CreateSalesOrderOracleRequestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="CreateSalesOrderOracleBinding" type="client:CreateSalesOrderOracle">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
   
</wsdl:definitions>