<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="PublishARSupplPaymntReversalsOracleToOSG_BPEL"
     targetNamespace="http://xmlns.oracle.com/OSG/PublishARSupplPaymntReversalsOracleToOSG/PublishARSupplPaymntReversalsOracleToOSG_BPEL"     
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:client="http://xmlns.oracle.com/OSG/PublishARSupplPaymntReversalsOracleToOSG/PublishARSupplPaymntReversalsOracleToOSG_BPEL"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="PublishARSupplPaymntReversalsOracleToOSG_BPEL">
        <plnk:role name="PublishARSupplPaymntReversalsOracleToOSG_BPELProvider">
            <plnk:portType name="client:PublishARSupplPaymntReversalsOracleToOSG_BPEL"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/OSG/PublishARSupplPaymntReversalsOracleToOSG/PublishARSupplPaymntReversalsOracleToOSG_BPEL"
                 schemaLocation="../Schemas/PublishARSupplPaymntReversalsOracleToOSG_BPEL.xsd"/>
        </schema>        
    </wsdl:types>
    <wsdl:message name="PublishARSupplPaymntReversalsOracleToOSG_BPELRequestMessage">
        <wsdl:part name="payload" element="client:process"/>
    </wsdl:message>
    <wsdl:portType name="PublishARSupplPaymntReversalsOracleToOSG_BPEL">
        <wsdl:operation name="process">
            <wsdl:input message="client:PublishARSupplPaymntReversalsOracleToOSG_BPELRequestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
