<?binding.jca SelectOSGSupplPaymntReversalsFeedFromOracle_db.jca?>
<wsdl:definitions name="SelectOSGSupplPaymntReversalsFeedFromOracle" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSG/PublishARSupplPaymntReversalsOracleToOSG/SelectOSGSupplPaymntReversalsFeedFromOracle" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/SelectOSGSupplPaymntReversalsFeedFromOracle" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSG/PublishARSupplPaymntReversalsOracleToOSG/SelectOSGSupplPaymntReversalsFeedFromOracle" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
    <plt:partnerLinkType name="SelectOSGSupplPaymntReversalsFeedFromOracle_plt">
        <plt:role name="SelectOSGSupplPaymntReversalsFeedFromOracle_role">
            <plt:portType name="tns:SelectOSGSupplPaymntReversalsFeedFromOracle_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SelectOSGSupplPaymntReversalsFeedFromOracle"
                    schemaLocation="../Schemas/SelectOSGSupplPaymntReversalsFeedFromOracle.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="SelectOSGSupplPaymntReversalsFeedFromOracleInput_msg">
        <wsdl:part name="SelectOSGSupplPaymntReversalsFeedFromOracleInput_msg" element="db:SelectOSGSupplPaymntReversalsFeedFromOracleInput"/>
    </wsdl:message>
    <wsdl:message name="SelectOSGSupplPaymntReversalsFeedFromOracleOutputCollection_msg">
        <wsdl:part name="SelectOSGSupplPaymntReversalsFeedFromOracleOutputCollection" element="db:SelectOSGSupplPaymntReversalsFeedFromOracleOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="SelectOSGSupplPaymntReversalsFeedFromOracle_ptt">
        <wsdl:operation name="SelectOSGSupplPaymntReversalsFeedFromOracle">
            <wsdl:input message="tns:SelectOSGSupplPaymntReversalsFeedFromOracleInput_msg"/>
            <wsdl:output message="tns:SelectOSGSupplPaymntReversalsFeedFromOracleOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
