<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="OracleSFDCNoItemBillToProv_BPEL" targetNamespace="http://www.sunpowercorp.com/OnlineOrderingNoItemOracleToSFDC/OracleSFDCNoItemBillToProv/OracleSFDCNoItemBillToProv_BPEL" xmlns:ns2="urn:partner.soap.sforce.com" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessOnlineOrderingNoItemOracleToSFDC/V1" xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:ns3="http://schemas.xmlsoap.org/ws/2003/03/addressing" xmlns:client="http://www.sunpowercorp.com/OnlineOrderingNoItemOracleToSFDC/OracleSFDCNoItemBillToProv/OracleSFDCNoItemBillToProv_BPEL" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
   <plnk:partnerLinkType name="OracleSFDCNoItemBillToProv_BPEL">
      <plnk:role name="OracleSFDCNoItemBillToProv_BPELProvider">
         <plnk:portType name="client:OracleSFDCNoItemBillToProv_BPEL"/>
      </plnk:role>
   </plnk:partnerLinkType>
   <wsdl:import namespace="urn:partner.soap.sforce.com" location="SFDCPartner.wsdl"/>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://www.sunpowercorp.com/BOD/ProcessOnlineOrderingNoItemOracleToSFDC/V1"
                 schemaLocation="Schemas/CDM/BOD/Nouns/OnlineOrderingNoItemOracleToSFDC/V1/ProcessOnlineOrderingNoItemOracleToSFDC.xsd"/>
      </schema>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
         <xsd:import namespace="http://schemas.xmlsoap.org/ws/2003/03/addressing"
                     schemaLocation="Schemas/wsaaddress.xsd"/>
      </xsd:schema>
      <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
         <xsd:import namespace="http://www.sunpowercorp.com/OnlineOrderingNoItemOracleToSFDC/OracleSFDCNoItemBillToProv/OracleAccountNumbers/xsd/v1"
                     schemaLocation="Schemas/OracleAccountNumbers.xsd"/>
      </xsd:schema>
   </wsdl:types>
   <wsdl:message name="OracleSFDCNoItemBillToProv_BPELRequestMessage">
      <wsdl:part name="payload" element="ns1:ProcessOnlineOrderingNoItemOracleToSFDC"/>
   </wsdl:message>
   <wsdl:portType name="OracleSFDCNoItemBillToProv_BPEL">
      <wsdl:operation name="process">
         <wsdl:input message="client:OracleSFDCNoItemBillToProv_BPELRequestMessage"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
