<?binding.jca UpdateFDSDB_db.jca?>
<wsdl:definitions name="UpdateFDSDB" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/WarrantyRegistrationFDSToSFDC/WarrantyFDSToSFDCReq/UpdateFDSDB" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/WarrantyRegistrationFDSToSFDC/WarrantyFDSToSFDCReq/UpdateFDSDB" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateFDSDB">
    <plt:partnerLinkType name="UpdateFDSDB_plt">
        <plt:role name="UpdateFDSDB_role">
            <plt:portType name="tns:UpdateFDSDB_ptt"/>
        </plt:role>
    </plt:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/UpdateFDSDB"
                    schemaLocation="../Schemas/UpdateFDSDB_table.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="WarrantyViewFlushCollection_msg">
        <wsdl:part name="WarrantyViewFlushCollection" element="top:WarrantyViewFlushCollection"/>
    </wsdl:message>
    <wsdl:portType name="UpdateFDSDB_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:WarrantyViewFlushCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
