<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="WarrantyFDSToSFDCCanonical"
     targetNamespace="http://www.sunpowercorp.com/WarrantyFDSToSFDCCanonical/"
     xmlns:ns1="http://www.sunpowercorp.com/WarrantyFDSToSFDCCanonical/"
     xmlns:plnk="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    >
    <plnk:partnerLinkType name="WarrantyFDSToSFDCCanonical_PL">
        <plnk:role name="WarrantyFDSToSFDCCanonical_Role">
            <plnk:portType name="ns1:WarrantyFDSToSFDCCanonical"/>
        </plnk:role>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://www.sunpowercorp.com/WarrantyFDSToSFDCCanonical/"
                 location="WarrantyFDSToSFDCCanonical.wsdl"/>
</wsdl:definitions>
