<?xml version = '1.0' encoding = 'UTF-8'?>
<xsl:stylesheet version="1.0" xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20" xmlns:bpws="http://schemas.xmlsoap.org/ws/2003/03/business-process/" xmlns:bpel="http://docs.oasis-open.org/wsbpel/2.0/process/executable" xmlns:ns3="http://www.sunpowercorp.com/Noun/ACBClaimToSFDC/V1" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:tns="http://www.acbcoop.com/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bpm="http://xmlns.oracle.com/bpmn20/extensions" xmlns:ns5="http://www.sunpowercorp.com/Common/ACBClaimToSFDCCommonTypes/V1" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:ns2="http://www.sunpowercorp.com/Verb/VerbCommonTypes/V1" xmlns:ns1="http://www.sunpowercorp.com/BOD/ProcessACBClaimToSFDC/V1" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:ora="http://schemas.oracle.com/xpath/extension" xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator" xmlns:ns0="http://www.sunpowercorp.com/ACBClaimAll/" xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction" xmlns:ns4="http://www.sunpowercorp.com/Common/CommonDataTypes/V1" xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue" xmlns:hwf="http://xmlns.oracle.com/bpel/workflow/xpath" xmlns:med="http://schemas.oracle.com/mediator/xpath" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ids="http://xmlns.oracle.com/bpel/services/IdentityService/xpath" xmlns:xdk="http://schemas.oracle.com/bpel/extension/xpath/function/xdk" xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ldap="http://schemas.oracle.com/xpath/extension/ldap" exclude-result-prefixes="xsi xsl tm tns soap12 soapenc soap wsdl mime http xsd ns3 ns5 ns2 ns1 ns0 ns4 xp20 bpws bpel bpm ora socket mhdr oraext dvm hwf med ids xdk xref ldap" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas">
  <oracle-xsl-mapper:schema>
      <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
      <oracle-xsl-mapper:mapSources>
         <oracle-xsl-mapper:source type="WSDL">
            <oracle-xsl-mapper:schema location="../WSDLs/ACBClaimAll.wsdl"/>
            <oracle-xsl-mapper:rootElement name="GetAllClaimsResponse" namespace="http://www.acbcoop.com/"/>
         </oracle-xsl-mapper:source>
      </oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:mapTargets>
         <oracle-xsl-mapper:target type="WSDL">
            <oracle-xsl-mapper:schema location="http://dev-fusappdca02.sunpowercorp.com:7004/ACBGetAllClaimsmergeSvc/Proxy/ACBGetAllClaimsmergeSvcPS?wsdl"/>
            <oracle-xsl-mapper:rootElement name="ProcessACBClaimToSFDC" namespace="http://www.sunpowercorp.com/BOD/ProcessACBClaimToSFDC/V1"/>
         </oracle-xsl-mapper:target>
      </oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:mapShowPrefixes type="true"/>
      <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.0.0(XSLT Build 151013.0700.0085) AT [FRI OCT 07 17:31:32 IST 2016].-->
   </oracle-xsl-mapper:schema>
   <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
   <xsl:template match="/">
    <ns1:ProcessACBClaimToSFDC>
      <ns2:ApplicationArea>
        <ns2:Sender>
          <ns2:LogicalId>
            <xsl:text disable-output-escaping="no"/>
          </ns2:LogicalId>
          <ns2:ComponentId>
            <xsl:text disable-output-escaping="no">zc</xsl:text>
          </ns2:ComponentId>
        </ns2:Sender>
      </ns2:ApplicationArea>
      <ns1:DataArea>
        <ns3:ACBClaimToSFDC>
          <ns3:ACBClaimToSFDCDetails>
            <ns5:DlrName>
              <xsl:value-of select="/tns:GetAllClaimsResponse/tns:GetAllClaimsResult/tns:WebServiceClaims/tns:DlrName"/>
            </ns5:DlrName>
          </ns3:ACBClaimToSFDCDetails>
        </ns3:ACBClaimToSFDC>
      </ns1:DataArea>
    </ns1:ProcessACBClaimToSFDC>
  </xsl:template>
</xsl:stylesheet>