<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="InsertJobFeedSF2Oracle" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SuccessFactor/JobFeedSF2Oracle/InsertJobFeedSF2Oracle" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SuccessFactor/JobFeedSF2Oracle/InsertJobFeedSF2Oracle" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertJobFeedSF2Oracle">
   <plt:partnerLinkType name="InsertJobFeedSF2Oracle_plt">
      <plt:role name="InsertJobFeedSF2Oracle_role">
         <plt:portType name="tns:InsertJobFeedSF2Oracle_ptt"/>
      </plt:role>
   </plt:partnerLinkType>
   <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
         <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertJobFeedSF2Oracle" schemaLocation="../Schemas/InsertJobFeedSF2Oracle_table.xsd"/>
      </schema>
   </wsdl:types>
   <wsdl:message name="XxspwrSfJobFeedCollection_msg">
      <wsdl:part name="XxspwrSfJobFeedCollection" element="top:XxspwrSfJobFeedCollection"/>
   </wsdl:message>
   <wsdl:portType name="InsertJobFeedSF2Oracle_ptt">
      <wsdl:operation name="insert">
         <wsdl:input message="tns:XxspwrSfJobFeedCollection_msg"/>
      </wsdl:operation>
   </wsdl:portType>
</wsdl:definitions>
